### ISSUE TITLE
Chat manager issues

### ISSUE THREAD

**Issue by lol768** [drtshock/Factions#100]
![image](https://prtscr.us/u/525571414623357.png)

Relevant IRC conversation:

```
[22:51:58] <oddmonster> Removing the chat manager fixes the problem, but causes more problems.
[22:52:21] <oddmonster> I'll e-mail him.  Thanks for it.
[22:52:48] <oddmonster> It's Essentials Chat.
[22:53:05] <oddmonster> I tried uploading different chat managers, all with the same result.
```

**Comment by ghost** [comment]
The problem happens with the legacy version, and the UUID one. Only plugins installed:  Group Manager, Vault, Essentials Chat, Essentials, Essentials Spawn, Factions UUID.

**Comment by drtshock** [comment]
@kashike

**Comment by milkmoron** [comment]
I also have this problem. Removing Essentials Chat fixes it for me too, but I'd like to use Essentials Chat. Have you found any other chat formatting plugin that is compatible?

I mostly just want to remove the <> brackets and color chat for ranks

**Comment by drtshock** [comment]
Going to bring discussion to this issue for any future chat related issues. 

Chat essentially needs an entire rewrite. The way it's currently implemented is pretty bad.
