### ISSUE TITLE
No Faction spacing

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1001]
Using Deluxe Chat and when using the %factions_chat_tag% tag, if I put a space in between factions chat tag and prefix when player is not in a faction there will be an empty space in chat. How can I fix this ?

Example:
https://gyazo.com/a23453f17b99de4bbe8f0c311372f2a2

**Comment by WizzleBear** [comment]
Go to the conf.json file and make "chatTagPadAfter" true.

**Comment by ghost** [comment]
Thanks for the reply, I've done that but nothing changed. Here's my Conf file if that helps: https://hastebin.com/ixativugum.json
