### ISSUE TITLE
f econenable true

### ISSUE THREAD

**Issue by MrSuricate2** [drtshock/Factions#1003]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.1.21

Server software (run `/version`): 1.12.2-R0.1-SNAPSHOT

Server (`logs/latest.log`): 

Details:
/f econenable true
The problem is that the factionrankup plugin uses this function and I am forced to redo the command so that the plugin can take the money of the faction
Factionrankup : https://www.spigotmc.org/resources/factionrankup.43316/

**Comment by drtshock** [comment]
What's the exact issue you're having? I don't get it.

**Comment by MrSuricate2** [comment]
I make the command / f econenable true so that the FactionRankup plugin can take the money in the faction. But the problem is that every time the server reboots or reload the option and activate in the file config.json but the plugin can not withdraw the money from the faction.

**Comment by drtshock** [comment]
You must have some permission issues because it's saved in conf.json and persists between restarts. Are you having any issues saving faction data?

**Comment by MrSuricate2** [comment]
How can we see that?

**Comment by drtshock** [comment]
check the file `plugins/Factions/conf.json`

**Comment by MrSuricate2** [comment]
Line ?

**Comment by drtshock** [comment]
Search for "econEnable"

**Comment by MrSuricate2** [comment]
true !
