### ISSUE TITLE
new command /f fly

### ISSUE THREAD

**Issue by natezfite** [drtshock/Factions#1007]
Hello I would like to suggest a new command
/f fly
this command will allow you to fly in claimed land only once you leave your land /f fly is disabled
also the command /f fly will be disabled once in combat to avoid flying away and using it 
as a advantaged

**Comment by natezfite** [comment]
and for /f fly being disabled during combat one can following add combatlog to the server and add /f fly to the disabled commands once in combat mode

**Comment by xGaminqPvPx** [comment]
I can probably custom make you this for $$$

**Comment by drtshock** [comment]
Added :D
