### ISSUE TITLE
Factions blockbreak error

### ISSUE THREAD

**Issue by LoXR** [drtshock/Factions#1008]
FactionsUUID version (run `/f version`): Factions version 1.6.9.5-U0.2.0-SNAPSHOT-b27

Server software (run `/version`): git-Paper-1310 (MC: 1.12.2)

Server (`logs/latest.log`):

Details: https://pastebin.com/WWT4W0wD

**Comment by drtshock** [comment]
Thanks for reporting. Fixed it :)
