### ISSUE TITLE
Issue On Startup After Implementing Perms

### ISSUE THREAD

**Issue by Driftay** [drtshock/Factions#1010]
21.01 16:40:42 [Server] INFO Disabling Factions v1.6.9.5-U0.1.19-RC1
21.01 16:40:42 [Server] INFO ... 21 more
21.01 16:40:42 [Server] INFO at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:104) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_141]
21.01 16:40:42 [Server] INFO at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:1.8.0_141]
21.01 16:40:42 [Server] INFO Caused by: java.lang.InstantiationException
21.01 16:40:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
21.01 16:40:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at com.massivecraft.factions.P.onEnable(P.java:79) ~[?:?]
21.01 16:40:42 [Server] INFO at com.massivecraft.factions.zcore.persist.json.JSONFactions.load(JSONFactions.java:73) ~[?:?]
21.01 16:40:42 [Server] INFO at com.massivecraft.factions.zcore.persist.json.JSONFactions.loadCore(JSONFactions.java:93) ~[?:?]
21.01 16:40:42 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:717) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:768) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:803) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:107) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
21.01 16:40:42 [Server] INFO java.lang.RuntimeException: Failed to invoke public com.massivecraft.factions.zcore.persist.json.JSONFaction() with no args

**Comment by Driftay** [comment]
com.massivecraft.factions.zcore.persist.json.JSONFaction() with no args

Super'd so im not seeing the problem

**Comment by drtshock** [comment]
What do you mean after ipmlementing perms?

**Comment by Driftay** [comment]
So ive been updating it as you have been releasing changelogs, but after adding the CmdPerm and editing everything else, it gave me that error

**Comment by drtshock** [comment]
Did you grab the build from last night? If so, please paste the error.

**Comment by Driftay** [comment]
yea the 17 hours ago one i did

**Comment by drtshock** [comment]
Well
```21.01 16:40:42 [Server] INFO Disabling Factions v1.6.9.5-U0.1.19-RC1``` is an old version and that's the last error you posted. You said you grabbed a build from last night, which means that you should have a new log file with a new version.

**Comment by Driftay** [comment]
yea i have a old build, but i keep updating it because i coded co leaders into my current build

**Comment by Driftay** [comment]
i didnt grab the whole file, i just grabbed the code

**Comment by drtshock** [comment]
Well I need an update log with the error from the updated version.

**Comment by Driftay** [comment]
to make it easier should i grab source from the most recent update and just re-add my changes ? to save us both time?

**Comment by drtshock** [comment]
You're telling me that you have an issue and I'm asking for logs of when the issue happened. Can I please have the logs from when this issue still happened on build 29 from https://ci.ender.zone/job/FactionsUUID/
