### ISSUE TITLE
Prefix Tag

### ISSUE THREAD

**Issue by Baerable** [drtshock/Factions#1018]
FactionsUUID version (run `/f version`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

Details:

In chat, if a player does not have a faction the "wilderness" tag appears in front of their name. Is there any possible fix or possibly a %blank_wild% placeholderAPI placeholder? 
I am using DeluxeChat 

Thank you!

**Comment by drtshock** [comment]
There's a factionless tag in the lang.yml. Which placeholder are you using exactly? Because it's unlikely you're using mine.

**Comment by Baerable** [comment]
%rel_factions_relation_color%%factions_role%%factionsuuid_faction_name%
All placeholders for each group ^

**Comment by drtshock** [comment]
The first one isn't me. But yes i think we could add it so it pulls the "factionless" tag from the lang.yml

**Comment by Baerable** [comment]
Great, thanks! Is this currently possible?
