### ISSUE TITLE
Issue with lang.yml

### ISSUE THREAD

**Issue by GeeorgeUK** [drtshock/Factions#1021]
FactionsUUID version (run `/f version`): 
**v1.6.9.5-U0.1.21**

Server software (run `/version`): 
**This server is running CraftBukkit version git-Spigot-4bd94dc-015bda4 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

Server (`logs/latest.log`): 
**A copy of the error thrown that references the first line** https://gist.githubusercontent.com/GeeorgeUK/15daad97ce0294fe423bbb222bd4186b/raw/ca2875b6d069072de1c366354d811c1673f8a69a/unnamed.txt

Details: 
**Attempting to use a modified lang.yml doesn't properly load the file.** The problem is caused by an error message thrown in the console, which references a few lines starting with a % which haven't been given a single quote at the start. These lines are: 152, 153, 235, 238, 239, 244, 245, 246, 384, 545, and 574. Additionally, once these lines have been given appropriate quotes, each entry has no colours, which is caused by the removal of all of the bracketed tags.

–––Edit–––

Interestingly, the language file on GitHub (https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/lang/en_US.yml) is different to the one that is generated by Factions itself.

**Comment by GeeorgeUK** [comment]
Relates to this unanswered issue from 2016 https://github.com/drtshock/Factions/issues/801

Also probably causes these issues from 2016 and earlier https://github.com/drtshock/Factions/issues/710 https://github.com/drtshock/Factions/issues/682 https://github.com/drtshock/Factions/issues/577 https://github.com/drtshock/Factions/issues/405 https://github.com/drtshock/Factions/issues/363

–––Edit–––
Discussed on discord, changing the tags back now. I'll post a gist of a fixed one soon.

**Comment by GeeorgeUK** [comment]
Added gist https://gist.github.com/GeeorgeUK/df8f1e0843efe146ff1103acc1c195c7

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
