### ISSUE TITLE
FactionsUUID Additions

### ISSUE THREAD

**Issue by Inso187** [drtshock/Factions#1025]
/f coleader
adds a co-leader rank. This rank gets /f alert. If you want, I can also make a /f fly add-on for FactionsUUID.
Leader: ***
Co Leader: **
Mod: *
Member: +
Recruit: -

**Comment by drtshock** [comment]
What's /f alert? 

What's special about co leader?

**Comment by Inso187** [comment]
co leader and leader have /f alert and /f lockchat. 
/f alert = a broadcast for the whole faction. It shows the broadcast in the title as well and when you /f alert, it plays a configurable sound.

/f lockchat = locks faction chat

Also add factions coins. With these coins you can do /f perk and buy different perks for your faction. The leaders and co leaders can manage these coins and buy perks. You can buy perks like /f fly or /f pv or something. If you want, you can come onto SaiCoPvP, on the wither realm and do /f perk to see everything you can buy, including /f coins.
