### ISSUE TITLE
Error conf.json

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1027]
FactionsUUID version (run `/f version`): 
**v1.6.9.5-U0.2.0-b46**

Server software (run `/version`): 
**git-TacoSpigot-"fe7806b0" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

Details:
Even after regenerating conf. json, the following settings are not generated.
```
mapHeight
mapWidth
```

**Comment by drtshock** [comment]
Check for https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/Conf.java#L368

Please paste your conf.json if you still don't see it (in a pastebin)

**Comment by drtshock** [comment]
Fixed.
