### ISSUE TITLE
REQ: Allow faction descriptions in chunk boundary messages

### ISSUE THREAD

**Issue by GeeorgeUK** [drtshock/Factions#1028]
**Feature Request**

In old versions of Factions, the message shown when moving between different chunk claims included the description of the plugin. 
Example: https://imgur.com/jndRirW
It would be great for this to be reimplemented!

The current message that is sent contains just two values - the old faction tag and the new one. https://gist.githubusercontent.com/GeeorgeUK/9dc67e1f529f0cc97fe2e632129f5f83/raw/ea8c900760f65b6e824d02b735029df415307c2c/MemoryFPlayer.java

Perhaps two new tags could be implemented, %3$f and %4$f, which contain the descriptions of both the faction that is being entered and the faction that is being exited?

-G

**Comment by mbax** [comment]
Doable in latest.
