### ISSUE TITLE
Faction Void Chests

### ISSUE THREAD

**Issue by Inso187** [drtshock/Factions#1030]
/f voidchest - Admin Command (/f bypass)

/f voidchest is executed by an admin and give them a chest which sells all its contents either in time or when the chest has been right or left clicked. So like the chest either sells all its contents in an 1 hour or so or they just sell when right/left clicked. It will be configurable. We can change how we want the void chest to look. The void chests sells the items that are sell-able in essentials, so this will hook into the Essentials plugin and get all of its sell-able items.

**Comment by Agazed** [comment]
Why would this even need to hook into Factions? Should be an entirely new plugin.

**Comment by Inso187** [comment]
It would be a good addition to FactionsUUID. But I guess i'll look for someone to make this then.
