### ISSUE TITLE
/f who error

### ISSUE THREAD

**Issue by cloakfox** [drtshock/Factions#1031]
FactionsUUID version (run `/f version`): 
v1.6.9.5-U0.2.0-b46
Server software (run `/version`): 
PaperSpigot 1.8.8
Server (`logs/latest.log`):
https://hastebin.com/najabafoze.vbs

**Comment by cloakfox** [comment]
Since this only seems to happen with a certain faction.
here is the factions.json
https://hastebin.com/uwatopofik.json

**Comment by WizzleBear** [comment]
I have had this before. It has something to do with Recruit and Member. For more support (if you bought the plugin), go to the Discord.

**Comment by cloakfox** [comment]
Tried again on build Factions v1.6.9.5-U0.2.1-SNAPSHOT-b52
Same error it seems: https://hastebin.com/tububiwiri.vbs

**Comment by drtshock** [comment]
Fixed in latest dev builds.
