### ISSUE TITLE
/f map coords are inaccurate

### ISSUE THREAD

**Issue by cloakfox** [drtshock/Factions#1032]
FactionsUUID version (run `/f version`): 
Latest and greatest, see my last issue.
Server software (run `/version`): 
See my last issue
Server (`logs/latest.log`):
NaN
Screenshot: https://imgur.com/a/vFudO

**Comment by WizzleBear** [comment]
Coordinates are based on chunk location, not player location. It says you're in the X 100 and Z -134 chunk. This should be obvious. And if you are still confused about the map, gray areas are chunks.
