### ISSUE TITLE
Another error, not sure what causes this though

### ISSUE THREAD

**Issue by cloakfox** [drtshock/Factions#1033]
FactionsUUID version (run `/f version`): 
See my first issue
Server software (run `/version`): 
See my first issue
Server (`logs/latest.log`):
https://hastebin.com/fobagawohe.vbs

**Comment by drtshock** [comment]
Can you tell me what you did that triggered this?

**Comment by cloakfox** [comment]
No idea, I saw it pop up in my console.

**Comment by drtshock** [comment]
kk will take a look. Can you confirm if it works on build 49 or above? I linked the dev builds to you in a pm on spigot.

**Comment by cloakfox** [comment]
Alright this is some error spam in console right now on build 52.
https://hastebin.com/esefonufuf.vbs

**Comment by prosavage** [comment]
getItemInHand method does not exist in ur spigot thing apparently

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
