### ISSUE TITLE
[Suggestions] 

### ISSUE THREAD

**Issue by ItsDomHD-zz** [drtshock/Factions#1036]
**Faction Co-Leader**
Banned (permanent or configurable over *x* amount of time) owner makes the Co-Leader the new owner.
Expanded rank hierarchy

**Unprotected Blocks**
Setting a certain block in the config under this would allow it to be used, altered or mined by anyone no matter the faction.

**Faction Flight**
More and more servers use something like this, used for building and AFKing spawners that are in the air. Disabled when someone is within *x* amount of blocks away from them. Also allow toggling it on for another player.
Can be permission specific.
- factions.fly.own
- factions.fly.wilderness
- factions.fly.safezone
- factions.fly.warzone
- factions.fly.ally
- factions.fly.truce
- factions.fly.neutral
- factions.fly.enemy
- factions.fly.admin (given to staff so they can fly anywhere if needed)

**Faction Stealth**
This can be toggled to stop other players flight being toggled off, can be used for Staff if they're monitoring players in a staff mode thing. Allow this being toggled on for another player too.

**Faction Titled Colors**
Set a players prefix in a faction (/f title) to allow & color codes from Essentials.

**Comment by mbax** [comment]
Most of this is implemented, otherwise handled by other features.
