### ISSUE TITLE
Scoreboard Placeholders

### ISSUE THREAD

**Issue by michelecoco** [drtshock/Factions#1037]
FactionsUUID version (run `/f version`): You are running Factions v1.6.9.5-U0.2.1-SNAPSHOT-b53

Server software (run `/version`): CraftBukkit version git-PaperSpigot-1f7d532 (MC: 1.7.10)

Server (`logs/latest.log`): https://hastebin.com/onohigukir.md

Details:
Placeholders are not replaced in the scoreboard:
https://image.prntscr.com/image/_2AdU81ETVqWxLkIfHstpQ.png
(Yes, I've installed PlaceholderAPI, vault and LuckPerms expansions)

**Comment by drtshock** [comment]
This was fixed recently after your ticket was made.
