### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Baerable** [drtshock/Factions#1039]
FactionsUUID version (run `/f version`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

Details:

All regular members on my servers can use the command /f sethome , whereas the faction moderators cannot. Moderators of factions are unable to kick players and use commands they should be able to. Is there any way to edit the permission nodes? Thank you

**Comment by Baerable** [comment]
Nevermind - just saw the build posted on 2/12. Still wondering if permission editing is possible, though. Thanks :)

**Comment by drtshock** [comment]
Issue fixed. And yes with /f perm
