### ISSUE TITLE
FactionsUUID scoreboard is not work.

### ISSUE THREAD

**Issue by ArchieWasTaken** [drtshock/Factions#1040]
FactionsUUID version (run `/f version`): Factions v1.6.9.5-U0.1.21

Server software (run `/version`):  CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Server (`logs/latest.log`): 
[Log.log](https://github.com/drtshock/Factions/files/1732268/Log.log)
I did edit it to take out my IP just so you know

Details: The scoreboard will not come up. It only comes up for a split second if I reload. (I know reloading is not the best for a server)

**Comment by WizzleBear** [comment]
The scoreboard is kind of confusing to most, so hop on the Discord support server and you can probably figure out how to use it. If you don't like it, I recommend NameTagEdit and TitleManager for the scoreboard and tablist. For placeholders, get PlaceholderAPI.

**Comment by ArchieWasTaken** [comment]
I am already on the discord server. Do the placeholders work in other plugins? I already have placeholderapi and nametagedit :)

**Comment by WizzleBear** [comment]
For PlaceholderAPI, only specific plugins can accept the placeholders. If you go to https://www.spigotmc.org/wiki/placeholderapi-compatible-plugins/ it will tell you all the plugins that accept the placeholders in PAPI.

**Comment by ArchieWasTaken** [comment]
ok thank you :)
