### ISSUE TITLE
F map error

### ISSUE THREAD

**Issue by Baerable** [drtshock/Factions#1041]
FactionsUUID version: U0.2.1-SNAPSHOT-b54 (used 3 previous versions as well, none worked)

Server software: git-spigot-21fe707-e1ebe52 (MC 1.8.8)

Server: Latest log was empty, however when I restarted the server I did not see any errors relating to Factions.

Details:

When I click to claim in the f map, it claims the chunk, however the map never updates. Also, for some players, the map is bugged and it shows nothing, however for others (with the same permission nodes) it works.
I have already tried removing all files and reloading the server, however the f map still doesn't work for some players.
https://i.imgur.com/Bd95S7J.png
Thank you! :)

**Comment by drtshock** [comment]
Why did you just ignore the information that the template asked you for? I ask it for a reason. Please fill it out.

**Comment by Baerable** [comment]
Fixed, sorry. Didn't think it was needed because I tried different versions, should have added that in my issue.
