### ISSUE TITLE
F Top (Dependency?) Issue

### ISSUE THREAD

**Issue by Baerable** [drtshock/Factions#1042]
FactionsUUID version (run `/f version`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

Details:

https://i.imgur.com/eFPShMO.png
Not sure if this is an error with this plugin's dependency or just an error with novuc's f top, however if I type "/f top," novuc's f top shows. But if I type "f top 2" this shows.
Is there any way to disable the f top? Not sure if this is something built into FactionsUUID.
Or is this an issue completely unrelated to FactionsUUID?

Thank you :)

**Comment by drtshock** [comment]
Yes we have an f top command. Looks like theirs is interfering.

**Comment by Baerable** [comment]
Okay, I will contact them. Thanks
