### ISSUE TITLE
Suggestion: PremiumVanish Support

### ISSUE THREAD

**Issue by QualityNodeNet** [drtshock/Factions#1049]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.2.1-SNAPSHOT-b56

Server software (run `/version`): CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Server (`logs/latest.log`): Nil

Details: Add PremiumVanish support, they have a nice API this way people can't see Staff through commands such as /f who as they show up as "online".

**Comment by drtshock** [comment]
I'm thinking we could make this happen by just checking if the player "can see" the target player using the bukkit api.

**Comment by drtshock** [comment]
There we go. Thanks for the suggestion.
