### ISSUE TITLE
Bug when... i log/move/mobmove... ewh

### ISSUE THREAD

**Issue by Miaourt** [drtshock/Factions#105]
https://gist.github.com/Technowix/f08e46b98a4a1d836001
:) but the plugin won't crash !.... good new ?

**Comment by drtshock** [comment]
Can you give us steps to reproduce this? We had someone else report it but we have no idea how it comes about. The line it points to doesn't help much.

**Comment by Miaourt** [comment]
I use the latest spigot version (patch)  on a fresh server (nothing on) and
i got that just after I log in ^^!

**Comment by drtshock** [comment]
Yes but how would I reproduce this with a fresh server? And on u0.1.9?

**Comment by Miaourt** [comment]
Like is say ?... When people log on the server... they give the first error
in my log... (look at the time..?) And after, if i move, second error ._.
etc etc

2014-11-01 22:07 GMT+01:00 Trent Hensler notifications@github.com:

**Comment by drtshock** [comment]
On a fresh server?

**Comment by Miaourt** [comment]
Yes, a server with nothing on it (from my side) the plugin just generated
his config/ world are totally new :')
