### ISSUE TITLE
Permissions so broken

### ISSUE THREAD

**Issue by Agazed** [drtshock/Factions#1050]
When you set a perm for a certain relation, it sets that perm for all relations.

Also, converting from old data, players cannot set perms in their existing factions.

No idea why you reverted https://github.com/drtshock/Factions/commit/9f8c2e3905dee5cb4ae1b8b918b94d416bd7b160 instead of fixing the issue.

**Comment by drtshock** [comment]
Because that commit was breaking the permissions maps for Factions and causing data to get fucked up.

You ignored the issue template so I have no idea which build you are on.

**Comment by Agazed** [comment]
Have you even tested it? I'm on the latest with a clean install.
