### ISSUE TITLE
Incorrect Placeholder - b56

### ISSUE THREAD

**Issue by QualityNodeNet** [drtshock/Factions#1055]
FactionsUUID version (run /f version): v1.6.9.5-U0.2.1-SNAPSHOT-b56

Server software (run /version): CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Server (logs/latest.log): Nil

Details: When you do /f show with the default config it shows https://image.prntscr.com/image/ecLgJO-gSVSfHfrytPkovg.png ({player-balance} however that placeholder is outdated and is now just {balance}

**Comment by GrizzsChannel** [comment]
Make it a pull request. Imma fix right now, so hold your horses.

**Comment by drtshock** [comment]
Thanks for pointing out.
