### ISSUE TITLE
Tags for VentureChat/HeroChat missing

### ISSUE THREAD

**Issue by Fortepsai** [drtshock/Factions#1056]
I have tried all the options for Tags and non of them were working. Please fix this issue  and update your manual . There are others plugin for free and have way better manual than UUID FACTIONS .

**Comment by drtshock** [comment]
What exactly is your issue?

Also, what's your spigot name?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
