### ISSUE TITLE
Chat error

### ISSUE THREAD

**Issue by cloakfox** [drtshock/Factions#1059]
Factions version: [Factions] You are running Factions v1.6.9.5-U0.2.1-SNAPSHOT-b56
Error: https://pastebin.com/1tQG88z4
PaperSpigot 1.8.8

**Comment by cloakfox** [comment]
Downgrading to build 46 did not fix the issue. (same error)

**Comment by drtshock** [comment]
Yeah an issue of the role being null for w/e reason. Updating should fix it.
