### ISSUE TITLE
Could not pass CreatureSpawnEvent

### ISSUE THREAD

**Issue by xDacon** [drtshock/Factions#106]
Console being spammed with: http://hastebin.com/efituwoloj.avrasm

**Comment by Kakifrucht** [comment]
Are you running any other plugins working with CreatureSpawning, maybe spawning unrecognized entities leading to NullPointers?
I'm running the latest version and am not getting any Exceptions.

**Comment by xDacon** [comment]
This error happens when there are no plugins on the server

**Comment by drtshock** [comment]
Then clearly it's not factions.
