### ISSUE TITLE
Removing brackets

### ISSUE THREAD

**Issue by Inso187** [drtshock/Factions#1060]
How do you remove the [] from players that are not in a faction? 
https://imgur.com/a/0m3xg

**Comment by drtshock** [comment]
which chat plugin are you using and what does your chat config look like? I'm guessing you have it [[FACTION]] meaning the outside brackets will always be there, and can't and won't be changed by us.

**Comment by Inso187** [comment]
I'm using Essentials chat section in its config.

**Comment by Baerable** [comment]
The brackets are not a part of the placeholder. You manually added the brackets for the prefix.
This is not something to do with Factions, and it's a simple fix - just remove the brackets lol
