### ISSUE TITLE
Small Suggestion: Blank WIlderness Placeholder?

### ISSUE THREAD

**Issue by Baerable** [drtshock/Factions#1061]
FactionsUUID version (run `/f version`): Just a feature request :)

Server software (run `/version`): Just a feature request :)

Server (`logs/latest.log`): Just a feature request :)

Details:

Wilderness shows up as "Wilderness" in chat. I've seen some other plugins use a %factions_faction_name_blank% placeholder (basically, Wilderness wouldn't show as a prefix).
I'm guessing the reason it shows up as "Wilderness" for me is because I'm not using luckperms, however it would take too long to switch over. 

Thanks :)

**Comment by drtshock** [comment]
Which chat plugin are you using and what's the configuration?

**Comment by Baerable** [comment]
Deluxechat. I tested it out, and this is the permission node that shows Wilderness: %factionsuuid_faction_name%
