### ISSUE TITLE
Small Suggestion

### ISSUE THREAD

**Issue by Baerable** [drtshock/Factions#1066]
FactionsUUID version (run `/f version`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

Details:

Option in config to remove the built in /f top? I have a plugin that handles it, however it's battling with the built in FactionsUUID one.

Thanks!

**Comment by drtshock** [comment]
What's the plugin?

**Comment by Baerable** [comment]
I'm using /f top | Factions Top by Novucs. I want this plugin to handle the f top, and it does for /f top, but if you type /f top 2, FactionsUUID's built in f top is show.

**Comment by drtshock** [comment]
If you grab dev build 80 or higher, the FactionsUUID /f top command will not be registered as to let FactionsTop take full control.
