### ISSUE TITLE
f sethome

### ISSUE THREAD

**Issue by ValhallaAdmin** [drtshock/Factions#1073]
FactionsUUID version (run `/f version`): Latest

Server software (run `/version`): 1.8.8 (with ViaVersion)

Server (`logs/latest.log`):

Details: f sethome doesnt work for anyone but ops. I tried adding the permission node for it but still nothing. No "error no perms" message or nothing. Just a blank space and simply nothing happends when you do it. PLEASE FIX!

**Comment by drtshock** [comment]
Latest isn't a version. Please fill out the info that we asked for, including your server logs.

Also - what's your spigot username?

**Comment by nestormaldonado** [comment]
I've the same error, i use 1.6.9.5-U0.2.0-b46 and my name in SpigotMC is Jeruhmi

**Comment by drtshock** [comment]
This issue is fixed in dev builds.
