### ISSUE TITLE
Faction Sethome issue

### ISSUE THREAD

**Issue by AmazedMender16** [drtshock/Factions#1077]
Factions v1.6.9.5-U0.2.1-SNAPSHOT-b90
CraftBukkit version git-Spigot-4bd94dc-f4ca180 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

When trying to set a home in your factions you get a message that you can set a home in another faction
http://prntscr.com/ioll1u

**Comment by dariasc** [comment]
I believe I know the reason for this, I'll open a PR tonight

**Comment by RzSquaD** [comment]
I have this probleme, only the member of your faction can /f sethome

**Comment by drtshock** [comment]
Fixed in build 91
