### ISSUE TITLE
Chest-Door Can be open in territory

### ISSUE THREAD

**Issue by RzSquaD** [drtshock/Factions#1080]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.2.0-b46

Server software (run `/version`): CraftBukkit version git-Spigot-0359393-9cd1111 (Mc 1.8.8)

Hi !
I have got a problem,
I can open chest/door on any territory, my config is done.
Config: https://pastebin.com/SkiH759V

Have a nice day ;)

**Comment by Crusby** [comment]
Which type of door ? Spruce_door or something like that ?

**Comment by RzSquaD** [comment]
Normal door and chest simple chest, double chest ect

**Comment by RzSquaD** [comment]
UP !

**Comment by drtshock** [comment]
This is resolved on newer builds.
