### ISSUE TITLE
Dynmap colors not applying

### ISSUE THREAD

**Issue by KyroOW** [drtshock/Factions#1088]
The dynmap colors doesn't seem to be applying for SafeZone and Warzone (player created factions does seem to work though)

Here is the default settings:
https://i.imgur.com/Q9hl8N9.png

Result:
https://i.imgur.com/0P87HDt.png

According to the config file default settings, Safezone should be Pink (FF00FF) and Warzone Red (FF0000)

EDIT: It also seems that the faction homes doesn't appears at all on the dynmap (tried various things, never got the little flag icon to show up on the dynmap.)

**Comment by drtshock** [comment]
We'll fix this after the current release.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
