### ISSUE TITLE
Dynmap support ?

### ISSUE THREAD

**Issue by Miaourt** [drtshock/Factions#109]
Hey !
For some idea, that could be cool to see a out-of-the-box dynmap support from faction uuid ! :p
Also, what version of "faction dynmap" plugin we should use ? As of this faction are based on 1.6.9 version...?

**Comment by drtshock** [comment]
No idea, I've never looked at dynmap. I'll see what it would take for integration.

**Comment by drtshock** [comment]
Curious as to why you'd want this though? Doesn't that sorta defeat the purpose of raiding servers?

**Comment by Miaourt** [comment]
This is really a plus, i don't want to have a hinding/finding only, build
real defences could be great.

**Comment by drtshock** [comment]
Added!

**Comment by Miaourt** [comment]
Thx <3 this is on the main thread or nope ?

**Comment by drtshock** [comment]
Some of it is, some of it isn't.
