### ISSUE TITLE
Issues with /f fly

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#1090]
first issue: only the leader of the faction can use /f fly by default, not mods/officers whatever they are called or lower. All people in a faction should be able to use it if the perms are undefined

second: you are able to continue to fly after starting to fly in a claimed chunk, and then unclaiming it.

**Comment by PhanaticD** [comment]
also if you do the command right before you teleport you can keep flying, players have been able to fly in my spawn doing that

**Comment by drtshock** [comment]
Forgot to tag in the commit but added https://github.com/drtshock/Factions/commit/a4581ac9a04de660a4e5f5fed4ad19993f55bc0b
