### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by WizzleBear** [drtshock/Factions#1091]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.2.1-SNAPSHOT-b94

Server software (run `/version`): git-Paper-1349 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`): 

Details: The "click to claim" thing on the /f map is so buggy you should just remove it, unless you already did or fixed it. I click to claim a chunk next to me, then 5 chunks away is the claim.

**Comment by drtshock** [comment]
Temp disabled https://github.com/drtshock/Factions/commit/760f16a2b797c78dc39bec0fd141bd5ed7e18e66
