### ISSUE TITLE
Problem with Slimefun and LockettePro

### ISSUE THREAD

**Issue by RK96** [drtshock/Factions#1092]
FactionsUUID version 1.6.9.5-U0.2.0-b46 

Server software (run `/version`): CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12)

I have this problem, big broblem, can you help me?

[error.txt](https://github.com/drtshock/Factions/files/1823312/error.txt)

**Comment by WizzleBear** [comment]
Not a FactionsUUID problem

**Comment by DoNotSpamPls** [comment]
With Slimefun's codebase, I'm not suprised. lol

**Comment by drtshock** [comment]
This is their fault for not handling multiple versions of Factions.
