### ISSUE TITLE
{total-online} placeholder counting vanished players

### ISSUE THREAD

**Issue by KyroOW** [drtshock/Factions#1093]
FactionsUUID version: Factions v1.6.9.5-U0.2.1-SNAPSHOT-b96

When using the {total-online} placeholder in the built in scoreboard of the plugin, vanished players are still being counted

https://i.imgur.com/EM7ZJ1a.png

(Screenshot was taken on the other player side, Frank.)
(En Ligne is for Online Players in the scoreboard)

**Comment by CmdrKittens** [comment]
Added `{total-online-visible}` for 0.5.1 release
