### ISSUE TITLE
F map crash

### ISSUE THREAD

**Issue by GetMullered** [drtshock/Factions#1097]
FactionsUUID version (run `/f version`): 
https://i.gyazo.com/thumb/1200/b0fa65dd777162ec333d9439df3223f1-png.jpg

Server software (run `/version`): 
https://gyazo.com/9374c38a196b60be8425fa386614e595

Server (`logs/latest.log`):
20.03 13:28:46 [Server] INFO UUID of player Customm is a881cf87-e0b5-4429-a2b4-cd62de000f9c
20.03 13:28:46 [Connect] User Customm, IP 94.12.35.172
20.03 13:28:46 [Multicraft] Customm ran command Message of the Day
20.03 13:28:53 [Server] INFO Customm issued server command: /version
20.03 13:29:10 [Server] INFO CONSOLE issued server command: /list 
20.03 13:29:10 [Server] INFO Default: Customm
20.03 13:31:10 [Server] INFO Customm issued server command: /f map
20.03 13:31:11 [Server] ERROR io.netty.handler.codec.EncoderException: String too big (was 29918 bytes encoded, max 32767)
20.03 13:31:11 [Server] ERROR io.netty.handler.codec.EncoderException: String too big (was 29918 bytes encoded, max 32767)
20.03 13:31:11 [Server] ERROR io.netty.handler.codec.EncoderException: String too big (was 29918 bytes encoded, max 32767)
20.03 13:31:11 [Server] ERROR io.netty.handler.codec.EncoderException: String too big (was 29918 bytes encoded, max 32767)
20.03 13:31:11 [Server] ERROR io.netty.handler.codec.EncoderException: String too big (was 29918 bytes encoded, max 32767)
20.03 13:31:11 [Server] ERROR io.netty.handler.codec.EncoderException: String too big (was 29918 bytes encoded, max 32767)
20.03 13:31:11 [Server] ERROR io.netty.handler.codec.EncoderException: String too big (was 29918 bytes encoded, max 32767)
20.03 13:31:11 [Disconnect] User Customm has disconnected, reason: Disconnected
20.03 13:31:11 [Server] INFO Customm left the game.
Details:

**Comment by GetMullered** [comment]
https://gyazo.com/bca9004dbd1bcfce45c439ac402875bf

**Comment by GetMullered** [comment]
https://timings.aikar.co/?id=50a5a9c782e946548909dbd86ca3d512. I swear Factions is lagging my server also

**Comment by drtshock** [comment]
What version is your client?

**Comment by GetMullered** [comment]
1.8.8

**Comment by drtshock** [comment]
Can you give me your conf.json, board.json and factions.json please? Feel free to pm on discord if you don't want to post publicly.

**Comment by drtshock** [comment]
Still waiting on more info. Anyone else have this same issue that can bump / add more info?

**Comment by luwie556** [comment]
Haven't gotten this issue i don't really know what he did to cause his server to crash could you give me the commands you typed to cause the crash

as you are on an outdated version of FactionsUUID update to the latest version and try it again  and you should be okay but when doing so make sure that you backup your factions folder just incase.

**Comment by GetMullered** [comment]
I'm on the latest build already still happens, players can also all spam /f map at the same time and my whole server crashes xd
