### ISSUE TITLE
Config bug

### ISSUE THREAD

**Issue by WizzleBear** [drtshock/Factions#1098]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.2.1-RC-b98

Server software (run `/version`): git-Paper-1357 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`):

Details: If you add `{offline-list}` to this `&7Offline &c({offline}&c&l/&c{members}) &8&l»`, the » and / become white.

**Comment by drtshock** [comment]
Screenshot and expected output?

**Comment by WizzleBear** [comment]
![](https://s7.postimg.org/hnecfsw63/Screen_Shot_2018-03-29_at_8.42.13_PM.png)
White areas are supposed to be gray

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
