### ISSUE TITLE
Faction tag land notifications not appearing

### ISSUE THREAD

**Issue by Hobby-boy** [drtshock/Factions#11]
In the older version of this plugin, I'm certain that when you logged into the server, it would notify you whether it was safezone/warzone/wilderness or a factions land, but that notification hasn't been coming up on a server I use which is running this fork of the plugin.

**Comment by Hobby-boy** [comment]
I've just setup my own test server with Spigot 1.7.9 and the latest build of factions, and the notifications aren't coming up even though 
  "ownedMessageOnBorder": true,
  "ownedMessageInsideTerritory": true,
  "ownedMessageByChunk": true,
are all set to true in the config.
However, with the older version from bukkitdev, the notifications do come up.

**Comment by roastnewt** [comment]
@drtshock 
This seems to be the responsible line of code:

https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/listeners/FactionsPlayerListener.java#L93

It always sets changedFaction to false, so lines 102-116 never execute.

**Comment by drtshock** [comment]
Fixed. http://git.io/D9mlZQ
