### ISSUE TITLE
Mutes are bypassed with factions using BanManager's Mute functions.

### ISSUE THREAD

**Issue by Leopere** [drtshock/Factions#110]
https://imgur.com/jYTwGkv

**Comment by Leopere** [comment]
Ticket as reported by one of my mods:

Muted people are able to use faction ally chat.

Not sure if its a big issue, however muted people still have access to /f chat ally & can continue to speak through those means. It does tell them that they are muted and such, but the messages still go through.
I used my alts to test this, and can provide proof here:
http://puu.sh/bqXx6/28093636ee.png http://puu.sh/bqXyg/b457a3f59b.png

**Comment by drtshock** [comment]
Yes I'm aware of this. It's how this plugin handles chat. It cancels the event in the case of ally / faction chat instead of modifying the recipients list. The entire chat system really needs a complete rewrite.

**Comment by squidicuzz** [comment]
That is why it did get a rewrite in future versions...

**Comment by drtshock** [comment]
Duplicate of #100
