### ISSUE TITLE
title issue

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#1101]
using 1.8.8 and factions as of https://github.com/drtshock/Factions/commit/20cd874026af384f35097ef2c41b7043ba34c90a

players can put characters like a comma in their title which can fake list players in your faction for example anyone could set their title as"
```
    "title": "PhanaticD,",
```
and make it look like i am in their faction, maybe need a regex check for allowed characters or something

**Comment by drtshock** [comment]
Still happening on newer builds? Also can you post a screenshot of what you mean?

**Comment by PhanaticD** [comment]
https://i.gyazo.com/2176fea877c326a04f44a7d0f5733069.png

I am not on the very latest, but nothing code wise has changed for touching this I dont believe

**Comment by drtshock** [comment]
Which characters do you think we should deny? All I'm seeing is a line where someone changed their title to something that includes a comma and a space.

**Comment by PhanaticD** [comment]
id say deny comma

**Comment by drtshock** [comment]
Sure.. Fixed in next release.
