### ISSUE TITLE
Warzone Claim Issues (TacoSpigot)

### ISSUE THREAD

**Issue by xxJinxedxx** [drtshock/Factions#1102]
**FactionsUUID version (run `/f version`):** v1.6.9.5-U0.2.1-RC-b97

**Server software (run `/version`):** git-TacoSpigot-"bf023c7d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Server (`logs/latest.log`):** https://hastebin.com/ocawuyiyez.vbs

**Details:** Having some issues when autoclaiming warzone. The error above shows the error console message. And after checking with _"/f map"_ the warzone looks like a swiss cheese. I'm not sure what has the title thing to do with claiming warzone tho...
![image](https://user-images.githubusercontent.com/13562136/37691605-ba7528da-2cbb-11e8-85be-11a1adb66f02.png)

**Comment by drtshock** [comment]
Fixed.
