### ISSUE TITLE
Feature Request: faction fly disable near enemies

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#1103]
using 1.8.8 and factions as of https://github.com/drtshock/Factions/commit/20cd874026af384f35097ef2c41b7043ba34c90a

I would like to request that faction fly be disabled when a player is in a configurable radius to enemies, and should probably have a warning of like 5 seconds before it gets turned off so they can land safely

**Comment by drtshock** [comment]
I'd assume that it'd just take them out of fly but negate any fall damage? Or perhaps warn at x blocks away, and take away at y (which is lower than x) blocks away.

**Comment by PhanaticD** [comment]
that could work too, but if they enderpearl or teleport you wouldnt really get any warning time is a flaw with that method

**Comment by xxJinxedxx** [comment]
Keep the notification, just when the enemy is in the range where the fly will get disabled it will show to the flying player that after "x" amount of seconds the fly will be disabled if he is still in the range of his enemy.
Maybe even add a placeholder or plain hardcoded one for the range that the enemy is in the message?
This way it will work both with and without the e-pearl in the equation.

**Comment by drtshock** [comment]
Added in build 103
