### ISSUE TITLE
Permission Nodes...

### ISSUE THREAD

**Issue by EmanuelSimard** [drtshock/Factions#1104]
https://github.com/drtshock/Factions/wiki/Commands

I found the permission nodes.. 

Tried the followings using Luck Perms..

/lp group Default permission set [nodes] 

but for some reason it isn't working... o_O?

factions.permissions factions.mod together don't work for players being able to promote each other as admin of the Faction.

**Comment by drtshock** [comment]
You ignored the issue template ._. Please fill it out.

Please also check with luckperms to check to see if the user has the command you're attempting to use.
