### ISSUE TITLE
Faction Fly unclaim bug

### ISSUE THREAD

**Issue by WizzleBear** [drtshock/Factions#1109]
FactionsUUID version (run `/f version`): Build #101

Server software (run `/version`): Paper Spigot 1.12.2

Server (`logs/latest.log`):

Details: Enable /f fly, fly into the air, unclaim land, and you can fly around anywhere.

**Comment by dariasc** [comment]
I'll get to this in a few hours, good catch

**Comment by drtshock** [comment]
Fixed
