### ISSUE TITLE
Enemy Relations reveals vanished players.

### ISSUE THREAD

**Issue by Leopere** [drtshock/Factions#111]
As reported by my moderators:
As title says, on factions 1 if a staff member is enemies with someone they are watching, if said player tries to f home they cant due to the mod being an enemy and blocking the tp, thus revealing to the player that they are being monitored, which is something they obviously shouldn't know or be told about.

**Comment by drtshock** [comment]
This is likely a bug that's been present for a long time, not anything to do with our code. We'll just hook into essentials to check if a nearby player is vanished or not.
