### ISSUE TITLE
/f vault bug

### ISSUE THREAD

**Issue by WizzleBear** [drtshock/Factions#1113]
FactionsUUID version (run `/f version`): Builds #101

Server software (run `/version`): Paper Spigot 1.12.2

Server (`logs/latest.log`): 

Details: Error when trying to open vault: https://hasteb.in/agazadag.avrasm

**Comment by drtshock** [comment]
Can you give me your /version playervaults as well please?

**Comment by WizzleBear** [comment]
4.0.4. Accidentally closed it XD
