### ISSUE TITLE
Error: /f banlist <faction>

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1115]
FactionsUUID: **Factions v1.6.9.5-U0.2.1-RC2-b100**

Version: **Paper** version git-Paper-1342 (MC: 1.12.2) (Implementing API version **1.12.2-R0.1-SNAPSHOT)**

I found a bug with the new command /f banlist
I'm in the "test" faction. When I enter the command"/f banlist", I receive the message related to the banned list. But when I enter the command"/f banlist TEST123" for example (faction that does not exist), I receive an internal error.

Error: https://pastebin.com/vM9T4kcA

**Comment by drtshock** [comment]
Fixed, thanks.
