### ISSUE TITLE
Plugin addons

### ISSUE THREAD

**Issue by jboss23** [drtshock/Factions#1118]
Taking a look into SavageFactions plugin we can take a few great ideas for a better plugin! Here us one:
Name: Clickable f map
What do they do: Allows players to claim land by just clicking on the f map
Command: /f map
Notes: Add Description to claimed lands and make right click claim/left click unclaim/middle click enemy the faction. I dont know you can go wild :P
https://imgur.com/a/Khl4G

**Comment by drtshock** [comment]
They pulled clickable f map from this repo.
