### ISSUE TITLE
overpaying faction bank with essentials balance cap causes money loss

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#1119]
title pretty much says it all, if you deposit money into your factions bank that goes over the essentials bal cap it just disappears instead of denying the transaction

**Comment by drtshock** [comment]
Can you please give me the info in the issue template as well as the server log of this happening with /ess debug enabled?

**Comment by PhanaticD** [comment]
[19:12:21] [Server thread/INFO]: PhanaticD issued server command: /f money d 50000000
[19:12:21] [Server thread/INFO]: [Factions v1.6.9.5-U0.2.1-RC2-b${build.number}] PhanaticD deposited 50,000,000 in the faction bank: the

after this bal shows $0 and f money bal shows $300021 which is what I had before

essentials config bal cap is 50000000

nothing shows up from essentials with debug on

**Comment by PhanaticD** [comment]
using 1.8.8

**Comment by drtshock** [comment]
Since you're using essentials eco, I need the ess debug log so I can see what the fuck essentials is doing with money (yes i know that's my plugin too but still :D)

**Comment by drtshock** [comment]
Resolved in https://github.com/drtshock/FactionsUUID/commit/916d1748555f07c9f2b42cee176ccbf41ab4b5fa
