### ISSUE TITLE
/f perm bug

### ISSUE THREAD

**Issue by AmazedMender16** [drtshock/Factions#1121]
FactionsUUID version (run `/f version`): 
b100
Server software (run `/version`): 
Spigot 1.12.2

if I change anything in /f perms the chat said I changed it, but when I check it it is undefined.

**Comment by drtshock** [comment]
Can you give me your server log as well as your factions.json please?

**Comment by AmazedMender16** [comment]
https://pastebin.com/8nVAnd8X

**Comment by luwie556** [comment]
I checked on a latest build of FactionsUUID which it didn't do what you described for mine, have you tried to update your factions? 

If you do make sure to backup your Factions folder before doing so.

**Comment by AmazedMender16** [comment]
Have had a talk with @dariasc on discord PM send him my files he doesnt know whats up aswell. This is still happening on b112

**Comment by drtshock** [comment]
Was this a faction created before the initial perm update? If so, can you try disbanding, recreating, and see if it still happens?

**Comment by AmazedMender16** [comment]
Yeah they were created before the perm update. There is no way with it getting to work without recreating the faction?

**Comment by drtshock** [comment]
This is an edge case that I haven't been able to figure out, and that's the only workaround that I currently know about :\

**Comment by AmazedMender16** [comment]
I was aware of this worldaround. but im not quite sure if my players will like to reset their entire factions..

**Comment by AmazedMender16** [comment]
This is still an issue on build: 122

**Comment by Drc-DEV** [comment]
Still an issue on build 122

**Comment by CmdrKittens** [comment]
This may be resolved in 0.5.0 (testing, then release soon) which converts stored perms data (and thus should either wipe bugged data or migrate what it can)
