### ISSUE TITLE
New Feature Suggestion | Officer Chat

### ISSUE THREAD

**Issue by luwie556** [drtshock/Factions#1124]
Officer Chat is a new chat mode which is obvious by the title but pretty self explanatory you have to go and  enter the officer chat mode which allows Moderators, Co-Leaders and Leaders in the chat mode.

But if wanted you could add a permission in /f perm where you can allow or disallow certain roles to access it.

**Comment by Dariasc** [comment]
I believe ProSavage implemented a mod/officer chat where officer+ can see and talk in it

**Comment by luwie556** [comment]
I haven't seen it around but i could be wrong but is it a third party thing or?
I mean it could just be nice to go and have it in the main build and things like that.

**Comment by drtshock** [comment]
You can do /f chat mod https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/cmd/CmdChat.java#L39 in FactionsUUID.
