### ISSUE TITLE
Faction Rank Reset on Player forced into a faction.

### ISSUE THREAD

**Issue by luwie556** [drtshock/Factions#1129]
Factions Version: Build 1.12
Spigot Ver; 1.8.8 (with back compat to 1.7.x)

Issue:
When you force a player into a faction with /f bypass enabled (// player is opped) and you use /f join <faction> <playerName>
You will have them join the faction but the leader will be set to default member (or default join rank set via config)

f show before: 
![image](https://user-images.githubusercontent.com/21987927/37926292-f629656a-3104-11e8-8c89-98751bf211d1.png)

f show after: 
![image](https://user-images.githubusercontent.com/21987927/37926361-25ce0082-3105-11e8-8da0-dbe27fb00bed.png)

**Comment by drtshock** [comment]
Thanks, we were setting the role for the player executing the command, not the player joining the Faction. Quick 1 line fix that will be in the next release :)
