### ISSUE TITLE
WorldGuard /f claim Issues

### ISSUE THREAD

**Issue by Robustian** [drtshock/Factions#113]
https://gist.github.com/Robustian/684f39fd839a0e5f1408

07.11 22:28:55 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/List;)Ljava/util/List;

**Comment by Robustian** [comment]
Issue is with WorldGuard 6.x, and since it is currently in Beta, issue closed.

**Comment by drtshock** [comment]
Yeah, we don't support it yet as I've heard people tell me it's not very stable. We'll add support once they have a proper release.
