### ISSUE TITLE
Suggestion | MySQL Data Storage Option

### ISSUE THREAD

**Issue by luwie556** [drtshock/Factions#1132]
As said in the title it would have an option to go store information into a MySQL database so that the server would lose some load from reading/writing from json files.

With the faction chat logs as I've always wanted to have an option to also go and have that in a MySQL  database just so that you can have easier access of reading certain logs of certain factions or players just incase something comes up with that specific person or faction.

**Comment by drtshock** [comment]
Yes would be nice :( just lots of work.

**Comment by ImNachoMans** [comment]
+1

**Comment by drtshock** [comment]
You can react to suggestions instead of +1'ing them. Easier to see how many people are voting for it :)

**Comment by ThatWills** [comment]
+1

**Comment by Blamo27** [comment]
@drtshock This feature could be awesome!

**Comment by Momonche** [comment]
Very awesome ! Maybe for multiserversbungeecordfactionawesome :O

**Comment by Blamo27** [comment]
@drtshock I give you the power to develop this feature
༼ つ ◕_◕ ༽つ DRTSHOCK TAKE MY ENERGY ༼ つ ◕_◕ ༽つ
