### ISSUE TITLE
Error: EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1137]
FactionsUUID: Factions v1.6.9.5-U0.2.2-b112

Server software: Paper version git-Paper-1363 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Error: https://hastebin.com/baxirilici.vbs

Hello,
I just got this error. Nothing too bad for me to understand, but it's better to take a look.

Thanks,

**Comment by drtshock** [comment]
Unfortunately this error doesn't give us anything to go on. Can you please re open when you can give us the full server log?
