### ISSUE TITLE
/f owner broken

### ISSUE THREAD

**Issue by spongetabilous** [drtshock/Factions#1138]
Latest Factions UUID ver (b112), PaperSpigot 1.8.8.
Issue: Build perms given to anyone including members/recruits via /f perms bypasses owner-ed claims, many complaints from players stating they got insided.
No issues or logs, but here is the video:
https://gaming.youtube.com/watch?v=s00iY5ilE7Q&feature=share

**Comment by drtshock** [comment]
Thanks for calling out. I updated the check to look for owned claims BEFORE it looks for f perms.
