### ISSUE TITLE
Error: Unhandled exception executing command

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1139]
FactionsUUID: Factions v1.6.9.5-U0.2.2-b112

Server software: Paper version git-Paper-1363 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Error: https://hastebin.com/azumohehid.vbs

Thanks to fix this error.

**Comment by dariasc** [comment]
Duplicate of #1128

**Comment by drtshock** [comment]
Fixed in latest release.
