### ISSUE TITLE
AutoMatic Perms/fly

### ISSUE THREAD

**Issue by TheBigDude5** [drtshock/Factions#1145]
FactionsUUID version (run `/f version`): 
Factions V1.6.95-U02.2-b116
Server software (run `/version`): 

Server (`logs/latest.log`):

Details:
Hello. I am requesting a Feature which will be super usefull. You can set In factions.json
You can change UNDEFINED to ALLOW/DENY this will make it so when you create a faction there are already perms for the faction. Also the other thing is with fly is you can set it so you can as soon as you walk into your land it will automatically enable flight!

**Comment by dariasc** [comment]
@drtshock This would go hand in hand with the perm system overhaul?

**Comment by mbax** [comment]
Closing this issue as permissions have been completely rewritten
