### ISSUE TITLE
Converting Old Data and UUID Problem

### ISSUE THREAD

**Issue by ygtdmn** [drtshock/Factions#1147]
FactionsUUID version (run `/f version`): 
Build 119 (i can't check because plugin don't load.)

Server software (run `/version`): 
TacoSpigot 1.8.8 build 29

Server (`logs/latest.log`):
https://pastebin.com/mSTZ5QGy

Details:
I'm running a cracked server for a long time. I was using the old Factions 1.6.9.5 but it is time to update since it has a lot of bugs. Then i found this plugin and download latest test build for testing.

It tried to convert my players to UUID system but it exceed rate limit. But since my server is not online mode server it doesn't necessary. Just create offline uuids. It won't try to connect mojang and it wont exceed the rate limit. Also it will solve UUID related problems for offline mode servers.

I will buy plugin if the problem is solved.

Thanks.

**Comment by WizzleBear** [comment]
You'll get support once the plugin is bought. 😄

**Comment by ygtdmn** [comment]
If i buy the plugin in this state it'll be worthless to me.

**Comment by WizzleBear** [comment]
Not much we can do. 🤷‍♂️

**Comment by ygtdmn** [comment]
Lets see what @drtshock will say.

**Comment by drtshock** [comment]
Not going to add anything to support offline servers.
