### ISSUE TITLE
Use titles on territory enter

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#115]
Just like how we use scoreboards instead of chat, we should add the option for titles (mc 1.8 feature).

**Comment by drtshock** [comment]
This would require me to either put a spigot jar in the repo to allow others to compile or force others to find a spigot jar to compile it. Will revisit this once 1.8 is released and we can depend on something that is legal to distribute.

**Comment by drtshock** [comment]
This is doable now.

**Comment by dariasc** [comment]
Done https://github.com/drtshock/Factions/commit/12ab4f4fed3848c07397bebd20bb97f43a993054
