### ISSUE TITLE
Error: Could not pass event FPlayerLeaveEvent

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1150]
FactionsUUID version: Factions v1.6.9.5-U0.2.2-b116

Server software:  Paper version git-Paper-1381 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Error: https://hastebin.com/zitacajogu.vbs

Please fix this error. Thanks,

**Comment by dariasc** [comment]
That doesn't show the part that tells us where it occurred, full log or at least full error

**Comment by ghost** [comment]
Full log (00:00 - 06:00): https://hastebin.com/ajipolomiw.md

**Comment by drtshock** [comment]
Can you use a paste service that doesn't expire? Sorry but I didn't get to check the issue until now, and now those pastes are empty :(

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
