### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by StefvanderMeer** [drtshock/Factions#1151]
FactionsUUID version (run `/f version`): 
You are running Factions v1.6.9.5-U0.2.2-b116

Server software (run `/version`): 
PaperSpigot 1.8.8

Server (`logs/latest.log`):
no errors found

Details:
When using the command /f warp you can put items inside the menu and they will disappear. You can't take them back.

----------------------------------------------------------------------

FactionsUUID version (run `/f version`): 
You are running Factions v1.6.9.5-U0.2.2-b116

Server software (run `/version`): 
PaperSpigot 1.8.8

Server (`logs/latest.log`):
no errors found

Details:
When not having a faction or anything you have the prefix as: [4-] not sure why but yeah

**Comment by drtshock** [comment]
Prefix for factionless is set in the lang.yml.

Other one is interesting. Can fix.

**Comment by dariasc** [comment]
Should be fixed once we merge UI refactor

**Comment by CmdrKittens** [comment]
Refactor was merged in May. Please let me know if this still happens.
