### ISSUE TITLE
Wilderness players can sometimes open other factions Doors

### ISSUE THREAD

**Issue by KyroOW** [drtshock/Factions#1152]
FactionsUUID version (run `/f version`): You are running Factions v1.6.9.5-U0.2.2-b116

Server software (run `/version`): Spigot 1.12.2 (This server is running CraftBukkit version git-Spigot-b6ecf3b-68b4fb6 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT))

Details:

Sometimes, wilderness players can open the doors of other factions, for example the same player can open doors of a faction, but 3 minutes later he won't be able to anymore, then later he will be able again, without reconnecting or changing factions (still in wilderness).

I noticed in the console this message "Cancelling alzaw WOODEN_DOOR" is missing when the player can open doors.

Situation: https://i.imgur.com/5JGof2c.png

The little red lines shows the doors (indicated by arrows), i think when the players was able to open them was because he was inside the Warzone, so maybe when a player is in a warzone he can open doors from there, not sure about it though as he managed to open doors inside the claim, will try and report back.

**Comment by KyroOW** [comment]
Update on the issue: It doesn't depend of the zones i'm standing in.

**Comment by CmdrKittens** [comment]
Since this issue was submitted the handling system for permissions was completely rewritten. As there have not been reproducible cases provided since, I am assuming this is resolved (but am open to new tickets with reproduction steps).
