### ISSUE TITLE
[Request] Offline factions invites

### ISSUE THREAD

**Issue by AmazedMender16** [drtshock/Factions#1153]
**FactionsUUID version:** 
1.6.9.5-U0.2.2-b119
**Server software:** 
git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Details:**
Would love to see offline factions invite to be added, So players that are from different timezones can invite their friends to the faction without both having to be online at the same time!

**Comment by drtshock** [comment]
Sounds reasonable.

**Comment by mbax** [comment]
Turns out this has been possible, just not clear because it would never confirm the invite happened to the person sending it. Fixing for 0.5.26
