### ISSUE TITLE
Arrows turn white

### ISSUE THREAD

**Issue by WizzleBear** [drtshock/Factions#1159]
FactionsUUID version (run `/f version`): Build #122

Server software (run `/version`): Paper Spigot 1.12.2

Server (`logs/latest.log`):

Details:
Config:
 ```yaml
  - '&8&m&l                      &f {faction} &8&m&l                      &f'
  - '&7Description &8&l»&c {description}'
  - '&7Joining &8&l»&c {joining}'
  - '&7Land &l/ &7Power &l/ &7Maxpower &8&l»&c {chunks}&l/&c{power}&l/&c{maxPower}'
  - '&7Bans &8&l»&c {faction-bancount}'
  - '&7Allies &c({allies}&c&l/&c{max-allies}) &8&l»&f {allies-list}'
  - '&7Online &c({online}&c&l/&c{members}) &8&l»&f {online-list}'
  - '&7Offline &c({offline}&c&l/&c{members}) &8&l»&f {offline-list}'
```
Image: ![Image](https://cdn.discordapp.com/attachments/399982246351863808/439594719446695959/Screen_Shot_2018-04-27_at_9.12.17_PM.png)

Once the list placeholders are removed original colors are restored.

**Comment by dariasc** [comment]
This might have to do with FancyMessages, I still can't find out what exactly

**Comment by dariasc** [comment]
Should be fixed with the ChatComponent API

**Comment by dariasc** [comment]
Said that so that we could reference it later...

**Comment by WizzleBear** [comment]
Well man, you could've said the issue was still there

**Comment by mbax** [comment]
More than 3 years later, finally sorted out the actual cause. Kinda awkward that the solution was so simple but darnit I found it!

![image](https://user-images.githubusercontent.com/181668/224523320-5fc135b4-8c44-469a-9090-cabd3b1e3d5c.png)
