### ISSUE TITLE
Chat Error

### ISSUE THREAD

**Issue by WizzleBear** [drtshock/Factions#1161]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.2.2-b122

Server software (run `/version`): git-Paper-1466 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`): https://hasteb.in/hosakaro.md

Details: Error persists and I believe the problem is FUUID. Reset entire folder and plugin and it still shows the error.

**Comment by VictorML11** [comment]
What error?
