### ISSUE TITLE
Truces Claims are not shown in F Map - With Solution

### ISSUE THREAD

**Issue by VictorML11** [drtshock/Factions#1164]
FactionsUUID version (run `/f version`):  v1.6.9.5-U0.2.2-b118

Server software (run `/version`): Custom Spigot 1.8.8

Server (`logs/latest.log`): No Erros

Details:
Faction Claims From truces are not shown in F map. They are only shown when you are inside of them and they are connected.
I will make a Fix For it and add the option in the conf.json. 
The problem is coming from **MemoryBoard** 
_ public ArrayList<FancyMessage> getMap(FPlayer fplayer, FLocation flocation, double inDegrees)_
Since the truces relations are not included to be shown.

Some pictures:
[Not Truces](https://gyazo.com/d4d078c9570547406872c974f263c165)
[Truces](https://gyazo.com/9529a9b905e9dcc4b523211abe79d12d)
[Claims Shown when you are on them](https://gyazo.com/c38621d59cff86ae4d5e3f70603de7f3)
[Other side](https://gyazo.com/9540c9767cc543a247ef9af5bdd1533d)
[FShow](https://gyazo.com/d5f8f9f64d556a221f47d972eb04681e)

**Comment by dariasc** [comment]
Fixed by drtshock, Thanks
