### ISSUE TITLE
Money deposited using /f money gets cleared on restart

### ISSUE THREAD

**Issue by nauaf101** [drtshock/Factions#1165]
FactionsUUID version (run `/f version`): Factions v1.6.9.5-U0.2.2-b116

Server software (run `/version`):  CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[latest.log](https://github.com/drtshock/Factions/files/2173967/latest.log)

Server (`logs/latest.log`): https://gist.github.com/nauaf101/e5d204fdf4088b0f716f4decf94a8cb3

Details: Whenever money is deposited using /f money deposit, upon restart the money would get cleared.

**Comment by VictorML11** [comment]
To be honest I do not see anything strage.
I have just checked it and at least it is working fine for me.
Try to shut down the server, remove the conf.json and generate a new one.
Then shut down the server again and change the conf.json

Tell me if that solved it. Cause I do not actually get any error from that and It is working fine for me.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
