### ISSUE TITLE
Automatic f map updates with Flight

### ISSUE THREAD

**Issue by Rasturize** [drtshock/Factions#1166]
FactionsUUID version (run `/f version`): 
v1.6.9.5-U0.2.2-b116
Server software (run `/version`): 
1.12.2 PaperSpigot (0e72c9d1)
Server (`logs/latest.log`):
N/A
Details:
Players using factions fly with /f map on "automatic" mode don't get updated when they reach a new chunk.

**Comment by VictorML11** [comment]
I already solved this:
#1156 
#1163

**Comment by Rasturize** [comment]
My apologies, thank you.

**Comment by dariasc** [comment]
Added your fix on https://github.com/drtshock/Factions/commit/d5cc5070d8bb1ddf2553cd778780e2d986fdcf33#diff-dba339e247b7e8d53bc67d10f53caf97R1044
