### ISSUE TITLE
./f demote and ./f promote

### ISSUE THREAD

**Issue by StefvanderMeer** [drtshock/Factions#1167]
FactionsUUID version (run /f version):
You are running Factions v1.6.9.5-U0.2.2-b116

Server software (run /version):
PaperSpigot 1.8.8

Server (logs/latest.log):
no errors found

Details:
./f demote and ./f promote does not work players say they do not have permissions I tried giving them but it doesn't work.

**Comment by CmdrKittens** [comment]
Could not reproduce issue.
