### ISSUE TITLE
/f vault error

### ISSUE THREAD

**Issue by WizzleBear** [drtshock/Factions#1168]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.2.2-b122

Server software (run `/version`): git-Paper-1500 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`): https://hasteb.in/utohovum.lua

Details: /f vault doesn't work with the latest version of PlayerVaultsX (4.0.5)

**Comment by drtshock** [comment]
Fixed, thanks for your patience and bug reporting.
