### ISSUE TITLE
Faction error when typing

### ISSUE THREAD

**Issue by WizzleBear** [drtshock/Factions#1169]
FactionsUUID version (run `/f version`): v1.6.9.5-U0.2.2-b122

Server software (run `/version`): git-Paper-1500 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`): https://hasteb.in/inalebid.apache

Details: https://hasteb.in/ocigijah.yaml https://hasteb.in/hucahozu.coffeescript 
https://hasteb.in/opodejip.json These are my configuration files. I am not sure what is wrong, so anyone who might know what this means your help would be greatly appreciated!

**Comment by dariasc** [comment]
Is this still an issue? Can we get the logs again?

**Comment by WizzleBear** [comment]
No, it seems it has gone away. Might have been a typo on my part
