### ISSUE TITLE
Same players auto-removed for inactivity over and over.

### ISSUE THREAD

**Issue by d1One** [drtshock/Factions#117]
I get my console spammed with the players being removed by inactivity all day long.
Not sure whats causing it.

**Comment by drtshock** [comment]
Can you paste your log and conf.json in https://gist.github.com? I feel like you probably touched your auto removal setting and it's removing people based on inactivity, which is normal.

**Comment by d1One** [comment]
Yes i have auto removal tuned on. The thing is it removes a set of players, then some timer after that it removes the same players again, then again, and again. It seems like its trying to remove them but not actually doing so.
Conf.Json http://pastebin.com/DGLgEDqX
Log : http://pastebin.com/L2iuhgN3

In line number 869 You can see 3 players being removed then in 1440 they are removed again, and in 1423 same players removed again and this goes on thru-out the log...

Could it be some other plugin interfering? I a PvPManager error in the startup.

**Comment by drtshock** [comment]
Can you post your players.json as well? I have a feeling there are just some invalid players in there since it's only happening to 3 every time.

**Comment by d1One** [comment]
Well... It starts with a couple of players and as the server is up for longer more players get added to the 'list' and it gets bigger and bigger...
PasteBin doesn't allow me to paste cause it excedes the max file size i uploaded to my dropbox:
https://www.dropbox.com/s/phuvo1v01319e4t/players.json?dl=0

**Comment by d1One** [comment]
Upss i didn't man to close this sorry, wrong button.

**Comment by d1One** [comment]
Whatever the issue is i think is also causing a lot og lag http://prntscr.com/55cyn2

**Comment by d1One** [comment]
Adding full server timings and board.json
http://timings.aikar.co/?url=8973518
board.json: http://pastebin.com/nn2R200Z

**Comment by drtshock** [comment]
When did you start using my version? Did you start from the old 1.6.9.5 then convert? And if so, which version of my plugin did you use when you converted?

**Comment by d1One** [comment]
I checked to logs and apparently i moved from Factions v1.6.9.5-U0.1.5 to v1.6.9.5-U0.1.9
After that constantly upgrade to each release that came out. In my logs a cant really find a point were the database was converted, is it possible that it was not converted?

**Comment by d1One** [comment]
Is theres a solution for this or do i need to reset my database? Cause that will make everyone rage =(

**Comment by drtshock** [comment]
Even after looking at everything I don't see anything pointing to any issues. It's like your server is some weird anomaly that I can't explain.

**Comment by d1One** [comment]
Well. I guess ill have to reset factions then.. =(
If i just remove the players.json could it work? What exactly gets reset if i just delete that single file?

**Comment by Kakifrucht** [comment]
I'm having the same issue too! Just realized it. Every hour my server is removing the same set of players for inactivity.
I started using your plugin, no other version before.

**Comment by PixelKitsune** [comment]
I'm also having the same issue, about every 5 minutes it removes the same players.

**Comment by drtshock** [comment]
Does anyone know which build this started on?

**Comment by d1One** [comment]
I do. For me it was when i moved from v1.6.9.5-U0.1.5 TO v1.6.9.5-U0.1.9

**Comment by Kakifrucht** [comment]
I did some additional research on this bug. The players are actually autoremoved, but they somehow persist in the servers RAM? I have set an hourly inactivity check, at the beginning of the day it only removes a couple of players, but this somehow accumulates throughout the day. Players that already have been removed show up on every new autoremove again. This is fixed through server restart, the autoremoval list is being reset. 
Let me examplify this a bit more: Player A gets auto removed on 11:00, one hour later, he will again show up in the console as auto removed. If on 13:00 Player B gets removed, it will show him at the TOP of the list, player A will be below him (and Player A was removed already).
This started happening on Factions v1.6.9.5-U0.1.8, 100% sure about that ;)

**Comment by drtshock** [comment]
It looks like the issue originated here: https://github.com/drtshock/Factions/commit/ee52016a8709b4596b9ab888b7f9163abfa1479e#diff-473aab46c87b5e883351b35563e7c864L18

Now just to pinpoint exactly why it's doing that.
