### ISSUE TITLE
Issues with /f fly and /f vault

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1185]
FactionsUUID version (1.6.9.5-U0.2.1-RC2-b100): 

Server software (1.8.8`): 

Server (https://pastebin.com/11gjeMYu):

Details:
I just updated, to the latest version of factionUUID so I could use the latest features, but I have issues with /f fly. When I do /f fly it works for like 5 seconds and then I fall to the ground, after I fall am not able to double tab space to fly again, I have to disable it and enable it again, that only happens to default players

also, I have issues with /f vault where when I try to use the command, it says "An internal error occurred while attempting to perform this command" and that happens even though I'm op

**Comment by EmilKnudsen** [comment]
Hello, I have the same error. Any response on this so far ?

**Comment by EmilKnudsen** [comment]
https://pastebin.com/dLHu3DFJ I have this error when I do /f vault.
Even though I am more curious about the faction fly.

Question, how do I set faction fly permission-based, so players only has access to faction fly on permission ?

**Comment by RogerPlaysMC** [comment]
Question on the Vaults parts, do you have PlayerVaults installed? That’s the first part of your “Caused by” section of the error.

**Comment by drtshock** [comment]
vault issue is known. Please keep tickets to 1 single issue.
