### ISSUE TITLE
While in peaceful faction, one is unable to hit somebody even in bypass mode

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#119]
This would probably fall under the category enhancement, however it would be nice as an administrator, while being in a peaceful "Team" faction, to still being able to hit a player (for testing purposes for instance) while in /f bypass mode.

**Comment by drtshock** [comment]
I don't believe this would be wise to add. The admin can simply toggle their status of the faction. If I added this, it would be abused on many servers and I don't think it's within the project scope.

**Comment by Kakifrucht** [comment]
I mean sure, you could disable peaceful, but that would still not override the fact that I need do declare war for instance.
Sometimes you want to test if a player has anti knockback or stuff in it.
If an admin wants to abuse on his own server I'd say that that would be his choice.

**Comment by drtshock** [comment]
f bypass is a too used to bypass claims, not used as a way to abuse pvp.
