### ISSUE TITLE
ParticleEffect configuration issue

### ISSUE THREAD

**Issue by jwc65** [drtshock/Factions#1191]
### FactionsUUID Version

You are running Factions v1.6.9.5-U0.3.0-b129

### Server Version

This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
 
### Logs

https://gist.github.com/ipr0james/a708be82592a89e54488c42dd7ed4bbd

### Details

Issue resulted at startup when creating configuration files.
Configuration value for 'see-chunk.particle' is invalid, the methods use ParticleEffect.fromName(), the value in config is 'REDSTONE' whereas the given name in ParticleEffect is 'reddust'

**Comment by drtshock** [comment]
So the default value is now invalid?

**Comment by dariasc** [comment]
Didn't really think this might be an issue, maybe we should update ParticleEffect enum to REDSTONE? @drtshock?

**Comment by dariasc** [comment]
> So the default value is now invalid?

It seems to be invalid when using the Packet provider ie the ParticleEffect library

**Comment by drtshock** [comment]
^^ can include in your PR to fix this.
