### ISSUE TITLE
Error message on player leave

### ISSUE THREAD

**Issue by jeannen** [drtshock/Factions#1195]
### FactionsUUID Version
*Run `/f version` and give us your output.* 
You are running Factions **v1.6.9.5-U0.3.0-b133**

### Server Version
*Run `/version` and give us your output.*
This server is running CraftBukkit version git-Spigot-cf694d8-5259d80 (MC: 1.13.2) (Implementing API version **1.13.2-R0.1-SNAPSHOT**)

### Logs
*Give use your logs by going to `logs/latest.log`.*

(I don't have access to logs atm)
**https://pastebin.com/mrxiF5da**

### Details
I just saw this error in my log, it doesn't cause any problem so far but it's always good to report it :)

**Comment by drtshock** [comment]
I see. We just need to add a nullcheck here. It won't break anything in the mean time.

**Comment by jeannen** [comment]
Hey !

I still have the error, is that normal ? No big deal but it's kinda spammy in the logs ^^

**Comment by prosavage** [comment]
Add the null check then lol.

**Comment by jeannen** [comment]
What's a null check ?

**Comment by CmdrKittens** [comment]
Added that null check. Thanks @ProSavage for the pro tip!
