### ISSUE TITLE
[4-] displayed in the placeholder

### ISSUE THREAD

**Issue by jeannen** [drtshock/Factions#1197]
### FactionsUUID Version
*Run `/f version` and give us your output.* 

You are running Factions **v1.6.9.5-U0.3.0-b133**

### Server Version
*Run `/version` and give us your output.*

This server is running CraftBukkit version git-Spigot-cf694d8-5259d80 (MC: 1.13.2) (Implementing API version **1.13.2-R0.1-SNAPSHOT**)

### Logs
*Give use your logs by going to `logs/latest.log`.*

https://pastebin.com/EJPkjsVr

### Details
*Please explain the problem.*

When a Player has no Factions, the PlaceholderAPI **%factionsuuid_faction_name%**
 display **[4-]** instead of nothing. It wasn't doing this before, I don't know exactly when it happenned (maybe with the update). I tried to delete my config and restart, and put FactionsUUID on a local server (with only PAPI & Factions,, the problem is still there)

**Comment by dariasc** [comment]
So it even happens on local server with no other plugin? Will check out

**Comment by jeannen** [comment]
With Vault, EssentialsX and ProtocolLib, but I don't think they can do anything to Factions/PAPI

**Comment by BboyZeroOne** [comment]
Check your conf.json, if not wrong you can edit it there.

**Comment by jeannen** [comment]
> Check your conf.json, if not wrong you can edit it there.

I've already checked every file, I didn't found anything

**Comment by CmdrKittens** [comment]
Can confirm this is a very real thing that happens. Kinda neat, kinda weird.

**Comment by CmdrKittens** [comment]
Well, this was in front of our eyes the entire time.

It's lang.yml's `nofactions-prefix` which defaulted to saying `&6[&a4-&6]&r`. New value in 0.5.0 will be: `&6[&ano-faction&6]&r`

**Comment by jrodr10** [comment]
what about in a version kinda older

**Comment by jrodr10** [comment]
like where the lang.yml isnt there

**Comment by CmdrKittens** [comment]
@jrodr10 Update to latest! :)

**Comment by jrodr10** [comment]
@CmdrKittens alot harder then you think
