### ISSUE TITLE
FactionsUUID /top

### ISSUE THREAD

**Issue by realDYl4N** [drtshock/Factions#1198]
### Idea
I want the command /f top to be added

### Details
/f top would give you a list of the top factions based on power, money, land, etc

**Comment by CmdrKittens** [comment]
This has existed for several releases :)

**Comment by realDYl4N** [comment]
I'm sorry what's this in reference too?

**Comment by CmdrKittens** [comment]
https://github.com/drtshock/Factions/issues/1198

**Comment by realDYl4N** [comment]
ahh I see, that was many months ago hahaha. Well I dont need this anymore
but I appreciate your response.
