### ISSUE TITLE
Translation Files

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#12]
Would be nice to have some TL files for things like:
- Warzone tag
- WIlderness tag
- Safezon tag
- Default faction desc
- Anything else I suppose.

**Comment by TheKnight787** [comment]
How do I exactly create a TL file?

**Comment by drtshock** [comment]
This was just a note so I remember what I should add when I have time to work on it. There's currently not a way to do this.

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/compare/753c32785d55...955958ce61a4 weeee

**Comment by TheKnight787** [comment]
Will there be an ability to change default faction description?

**Comment by drtshock** [comment]
Yes, I still have a lot of keys to add.
