### ISSUE TITLE
[Feature Request] Custom /f perms

### ISSUE THREAD

**Issue by rcj0003** [drtshock/Factions#1204]
### Idea
Add API to add custom /f perms via a config or alternative method

### Details
Currently, if you need custom permissions there are only 2 options to add them: create a new fork with custom permissions or do some type of hack solution. Both options are unreliable and inconvenient.

It may take a bit of work, but it could be doable if PermissableAction was converted into a class instead of an Enum and whatnot.

Thanks for your consideration, this would be great for me (and for others I’m sure) to devote my full focus to developing the plugins and not the means on which the plugin will work.

**Comment by dariasc** [comment]
This has been discussed, but the time hasn't arisen to develop it, it could definitely be added down the line, the new features/refactors have other developers in mind (UI, Upgrades), if you have any API ideas be sure to create an issue, Thanks

**Comment by mbax** [comment]
This was implemented in 0.6.0
