### ISSUE TITLE
Users can interact with entity blocks, such as Armor stands and Item frames.

### ISSUE THREAD

**Issue by ManOfPaper891** [drtshock/Factions#1208]
### FactionsUUID Version
*Run `/f version` and give us your output.* 
"You are running Factions v1.6.9.5-U0.3.0b133"

### Server Version
*Run `/version` and give us your output.*
"This server is running Paper version git-Paper-65 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

*5 versions behind*

### Logs
*Give use your logs by going to `logs/latest.log`.*
[latest.log](https://github.com/drtshock/Factions/files/3268987/latest.log)

### Details
*Please explain the problem.*
Players with out f bypass/admin can edit SafeZone and Warzone's Item Frames and Armor stands. I would assume this could be fixed pretty easily. I did not see an option to change this in any of the config files. Thank you.

**Comment by CmdrKittens** [comment]
I believe I have fixed this in the latest dev build, but because it is 2am I am going to bed without testing. Leaving the issue open until I can test it.

**Comment by CmdrKittens** [comment]
Updating to say it's not quite fixed, and I'll be fixing *with* testing possible now.

**Comment by CmdrKittens** [comment]
Handled as of build 147
