### ISSUE TITLE
1.13 hostile mobs do not die, and will sometimes spawn in SafeZone

### ISSUE THREAD

**Issue by ManOfPaper891** [drtshock/Factions#1209]
### FactionsUUID Version
*Run `/f version` and give us your output.* 
"You are running Factions v1.6.9.5-U0.3.0b133"

### Server Version
*Run `/version` and give us your output.*
"This server is running Paper version git-Paper-65 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

*5 versions behind*

### Logs
*Give use your logs by going to `logs/latest.log`.*
[latest.log](https://github.com/drtshock/Factions/files/3268989/latest.log)

### Details
*Please explain the problem.*
Pretty self explanatory. 1.13 mobs will spawn in SafeZone. These include Drowned Zombies & Phantoms that I have noticed. There could be more that I haven't noticed. 
![2019-06-08_16 09 28](https://user-images.githubusercontent.com/11999819/59153213-b3a7c980-8a08-11e9-8743-d314039d1c0e.png)
![2019-06-08_16 09 24](https://user-images.githubusercontent.com/11999819/59153214-b73b5080-8a08-11e9-9a3c-1a1f2270cfb6.png)

**Comment by CmdrKittens** [comment]
This issue is my next target for resolution. Fixing this in a future-proof way will require some re-arranging of the codebase. I have begun this work.

**Comment by CmdrKittens** [comment]
Should be resolved in the latest dev build. Please respond to this issue if it continues to happen.
