### ISSUE TITLE
New 1.14 blocks are not being blocked

### ISSUE THREAD

**Issue by WhyDoWeWonder** [drtshock/Factions#1211]
Chests doors and other older blocks are functioning perfectly normally, people who do not have permission cannot edit them. The new 1.14 blocks have issues, barrels, smokers, and blast furnaces are not protected by faction claims.

**Comment by Lmmb74** [comment]
1.14 containers have not been added yet here: https://github.com/drtshock/Factions/blob/a1e9db100b940395b7cd5374c8b8cfb35039bad9/src/main/java/com/massivecraft/factions/listeners/FactionsPlayerListener.java#L428

**Comment by Lmmb74** [comment]
Give me a couple of hours and I can make a pull request. I'm in class right now.

**Comment by CmdrKittens** [comment]
Resolved in latest dev build.
