### ISSUE TITLE
DTR Factions

### ISSUE THREAD

**Issue by Crusbyofficial** [drtshock/Factions#1218]
Hello there, i have one big request.
Revive DTR to FactionsUUID that means rework it to only DTR not like this one. Now it is like Power DTR. In older versions it was like it doesnt matter how many claims u have it still matter on DTR. For example u have 1000000x claims but it doesnt matter on power there wasnt any power there was only DTR. For example u have 36 lands and 1.01 DTR and than u need to die twice to be raidable. If u have more question about it just comment it. I know my english is very bad but i try my best to give you any info about this.

**Comment by Crusbyofficial** [comment]
There is and old config for DTR factions
https://github.com/drtshock/HCFactions/blob/dtr/src/main/resources/config.yml

**Comment by CmdrKittens** [comment]
Please take a look at #1223 which will be used for plotting this out.
