### ISSUE TITLE
Internal Errors on Certain Commands

### ISSUE THREAD

**Issue by Evap88** [drtshock/Factions#122]
Using most recent build of: FactionsUUID, Vault.

Upon typing the /f warp command. Many commands give this error and the error is the same. Server uses Java 6 and Java 7 on linux.
https://gist.github.com/zdylann/165fa016176940f647ab

**Comment by drtshock** [comment]
Update to the latest build on the jenkins server 0.1.11-SNAPSHOT. It's fixed there.
