### ISSUE TITLE
/f perm shows an empty menu with "invisible icons"

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1221]
This is how it looks like. The "invisible" icons seems to be working. but it doesn't appear, weird.

https://imgur.com/a/qPlSa0P

I am using the latest version of FactionsUUID on a 1.13.2 paperspigot.

**Comment by drtshock** [comment]
You'll need to let your config.yml reset for it to fill in the values, or grab the bottom of it from https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/config.yml#L405
