### ISSUE TITLE
/f show Shows internal error and /f home (faction) does not work.

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1222]
First of all, whenever I do /f show, it keeps showing me this error message.

"An internal error has occurred while attempting to perform this command."

https://imgur.com/a/fQCM128

Secondly, I'm not sure if /f home (faction) is part of the command instead of just /f home. But if it isn't, then /f home (faction) would be a great addition like how mcore Factions used to have it. 

I am using the latest version of FactionsUUID with 1.13.2 paperspigot. On my spigot server, the same errors does show up too. Thanks~

**Comment by CmdrKittens** [comment]
Believed to be fixed by remix branch, waiting for testing

**Comment by animeavi** [comment]
I do miss the /f home (faction) command from when I used the other version of Factions.
Would you consider adding that? If so, should I open another issue for it?

**Comment by CmdrKittens** [comment]
#849 has you covered. Added to todo list.

**Comment by CmdrKittens** [comment]
Both resolved in latest dev build. Hoping to release on Spigot soon.
