### ISSUE TITLE
HCF Planning

### ISSUE THREAD

**Issue by CmdrKittens** [drtshock/Factions#1223]
* DTR. Magical value that allows separate tracking of raidability and land claims
  - [x] Implement DTR value.
  - [x] Base DTR granted to faction for existing.
  - [x] DTR per faction member
  - [x] Maximum and minimum value for DTR
  - [x] DTR regained per minute per faction member
  - [x] DTR death loss modifier per world (counts for less in nether, for example)
  * Death freeze - upon member death:
    - [x] Freezing of DTR gain for a given duration
    - [x] Prevention of join/leave/disband
    - [x] Penalty for kicking while frozen
  - [x] Command for DTR control
  - [x] Tags
  - [x] Placeholders
* Land claiming control
  - [x] Each player in a faction grants an amount of claimable land.
  - [x] Maximum claimable land per faction.
  - [x] Land cannot be stolen

**Comment by Crusbyofficial** [comment]
Answer to your question. In DTR Factions u cannot claim others factions. There is only "Raid" that means if faction is raidable (that means if the factions have minus DTR) everyone can break in their territory and opens chests.

**Comment by CmdrKittens** [comment]
> Answer to your question. In DTR Factions u cannot claim others factions. There is only "Raid" that means if faction is raidable (that means if the factions have minus DTR) everyone can break in their territory and opens chests.

So, a faction can never lose territory? What if I create a faction, get ten friends to join, claim a TON of land, and then have everyone leave except myself? That feels a bit unfair, doesn't it?

**Comment by Crusbyofficial** [comment]
No it doesnt. If they leave his faction it doesnt matter that he has maximum of claims what faction can have. I think if all leave faction you lose motivation to play. And nobody has ever resolved this possibility i think it just stayed on maximum lands.

**Comment by CmdrKittens** [comment]
> nobody has ever resolved this possibility

Except that in other modes of factions you can claim a faction's land if they don't have enough power. There are ways to fix the problem, I'm just trying to figure out how to best go about doing so.

**Comment by Crusbyofficial** [comment]
Yey, i know but power fac and dtr fac are really different. There was no enemy claiming in DTR fac. there was only raiding

**Comment by Crusbyofficial** [comment]
If ur raidable than everyone can break all your territories and opens chest in all your territories.

**Comment by Crusbyofficial** [comment]
Maybe add me on discord for fast feedback Crusby#9358

**Comment by vqty** [comment]
Add an option to disable dtr regen when every member is offline.
so you only regen dtr when there are members online

**Comment by CmdrKittens** [comment]
Status update: https://github.com/drtshock/Factions/commit/6a2b246d4e07c3391bcc23710f95a6d53a7213a7

DTR foundation is in play. Land claim management still needs implementation.

**Comment by CmdrKittens** [comment]
It's in!
