### ISSUE TITLE
/f home <name> for non-admins

### ISSUE THREAD

**Issue by animeavi** [drtshock/Factions#1227]
I see you added /f home [name] but can you also extend it for non-admins?
The way MCore Factions did it was having a "home" permission that allowed you to TP to the faction's home.

**Comment by CmdrKittens** [comment]
Waiting on #1228 for this.

**Comment by CmdrKittens** [comment]
The `home` permission in `/f perms` needs an item to use! `sethome` currently has compass. Bed is out, because it can't be made to appear enchanted :(

**Comment by CmdrKittens** [comment]
https://github.com/drtshock/Factions/commit/f25f62775e63fc330a77fbf5fad7483d495ef2b8
