### ISSUE TITLE
Permissions overhaul

### ISSUE THREAD

**Issue by CmdrKittens** [drtshock/Factions#1228]
Rip out existing handling of who can do what when. Replace with system managed like current `/f perms` with added complexity:

* Allow server administrator to define defaults for each permission/relation. 
  * e.g. Default allies can access containers.
* Allow server administrators to define which permissions can be controlled by faction leaders, and which are locked.
  * e.g. Enemies cannot build, and factions cannot allow it.
* Remove everything set in `conf` related to permissions.

**Comment by Neeonn** [comment]
Add the ability for faction leaders to allow/disallow claiming/unclaiming for moderators/coleaders with the "TERRITORY" permission in `/f perms`.
