### ISSUE TITLE
{faction} variable relation color missing in /f show

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1229]
### FactionsUUID Version
*Run `/f version` and give us your output.*   
Factions v1.6.9.5-U0.4.1-b154

### Server Version
*Run `/version` and give us your output.*  
Paper-127 MC 1.14.3

### Logs
*Give use your logs by going to `logs/latest.log`.*  
https://pastebin.com/sbLQFANQ

### Details
*Please explain the problem.*
I wanted to set a custom header for /f show. Here's what it looks like in config.yml:  
&8&m--------------&8<&r {faction} &8>&m--------------
Here's what it looks like in game:  
https://i.imgur.com/7xnLzsI.png

**Comment by CmdrKittens** [comment]
Added `{faction-relation-color}` tag. Try build 155 on the CI and adding that:
`&8&m--------------&8<&r {faction-relation-color}{faction} &8>&m--------------`
https://github.com/drtshock/Factions/commit/f350c5ee85259a9d9604ee1ac3f2a3e8cb5fe039

**Comment by ghost** [comment]
That worked, thank you for getting to this so quickly!

**Comment by ghost** [comment]
Oh, another thing to add. That seems to produce this for factionless:
https://i.imgur.com/yHvQjMR.png

**Comment by CmdrKittens** [comment]
Well, that's strange! Working on a fix. Build 157 will be the right build. 156 still has the issue.

**Comment by CmdrKittens** [comment]
Build 157 coming up now.
