### ISSUE TITLE
dynmap

### ISSUE THREAD

**Issue by timriker** [drtshock/Factions#1234]
### Idea

I'm trying to find a dynmap plugin that works with current FactionsUUID.
Here are three I've found, and none seem to work with the current API:
https://www.massivecraft.com/factionsdynmap (2.x)
https://dev.bukkit.org/projects/dynmap-factions (2.x)
http://mikeprimm.com/dynmap/builds/Dynmap-Factions-1.8.x/

### Details

I would like to see the claimed area for each faction, and optionally show faction warps and faction homes. It would be awesome if hovering over faction land would show a /f show like scoreboard as a popup. This should include safezones and warzones.

**Comment by timriker** [comment]
I didn't know there was some built in support. :( Was that for an old dynmap release? I'm running Dynmap-3.0-beta-5-spigot.jar

**Comment by mbax** [comment]
There was a brief period where dynmap was disabled due to some big bugs. Not an issue anymore.
