### ISSUE TITLE
WorldBorder support not working

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1237]
### FactionsUUID Version
*Run `/f version` and give us your output.* 
Factions v1.6.9.5-U0.4.3-b170

### Server Version
*Run `/version` and give us your output.*
Paper(134) 1.14.3-R0.1-SNAPSHOT

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://pastebin.com/NvDJE229

### Details
*Please explain the problem.*
In the log you can see I was able to claim 995,999 on a non-op account when the border is 1000,1000. I have WorldBorder version 1.9.10. If this support means the Minecraft world border, i did make sure that matches, so the vanilla physical barrier is at the same point as the WorldBorder plugin border.

**Comment by CmdrKittens** [comment]
Could you also include your config.yml and conf.yml

**Comment by ghost** [comment]
conf.json:  
https://pastebin.com/nce2hAZv  
config.yml:  
https://pastebin.com/rFksehh6

**Comment by CmdrKittens** [comment]
This is for the Minecraft built-in feature.

I just did a test:

1) Set worldborder to a ridiculous 160 blocks
2) Went to each border edge and corner, tested claiming with buffer as 0.
3) Repeated step 2, updated buffer to 1. Could not claim closest chunk overlapping border.
4) Repeated step 2, updated buffer to 2. Could not claim closest chunk overlapping or next chunk inside.

Would you be interested in running a modified plugin that outputs some data about the border when it checks if claiming is allowed?

**Comment by ghost** [comment]
Yes, I could do that.

**Comment by CmdrKittens** [comment]
[Factions.zip](https://github.com/drtshock/Factions/files/3412177/Factions.zip)
Had to shove it in a zip. Try to claim in that area again, it should give some output to the console.

**Comment by ghost** [comment]
Okay, I've done this with buffer set to 5 and this was the output:

```
Testing with buffer 5
WB Supported
Centered on 0,0 with size 6.0E7
Lim 1874995
1000 1000
[Factions v1.6.9.5-U0.4.3-bWBTEST]: xSkate claimed land at (-1000,-1000) for the faction: test
```

I double checked server.properties and max-world-size is set to 16000.

**Comment by CmdrKittens** [comment]
Could you run `/minecraft:worldborder get` please

**Comment by ghost** [comment]
Ah, I guess I wasn't previously aware that the setting in server.properties was different from this command. Turns out this was apparently set to 60000000. I set it to 32000 and now the compatibility is working properly, I just didn't know to check this command. Thanks for the help.

**Comment by CmdrKittens** [comment]
You're welcome! FactionsUUID could use some better documentation in some places.

**Comment by CmdrKittens** [comment]
I have added an additional line clarifying this to the default config: 
https://github.com/drtshock/Factions/commit/3defeb312faf3ad598628a0b225fb8c30832f6b1
