### ISSUE TITLE
/f map (faction names and claims colors)

### ISSUE THREAD

**Issue by ElementalXGaming** [drtshock/Factions#1238]
### Idea
Allow faction names to be displayed by their given relationship color

### Details
For example, when someone does /f map and they have their own claims within it, their claims and name-under-map would show as green. If an enemy claim is on that map, the claims and name of the fac will show as red. If an ally claim is on that map, the claims and name would show up as dark purple. If a truce claim is on that map, the claims and name would show up as light purple. If a neutral claim is on the map, the claim and name would show as white.

**Comment by CmdrKittens** [comment]
PR pulled, will be in 0.5.0
