### ISSUE TITLE
Non-Faction Members locking chest from claimed lands.

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1246]
### FactionsUUID Version
v.1.6.9.5-U0.4.3-b170

### Server Version
1.13.2 PaperSpigot

### Logs
-

### Details
I'm currently using LWC as my container locking plugin. The issue is where non faction members can lock chest from other unlocked chest in other faction land. Could this be prevented? Thanks!

**Comment by CmdrKittens** [comment]
Before further debugging, what is your LWC version and which LWC is it? (from where)

**Comment by BboyZeroOne** [comment]
Modern LWC 2.1.4jar from here
https://bit.ly/2ImzgE4

**Comment by BboyZeroOne** [comment]
This includes doors, trapdoors, fence gates etc

**Comment by CmdrKittens** [comment]
Generally speaking (though I don't think it's relevant here) you should check out LWCX, https://www.spigotmc.org/resources/lwc-extended.69551/ , from the guy who maintained ModernLWC for the last year (summary of the drama: LWCX is going to be where future improvements happen vs ModernLWC where the spigot page owner never improved the plugin but wouldn't hand over control so the actual maintainer could update the page on time)

Did you make sure `core.factionCheck` in the LWC config is set to true?

**Comment by BboyZeroOne** [comment]
Hey there! 

Alright, I will check that out. Before I switch from ModernLWC to LWCX, does the player's locked chest etc database be the same? Or everything will be reset. Thanks! 

I have checked the LWC folder and there isn't any config.yml. There is only core.yml but it doesn't show anything related to faction or even core.factionCheck.

**Comment by CmdrKittens** [comment]
Should behave the same without reset. 
Here's the latest config: https://github.com/pop4959/LWCX/blob/master/src/config/core.yml

**Comment by BboyZeroOne** [comment]
Okay thats cool! I've seen the config and it has that option. Thanks a lot, will try it out on my server and see how it goes!

**Comment by CmdrKittens** [comment]
@BboyZeroOne How did it go?

**Comment by BboyZeroOne** [comment]
It works! Thanks for informing me about LWCX. I guess you could close this thread!
