### ISSUE TITLE
Stop users from being able to block nether portals in claimed regions

### ISSUE THREAD

**Issue by Mxchael** [drtshock/Factions#125]
Nether portals can be blocked with blocks in claimed regions which causes the user to get stuck.

As you cannot type when inside a nether portal and you won't get teleported back through to the non stuck area you are sitting there with no ability to get out.

I suggest that you make it so that blocks cannot be directly placed in-front of the nether portal only like this http://file.spurlex.com/1folq/10vS2AnY This would allow the user to leave the nether portal and still not enter the base but make it so they can type commands and/or go back through to the safer area.

**Comment by RenegadeEagle** [comment]
This seems like something that shouldn't be apart of factions. I know however on daegonner before we disabled building in the nether, you could build a portal at an exact coordinate and be inside someones base with ease. Portal blocking is just part of the game. If I were you I would look into something external.

**Comment by drtshock** [comment]
I agree with @RenegadeEagle. This just isn't a Factions issue.
