### ISSUE TITLE
Ability to set a default height for /f map

### ISSUE THREAD

**Issue by trazzy7** [drtshock/Factions#1250]
### Idea
Add a way to change the default height for /f map. This will allow for faction servers with smaller borders to reduce the size of the map to be better suited to the size of the world. Currently, the map shows far too much land for the size of my borders.

**Comment by instantout** [comment]
I feel like there should e a Default in config.yml that says "Lines:" and one that says "Rows:"
So something like 

faction-map-command:
  rows: 20
  columns: 20
or 
length and width.

**Comment by CmdrKittens** [comment]
This already exists in conf.json

```
  "mapHeight": 17,
  "mapWidth": 49,
```
