### ISSUE TITLE
Claiming near border not possible

### ISSUE THREAD

**Issue by Zockerbeule** [drtshock/Factions#1261]
If I try to claim land near the border I get the issue that I'm not actually in the border. I have set the buffer to 0 in config.yml. Talked to Discord support and they couldn't really help me, so I'm here reporting and hoping it can get fixed soon. I'm on 1.8.8 and my border is 5k x 5k. The border middle is not on x and z 0.

PS: I was able to claim land directly next to the border in some other corners, so that's a bit weird.

**Comment by CmdrKittens** [comment]
Should be resolved for 0.5.0
