### ISSUE TITLE
More Protected Materials 

### ISSUE THREAD

**Issue by instantout** [drtshock/Factions#1265]
### Idea
so this is More Protected Materials for 1.14.4 or the New Faction updated etc. idk how this works.

### Details
- Signs (all types of Wooden signs). Since you can change the default text color with Dye.
- Smoker
- Blast Furnace
- Lectern
- Shulker Boxes (All Colors) but i feel there should be a Tag to define them all or something.

**Comment by CmdrKittens** [comment]
Three were already in the update, but lectern and sign are now added.
