### ISSUE TITLE
placeholder problem

### ISSUE THREAD

**Issue by alaajel** [drtshock/Factions#1268]
### FactionsUUID Version
*Run `/f version` and give us your output.* 
Factions v1.6.9.5-U0.4.3-b171

### Server Version
*Run `/version` and give us your output.*
1.14.4 paper spigot
This server is running Paper version git-Paper-171 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
### Logs
*Give use your logs by going to `logs/latest.log`.*
no errors in the conolse

### Details
*Please explain the problem.*
placeholder %factionsuuid_faction_name%
when player not in faction it shows [4-]
![image](https://user-images.githubusercontent.com/34905970/63174037-2f01a900-c052-11e9-85de-b7f834bb049f.png)

**Comment by CmdrKittens** [comment]
Check this out!

https://github.com/drtshock/Factions/issues/1197#issuecomment-521082235
