### ISSUE TITLE
Armor Stands and Item Frames

### ISSUE THREAD

**Issue by instantout** [drtshock/Factions#1277]
### FactionsUUID Version
`You are running Factions v1.6.9.5-U0.4.9-b176`

### Server Version
`This server is running CraftBukkit version git-Spigot-798ea6a-2012f1e (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)`

### Details
so, Item frames and Armor stands can get items or "entities" Removed or added from their slots.
Inside Warzone and Safezone.

Armor Stands Can Be destroyed and placed inside Warzone and Safezone.

**Comment by CmdrKittens** [comment]
Resolved in latest
