### ISSUE TITLE
Tags.json More colors Support.

### ISSUE THREAD

**Issue by instantout** [drtshock/Factions#1279]
### FactionsUUID Version
`You are running Factions v1.6.9.5-U0.4.9-b176`

### Server Version
`This server is running CraftBukkit version git-Spigot-798ea6a-2012f1e (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)`

### Details
Not enough support for color codes on tags.json
![javaw_xKgyXB0oNf](https://user-images.githubusercontent.com/9593902/63567042-68d82100-c524-11e9-9b07-44ba1c3fb8fe.png)
![javaw_DeKFnf79cl](https://user-images.githubusercontent.com/9593902/63567050-6fff2f00-c524-11e9-87f5-ece8841f6dee.png)

[Tags.json More Colors Link](https://hasteb.in/wasemiwo.json)
[For Testing in config.yml](https://hasteb.in/aqonasiy.rb)

what i noticed is the Lack of colors, this is so it's more easier to switch colors, also... just more support for tags.json would be nice. anyways, a Issue because not all the colors are designed with their names.

**Comment by CmdrKittens** [comment]
tags.json is for short-hand for a hacky set of color translation. It will be going away in 0.6.0

The left side is for shortcuts for the longer names on the right which are what is used.

Below are the names it would recognize on the right side of tags.json, followed by the char they represent.

```
<empty> -> 
<black> -> 0
<navy> -> 1
<green> -> 2
<teal> -> 3
<red> -> 4
<purple> -> 5
<gold> -> 6
<silver> -> 7
<gray> -> 8
<blue> -> 9
<lime> -> a
<aqua> -> b
<rose> -> c
<pink> -> d
<yellow> -> e
<white> -> f
```
