### ISSUE TITLE
Factions & Herochat

### ISSUE THREAD

**Issue by marium0505** [drtshock/Factions#128]
Hello, I bought and installed FactionsUUID today, but I'm having issues with Factions & Herochat.

When I have "chatTagEnabled" on true, will Factions handle the chat (that would not be that much of a problem if I figured out how to set up the chat format using Factions), but when I have it on false, then Herochat will, but the tag wont work...

I didn't have such issues when I had the MCCore version. :L
Regards,
Marium0505/Quenderin

**Comment by drtshock** [comment]
The MCCore version has a lot of herochat integration to support that overriding this for chat channels and what not. I don't think this is something that will be added in the near future.
