### ISSUE TITLE
FLocation#isOutsideWorldBorder needs fixing.

### ISSUE THREAD

**Issue by uf0h** [drtshock/Factions#1281]
### FactionsUUID Version
Latest build [#178](https://ci.ender.zone/job/FactionsUUID/178/)

### Server Version
`TacoSpigot 1.8.8`

### Details
The current implementation of FLocation#isOutsideWorldBorder `returns false` for chunks that are outside the worldborder. I believe it need's fixing to properly check neg X and Z values.

The following image shows `/f map` output with `/worldborder center 0.0 0.0` and `/worldborder set 128` having aligned the chunks correctly.
![proof](https://user-images.githubusercontent.com/24858857/63631933-af617480-c625-11e9-82ea-76f820b589b7.png)

**Comment by mbax** [comment]
Also seen in #1261

It definitely needs some cleaning up.
