### ISSUE TITLE
Config upgrade exception

### ISSUE THREAD

**Issue by animeavi** [drtshock/Factions#1287]
Using a version compiled from the [latest commit ](https://github.com/drtshock/Factions/commit/778021451e90b0922a560905f51c3c12ade7c3ec).

I thought it was an issue with my config files but it also happened with [newly created configs from 1.6.9.5-U0.4.3](https://github.com/drtshock/Factions/files/3539425/Factions.zip)
.
This is the log of the exception I'm getting at when attempting to convert.
https://pastebin.com/raw/53KXD4Ah

It points to
[Relation.java](https://github.com/drtshock/Factions/blob/778021451e90b0922a560905f51c3c12ade7c3ec/src/main/java/com/massivecraft/factions/perms/Relation.java#L9)
[TL.java](https://github.com/drtshock/Factions/blob/778021451e90b0922a560905f51c3c12ade7c3ec/src/main/java/com/massivecraft/factions/util/TL.java#L940)

**Comment by CmdrKittens** [comment]
https://github.com/drtshock/Factions/commit/94d281fc81aca39fdba778234f0da89608d6e83a
