### ISSUE TITLE
Command to find claimed chunks ID like /f showclaims

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1289]
### Idea
Command to find claimed chunks ID like /f showclaims

### Details
So that it can help us track where all our Faction claimed chunks are. Some players claim some land in both overworld and nether/theend and they couldnt track where they claim it.

It would be recommended that this permission is only allowed for staffs to use.

Thank you! Hope you will consider my feature request!

**Comment by mbax** [comment]
Forgot to close, does exist.
