### ISSUE TITLE
Command to claim a whole World Guard region

### ISSUE THREAD

**Issue by marium0505** [drtshock/Factions#129]
Hello!

I bought FactionsUUID today. :)
And I thought about a feature I would love to have, and I'm sure a lot of other server admins/owners would appreciate it as well!

The feature I want is a command to claim a whole World Guard region, to give an example, on my server I have quite a large server spawn, and instead of flying all around and make sure the whole spawn is claimed, could I just do ie. /f claimregion spawn <safezone|warzone|faction>

This would be a great feature, and I would be very grateful if you could add it. :)

Thanks.

Regards,
Marium0505/Quenderin

**Comment by Kakifrucht** [comment]
Why would you even want to claim the spawn? Just set worldGuardChecking in the config to true, voila, nobody can claim it anymore.

Useless feature imo. Also, the only thing that claim does is claim a chunk. Worldguard regions don't work with chunks.

**Comment by drtshock** [comment]
@Kakifrucht has a good point. What we /could/ do, if enough people think it'd be useful, is let you claim a certain zone for all of the chunks that a region touches. Not going to check to see if the region takes up the entire chunk.

**Comment by drtshock** [comment]
I don't see this coming to light.
