### ISSUE TITLE
Scoreboard not coloring across prefix/data (1.14.4)

### ISSUE THREAD

**Issue by CmdrKittens** [drtshock/Factions#1292]
![image](https://user-images.githubusercontent.com/52665651/63957746-05378180-ca57-11e9-8233-327eb6f3c3ef.png)

**Comment by Neeonn** [comment]
Isn't that just the character limit? Color codes count as characters as well if I'm not wrong, and you have several spaces before "Name:".

**Comment by CmdrKittens** [comment]
Resolved, coming soon to 0.5.3 release.
