### ISSUE TITLE
/f top money, wrong balance

### ISSUE THREAD

**Issue by Defterdar** [drtshock/Factions#1295]
### FactionsUUID Version
*Run `/f version` and give us your output.* 
Factions v1.6.9.5-U0.4.9-b187 (edit: updated to last dev, just in case)

### Server Version
*Run `/version` and give us your output.*
Paper version git-Paper-183 (MC: 1.14.4)

### Details
Running `/f top money` gives wrong balance. Looking directly at a faction gives correct money balance.
![ftop](https://user-images.githubusercontent.com/9363370/64251336-9fe10600-cf18-11e9-9691-26d034d718a3.png)

fyi, running EssentialsX version: 2.17.1.12 and Vault v1.7.2-b107

**Comment by CmdrKittens** [comment]
Seems the `/f top` command adds on the player balances on top of the faction's balance.

Not sure if which is the ideal strategy.

**Comment by Defterdar** [comment]
It must be some default value, because the players own balances is like >1mil
quick notice: the `/f top` balance is 2000$ off per player in the faction

**Comment by Ichbinjoe** [comment]
Claiming

**Comment by mbax** [comment]
Will be resolved in 0.5.25, coming soon.
