### ISSUE TITLE
Scoreboard to only show on one world

### ISSUE THREAD

**Issue by phantom881** [drtshock/Factions#1296]
### Idea
*Tell us what you want!*
have the ability to only show the factions scoreboard on one world

### Details
*Give some more information so we can get an idea.*
right now the scoreboard shows on all worlds which is a really big problem for servers like mine which arent just factions, my server is factions, kitpvp and survival with a world for each one of these but the scoreboard shows on all worlds which is a big problem so i'd really like to see you add it so that in the config there will be a "disabled worlds" where users can input world names were the scoreboard wont show on these worlds

**Comment by CmdrKittens** [comment]
This would probably fall under #1288 

Check out the recent comment for information on helping test it out with a test jar.

**Comment by CmdrKittens** [comment]
Above linked PR is merged
