### ISSUE TITLE
Beast Core Compability

### ISSUE THREAD

**Issue by xdLulux** [drtshock/Factions#1300]
### FactionsUUID Version
*Run `/f version` and give us your output.* 
Factions v1.6.9.5-U0.5.2-b198

### Server Version
*Run `/version` and give us your output.*
TacoSpigot Fork 1.8.8

### Logs
[latest.log](https://github.com/drtshock/Factions/files/3667138/latest.log)

### Details
*hello, I have a lot of plugins that is compatible with FactionUUID but since couple updates you guys change the compability stuff and one of you team member called mbaxter after the version 0.5.0 all compabilities change and I should send the plugin in the discussion channel in discord, the problem is that the plugin is a paid one, its called BeastCore and here is the discord of the dev: BrutalFisting
#5341 and here is the discord of the plugin https://discord.gg/sN4SwWf . I hope this could fix the compabilities since a lot of users are complaning etc. have a nice day

**Comment by CmdrKittens** [comment]
Beast Core do not share their source openly, so I cannot contribute any code to them to assist. As a paid plugin that treats its code as inexplicably sacred ("You are not allowed to decompile this resource. You are not allowed to redistribute this resource"), the burden is on them to maintain compatibility.

Reach out to them for updating their plugin. We are, of course, willing to answer any questions they have. I'm closing this issue, but that does not mean conversation here has to stop. Feel free to reply here. 😃 

If you have other plugins also breaking, create a new issue for them.
