### ISSUE TITLE
[Suggestion] Adding placeholders for the territory a player is standing on

### ISSUE THREAD

**Issue by Jadiction** [drtshock/Factions#1301]
### Idea
While standing on a faction's territory, placeholders for that faction would be nice. The idea is when you're standing on their territory, you can put the faction's name & whatever else you'd want in the scoreboard.

Also, if you're not standing on a claimed territory, perhaps add a configuration to change what the `territory_name` placeholder is. For example, I'd like (and probably default) it to be Wilderness.

### Details
Some examples could be:

%factionsuuid_territory_name%
%factionsuuid_territory_raidable%
%factionsuuid_territory_power%
%factionsuuid_territory_online%
%factionsuuid_territory_offline%
%factionsuuid_territory_leader%
etc...
(Essentially, you could add most, if not all the placeholders from the "Faction" category)

**Comment by dariasc** [comment]
Seems like a simple change, could definitely add this if other people are onboard
