### ISSUE TITLE
config missing enabled-worlds

### ISSUE THREAD

**Issue by timriker** [drtshock/Factions#1308]
### FactionsUUID Version
> f version
[17:32:25 INFO]: You are running Factions v1.6.9.5-U0.5.3-b200

### Server Version
> version
[17:32:42 INFO]: This server is running Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[17:32:42 INFO]: Checking version, please wait...
[17:32:43 INFO]: Previous version: git-Paper-186 (MC: 1.14.4)
[17:32:43 INFO]: You are 1 version(s) behind

### Logs
*Give use your logs by going to `logs/latest.log`.*

### Details
This fails:
unzip -c Factions-200.jar config.yml | grep enabled-worlds

Note: if you want access to my server, holler on Discord. Great work!

**Comment by animeavi** [comment]
Its in main.conf, it's generated at runtime.

**Comment by CmdrKittens** [comment]
Look for `restrictWorlds` in `main.conf` :)

**Comment by timriker** [comment]
I don't see a main.conf in the jar file. I suppose this is a work in progress, right? How would upgrading users know what to add? I manually extracted the config.yml from the jar and did the merging by hand. This is removing the old perm ui settings, adding things like {raidable} that were missing, etc. How is an upgrade user to find these changes? I don't see a main.conf in the jar file.

There are some other config changes that could happen.
* explain what "factionless-enable" does.
* {raidable} is not listed in the variables list
* \<a\> and \<i\> could be documented
* list.factionless could use a \<a\>
* s/will not sure up/will not show up/
* [raidable] should be {raidable} ?
* I add Kills, Deaths, and Enemies to show
* I add Raidable (and DTR) to list.entry
* I shorten some of the scoreboards
* hcf.dtr should probably be removed and replaced with format lines

My config here:
https://pastebin.com/gaqNuiC5
By the way, I like the improvements. :)

**Comment by CmdrKittens** [comment]
> I don't see a main.conf in the jar file.

It isn't there, because it's generated on startup.

> I suppose this is a work in progress, right?

Nope, it's in already.

> How would upgrading users know what to add?

They need to add nothing, it auto-generates the relevant sections on startup.

Though, I'm open to the idea of auto-generating a viewable diff between versions for folks who don't want a double reboot.

Could you create a new ticket for the config proposals? :)
