### ISSUE TITLE
/f list - show raidable status

### ISSUE THREAD

**Issue by timriker** [drtshock/Factions#1309]
### Idea
/f list should show raidable status

### Details
This might be a "(raidable)" text, or a color change, or both. :)

Perhaps this is already indicated here and I'm not seeing it?

I changed list.entry to:
`entry: '<a>{faction-relation-color}{faction} <i>{online} / {members} online, <a>Land / Power / Maxpower: <i>{chunks}/{power}/{maxPower} <a>Raidable: <i>{raidable}'`
which might be a good default.

**Comment by CmdrKittens** [comment]
What does it look like when you set that list entry?

**Comment by timriker** [comment]
looks great except for "DTR:" being in the wrong color. IMHO, hcf.dtr should go away and DTR: should be added to the relevant display strings.
What does hcf stand for here? :)
Console output:
```
[15:30:24 INFO]: ----------[ Faction List 1/1 ]----------
[15:30:24 INFO]: Factionless 0 / 10 online
[15:30:24 INFO]: TheIrish 0 / 8 online, Land / Power / Maxpower: 27/38/80 Raidable: false DTR: 3
[15:30:24 INFO]: PartyBus 0 / 7 online, Land / Power / Maxpower: 50/57/70 Raidable: false DTR: 2
etc
```

**Comment by CmdrKittens** [comment]
DTR is now (well, will be in 0.5.4) its own separate item.
