### ISSUE TITLE
/f access

### ISSUE THREAD

**Issue by oFrostMC** [drtshock/Factions#131]
Like in new factions there is this one very useful command that replaces /f owner - /f access. I am playing on a server based off of your plugin and I really would like it if they updated it with /f access - as they know minimal coding and are using only your plugin and its updates.

**Comment by JordanAtFuze** [comment]
I would like to see this added aswell.

**Comment by RenegadeEagle** [comment]
There is no difference other then the command alias I believe.

**Comment by drtshock** [comment]
What exactly am I adding that can't be done with /f mod or /f owner?

**Comment by oFrostMC** [comment]
With /f access there are many pros - its a huge time saver and it does something that f owner does not.
1. /f access will allow you to access/remove access to WHOLE Factions instead of just 1 player as /f owner you can only access individual players/factions.
2. You can access players not in a faction/another faction which im pretty sure /f owner does not have
3. You can do all of this much faster 
4. /f mod makes you a moderator in the faction that you can do anything like invite, kick, unclaim, claim,etc - If you need a reference any version 1.8.2 and up includes this command

**Comment by drtshock** [comment]
@oFrostMC your message really confuses me

**Comment by drtshock** [comment]
#146 explains it better.
