### ISSUE TITLE
About one of the placeholders for PAPI

### ISSUE THREAD

**Issue by itsmezed** [drtshock/Factions#1316]
The current placeholder for land value is not working, it's not registered or something. Is this something you could look into?

**Comment by drtshock** [comment]
Can you please fill out the issue template that you ignored... Otherwise we can't help.

**Comment by CmdrKittens** [comment]
Without further info, best I can offer:

`factionsuuid_faction_land_value` is the placeholder and it works as long as you have an economy plugin, vault, and econ enabled in factionsuuid. Otherwise it by default says "no value"

**Comment by itsmezed** [comment]
Where would I find it?

**Comment by itsmezed** [comment]
@CmdrKittens It does not work, when I parse it, it just returns with the actual argument/placeholder.

**Comment by CmdrKittens** [comment]
@itsmezed You just closed it. Does this mean you resolved it? I'd be curious how you fixed it :)
