### ISSUE TITLE
Issue with one of your placeholders.

### ISSUE THREAD

**Issue by itsmezed** [drtshock/Factions#1317]
### FactionsUUID Version
I am currently using SavageFactions which includes your placeholders etc, the version is:
Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-6

### Server Version
Since we're runnig beerspigot, what I got was BeerSpigot premium "1.2", a part from that we're using 1.8.8.

### Logs
I could not provide this cause of privacy information.

### Details
It's quite easily explained, %factionsuuid_faction_land_value% is not working for me, I honestly don't know why. When using /papi parse me %factionsuuid_faction_land_value%, then it returns with the placeholder (not empty, no number, no string or anything).

**Comment by CmdrKittens** [comment]
Howdy! You're going to want to upgrade to FactionsUUID, which is a substantially better maintained plugin. 

Once you've done so, come on back and let us know how well that placeholder is successfully running! :)

**Comment by CmdrKittens** [comment]
Can confirm, it's broken in their plugin. Not in ours! :)

**Comment by itsmezed** [comment]
Good to know, thank you very much. I will update your plugin and run that instead!
