### ISSUE TITLE
Issue with /f disband command

### ISSUE THREAD

**Issue by MrKittle** [drtshock/Factions#1318]
### FactionsUUID Version
*Run `/f version` and give us your output.* 

**Factions v1.6.9.5-U0.5.3-b200**

### Server Version
*Run `/version` and give us your output.*

**This server is running CraftBukkit version
git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API
version 1.12.2-R0.1-SNAPSHOT)**

### Logs
*Give use your logs by going to `logs/latest.log`.*

**The issue  doesn't show error at all.**

### Details
*Please explain the problem.*

**I noticed that when using the / f disband <faction> command, if I omit the faction argument, the command runs and informs me that the amount of the faction bank has been restored. However, this amount actually remains in the suppressed faction. Later, if another player creates a faction with the same name as the one I just deleted, he then recovers the faction with the amount it contained.

I think you could simply make a change to control that the <faction> argument is mandatory when using this command.

Edit 00:39 07/11/2019 -> This issue occures when the disbanded faction was set to permanent (/f permanent)  If define it as "non permanent" all works well.

With thanks.
Regards,
Mr_Kittle**

**Comment by CmdrKittens** [comment]
Hi @MrKittle ! Sorry, I missed this ticket come in. I'll look into this soon. :)

**Comment by CmdrKittens** [comment]
Are you certain permanent is the correct term? I'm looking at the code and any permanent faction gets this:

> This faction is designated as permanent, so you cannot disband it.

**Comment by MrKittle** [comment]
Hello,
I was misled by a sentence telling me that the amount of the faction bank had been returned to me when it had not been returned. The faction I dissolved could not be because it was defined as "permanent". The fact of having received a notification of success in the dissolution of the faction accompanied by another notification of refund of the amount of the bank let me think that the faction was well destroyed. I think there is a notification of success that should not be present. Cordially.
Kittle

**Comment by CmdrKittens** [comment]
```java
if (faction.isPermanent()) {
    context.msg(TL.COMMAND_DISBAND_MARKEDPERMANENT.toString());
    return;
}
```

This code causes a disband attempt to be abandoned long before the money returning messages happen, long before any success messages fire.

Based on your unsubstantiated claims of severe, improbable bugs moments before leaving our support discord (before we could get any information to help fix the claimed issues) I'm not going to further investigate this issue until reported by another user.

**Comment by drtshock** [comment]
```Logs
Give use your logs by going to logs/latest.log.

**The issue doesn't show error at all.**
```

It really bothers me when people do this. We're not asking for logs looking for errors. We log a lot of things that aren't necessarily errors that are helpful for debugging.

If you want help, please provide the info we asked for.
