### ISSUE TITLE
Issue with /f invite

### ISSUE THREAD

**Issue by maginka** [drtshock/Factions#132]
I invite a player to the faction, and in game, I see in my chat
*_Magz Magz has invited you to join Magz
*_ Magz invited Harribo to your faction.

The invited player Harribow doesnt see anything.

If i do /f deinv Harribow, the player does see
**Magz Magz revoked your invitation to Magz

I just reverted back to the version available on spigot, and the Invite works as expected.

This behaviour occurs on builds from 128 to latest, 132

I see no errors in the console whatsoever, so nothing to report or show you there.

**Comment by drtshock** [comment]
Oh I see. I have it sending to the wrong player. Nice catch ;)
