### ISSUE TITLE
Title descriptions

### ISSUE THREAD

**Issue by KyroOW** [drtshock/Factions#1320]
Show factions descriptions in titles like it does in factions 2.

Currently in FactionsUUID it doesn't show it, which results in this: https://i.imgur.com/yxcPP4O.png

It should show this: https://i.imgur.com/qfvhihh.png (without the parenthesis of course)

**Comment by KyroOW** [comment]
Description text color should be light gray (&7) for some contrast with the white neutral faction name. (Or perhaps configureable color ?)

**Comment by CmdrKittens** [comment]
https://github.com/drtshock/Factions/commit/b4032690ce3af428afaa4a689fdd946fa1eb3d56

**Comment by CmdrKittens** [comment]
Better customization added in the next commit. It now handles color codes too.
