### ISSUE TITLE
TnTBank

### ISSUE THREAD

**Issue by storm0chaser** [drtshock/Factions#1321]
A virtual storage tnt storage bank which can be viewed with /f tnt 
You can fill dispensers with /tntfill (amount) (range)
/untntfill (range)
which well untntfills

Making sure it works with other plugins such as tntwands would be a huge +
/f tnt d/deposit 
deposits tnt in your inventory 
/f tnt t/take (amount)
takes tnt out of the bank and puts it into your inventory

**Comment by CmdrKittens** [comment]
> /tntfill (amount) (range)

Would range mean any dispenser within that many blocks gets that amount of TNT? Is the amount a per-dispenser or a total balanced among them?

> which well untntfills

What does that mean?

> /f tnt t/take (amount)

Perhaps withdraw, as that's used elsewhere, as another way of writing it?

**Comment by storm0chaser** [comment]
It would get all of the tnt from the dispensers and put any tnt in them into your f tnt bank in the range said by the command.
So if f untntfill 30 (would take tnt within 30 blocks range)
f tnt withdraw would be much better thanks.

**Comment by CmdrKittens** [comment]
But for filling, is the amount the total, or per-dispenser? As in, if I did `/tntfill 30 5` with 3 dispensers nearby, would each get 30, or would each get 10 (30 divided by 3 dispensers) ?

**Comment by storm0chaser** [comment]
per dispenser thanks

**Comment by CmdrKittens** [comment]
If there's not enough to fill them (90 in the above example) which should it do:

* Fail with error message
* Attempt to evenly distribute with message indicating such ("I could only put 20 in each")
* Fill starting with closest to player, meaning some will have less or none (30, 30, 0)
* Kill the player, distribute the faction's TNT around its land claims but in particular around chests and expensive blocks, disband the faction, and ignite all the TNT (in waves so subsequent explosions damage items dropped in the first wave)

**Comment by storm0chaser** [comment]
A error message saying, to fill this you need “x” amount to fill this. You have “c” amount.


Also can you make the f tnt balance a customisable amount which can be changed in config.

**Comment by xxJinxedxx** [comment]
All of these together can be a combined solution if: (amount TnT) < (X-range of X-Dispensers) 
1. Attempt to evenly distribute.

2. Fill starting with closest to player, meaning some will have less or none (30, 30, 0)

3. Fail with error message (You didn't had enough TnT in you TnT Bank to fill/distribute equally across all dispensers in that radius.)

**Comment by storm0chaser** [comment]
I think 1 would be best. As long as it evenly dispenses all the tnt.

**Comment by CmdrKittens** [comment]
Added, will appear in 0.5.7
