### ISSUE TITLE
Factions Scoreboard

### ISSUE THREAD

**Issue by obraundawg** [drtshock/Factions#1323]
This, I feel, could go under all 3 categories. I'm not familiar with placeholders or making scoreboards, and I'm grateful that this one already has a scoreboard plugin built in, but I think there should be more description behind the scoreboard set up and an example template for the scoreboard. I looked all over for specific videos on it, but I could only find FeatherBoard videos. It might just be me, but I feel some other users are having issues with this. This is more a reach for help than anything, and I understand this isn't your responsibility for the few who can't figure it out, but please take this into consideration. If someone could send me a template or an example of a configuration and output that would be great. Thanks and have a good day.

**Comment by CmdrKittens** [comment]
Check out the scoreboard section of the `config.yml` file!

A good starting place would be to set `default-enabled` to true, and look at what modifying values in the `default` section below it does.

Maybe explain what you're trying to do?
