### ISSUE TITLE
Factions broke my rank plugin

### ISSUE THREAD

**Issue by SydneyMae** [drtshock/Factions#1326]
### FactionsUUID Version
Factions V1.6.9.5-U0.2.2-b116

### Server Version
MC: 1.14.4 CraftBukkitVersion: git-Spigot-56f8471-7554e08

### Logs
Nothing in logs

### Details
Your plugin disabled my rank plugin, so now all of my players do not have access to perms, and the ranking system  (Member, VIP, MVP, ect) has stopped showing up entirly. Please tell me how to disable your chat override.

**Comment by CmdrKittens** [comment]
Howdy! Go ahead and grab the latest release off spigot first! Link: http://www.spigotmc.org/resources/factionsuuid.1035/

 You're running code from almost two years ago!

Try that out, see what issues you run into, then create a new reply with the updated info. For version stuff please just run `/f debug mini` which will give us the server and plugin version and paste all four lines.

**Comment by SydneyMae** [comment]
I am 1 version behind, and I don't know how to update spigot without having to reinstall everything. Also, running the /f debug mini command gives me a "Strange Argument" error

**Comment by CmdrKittens** [comment]
My download link above was to FactionsUUID not to spigot! :) Your Factions version is almost 2 years outdated.

Download the new FUUID, stop the server, place the plugin jar in the plugins folder replacing the current one, and start the server.

**Comment by SydneyMae** [comment]
Ah, alright, thank you

**Comment by CmdrKittens** [comment]
You are welcome to just leave it open until you get things figured out, but if you prefer you could make a new ticket. Don't forget to run `/f debug mini`  :)
