### ISSUE TITLE
Vault and economy plugins are not working.

### ISSUE THREAD

**Issue by aldumgames** [drtshock/Factions#1327]
I've tried but no one can transfer any money from their wallet to their factions and cant buy land.

**Comment by CmdrKittens** [comment]
Howdy! To make things simpler, could you please run `/f debug` and share that URL here! :)

**Comment by aldumgames** [comment]
https://paste.gg/p/anonymous/f24118149a0542d687f1574dae69a62b

**Comment by CmdrKittens** [comment]
Hmm. Everything there looks fine enough. Can you check the server log when you try to run one of those commands? There is possibly a big ol' stacktrace (giant error thing). I'd like to see the whole thing if you have one. If not I'll need to look a bit closer at how ultimate economy works.

**Comment by aldumgames** [comment]
Nothing, it's just nobody has the ability to put money in their faction, and the funny thing is when we do /f top the money shows up, but when you do /f money b it says 0

**Comment by CmdrKittens** [comment]
What happens if you try a different economy plugin?

**Comment by aldumgames** [comment]
the last time i tried it almost crashed the server

**Comment by aldumgames** [comment]
we're running 1.14.4, and there aren't many economy plugins

**Comment by aldumgames** [comment]
we tried aconomy and faction hated it, it threw errors left and right

**Comment by CmdrKittens** [comment]
From usage stats, it appears the most success is had using Essentials economy

**Comment by aldumgames** [comment]
where can I get it

**Comment by aldumgames** [comment]
can you tell me where to get it.

**Comment by CmdrKittens** [comment]
https://essentialsx.github.io/#/

Google is your friend :)

**Comment by aldumgames** [comment]
Yeah, I wasn't sure if it was that essentials, there are a few.

**Comment by aldumgames** [comment]
yeah, I guess factions doesn't work with aconomy and ultimate economy, although it would bee amazing if it worked with ultimate, but it is fine.

**Comment by CmdrKittens** [comment]
This may be resolved in the next release. If not, it probably can't be resolved.
