### ISSUE TITLE
/f power {name} {#}

### ISSUE THREAD

**Issue by thomasb454** [drtshock/Factions#133]
Hi,

I think it would be great if you could add a command to set a player's power.
In the title I've provided what I think would be a suitable way of achieving this.

Thanks!

**Comment by drtshock** [comment]
Definitely want to add this. How does this syntax sound:

/f power <name> <#>

**Comment by thomasb454** [comment]
You'd need to add a name field to modify others.

**Comment by drtshock** [comment]
Oh, I typed that as <name> but it didn't show up

**Comment by drtshock** [comment]
Ugh
/f power name number

**Comment by thomasb454** [comment]
Heh, no worries.

Sounds great!
