### ISSUE TITLE
No autocomplete for /f money

### ISSUE THREAD

**Issue by ewof** [drtshock/Factions#1331]
### Stuff
    
    1.6.9.5-U0.5.6-b210 however mbaxter gave me a custom jar to fix a bug with TNE and Factions and Vault

### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 
https://elwolf6.feen.us/3pm74e.png

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://hastebin.com/mococazuqe.md
https://elwolf6.feen.us/8qmch6.png
    https://elwolf6.feen.us/x8z957.png
    https://elwolf6.feen.us/g2venq.png

### Details
*Please explain the problem.*
the command `/f money` the "money' part autocompletes if u type in `/f m` but if you do `/f money d` it doesnt autocomplete to "deposit" it shows the d in red text and says that its an error (even tho the command runs completely fine) even when you type out `/f money deposit`

**Comment by CmdrKittens** [comment]
Resolved for 0.5.7
![image](https://user-images.githubusercontent.com/52665651/71775752-2e5fa580-2f54-11ea-8336-07ec03c305ae.png)
