### ISSUE TITLE
log dynmap support on startup

### ISSUE THREAD

**Issue by timriker** [drtshock/Factions#1333]
On mod load Factions loads many useful state messages, but I don't see one for when it enables dynmap support. It might be useful to log whether enabled or disabled to give an indication that it's available. ie:

`[Factions] Enabling support for Dynmap v3.0-beta-8-244
`
or

`[Factions] No dynmap plugin detected`

or can it be disabled?

`[Factions] Detected Dynmap v3.0-beta-8-244, but dynmap disabled`

**Comment by CmdrKittens** [comment]
https://github.com/drtshock/Factions/commit/f591402eaecfb8b2b4323a020e3311fbaecf2d80

**Comment by timriker** [comment]
Would be nice to log the version as well. I think that's this?
Plugin.getDescription().getVersion();
