### ISSUE TITLE
F Owner collides with f perms

### ISSUE THREAD

**Issue by imuncertain** [drtshock/Factions#1338]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 

### Logs
*Give use your logs by going to `logs/latest.log`.*

### Details
I have adjusted all of the config files, ensured I was even updated to the latest FUUID changed all the existing factions data to no avail, when I'm in a faction territory, if it is owner claimed I cannot open the chests, if it is not owner claimed I can.

**Comment by mbax** [comment]
Covered by upcoming zones feature. Redirecting issue to #1437
