### ISSUE TITLE
Faction Chest

### ISSUE THREAD

**Issue by Avizoh** [drtshock/Factions#1343]
### Idea
*Tell us what you want!*
To have a virtual chest, sort of like a playervault, but for the FACTION.
Command: /f chest
This will allow players to store trench pickaxes etc.

Also another command: /f chestlog
This will allow whatever role that is set in /f perms to have permission to see who took said items out. with timestamps.

### Details
*Give some more information so we can get an idea.*
Virtual player vault for a faction. Non-raidable, ONLY 1 row, so a total of 9 slots.

**Comment by CmdrKittens** [comment]
Worth noting the plugin already has PlayerVaultsX integration which allows for a faction-shared inventory.
