### ISSUE TITLE
Faction Vault/TNT Fill

### ISSUE THREAD

**Issue by Avizoh** [drtshock/Factions#1345]
### Idea
*Tell us what you want!*
A faction vault with tnt with tntfill support.
https://gyazo.com/fca94dc76e623944021fa27f77591a72
https://gyazo.com/2fe65f26ce90d26e1b8a4122ef5fab1e

/f vault - opens the faction vault

w - withdraw ; d - deposit ; f - fill
/f tnt <w;d;f> <amount> <radius>
Command is kind of self explanatory.
Have a check if args[2] (if counting f as an arg) otherwise args[1] is w OR d then have it ignore the <radius> portion of the command

### Details
*Give some more information so we can get an idea.*
This would allow a faction to deposit tnt into their vault, while allowing players to withdraw tnt by using the tntfill.

**Comment by CmdrKittens** [comment]
The vault side is already covered by another ticket of yours, and this plugin has had TNT bank support since the latest release :)
