### ISSUE TITLE
Customizable Info Scoreboard Title

### ISSUE THREAD

**Issue by ewof** [drtshock/Factions#1348]
### Idea
Customizable Info Scoreboard Title

### Details
I want to be able to change the title of the info scoreboard like how you can on the constant scoreboard. It would be nice if there could be a placeholder u could put to change the color depending on relationship so people can choose if they want it to be like that but if not a simple bool called something like colorByRelationship would be cool.

**Comment by CmdrKittens** [comment]
Coming soon to a 0.5.8 near you
