### ISSUE TITLE
Territory relation color placeholder & A couple other placeholder suggestions

### ISSUE THREAD

**Issue by Jadiction** [drtshock/Factions#1352]
### Idea
For the (relatively new) territory placeholders, I'd like to have a relation color for the name placeholder (%factionsuuid_faction_territory_name%).

### Details
The idea is to add a new placeholder for the faction territory name relation color. 

### Idea 2
A placeholder to display the total amount of allies online and total members.

### Details 2

%factionsuuid_ally_online%

%factionsuuid_ally_offline%

%factionsuuid_ally_size%

**Comment by CmdrKittens** [comment]
Added and tested!
