### ISSUE TITLE
Disabling faction fly

### ISSUE THREAD

**Issue by RyzeR0it** [drtshock/Factions#1355]
(This is for my friend I am trying to help him out) He has a 1.15.2 Minecraft server, factionsUUID updated to the latest update, and he wants to disable faction fly, but no matter what he does faction fly doesn't stay disabled.

**Comment by CmdrKittens** [comment]
Please create a new issue following the instructions by clicking here - https://github.com/drtshock/Factions/issues/new?template=issue.md

Alternatively, visit our Discord support for faster answers - https://discord.gg/PHpuzZS
