### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by Drc-DEV** [drtshock/Factions#1356]
stacktrace: https://pastebin.com/Pai0rmnq

Since commit f5545d6 factions does not startup due to an IllegalArgumentException (Configuration does not accept objects of type class com.massivecraft.factions.config.file.DynmapConfig$Style), see the paste for the stacktrace.

@CmdrKittens

**Comment by CmdrKittens** [comment]
Known issue, thanks! Try the latest *release* from here instead - https://www.spigotmc.org/resources/factionsuuid.1035/

**Comment by Drc-DEV** [comment]
I just wanted to report, I use my own fork, so I'll just cherry pick that commit for now.

**Comment by drtshock** [comment]
Care to PR anything upstream? <3

**Comment by CmdrKittens** [comment]
Request for PR still stands, but this specific issue is resolved.

**Comment by Drc-DEV** [comment]
> 
> 
> Care to PR anything upstream? <3

Sure why not

**Comment by Drc-DEV** [comment]
PR is opened https://github.com/drtshock/Factions/pull/1357
