### ISSUE TITLE
Per chunk player/faction access

### ISSUE THREAD

**Issue by dice231** [drtshock/Factions#1358]
### Idea
Implementation of an /f access command to give players or factions the ability to interact with blocks and other stuff within a chunk.

### Details
Giving someone access in a chunk would allow them to build, open chests, interact with buttons, levers, etc. The command ‘/f access view’ would be used to view who has access within the chunk you are standing in. ‘/f access player <player> yes/no’ would either give/revoke access to a player within the chunk you’re standing in and ‘/f access faction <faction> yes/no’ would do the same except for an entire faction. By default these commands would be available for mods+ but maybe the ability to change that in /f perm could be added.

**Comment by mbax** [comment]
Covered by upcoming zones feature. Redirecting issue to #1437
