### ISSUE TITLE
FactionsUUID Wont work

### ISSUE THREAD

**Issue by AquaDripper** [drtshock/Factions#1362]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 

### Logs
ERROR Error occurred while enabling Factions v1.6.9.5-U0.5.8-b220 (Is it up to date?)
04.03 04:30:37 [Server] INFO java.lang.NullPointerException
04.03 04:30:37 [Server] INFO at com.massivecraft.factions.data.json.JSONFactions.loadCore(JSONFactions.java:88) ~[?:?]
04.03 04:30:37 [Server] INFO at com.massivecraft.factions.data.json.JSONFactions.load(JSONFactions.java:68) ~[?:?]
04.03 04:30:37 [Server] INFO at com.massivecraft.factions.FactionsPlugin.onEnable(FactionsPlugin.java:333) ~[?:?]
04.03 04:30:37 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
04.03 04:30:37 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

### Details
I dotn know why its not working like I cant claim or nothing

**Comment by CmdrKittens** [comment]
Howdy! Here's some thoughts:

1. If you hop onto our support discord we may be able to resolve this faster.
2. Do you use a FactionsTop plugin? We have seen several instances recently of Factions crashing in the presence of some other plugins.
3. Can you provide your whole server log? You could privately send it if on our support discord.

[Support Discord](https://discord.gg/PHpuzZS)
