### ISSUE TITLE
Faction Bank clearing for no reason

### ISSUE THREAD

**Issue by Spyhawkguy** [drtshock/Factions#1363]
Details
For no reason the faction bank is clearing for every faction. It happens at random times so I can get any more info on it.

**Comment by CmdrKittens** [comment]
The economy code has been reviewed a few times in full since this ticket, and it appears sound. This ticket lacks any information that could help beyond code review.

If this issue persists, please reach out over discord where we can throw custom builds into the mix for debugging purposes.
