### ISSUE TITLE
Ability to specify protected/unprotected containers/blocks in config

### ISSUE THREAD

**Issue by Fishbowl1864** [drtshock/Factions#1369]
### Idea
It would be great for there to be a way to specify containers (and blocks as a whole) to either be protected or not protected in config. 

### Details
Some other factions plugins I've worked with in the past (been setting up factions servers since ~2015) had some sort of list of protected things that you could add or remove things from, like pressure plates, buttons, trapped chests, normal chests, furnaces, etc. For example our community would like to be able to disable protections for barrels in claimed territory so outsiders can leave items in these containers. Being able to configure this would add a lot more adaptability to the plugin, and would let it apply to more use cases as some people want only doors protected but not chests or any other odd combo of protections.

Spoke to mbaxter on the Discord and he said a container exception list was a decently viable and simple thing to add and told me to put an issue up on github.

**Comment by CmdrKittens** [comment]
https://github.com/drtshock/Factions/commit/0a2f2070e80196f379a4d3cb5bc600f0ed92ee42
