### ISSUE TITLE
The ability to protect creatures in peaceful territories 

### ISSUE THREAD

**Issue by Jadiction** [drtshock/Factions#1372]
### Idea
The ability to disable creature damage in peaceful territories. I.E if a peaceful faction has villagers and animals in a claim, they should not be damaged by other players.

### Details
The idea behind this is so peaceful factions can freely build aesthetically (as opposed to strategically) without the worry of their animals being killed or harmed.
This may even be a nice option for non-peaceful factions as well but disabled by default. Everyone loves customization!

**Comment by mbax** [comment]
`territoryBlockEntityDamageMatchingPerms` config option should resolve this. Missed closure before.
