### ISSUE TITLE
/f bypass does not allow admins to use /f warpother

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1373]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 
Paper Version: git-Paper-133 (MC: 1.15.2)
Server ID: 33fa72db-c2a7-4fac-00a00009c5c9
Plugin Version: 1.6.9.5-U0.5.9-b222
Java Version: 1.8.0_191

### Logs
*Give use your logs by going to `logs/latest.log`.*
[latest.zip](https://github.com/drtshock/Factions/files/4376932/latest.zip)

### Details
As stated on the title, Admins who has enabled /f bypass are unable to use /f warpother. The output message says "You do not have permission to use (Faction) warps."

**Comment by BboyZeroOne** [comment]
Bump

**Comment by CmdrKittens** [comment]
Added for 0.5.11
