### ISSUE TITLE
/f powerboost add/set

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1374]
### Idea
*Tell us what you want!*
I would like to add a new feature for the current /f powerboost. /f powerboost (set/add) (faction/player) (name) (amount)

### Details
*Give some more information so we can get an idea.*
Currently it is only /f powerboost (faction/player) (amount).

I would like to have an option added where admins can add/set the amount of powerboost a faction can have with /f powerboost add (faction/player) (amount).

I am currently using a reward system where players can exchange points for faction powerboost. The current limitations of /f powerboost (faction/player) (amount) does now allow additional power but only a set amount of power. Therefore, if players continue to buy more powerboost, it will add to their current powerboost which the console executes /f powerboost add (faction/player) (amount)

Thanks for your time. I would really hope this suggestion would be implemented. Cheers!

**Comment by BboyZeroOne** [comment]
Bump. Hope this suggestion won't go un-noticed.

**Comment by mbax** [comment]
Forgot to close this when it was added.
