### ISSUE TITLE
Name in plugin.yml is not unique

### ISSUE THREAD

**Issue by hornta** [drtshock/Factions#1376]
I want to integrate my plugin with FactionsUUID but I'm having problem distinguishing this plugin with other factions-like plugins because the name in the plugin.yml is simply **Factions**.
Consider changing it to FactionsUUID to enable plugin developers to easily identify this plugin in their depend/softdepend list and also when they are checking if the plugin is loaded with this:
```Bukkit.getServer().getPluginManager().getPlugin("Factions")```

I've made a thread on this in Spigot forums also:
https://www.spigotmc.org/threads/plugins-with-same-name.427007/

**Comment by CmdrKittens** [comment]
Changing this name would break *all integrations* with the plugin.

Instead, you can identify FactionsUUID by version because we set our version in a very specific way. It starts with `1.6.9.5-U`, for example it presently starts with `1.6.9.5-U0.5.10` as we are currently at version 0.5.10
