### ISSUE TITLE
Other types of explosion are not prevented for 'offline' and 'peaceful' factions claims

### ISSUE THREAD

**Issue by cybermancerr** [drtshock/Factions#1377]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 
Paper version: git-Paper-155 (MC: 1.15.2)
Server ID: af84593d-506f-4fac-afac-012c00005f81
Plugin version: 1.6.9.5-U0.5.7-b215
Java version: 1.8.0_242

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://gist.github.com/cybermancerr/0c312dff4cc623ec38b1183c703e9f41

### Details
*Please explain the problem.*
other-explosion are not blocked in offline factions and peaceful factions claims. for example worldguard flag does this with '/region flag __global__ other-explosion deny' command.  Regions with this flag block all other types of explosions successfully.
Would like to be able to do this in faction config for offline and peaceful factions claims
main reason is because on my server we have Movecraft plugin and the torpedoes use other-explosions that bypass all factions protections when they explode, making offline and peaceful claims useless.  Here is what I found from WorldGuard GitHub in regards to 'other-explosions' code they used. https://github.com/search?q=blockOtherExplosions+repo%3AEngineHub%2FWorldGuard&type=Code

**Comment by CmdrKittens** [comment]
Coming to 0.5.11:

Peaceful factions no longer experience the previously not covered explosion events, if they are set to not have explosions.

Also, these config items:

```
territoryBlockOtherExplosions
territoryBlockOtherExplosionsWhenOffline
safeZoneBlockOtherExplosions
warZoneBlockOtherExplosions
wildernessBlockOtherExplosions
```
