### ISSUE TITLE
Factions Tax

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#138]
Everything described here basically http://www.spigotmc.org/resources/factionstax.1913/

**Comment by Techcable** [comment]
Do you already have a dependency on vault?

**Comment by cnr** [comment]
[Yes](https://github.com/drtshock/Factions/blob/1.6.x/pom.xml#L80-L85)

**Comment by Techcable** [comment]
Would it be implemented as a separate plugin, or added to this?

**Comment by drtshock** [comment]
Added to this.

**Comment by Techcable** [comment]
Working on this in [my fork](https://github.com/Techcable/Factions/tree/tax)

**Comment by cnr** [comment]
Something to keep in mind (that I noticed in your first commit): any submitted code that requires a lombok dependency is unlikely to be accepted.

**Comment by drtshock** [comment]
Can you explain your design decision to make TaxFaction and TaxPlayer (offline player based) objects?

**Comment by Techcable** [comment]
@drtshock 
Those are wrapper classes to simplify access to FPlayer and Faction because I wanted to minimize modifications to FPlayer and Faction.  Taxes and balance may still need to be retrieved for offline players. I think I will base TaxPlayer around FPlayer though.
@eueln 
Removing it from code

**Comment by drtshock** [comment]
rip
