### ISSUE TITLE
Peaceful Faction players unable to cure zombie_villager

### ISSUE THREAD

**Issue by DJLost12** [drtshock/Factions#1380]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 
[19:59:13 INFO]: Tuinity version: git-Tuinity-"071c8ed" (MC: 1.15.2)
[19:59:13 INFO]: Server ID: 45240292-c2a7-4fac-afac-0030000017ae
[19:59:13 INFO]: Plugin version: 1.6.9.5-U0.5.10-b224
[19:59:13 INFO]: Java version: 11.0.6

### Logs
*Give use your logs by going to `logs/latest.log`.*
Not relevant

### Details
*Please explain the problem.*
Due to peaceful faction members being unable to use splash potions that would harm, they are unable to cure zombie villagers. The process involved with curing a zombie villager starts with throwing a splash potion of weakness. Perhaps a config option to allow this specific potion, or any other way around this. Removing vanilla mechanics due to being peaceful hurts. (I restrict the switch to peaceful to a 1 time choice to avoid abuse, raiding, then going peaceful etc)

**Comment by mbax** [comment]
Finally resolved in 0.5.25 (coming soon)
