### ISSUE TITLE
faction fly

### ISSUE THREAD

**Issue by Koora7334** [drtshock/Factions#1382]
Hello, I'm running latest version of ur FactionsUUID plugin, with Paper 1.8.8 build, latest btw.

So, when we leave a faction, and when we have also the f fly option turned off in the config file, It still disable fly and send message when whe leave the faction.

The problem is only the message, and the flight disable.

**Comment by CmdrKittens** [comment]
I'm sorry, for some reason I did not notice the notification for this issue. It is best to get help via the support discord, but we can try here. Can you run the command `f debug` and post here the URL it gives? If you feel the information there is too sensitive, this can be done over Discord.

**Comment by CmdrKittens** [comment]
Closing for lack of response. Please reach out to us over Discord for easiest support, or create a new ticket with the output of `f debug` :)
