### ISSUE TITLE
Faction permissions don't work while set as peaceful

### ISSUE THREAD

**Issue by Jadiction** [drtshock/Factions#1386]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 
![image](https://user-images.githubusercontent.com/8557785/83426134-50baf980-a3f4-11ea-8951-072244b99091.png)

### Details
When factions are peaceful, faction permission seems to not be respected. I.E allying 2 peaceful factions and they have faction set build perms, they still cannot build.

**Comment by dariasc** [comment]
The issue stems from [this](https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/listeners/FactionsBlockListener.java#L59) check, it exits before it can check perms. I don't know if just removing is the correct way to approach this, patching this would lead to inconsistent behaviour in other parts, as there are many `.isPeaceful()` checks around the code, and I don't know what the intent behind the peaceful flag is.

**Comment by mbax** [comment]
From recent testing, this was resolved in 0.6.0
