### ISSUE TITLE
Is there a possible way to enable PVP between faction members?

### ISSUE THREAD

**Issue by Umbuktu** [drtshock/Factions#1389]
### Details
Not necessarily on faction territory, but I am trying to have a hunger games "mini-game", but people from the same faction can't hurt each other. Is there a simple solution for that, like the /f flags feature before?

Thanks!

**Comment by SirMeliodaz** [comment]
I'm looking to do the same thing. Somebody let me know too, pm me as well pls. Also sorry for not answering your question Umbuktu

**Comment by mbax** [comment]
In the next release it will be possible to create areas defined by WorldGuard where FactionsUUID largely stops caring about pvp (so you can have an arena inside your safezone for example)
