### ISSUE TITLE
/faction warp Internal Error

### ISSUE THREAD

**Issue by toxxicjtag** [drtshock/Factions#139]
Getting this error when in a faction and trying to see the list of warps.
http://pastebin.com/5GPDr3B4

**Comment by drtshock** [comment]
Your stack trace isn't complete.

**Comment by toxxicjtag** [comment]
How can I complete it, that was all that was in the Log.

**Comment by drtshock** [comment]
Oh wait. Which mc version is this no?

**Comment by toxxicjtag** [comment]
git-Spigot-1.7.9-R0.2-205-g48578ee (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by drtshock** [comment]
Which version is the user on?

**Comment by drtshock** [comment]
I think this only works on spigot R0.3-SNAPSHOT

**Comment by toxxicjtag** [comment]
I have been using an older version of your factionUUID with no problem. I guess i'll stick with it.
