### ISSUE TITLE
Add /f ignore or FUUID integration with CMI's or Essentials /ignore command.

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1390]
### Idea
*Tell us what you want!*
To add a command to ignore players from faction or ally/other relation faction.

### Details
*Give some more information so we can get an idea.*
For now my players can only use cmi's '/ignore' which ignores players in public chat but it does not work with FUUID.
It would be great if FUUID to work with cmi's ignore command. Unless you can add in a built-in command just for FUUID like '/f ignore (player)"

**Comment by BboyZeroOne** [comment]
Bump~

I hope this suggestion won't be forgotten~

**Comment by mbax** [comment]
Actually did this for EssX a few releases ago and forgot to close it!
