### ISSUE TITLE
FactionCreateEvent Cancellable 

### ISSUE THREAD

**Issue by cerealkillahh** [drtshock/Factions#1391]
### Idea
Make the `FactionCreateEvent` Cancellable if possible

### Details
It would be nice if we could cancel the FactionCreateEvent event so we can do several checks first and then possibly cancel it.

**Comment by CmdrKittens** [comment]
As the existing event happens *after* the faction has been created, a new event `FactionAttemptCreateEvent` will be added for the next release with just the player creating and the tag name requested. It will implement `Cancellable` and on cancel will silently abort, leaving it to plugin authors to inform the user of the cancellation.

**Comment by CmdrKittens** [comment]
The aforementioned release was... released.
