### ISSUE TITLE
Disable update message config

### ISSUE THREAD

**Issue by ShayBox** [drtshock/Factions#1392]
A config setting to disable the update notification spam, a single message in console is enough

**Comment by CmdrKittens** [comment]
There have been a total of 9 updates in 2020 thus far, and updating for all of them has been as simple as replacing the jar (or, preferably, placing the jar in `plugins/update` to allow faster restarts).

Out of curiosity, what is holding you back from promptly updating? :)

**Comment by ShayBox** [comment]
I have a test server I update all the plug-ins on at the same time and test, I don't update without testing, there's not many updates to this plug in but I don't like a block of text sent to all my staff every time they login until I get around to updating

**Comment by mibby** [comment]
I'd also like to see an option for disabling update notifications. I'm using the latest source compiled but it states the spigot release build is a newer version.

**Comment by ShayBox** [comment]
It's intentional

**Comment by mbax** [comment]
Plugin *already* has built-in way to disable it.
