### ISSUE TITLE
When executing the command /f ahome <player> from console it gives an error

### ISSUE THREAD

**Issue by GerwinVerkerk** [drtshock/Factions#1397]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 
![image](https://user-images.githubusercontent.com/43728830/89708416-33b42100-d977-11ea-9ffe-387d44f8c1e2.png)

### Logs
*Give use your logs by going to `logs/latest.log`.*
[latest.log](https://github.com/drtshock/Factions/files/5045149/latest.log)

### Details
*Please explain the problem.*
When trying to teleport the player to their /f home location using the command /f ahome <player> from console it gives an error. The command does work when executed from in-game.

https://paste.ubuntu.com/p/wjfzmQwXhR/

**Comment by CmdrKittens** [comment]
Thank you for this report! Fixed in next release.
