### ISSUE TITLE
[BUG] Power resets when server restarts and player is not in a Faction

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#1403]
### Debug info
*https://imgur.com/a/yh2IS8N* 

### Details
*When your power is boostered and you already reached the maximum power level, but then you remove your powerboost (adjusting your power level to the old power limit), and then restarting the server, it will cause your power to be reset, going back to 0.*

Example:
- "The default power limit defined is 10."
- "You powerboost yourself with +10, this will turn your powerlimit to 20."
- "You give yourself 20 of power so you already have maximum power."
- "Then you set back your powerboost to +0, turning your power limit back to 10, and it will adjust your current power level from 20 to 10."
- "Then you restart your server, and when you join back your server, your power will be reset to 0 without any reasons."

I haven't deeply investigated this bug, and I'm not sure if this is the only way to reproduce the bug.
Regards!

**Comment by dariasc** [comment]
I was not able to replicate the issue following your instructions, I think your `players.json` might not be saving properly. I even tried on 1.8 and 1.16. If you find a way to replicate this consistently it would be great to narrowing this problem down.

**Comment by ghost** [comment]
Thanks for replying!
I can't reach my computer right now, but later today I'm going to deeply investigate more about this issue so I can provide you more details to reproduce it. Regards!

**Comment by Tomi010817** [comment]
Thanks for replying!
I can't reach my computer right now, but later today I'm going to deeply investigate more about this issue so I can provide you more details to reproduce it. Regards!

**Comment by ghost** [comment]
Ok, I'm back again.
So it was pretty confusing to me at first, because I wasn't able to reproduce it, but now I can reproduce it again. So I tested the last dev build on a localhost, also being the only plugin on it. The config is the default without any changes, and this is the easiest way that I found to reproduce the bug:

1- Join with an account on the server.

2- Give yourself 10 of power with `/f mp [YourName] 10`.

3- Make sure that your power is now "10" using `/f power`.

4- Quit the server.

5- Restart the server.

6- Join back with the same account, and check your power. It will be reset to 0 instead of staying on 10. This due to your account's data on `players.json` rarely disappearing from it.

Hope you are able to reproduce it. It took me a while to investigate this since my PC is pretty bad and slow when executing tasks and doing actions xD.

**Comment by dariasc** [comment]
I was able to replicate the issue if player is not a member of a Faction, this seems to be intended behaviour as the plugin does not save player data for those that are not in a faction to conserve disk space. Is this happening while the player is in the faction?

[Source](https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/data/MemoryFPlayer.java#L50)

**Comment by ghost** [comment]
**I can confirm that this doesn't happen whenever I'm on a Faction.**
The idea to conserve disk space sounds really good to me, but I think that the player data should not be removed on any circumstance when the player is not in a Faction.

My best idea on this matter would be to not save the player data, only if the power is equal to the defined amount you start up with when you join by the first time. (in the default case, it would be at 0 power, so if the player is not in a Faction, and his power is 0, then his data won't be saved. Also this would not be unsaved in case that the player's power limit is modified by a powerboost)

Anyways, I read somewhere on the discord support, that MySQL is going to be a thing in the future, so I think that that is another reason of why this disk space conservation method should not be that strict as how it is right now.

**Comment by mbax** [comment]
In 0.5.25 the only time they won't save is if their power equals the currently configured starting power (meaning them being recreated on join would be the same as being saved) and they have no powerboost.

Additionally adding a config option to store in all cases.

**Comment by ghost** [comment]
Thank you @mbax

**Comment by mbax** [comment]
It only took me forever to do it! 😁

**Comment by ghost** [comment]
Yeah, nice speedrun right there!🤪
