### ISSUE TITLE
/f ban for /f join spam

### ISSUE THREAD

**Issue by Thefluffypvper1** [drtshock/Factions#1413]
A random person can do /f join [Faction] and spam the faction chat and /f ban [IGN] doesn't stop it. My suggestion is, when you do /f ban [IGN] it stops the player from spamming /f join [FACTION].
https://gyazo.com/fe3095691ca8e87ab5c79bc62c36402f?token=49cc097e3888920a0443af7ade480b0e

**Comment by mbax** [comment]
Resolved for 0.5.25
