### ISSUE TITLE
/f claimline <cardinal direction> <amnt of claims>

### ISSUE THREAD

**Issue by thomasb454** [drtshock/Factions#142]
Hi,

I've had a suggetion from a few of my players: the ability to claim in a line.

So you can stand in your base and /f claimline [{n}orth, {s}outh, {e}ast, {w}est}] [number of claims]

Essentially it would create a line of claims.

@ = base
# = claim

Let's set I wanted 5 north claims

North ->

@##### 
would be produced from /f claimline north 5

**Comment by Kakifrucht** [comment]
I don't see why this would be necessary. There is already the possibility to claim a radius from you. If you want to claim just a line you could just run in the direction you wanted to. Adding unnecessary stuff like this would just make Factions even more complex.

**Comment by thomasb454** [comment]
This feature is more than over due.
Yes you can claim a radius - but that's just the issue; it's a radius claim.

**Comment by drtshock** [comment]
Lots of people have expressed interest so I'll add it when I have time :)

**Comment by thomasb454** [comment]
Thanks :)
