### ISSUE TITLE
Vaults are not deleted after the clan disbanded

### ISSUE THREAD

**Issue by furkanbalci0** [drtshock/Factions#1426]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 

### Logs
*Give use your logs by going to `logs/latest.log`.*

### Details
*Please explain the problem.*

After doing a clan /f disband, vaults are not deleted.
After that, when a new clan is created, the contents of the vault are transferred to that clan.

**Comment by mbax** [comment]
Issue related specifically to disbanding the most recently created faction. Will be resolved in 0.5.25.
