### ISSUE TITLE
/f who <faction> formatting issue

### ISSUE THREAD

**Issue by thomasb454** [drtshock/Factions#143]
Hi,

Upon typing /f who <faction> (running version v1.6.9.6-U0.1.12-SNAPSHOT)

It displays:
http://www.diamcraft.com/uploads/Tom650353VlFM8505044st76430076498.png

**Comment by thomasb454** [comment]
Oops forgot to say - there's no space or comma between names.

**Comment by drtshock** [comment]
This should be fixed in the recent commits.
