### ISSUE TITLE
DTR penalty *BUG*

### ISSUE THREAD

**Issue by otakaros** [drtshock/Factions#1432]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 
https://ctrlv.cz/LG6f

### Logs
*Give use your logs by going to `logs/latest.log`.*
I don't want to publish.

### Details
*Please explain the problem.*

**DTR penalty is set up to 0.5 (default)**
**When you kick member in DTR Freeze, faction is going from full DTR to raidable.**
**Everything is set up correctly** 
Using latest FactionsUUID on 1.15.2 PaperSpigot

**Comment by mbax** [comment]
Please provide all requested information. You could reach out to me on the support discord directly if you don't want to post it all here.
