### ISSUE TITLE
Unregistered Scoreboard Component

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1440]
Hi, I'm not sure what the error is about, but it doesn't really affect me in game but the console outputs this error.

https://pastebin.com/9x7khEDS

Plugin Version: Factions v1.6.9.5-U0.6.7-b278
Java 1.18.1

**Comment by mbax** [comment]
You have some other plugin interfering with scoreboards. Reach out on Discord and I can possibly help identify the problem.
