### ISSUE TITLE
Silverfish infest and break blocks in peaceful territory

### ISSUE THREAD

**Issue by timriker** [drtshock/Factions#1443]
### Debug info
https://info.factions.support/b6a5170002894e48803cec3571a76fc9

### Logs
*Give use your logs by going to `logs/latest.log`.*
Nothing relevant in the logs.

### Details
*Please explain the problem.*
Siverfish can infest blocks inside claimed Peaceful chunks. Then they can break the chunks when they spawn. This allows players to indirectly break chunks in Peaceful territory.

**Comment by mbax** [comment]
Will be resolved in upcoming release.
