### ISSUE TITLE
main.conf commandBase doesn't work

### ISSUE THREAD

**Issue by MelonHell** [drtshock/Factions#1446]
### Debug info
https://info.factions.support/4ceb0b8c9ce1458e97eebd07d39a911b

### Details
commandBase option in main.conf not working

### My actions
- Stopped the server
- Edited commandBase in main.conf like this:
  ```conf
  # The command base (by default f, making the command /f)
  commandBase=[
      fc
  ]
  ```
- Started the server
- Introduced /fc and /factions:fc into the chat
  The server replied that the command was not found
  ![image](https://user-images.githubusercontent.com/53826469/184194615-ffb0e84c-74d5-410b-b803-8378d8684a19.png)
- Introduced /f and /factions:f into the chat
  The command worked, but it shouldn't. I want to disable the /f alias
  ![image](https://user-images.githubusercontent.com/53826469/184195146-2a67e4a5-922d-4887-b47e-7b224ec04b56.png)
  at the same time, in the help message, the server suggests using /fc
  
### My problem
My plugin uses the /f command and because of Factions my plugin's autocomplete doesn't work

**Comment by mbax** [comment]
Hi, yeah, that sounds about right. It broke at some point in the past. Temporarily you can edit plugin.yml inside the jar itself to change the command and that *should* do it.

**Comment by mbax** [comment]
Working on big update that will fix this, btw. 0.7.0 release will have the fix.
