### ISSUE TITLE
Players are able to check if a staff is online in vanish.

### ISSUE THREAD

**Issue by BboyZeroOne** [drtshock/Factions#1454]
### Debug info
*Run `/f ticketinfo` and paste the URL here.*
https://info.factions.support/6d83e754a9384551b40278bab309e5c4

### Logs
*Give use your logs by going to `logs/latest.log`.*
I don't think there is a need for this.

### Details
*Please explain the problem.*
Players are able to check staffs/admin who are in vanish online. 
Plugins used for vanish: CMI & SuperVanish

Example Issue:
![image (3)](https://user-images.githubusercontent.com/51330952/209572012-890d6c0b-b5f8-4a30-802f-e18deb7f0fe4.png)

**Comment by mbax** [comment]
Resolved.
