### ISSUE TITLE
Add player in faction placeholder for PlaceholderAPI?

### ISSUE THREAD

**Issue by catches** [drtshock/Factions#1456]
Just checks if a player is in a faction or not.

**Comment by mbax** [comment]
To confirm, do you mean a placeholder that returns something like `true` or `false` based on being in a faction?

There already are a few placeholders that do things distinct for not being in a faction, such as (I'm not including the %factions_...% bit):

`player_role` - It's empty if not in a faction
`player_role_name` - It's the lang.yml PLACEHOLDER->ROLE->NAME entry if not in a faction
`player_factionless` - It's empty if in a faction, and whatever your lang.yml calls factionless players if not in one
`faction_only_space` - It's literally a single space if in a faction and empty if not.

**Comment by catches** [comment]
Yo @mbax sorry I didn't get to this, but it was more so a placeholder that returns true or false yeah, since I'm using plugins that have conditions where I'm trying to detect if a player is in a faction, and I don't know how to do that with just empty spaces.

**Comment by mbax** [comment]
Do those plugins truly only take 'true' or 'false'? That's very odd to use placeholders that way and not allow for detecting `if(value is empty)` or similar for using that empty/notempty string.
