### ISSUE TITLE
Faction Issues

### ISSUE THREAD

**Issue by unl0ved** [drtshock/Factions#149]
./f who does not list the people in order of Owner->Moderator->Player
You should be able to see when you enter someones land in chat, other than just the scoreboard. For example when you enter Wilderness, Warzone, or Safezone it tells you in chat, but for claimed land, it doesn't say anything.

http://puu.sh/de9N1/4ec72a84fd.png

**Comment by drtshock** [comment]
You can disable the scoreboard in the config to show in chat instead. Also, if people have the scoreboard toggled off, it'll show in chat.
https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/config.yml#L87

Please open a separate ticket for the /f who suggestion and label it enhancement.

**Comment by unl0ved** [comment]
I have the scoreboard disabled, but when I enter someones claimed land it doesn't say it in chat, but it says when I exist back into Wilderness.
