### ISSUE TITLE
Economy not working

### ISSUE THREAD

**Issue by TheKnight787** [drtshock/Factions#15]
When in config econEnabled is set to true, you can't create, join, leave etc. even if it costs 0$.

**Comment by drtshock** [comment]
Are there any errors in console? Can you put your entire config in pastebin please. Do you have Vault and an economy plugin on the server that are functioning correctly?

**Comment by TheKnight787** [comment]
No errors show up.
Config: http://pastebin.com/edhA7qYE
I have Vault and Essentials plugins, which both function correctly, plugins like ChestShop work perfectly.

**Comment by Saiee** [comment]
It's true! I've tried it and also experienced the same problem.

**Comment by drtshock** [comment]
Which version of Vault?

**Comment by drtshock** [comment]
There are a lot of things that need to be updated to work with the new Vault version https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java in this class https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/integration/Econ.java

**Comment by externo6** [comment]
When will this be implemented?

**Comment by Totollie** [comment]
Any progress on this? It's clearly a long standing issue yet to be resolved :/

**Comment by drtshock** [comment]
Fixed!
