### ISSUE TITLE
error on console

### ISSUE THREAD

**Issue by Lynx76x** [drtshock/Factions#158]
Hello , I see from time to time an error in the console, but I do not really know when his does. I think when someone invites the player .
Thank you in advance. I just update server level and the same spigot 1.8 plugin.

http://hastebin.com/atidebajuc.avrasm

**Comment by Lynx76x** [comment]
What should I do ? Thank you in advance.

**Comment by drtshock** [comment]
It was fixed in that commit.

**Comment by Lynx76x** [comment]
And so I must wait for an update ?

**Comment by drtshock** [comment]
There are dev builds http://ci.drtshock.net/job/FactionsUUID/148/

If you don't have access and you purchased this, register and post your username on the spigot thread.

**Comment by Lynx76x** [comment]
Thank you , if the link not work :/

**Comment by Lynx76x** [comment]
I have to give my nickname here ? I registered an hour ago . Pseudo Lynx76xx

**Comment by drtshock** [comment]
@Lynx76x added :)

**Comment by Lynx76x** [comment]
The link still not working :( Thanks for your patience ;)

**Comment by Lynx76x** [comment]
Hello, I would like to add that I quite quickly because the bug plugin and I would like to participate in devbuild . Thank you in advance.
This is the information of the account:

http://ci.drtshock.net/user/lynx76x/
Identifiant d'utilisateur Jenkins: lynx76x

**Comment by drtshock** [comment]
I've already added you.

**Comment by Lynx76x** [comment]
I feel myself ridicul of souler you with that , but I just retest and I always make the same mistake at the beginning of the page.

HTTP ERROR 404

Problem accessing /job/FactionsUUID/148/. Reason:

```
Not Found
```

Powered by Jetty://
