### ISSUE TITLE
Error on most faction commands.

### ISSUE THREAD

**Issue by Evap88** [drtshock/Factions#159]
http://hastebin.com/vipuxurato.avrasm

The first one happens when a player creates a faction and types anything in chat.

The second error occurs when a player types certain commands like /f who or /f invite etc...

Most recent spigot 1.8 version with most recent public build of FactionsUUID I have tried deleting the factions folder and regenerating settings.

**Comment by drtshock** [comment]
Can you paste your conf.json in a gist please? It looks like you left something out.

**Comment by Evap88** [comment]
https://gist.github.com/zdylann/d4c6e3b83b1fbd7431ce

**Comment by drtshock** [comment]
Does this still happen with a fresh restart on the latest snapshot?

**Comment by Evap88** [comment]
I think I've figured out the issue. 

Accidentally mistaking a build from this: http://www.spigotmc.org/resources/factions-1-8-2-uuid.1119/ 
as a build from you. So the conversion from using that one to yours breaks players being loaded/unloaded. A fresh restart does work. 

I have just gone ahead and manually fixed the issues in players.json. All of the players were missing chat mode and role for some reason, but manually adding that to all players fixed the issues.
