### ISSUE TITLE
HCF - DTR

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#168]
Preamble: HCF are a list of features that people have requested, some of which can be done already, others just need a bit of tweaking. We'll be adding these to the HCF section of the config. If you're creating a PR, make sure that old behavior is always default and that you add the config option to the config.yml HCF section.

Make sure all showings of power can be replaced with a customized string from the TL. I believe this is already possible, just want to make sure there aren't any instances of this outside of the command classes.

**Comment by oFrostMC** [comment]
I agree that all of these are good ideas and should definitely be added - any progress on this so far? Wanted to add on that There should be 2 strings; DTR which caps at 5 and Land which caps at 36 on most servers including the original HCF server (ShotBow).

**Comment by drtshock** [comment]
Added. https://github.com/drtshock/Factions/commit/d888b320dbb18073faf35169de3962bcac11d5dd
