### ISSUE TITLE
HCF - Max Relation type

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#169]
Preamble: HCF are a list of features that people have requested, some of which can be done already, others just need a bit of tweaking. We'll be adding these to the HCF section of the config. If you're creating a PR, make sure that old behavior is always default and that you add the config option to the config.yml HCF section.

There should be an option to set the max amount of relations of each type for a faction. Example in the HCF section is below. The config should be set to 0 by default, which would be no limit (current default behavior).
max-relations:
  allies: 0
  enemies: 0
  neutrals: 0

**Comment by Kakifrucht** [comment]
This would be neat to have imo! There are some factions who just enemy every other faction.
