### ISSUE TITLE
FriendlyFire not functioning properly

### ISSUE THREAD

**Issue by TheKnight787** [drtshock/Factions#17]
When FriendlyFire is set to false in the config, an ally can still hit you with a BOW. Anything else works fine.

**Comment by drtshock** [comment]
So they can hit you with the bow? Or they can shoot an arrow from a bow?

**Comment by TheKnight787** [comment]
Shoot an arrow.

**Comment by TheKnight787** [comment]
Same thing with snowballs.

**Comment by TheKnight787** [comment]
The update fixed the issue. Case closed.
