### ISSUE TITLE
/f show error console

### ISSUE THREAD

**Issue by Lynx76x** [drtshock/Factions#172]
please I would like to have access to the update , because I find four files: essentials , MagicFurnace , PlayerVaults , Residence , drtshock in your list. :( Otherwise I have to do? Because I pay anyway ... Thanks in advance .

http://hastebin.com/ibajitovah.avrasm

**Comment by cnr** [comment]
Hello

You'll need to make sure you have a Vault-compatible permissions plugin on your server (GroupManager is the one that essentials recommends)

**Comment by Lynx76x** [comment]
Hello , here is the list of plugins that I updated with the spigot 1.8. Everything works fine on my server but for now the faction plugin. Just to add something, the faction plugin free work perfectly.

Vault 1.5.0 
groupmanager build #2.1.31 (15 Oct 14 09:40)

**Comment by Lynx76x** [comment]
solved , update spigot and error . thank you :)
