### ISSUE TITLE
unclaim radius

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#175]
People should be able to unclaim a radius just like they can claim one.

**Comment by drtshock** [comment]
Would still be nice.

**Comment by PhanaticD** [comment]
+1

**Comment by Acefore** [comment]
Please Do !

**Comment by drtshock** [comment]
+1

**Comment by drtshock** [comment]
+1

**Comment by CmdrKittens** [comment]
Some time between the last update to this ticket and now, this became a feature.
