### ISSUE TITLE
Potions in safe zones

### ISSUE THREAD

**Issue by thomasb454** [drtshock/Factions#177]
Hi,

Players are reporting that they can use mcMMO Alchemy potions (things like Haste) on players in SafeZones.

**Comment by drtshock** [comment]
I don't know what that is. Is that something specific to mcmmo?

**Comment by thomasb454** [comment]
I believe it allows you to just create potions that you otherwise couldn't (in Vanilla) e.g Haste, Absorption, etc.

**Comment by cnr** [comment]
Only the negative effects are intended to be blocked -- are you able to use negative-effect potions in safe zones?

**Comment by drtshock** [comment]
@thomasb454 can you provide more info please? :)

**Comment by thomasb454** [comment]
@drtshock not really, sorry.
I was only told by players and wasn't exactly able to confirm it.
I'll try and test this with my admins later.
