### ISSUE TITLE
Urgent Bug, Claiming 

### ISSUE THREAD

**Issue by JJkillzzz** [drtshock/Factions#178]
Hey @drtshock

Well, There is one bug. When users try to do ./f claim radus 5 or any radus it says you can't claim land from wilderness

And Yes I'm in a faction.

When I do ./f bypass I'm able to. :p

?? Please fix asap!

http://prntscr.com/5filbz

:D

**Comment by cnr** [comment]
Hello

The syntax for that command is `/f claim [faction] [radius]`

**Comment by JJkillzzz** [comment]
Users don't know that, That's never been the command. Its always been /f claim (radius)

**Comment by drtshock** [comment]
We didn't change that.

**Comment by JJkillzzz** [comment]
But it doesn't work as you see in the screenshot I posted.

**Comment by cnr** [comment]
It has always been `/f claim [faction] [radius]` on this version of factions (1.6.x).
