### ISSUE TITLE
Not compatible plugin tablist

### ISSUE THREAD

**Issue by Lynx76x** [drtshock/Factions#180]
[QUOTE="ednermanslaya12, post: 446854, member: 14677"]The issue is that you are not using the official Factions plugin, and BungeeTabListPlus was not made for a third party Factions plugin. I would recommend you switch back over to the official Factions plugin. The latest versions of Factions also support UUID's, so you shouldn't have anything to worry about.[/QUOTE]

Not compatible , you think we just do something?
Thank you in advance.

**Comment by drtshock** [comment]
What
