### ISSUE TITLE
BlockBreak Event error

### ISSUE THREAD

**Issue by iaxedu** [drtshock/Factions#187]
http://pastebin.com/1aNmi03t

With the following option:   "worldGuardBuildPriority": true

**Comment by drtshock** [comment]
Which version of worldguard?

**Comment by iaxedu** [comment]
WorldGuard v6.0.0-SNAPSHOT.1477-

**Comment by drtshock** [comment]
We don't yet support that version https://github.com/drtshock/Factions/blob/1.6.x/pom.xml#L89
