### ISSUE TITLE
not compatible

### ISSUE THREAD

**Issue by Lynx76x** [drtshock/Factions#188]
Faction + protocolsupport. ( http://www.spigotmc.org/resources/protocolsupport.2367/ )

I get little more on the server because of your plugin.

http://www.imabox.fr/14/12/19153lRUCZA21.jpg

**Comment by Lynx76x** [comment]
Faction 2.7.5 + massive core 2.7.5 no problem... Plz find a solution. Thank you in advance.

**Comment by drtshock** [comment]
You likely have your scoreboard title set too long. We're not going to provide support to plugins that do hacky shit like that.
