### ISSUE TITLE
/f who /f show shows incorrect info

### ISSUE THREAD

**Issue by TheKnight787** [drtshock/Factions#19]
When a player is offline, in the faction where all joined faction players are offline, and you type /f show name or /f who name, the output will be, that they don't have a faction. That means I can't check offline faction players factions.

**Comment by drtshock** [comment]
Is this still an issue? It was sort of duplicated by another and I'm not sure if I indirectly fixed this or not.

**Comment by TheKnight787** [comment]
It is fixed.
