### ISSUE TITLE
High use age factions commands

### ISSUE THREAD

**Issue by iaxedu** [drtshock/Factions#193]
[Factions] Loading Factions v1.6.9.5-U0.1.13-SNAPSHOT
git-Spigot-b43a31a-975c9ed (1.8)

http://timings.aikar.co/?url=9605514

Another one:
http://timings.aikar.co/?url=9606448

Look at 

Command: factions 

I've downgraded to 1.1.12 again which fixes massive lag spikes. Still shows quite some performance issues tho: http://timings.aikar.co/?url=9606606

**Comment by iaxedu** [comment]
Please respond the issue is still here even with 1.1.12
http://timings.aikar.co/?url=9634461

**Comment by cnr** [comment]
This should hopefully be resolved in the latest build. Please report back if you find out otherwise (:
