### ISSUE TITLE
F show lag

### ISSUE THREAD

**Issue by CullanP** [drtshock/Factions#195]
I recently noticed that the lag with this plugin is unbearable and only because of cmdshow.java, I tested/debugged and this line "for (FPlayer p : MiscUtil.rankOrder(faction.getFPlayers())) {" is causing lag on my server. I compiled with craftbukkit 1.7.10 and am using spigot 1.7.10 latest. When not in a faction and doing /f show its the worst

**Comment by iaxedu** [comment]
Basicly same issue as me: #193

**Comment by CullanP** [comment]
He'll fix it :P : I gave him enough info to help find a solution.

**Comment by cnr** [comment]
Duplicate of #193
