### ISSUE TITLE
f warps not working & warzone bug

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Factions#200]
When you try to set a warp (in your territory) nothing happens, no console message & no in game message.
Also when you disable powerloss in a world and have powerloss in warzone to false and die in warzone claims inside the world it will however make you loose power.

**Comment by drtshock** [comment]
This would've been fixed here https://github.com/drtshock/Factions/commit/a70cfdaf7178293cf69b02f4a8eee4582bb553f9
