### ISSUE TITLE
[Feature] /f powerloss (faction), /f promote, /f demote, Recruit rank!

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Factions#201]
Could you perhaps add /f powerloss (faction) so basically it denies powerloss in that factions claims, and if done twice it makes powerloss in that land possible again?
/f promote & /f demote would also be lovely. To revoke Mod and ive Mod to players in the fac easily.
And to be used for my next suggestion which would be a new Faction rank, "Recruit" So basically a recruit could have very strict limiations inside the faction. Call it a trial rank if you want. Were the recruit cant build, use doors anything basically just go the the /f home. Recruit would be before Member and yea overall a nice addition to the plugin.

**Comment by drtshock** [comment]
For the power loss, do you mean so no one can lose power in that land, or so that faction can't lose power?

**Comment by zRiaz** [comment]
Like /f powerloss (faction) = No one can loose power in territory, it helps creating  "custom" warzones/spawn claims etc.

**Comment by drtshock** [comment]
I don't quite see why that'd be needed.

**Comment by zRiaz** [comment]
Well many people like to create their own powerfaction to claim stuff on their servers.
Such as (ServerNameTerritory) or just the server name as a power faction.
Which is possible, but it lets people that dies in spawn for example loose power.

So personally a option to disable powerloss in certain factions (obviously a admin command) would be very helpful.

**Comment by drtshock** [comment]
You can change the name of the safezone to be your server name. Can also do it for warzone and wilderness.
