### ISSUE TITLE
/f show cause lagg

### ISSUE THREAD

**Issue by Hiirumi** [drtshock/Factions#209]
When a player spamm the command /f show, there are a lotts of laggs and tps decrease to 16, and the server freeze, can only be used in a faction with many members

**Comment by iaxedu** [comment]
Use the latest build from spigot. It's caused by the tool tips and removed in that build. They are working on a fix.

**Comment by Hiirumi** [comment]
what build? i upgraded to the last build of this faction plugin, but the problem persist

**Comment by drtshock** [comment]
This is resolved now as of https://github.com/drtshock/Factions/commit/91f9d1d8db602dd8bfe8ceb85fead691bd846199
