### ISSUE TITLE
Faction Chat Not Working

### ISSUE THREAD

**Issue by Glerden** [drtshock/Factions#21]
When I type in faction chat, it shows in public chat too. Please reply asap for I've been trying to find this issue for weeks.

factions.json - http://pastebin.com/uuViU9bK
screenshot   - http://gyazo.com/9081466a2d18553c0be24d8f4361c987

If you need more info, I'll just add. Thanks for your time.

**Comment by drtshock** [comment]
Which build are you on?

**Comment by Glerden** [comment]
I'm using the latest build, Build #28.

**Comment by Glerden** [comment]
... Reply please.

**Comment by Glerden** [comment]
Mate.

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/commit/526734b9f6ecd95f3b461e51247a0e0306145ac2 should be fixed there.
