### ISSUE TITLE
/f warp dont work with latest build

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Factions#213]
Basically everytime a player tries to set a faction warp they get this message:
"You dont have permission to set a warp for your faction" 
I was the Faction leader when I did that.
I opped myself and tried again and it worked.
Config:
warp-cost:
  enabled: true
  setwarp: -7500
  delwarp: 500
  warp: 5
Version: 1.6.9.5-UO.1.13

**Comment by cnr** [comment]
Do the players have the `factions.setwarp` permission (to set warps) and `factions.warp` (to use them)?

**Comment by zRiaz** [comment]
eh.. no.. I didnt know there was permissions (as I didnt see them on Spigot o_O)

**Comment by cnr** [comment]
Yeah, the documentation there needs improvement /cc: @drtshock 

Thanks for bringing this to our attention (:

**Comment by drtshock** [comment]
:c
