### ISSUE TITLE
Compatibility with Worldguard 6 Beta 4

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#214]
Hello,

when players try to claim land this exception is being thrown:
http://pastebin.com/YTAUKhFP

Spigot is on version 1.8, Factions latest build 196, an earlier one didn't work either.

This is very odd though. I decompiled both my Worldguard build and the Factions build, there is really no reason for the NoSuchMethod error. Worldguard clearly has this method unmodified, and Factions calls it right. I have no idea what's going on here. It even says successfully hooked into Worldguard, and on an empty server with only Worldguard/edit and Factions it works neither.
The only actual difference I found is that in the Beta they changed the method header from "public List<ProtectedRegion> getIntersectingRegions(List<ProtectedRegion> regions)
    throws UnsupportedIntersectionException" to "public List<ProtectedRegion> getIntersectingRegions(Collection<ProtectedRegion> regions)", so they only changed it from List to Collection, however List is a Collection, so this shouldn't really be a problem?

regards!

**Comment by drtshock** [comment]
Add me on skype and I'll send you a build to see if this fixes it. Skype is drtshock13

**Comment by Kakifrucht** [comment]
Well I could do that tomorrow, my Mainboard broke so I'm unable to test much right now.
