### ISSUE TITLE
Some important things are missing from TL

### ISSUE THREAD

**Issue by cnr** [drtshock/Factions#216]
Things missing from TL include:
- `/f help`: `getUseageTemplate` [sic] uses permission descriptions in config.yml [to describe commands](https://github.com/drtshock/Factions/blob/b923e1efd70748670c96334d1140976d8b2f1d16/src/main/java/com/massivecraft/factions/zcore/MCommand.java#L55)
- The [old `Lang.java`](https://github.com/drtshock/Factions/blob/b923e1efd70748670c96334d1140976d8b2f1d16/src/main/java/com/massivecraft/factions/zcore/Lang.java#L4-L9) wasn't migrated.

(these were issues brought up in IRC, so this is unlikely to be an exhaustive list)

/cc: @korikisulda

**Comment by Tahul** [comment]
btw i would like to add that most of common messages aren't in the language file. I took 3 hours to translate it, to notice that in game /f help didn't changed at all etc.. 

By the way in the future u could let us have a bit of influence on the formating, it would be very great.

Anyway thanks for the good job.

**Comment by drtshock** [comment]
@Bonkozorus to what exactly are you referring?

**Comment by Tahul** [comment]
@drtshock : I refer to the way messages are sent color & everything. By the way a lot of messages are missing from the language file i think you can easily see which ones.

**Comment by drtshock** [comment]
everything except a few economy things are configurable now.
