### ISSUE TITLE
Portal Check performance issues

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#225]
The new portal check function seems to, when called, cause some small lag.

Timings: http://timings.aikar.co/?url=9868323
It's not called alot, though.

**Comment by drtshock** [comment]
You can always disable the portals.limit option in the config and it won't even check anything after that. I'll have to take a look to see what specifically is taking up all the timings.

**Comment by drtshock** [comment]
See above linked ticket.

**Comment by Kakifrucht** [comment]
The onTravel check still takes around 200 ms.. I don't exactly understand why this was closed.

**Comment by Kakifrucht** [comment]
Currently laggspiking on my server, taking 500 ms in some cases. This really needs to be revisited.
