### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Factions#226]
Once again Im bringing a few features that seem pretty minor but I personally feel pretty nesecerry.

1) A config option or command to excempt certain factions giving the "You cannot build here" message. This is due to the fact that I do have a arena and a lms arena on my server, and if people hit a grass by accident etc they get spammed while trying to pvp. So a feature to just remove that message from a specific faction would be gr88

2) Make water/lava not flow into Warzone/safezone from Wilderness/another faction.
Seen a few people placing water at the border of warzone so it can flow into warzone, and overall just looks ugly and is annoying.

3) Update the Spigot page for FactionsUUID, make it include more information about all commands & all permission nodes.

4) As suggested before make the "Entering factions land" messages appear at the bottom of the mid screen (the 1.8 feature) as it would be increadably cool :P

5) Make the F map a bit bigger, Ive seen this in a newer version of MCore Factions, and my players would love it. (Or have a configurable option for it)

6) Suggested by myself before, but a recruit rank for basically recruits, with no more permissions then visit the f home perhaps. As a trial rank.. (With adding this a /f promote & /f demote command would be super super helpful aswell)

Thats all of my suggestions, now @drtshock when you're looking at these, would you please leave feedback for the ideas and or if you will include some of them in a update sometime?
Would be very nice to know if they are being considered/worked on or just denied suggestions :) <3

**Comment by drtshock** [comment]
1: there's an option in the config for worldsNoClaiming. Disable that and you shouldn't get a message.

2: Use worldguard regions.

3: I've been trying to bribe people to do documentation but no one will :(

4: Waiting for titles to have an API as I won't add NMS.

5: What?

6: Would love to have specifics instead of loose suggestions.

**Comment by zRiaz** [comment]
like the f map is larger on the newest version of mcore factions, and some of my players want that on my server aswell.

Ill make a more specific 6. Tomorrow

**Comment by drtshock** [comment]
Larger how?

**Comment by zRiaz** [comment]
Shows a bigger area, how idk look at the source of it :p

**Comment by DawnMC** [comment]
I agree larger f map.  A great example server would be OriginMC.  I know their's is custom coded but an f map modeled after theirs would be great.

**Comment by Kakifrucht** [comment]
I personally feel that suggestion number 6 would bloat Faction. It's not like Factions already complex and complicated enough to learn for players. This would raise so many questions.

**Comment by drtshock** [comment]
Please make individual tickets for features if you have further suggestions :)
