### ISSUE TITLE
DTR + F Show / Recommendations 

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#228]
http://prntscr.com/5xy88n
Found a few bugs you may want to fix.
You should add an HCFShow option, that converts f show into HCFs version, by eliminating the enemies bar, replace "Land / Power / Max Power" with "Land: x/32". As well as moving the raidable above DTR or adding to the DTR line "DTR: -1.1/5.5 (Raidable)"
I also reccomend adding point DTR as in 0.01, 0.02 going up. (Max being 5.50 instead of 5)
Maybe removing /f power when HCF Mode is enabled?

P.S, DTR is currently not working. It gives me maximum DTR in a 1 man faction.

Factions should have a maximum of 5.5 DTR, (For a full faction).
Each player is worth 0.51 DTR. 
When a player creates a faction, they should start at 0.00 DTR, and it should start increasing by 0.05 DTR every minute, I'm pretty sure, so every 12 seconds, they go up by 0.01 DTR.
If a player dies, you lose 1.01 DTR, and the DTR Freeze kicks in, no DTR regeneration for 1 hour. (Say the 1 hour counter is at 20 minutes, 32 seconds left, if another member dies, the timer goes back up to 60). Every new member to the faction accounts for 0.51 DTR, so if there is 2 people, DTR = 1.02, so on and so forth. Say there is 11 people in the faction, (Every person counts for 0.51DTR) although the match makes it 5.61, DTR would MAX at 5.50.

The rest I have below are just requests you could add in the future, if you're ever feeling like doing so. :)
Adding the message for when you move land.
"&eEntering &2Wilderness&e, leaving &4Warzone"
Adding in that you cannot claim 2 chunks from another faction, (To stop traps, etc).

**Comment by MoeXIV** [comment]
Updated my post to accurately reflect how DTR works.

**Comment by oFrostMC** [comment]
+1 this should be added, -snip- adding to its own issue thread. #231

**Comment by drtshock** [comment]
Please only do one suggestion per ticket. Reading through blocks of text trying to find useful information makes things take longer than they should and makes me lose motivation.

f show will be 100% configurable _soon_. That way you can just put whatever you want wherever you want.

You can revoke permissions if you want (which disable using of commands).

**Comment by MoeXIV** [comment]
The main issue is the DTR. Let's focus on that shall we?
Basically how I explained above is give or take a little, how DTR works on HCF / Kohi.

PS, I know you can revoke access to certain commands, but it would be a nice conversion to "DTR FactionsUUID", with the disabled commands, etc. would be an amazing touch. <3

**Comment by oFrostMC** [comment]
Ill be breaking what MoeXIV has explained up into multiple issues right now.

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.
