### ISSUE TITLE
What HCF /f show should look like.

### ISSUE THREAD

**Issue by oFrostMC** [drtshock/Factions#232]
I know you will be making /f show customizable soon but I was wondering when you do this you can add an essential variable to the /f show line, or even hardcode it into the plugin itself including the changes listed below.
1. Faction Home coordinates showing in a /f show line.
2. Replace "Land / Power / Max Power" with "Land: x/32"
3. Adding to the DTR line "DTR: -1.1/5.5 (Raidable)"

Screenshot of what /f show normally looks like in HCF:
http://prntscr.com/5ybt3u

**Comment by MoeXIV** [comment]
Kohi Screenshot FTW! c;
Thanks for splitting up my post, makes it a lot easier for me and DRTShock.

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.
