### ISSUE TITLE
DTR Per Player and Total DTR

### ISSUE THREAD

**Issue by oFrostMC** [drtshock/Factions#234]
- Factions should have a maximum of 5.5 DTR, (For a full faction).
- Each player is worth 0.51 DTR. 
- Start at 0.00 DTR.
- Increase by 0.05 DTR every minute (Every 12 seconds, they go up by 0.01 DTR)
- 1.01 DTR loss per death.
- Every new member to the faction accounts for 0.51 DTR, so if there is 2 people, DTR = 1.025
- DTR Maxes at 5.50

**Comment by MoeXIV** [comment]
DTR Maxes @ 5.50 not 5.05 <3
Maybe drt could add a configurable max?

**Comment by drtshock** [comment]
Just set the max power..

**Comment by MoeXIV** [comment]
For DTR? Can you do that in your plugin?
And can you have .01 DTR yet, or am I just blind..

**Comment by drtshock** [comment]
DTR is deaths til raidable. How would anything other than a whole number make sense?

**Comment by drtshock** [comment]
You can already set the powerFactionMax in the conf.json. That can be set to a non whole number. You can also set powerPlayerMax to be the max power a player can have (or DTR in this case).

**Comment by MoeXIV** [comment]
It's just the way DTR works, Every player is worth 0.51, and when they die, take 1.01 with them.

**Comment by drtshock** [comment]
You can already set that up with the current conf.json options that have been there for 3+ years.

**Comment by MoeXIV** [comment]
I understand. DTR is a lot more complicated then just setting someones power.
As he said above, the way it regenerates, how it's lost when someone dies, or joins, etc.

When someone joins, it starts adding, 0.01DTR per 12 seconds.
DTR doesn't support decimals yet, I've enabled "maxpower" to 5.50, and also tried 5.5, but it still generates as 1.

Factions should have a maximum of 5.5 DTR, (For a full faction).
Each player is worth 0.51 DTR.
Start at 0.00 DTR.
Increase by 0.05 DTR every minute (Every 12 seconds, they go up by 0.01 DTR)
1.01 DTR loss per death.
Every new member to the faction accounts for 0.51 DTR, so if there is 2 people, DTR = 1.02
DTR Maxes at 5.50

**Comment by drtshock** [comment]
The power that you'll see will be 5 but the actual power is a double / decimal to many places. You can already do all of this in the conf.json.

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.
