### ISSUE TITLE
DTR / Land

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/Factions#235]
With all the HCF features enabled, it only allows me to claim my land based on my power. 
The claims should not be limited by power. It should only be limited to what the config sets them. So,
if i have a 1 person faction, and i set the max fac claims in the config to 25, that one person faction should be able to claim all 25 of their land regardless of their dtr. But, even know they only have 1 power, and they have 25 claims, they still aren't raidable. They need 0 DTR in order to be raidable. 

http://gyazo.com/430464e251e66b8069c18bb4af5ba7ba

One more issue is the raidable issue. I have 1 land, 0 dtr, and it says Im not raidable. i Should be raidable xD
http://gyazo.com/5ae0c321c1ab7133962ffc5edcf5860f

**Comment by drtshock** [comment]
Please only have 1 feature or request per ticket.

**Comment by MoeXIV** [comment]
What SnakeDaoust is saying, is that the DTR is a main issue.
Instead of adding a mod to disable and enable a bunch of different HCF features, at different times, try adding a toggle for something like "HCFMode", where it disables all non HCF features, and kind of converts to DTR based factions, with the correct features enabled and disabled.

**Comment by SnakeDaoust1232** [comment]
No. Me and trent talk more in skype. Dtr isnt the issue. Trent knows what it does but i left some info out, and thats the result :p

**Comment by MoeXIV** [comment]
Oh, I understand now!
So there are no issues with DTR currently? I'm confused.

**Comment by SnakeDaoust1232** [comment]
Trent is making factions uuid hcf compatible. We are talking on skype and im putting the bugs here so he can keep track.

**Comment by MoeXIV** [comment]
Sounds good. And knowing you, you've got experience in the HCF community so you know exactly how it should be made, correct?

**Comment by SnakeDaoust1232** [comment]
Im not going to copy anyone. It will be a version of hcf. Not coping anyone.

**Comment by MoeXIV** [comment]
I meant the DTR, how DTR should work.

**Comment by oFrostMC** [comment]
@SnakeDaoust1232 How has this ben going - talking to drtshock about this?

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.
