### ISSUE TITLE
Warzone Claiming Issue with Latest CI Version

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#237]
Basically, if I type /f claim warzone, or /f claim safezone, it says "Your faction already owns this land", and I'm in wilderness. If I try to join Warzone or Safezone to do /f claim, it doesn't allow me to do that either...

**Comment by cnr** [comment]
The syntax for claiming is `/f claim <radius> <faction>`. (so you'd use `/f claim 1 warzone` or `/f claim 1 safezone`)
