### ISSUE TITLE
Need Help with DTR Part of factions

### ISSUE THREAD

**Issue by nscwalk** [drtshock/Factions#238]
So I bought this plugin with the intentions of this plugin having (DTR) Deaths Till Raidable feature with this plugin. I have been messing around with it for a while now but I can not find out how to enable it. Im pretty sure other people have it so I would like to know how to enable this feature as I would like to use it.

**Comment by nscwalk** [comment]
NeverMind I figured out how to do it. Ill be playing with the plugin alot reporting bugs when I find them ty

**Comment by drtshock** [comment]
Did you read the config and other tickets? There has been tons of discussion on it.

**Comment by nscwalk** [comment]
Yes but I dont know how to compile the source file into the factions plugin and I can not activate the DTR Aspect of the plugin

**Comment by drtshock** [comment]
What source file into factions?

**Comment by nscwalk** [comment]
I don't know how to add this to factions 
https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/cmd/CmdShow.java

**Comment by nscwalk** [comment]
I'm trying to add the DTR / Hardcore factions version to the plugin.

**Comment by MoeXIV** [comment]
NCS, you don't use the source. He has compiled versions of BETA DTR, on his CI, that you need to ask for. I'm also pretty sure you need a private jar to compile this plugin, but not 100% sure.

**Comment by nscwalk** [comment]
Well I just want the DTR factions ....

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.
