### ISSUE TITLE
[Feature Suggestion] /f access to replace /f owner

### ISSUE THREAD

**Issue by Ensun580** [drtshock/Factions#239]
So in factions 1.8.2 and above, /f access was added and /f owner was removed. The difference between the two was /f access could be used to access other factions, players not in your faction, or remove access from players in your faction. /f owner can only be used to restrict other members of your faction from building in certain chunks.

Commands:
/f access p [player](Used to access certain players or to unaccess them).
/f access f [faction](Used to access certain factions or to unaccess them).

**Comment by drtshock** [comment]
Duplicate of https://github.com/drtshock/Factions/issues/146
