### ISSUE TITLE
Enhancement: Ability to limit mods permissions

### ISSUE THREAD

**Issue by TheKnight787** [drtshock/Factions#24]
It would be good, if we could edit what mods can do and what can't.
For example, disallow mods to use /f unclaim, or allow them to use /f disband.

**Comment by drtshock** [comment]
Then why have a mod position?

**Comment by TheKnight787** [comment]
Players often trust someone in the mod position. But often they are just pretending to be their friends and shortly after /f unclaimall comes in.

**Comment by drtshock** [comment]
Isn't scamming and tricking people kind of the point of factions? ;P

**Comment by TheKnight787** [comment]
Maybe, but like that a lot of people left my server. They are saying "I lost everything, because of some ***\* and I don't want to start everything all over".

**Comment by drtshock** [comment]
We are planning on adding some neat things to a premium branch, we'll take a look at letting faction owners configure moderator permissions.

**Comment by squidicuzz** [comment]
Would the addition of a Recruit group, with permission below that of member, be a good idea?  Is there  still interest is this?

**Comment by drtshock** [comment]
#146 explains it better.
