### ISSUE TITLE
Cancel teleportation on move!!!

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#240]
Right now there is a way to /f home or /f warp with a cool down which is great but if the player moves the teleportation should be canceled because the players are easily getting out of pvp by using /f home and running away for 5 seconds

**Comment by killyouslow** [comment]
I Like this and think it should be added too, "not saying that factions premium is ALREADY AWESOME!!! CUZ IT IS :D"

**Comment by drtshock** [comment]
Definitely still needs to be added.

**Comment by drtshock** [comment]
[13:17:27]  <Connor>    #240 is already resolved
