### ISSUE TITLE
/f list shows UUIDs in offline list

### ISSUE THREAD

**Issue by ColeBennett** [drtshock/Factions#244]
This is quite a big issue and complaint among players:
http://gyazo.com/d54d0aef44f5030d3132fe10302c929b

Online list is fine, but the offline shows UUIDs. Would it be possible to keep records of the last known username in players.json to use in the offline list instead of UUIDs? Thanks

**Comment by cnr** [comment]
Which version are you running? players.json should already contain the last known username for each player as of U0.1.14

**Comment by ColeBennett** [comment]
Oh. I was running U0.07 apparently. Works great now with latest version! Sorry :D
