### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Factions#245]
Could you possibly make it so mobs (or just creepers) can not walk into warzone? As Im having quite a few complains about people leading creepers into warzone and make them blow up "spawnbases" by getting them all the way into the door sort of etc and then they blow up peoples spawnbases through that. Ive disabled them from spawning in warzone already, but they are being lead into warzone by players and I cannot currently find a way to stop this.

**Comment by cnr** [comment]
Change `warZoneBlockCreepers` to `true` in conf.json. We don't plan on restricting mob movement otherwise.

**Comment by zRiaz** [comment]
That wasnt the issue I was reporting.. but ok....

**Comment by zRiaz** [comment]
There is a difference between walking into warzone and exploding in warzone.

**Comment by zRiaz** [comment]
Would be nice if the warZoneBlockCreepers feature stopped them from walking into warzone aswell.
Because as I said I had disabled the destruction of blocks in warzone already but I wanted to keep them out of warzone aswell to prevent a issue with spawnbases...

**Comment by cnr** [comment]
It's painfully slow to despawn mobs when they walk into an area (preventing them from walking in at all isn't feasible either), which is why we're probably not going to add such a feature.
