### ISSUE TITLE
CombatLog

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#246]
This plugin doesn't work with combat log:

Version:
![goog](https://cloud.githubusercontent.com/assets/10871461/6068050/1922301e-ad47-11e4-9919-93e7ee421f48.png)

Error:
![goo2](https://cloud.githubusercontent.com/assets/10871461/6068056/2161f8ea-ad47-11e4-909f-3bf2cc3adecd.png)

**Comment by drtshock** [comment]
Yes, you need to get an updated version of that plugin or harass @jackproehl

**Comment by ghost** [comment]
The plugin is up to date and it use to work. It only doesn't work with your factions plugin.

I removed your Factions plugin and it worked fine.

**Comment by drtshock** [comment]
Because it's running on a 3 year old version of Factions.

**Comment by ghost** [comment]
I've been running that version of factions this entire time. It isn't like I downgraded. Go try it yourslef. Combatlog and Factions 1.6.5 (or whatever version it is) work together = what I used

Combatlog and Factoins UUID 1.6.5 (your version) don't work together = current issue
