### ISSUE TITLE
HCF Is not in my conf.json

### ISSUE THREAD

**Issue by nscwalk** [drtshock/Factions#247]
I have redownloaded the plugin with the latest version deleting all the past files. I look through both the config.json and the conf.json and it does not come with the HCF features to enable DTR and Raidable at the bottom. And when I copy the config from here and put it into mine it doesn't work. I can not enable hcf and this is very frustrating as I have been trying for the past week now

**Comment by drtshock** [comment]
You can use the max power per player and per faction to set it up just fine.

**Comment by nscwalk** [comment]
But I would like to enable DTR and raidable. I know I could use the power thing but then you have to overclaim the person for then to go raidable because I can not enable the no overclaim feature and raidable feature in the HCF part of the config file
