### ISSUE TITLE
"enablePVPAgainstFactionlessInAttackersLand" Not working

### ISSUE THREAD

**Issue by Saiee** [drtshock/Factions#249]
https://github.com/MassiveCraft/Factions/issues/619

This issue wasn't fixed even in the original Factions, I hope you guys can some how resolve it.

"enablePVPAgainstFactionlessInAttackersLand": true

Yet it still won't work. Tried it with all the Factions Version.

**Comment by nscwalk** [comment]
hmmmm try making sure you are turning off you server when you edit your config file. maybe try that but I wonder why it doesnt work

**Comment by Saiee** [comment]
Trust me, I did all of that. I've been using Factions for a long time, however this never got resolved.

**Comment by cnr** [comment]
Mind pasting your conf.json on [gist](https://gist.github.com)?

This setting is working for me locally.

**Comment by Saiee** [comment]
https://gist.github.com/Saiee/8306b6105058d4b6e44f

Could I see yours as well?

**Comment by cnr** [comment]
I've tested with your conf.json and it's working for me. Perhaps another plugin is at fault?

**Comment by Saiee** [comment]
Weird.. Before posting, I tested it 3 times on a Vanilla Minecraft Server with Factions only.

Didn't work.

**Comment by cnr** [comment]
What server software (+ version) are you running? Could you provide a startup log?
