### ISSUE TITLE
Invalid damage reduction.

### ISSUE THREAD

**Issue by TheKnight787** [drtshock/Factions#25]
When you are enemies with another faction. And when you are in their teritory, you can't deal any damage to them. With sharpness 20 sword you barely deal 1 heart of damage to a non armored player.

**Comment by drtshock** [comment]
Do you have a territory shield factor set?

**Comment by TheKnight787** [comment]
Yes, 0.3

**Comment by drtshock** [comment]
That would be the reason. It'll remove 30% of damage then.

**Comment by TheKnight787** [comment]
But it removes all of the damage. If a sharpness 5 sword should deal at least 3 hearts of damage, it does 0.

**Comment by iaxedu** [comment]
I'm having the same problem the damage reduction is bugging.

**Comment by TheKnight787** [comment]
If you set the shield factor to 0, this issue doesn't appear.

**Comment by drtshock** [comment]
Looks like it might just be an issue with how it's rounding off damage. (sorta saying that to leave myself a note for when I'm at my computer).

**Comment by drtshock** [comment]
That will make the damage be more precise. I haven't changed anything regarding damage other than this so I'm not sure why or how this issue would be isolated to my version.

**Comment by drtshock** [comment]
If that doesn't work, let me know and I have a few other ideas.

**Comment by nxtboyIII** [comment]
Well, it not only doesn't damage them, it actually HEALS them.

**Comment by drtshock** [comment]
@nxtboyIII still on build 38?

**Comment by nxtboyIII** [comment]
Yeah, I'm using latest Spigot build and #38 and the problem still persists.

**Comment by drtshock** [comment]
I just removed it, damage was changed and I don't want to rewrite how it handles it at this point. https://github.com/drtshock/Factions/commit/1fa7e28ffd9724ffa30fb91adc06d5dff7ea1606

**Comment by drtshock** [comment]
You can view this thread for an explanation http://forums.bukkit.org/threads/psa-read-if-you-modify-entitydamageevent-setdamage.288595/
