### ISSUE TITLE
Players can place water in WarZone

### ISSUE THREAD

**Issue by EliteWhopper** [drtshock/Factions#251]
I noticed that players can't break any block in WarZone etc, but they can place items hence, water, lava, spawn eggs, etc. I hope you can fix this because it gets annoying having to put out the water and lava, hah. Have a good one and thank you.

**Comment by cnr** [comment]
Is `warZoneDenyBuild` set to `true` in conf.json? If so, I can't reproduce -- please paste your conf.json in a [gist](https://gist.github.com)

**Comment by EliteWhopper** [comment]
Yes, it is.
https://gist.github.com/EliteWhopper/36c4f5e887d26122023b

**Comment by cnr** [comment]
Does this happen when Factions is the only installed plugin on the server?

**Comment by EliteWhopper** [comment]
Yes.

**Comment by aeonlamb** [comment]
This is still happening. Players can place buckets of lava and buckets of water inside of safezone & warzone. Happens on 1.6.9.5-U0.3.0-b133, Paper 1.13.2 .

**Comment by CmdrKittens** [comment]
Resolved in upcoming release. This was a quirk of several settings overlapping that are not defaults, so it was hard to catch until now.
