### ISSUE TITLE
I dont have the additional HCF portion of the config file

### ISSUE THREAD

**Issue by nscwalk** [drtshock/Factions#252]
When I load up my factions plugin and look at the config. it is diffrent from the one that your supposed to get that I have seen from drtshocks posts on here. it is missing the whole HCF additions at the bottom. I can not enable the raidable or dtr feature of this plugin. if there is a way I could get help that would be great

**Comment by cnr** [comment]
You'll have to manually paste in the relevant portions of the config yourself (or remove your current config and change things when it's created again).

It's been on the 'to do' list to have the config update itself, but I haven't had the opportunity to resolve it yet.

**Comment by nscwalk** [comment]
So how do I add this part to the plugin because when I copy and paste the config file into the plugin And enable the features it does not work
