### ISSUE TITLE
WorldBorder

### ISSUE THREAD

**Issue by zRiaz** [drtshock/Factions#254]
Would be awesome to have worldborder support.
So claiming outside the set worldborder would not be possible. That way my players will stop asking me to go outside the border and unclaim for them :P

**Comment by drtshock** [comment]
If spigot has a worldborder api then sure ;D

**Comment by zRiaz** [comment]
Mkay well Ive suggested getting a wb api on the Spigot Hub now.

**Comment by zRiaz** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/7714b7034f4f99387db967f2e6e28ec02a3f1cc5
Appearantly there already is a worldborder api @drtshock 
Atleast for bukkit.
