### ISSUE TITLE
Ho comprato il plugin ma non funziona!

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#255]
Appena avvio il server mi da una lista di player di cui non è stato possibile trasformare il nick in UUID, ma questo non è un problema visto che anche chi non sta in quella lista viene cacciato dalla fazione. Il plugin dunque è inutilizzabile. Posso dimostrare tutto tramite Teamviewer. Grazie per l'attenzione.

**Comment by drtshock** [comment]
English please.

**Comment by ghost** [comment]
As soon as I start the server from a list of players that have not been possible to transform the nick in UUID , but this is not a problem since even those who are not in that list is hunted by the faction . The plugin is therefore unusable. I can prove all via Teamviewer . Thank you for your attention.

**Comment by cnr** [comment]
Could you provide your server startup log and your players.json? (paste on [gist.github.com](https://gist.github.com))

**Comment by ghost** [comment]
This is my player.json
https://gist.github.com/PatatoneKiller/465aa3eff777863cd3ec

**Comment by ghost** [comment]
I can not see honeycombs start of my server with your plugin because when I saw that did not work I deleted and now since I have requested the redemption I can not download more .
