### ISSUE TITLE
/f top is run in the main thread, causing significant hangs

### ISSUE THREAD

**Issue by vemacs** [drtshock/Factions#256]
Timings displaying this issue with /f top money: http://timings.aikar.co/?url=10151090

**Comment by cnr** [comment]
Not sure if this can be fixed (in particular the `money` part), as Vault API isn't thread-safe. I'll see if the other options are causing any significant issues as soon as I can (probably this weekend).

worst-case: we can provide options to disable the individual `/f top` options

**Comment by minecrafter** [comment]
Looking at the code, it looks quite severe. It's summing up the balances of players in the factions, which isn't exactly a trivial operation - I'm very sure there's a faction with tens of players in it on @vemacs's server.

It might be workable by batching and caching results - I'm not sure if anyone really needs an on-demand top list, though. Most players should be fine with a list that's just a few minutes old.

**Comment by drtshock** [comment]
Would still love if this was fixed up @cnr :D

**Comment by Techcable** [comment]
Essentials money is thread safe. We could calculate f top async for essentials, and fallback to the main thread if there isn't essentials present.
This will only fix the problem with essentials, but thats not really an issue :)

**Comment by drtshock** [comment]
Assuming all econ plugins are threadsafe isn't really a good idea.

**Comment by Techcable** [comment]
@drtshock No, we do it async if we're dealing with essentials, and sync if were dealing with anything else.

**Comment by drtshock** [comment]
So solve the problem for a few people? :\

**Comment by vemacs** [comment]
Do it sync periodically, and cache the results? Would heavily reduce the load. Might even be possible to spread it across multiple ticks.

**Comment by Techcable** [comment]
@drtshock who doesn't use essentials econ? Pretty sure its by far the most popular.

**Comment by vemacs** [comment]
https://github.com/drtshock/Factions/pull/668
