### ISSUE TITLE
getLastDeath()

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/Factions#258]
We need "getLastDeath()" in factions

**Comment by drtshock** [comment]
that returns what?

**Comment by intelliJent** [comment]
The get last death. There's the option to set the last death, but not one for getting the last death.

Seen here:
https://github.com/drtshock/Factions/blob/1636708cef382ad0cd172421940fb39058ff28ac/src/main/java/com/massivecraft/factions/zcore/persist/MemoryFaction.java Ln. 43:

`protected long lastDeath;`
