### ISSUE TITLE
Enemy territory deny commands don't do anything

### ISSUE THREAD

**Issue by iaxedu** [drtshock/Factions#26]
Using build #35

Players can do /sethome (all blocked commands) in enemy territory. 

Some players have also reported they are unable to kick an player from their faction when they are offline. This does not always occur and no errors are reported.

**Comment by TheKnight787** [comment]
I also have the issue with some players unable to kick offline players.

**Comment by drtshock** [comment]
Ah, understandable. I will get to this when I'm at my laptop tomorrow.
