### ISSUE TITLE
Factions doesn't work with my scoreboard plugin

### ISSUE THREAD

**Issue by GhastLegion** [drtshock/Factions#263]
When I upload the factions jar and my scoreboard jar, the console gives me a lot of errors. Can you make an personal version for me?

Martijn

**Comment by drtshock** [comment]
Can you please give us a pastebin of the startup log.

**Comment by GhastLegion** [comment]
yes ofcourse,
This are the errors: http://pastebin.com/KEgbAiBw

Martijn

**Comment by drtshock** [comment]
They fixed this awhile ago http://dev.bukkit.org/bukkit-plugins/scoreboardstats/files/37-scoreboard-stats-v0-8-5/
