### ISSUE TITLE
[Bug] / [Feature Request] Dynmap "Flag" icons aren't working / showing up properly

### ISSUE THREAD

**Issue by killyouslow** [drtshock/Factions#265]
Im having trouble with the Factions sethome "GreenFlag" icon, it wont show up when i set my factions home, im using the lastest version of Dynmap and im using FactionsUUID premium

i dont know what im doing wrong for the life of me it just wont show up, which makes me super sad :(

Someone please help me

**Comment by killyouslow** [comment]
Would love for drtshock to add more dynmap support, just need to fix the icons for fsethome, im even willing to pay a little extra cash to make it happen? get in touch with me please dirtshock?

**Comment by drtshock** [comment]
Eh, not exactly high on the priority list unfortunately.

**Comment by killyouslow** [comment]
I understand your time is valuable :)

I've had to deal with alot of frustrations with mcore / factions for years, soo your plugin is my best way out, if there's a way for me to make this feature worth implementing for you let me know, should be a quick / easy fix, then again i wouldn't know because i'm not a developer =P

**Comment by drtshock** [comment]
Not sure what we don't have yet. If you still need something, open a new ticket :)
