### ISSUE TITLE
Package name change

### ISSUE THREAD

**Issue by kwek20** [drtshock/Factions#266]
Hi!

I want to add support for both this version and factions.
Unfortunately, they both run on the same package causing my IDE to be confused ;)

To fix this,I need to use reflection in order to acces fields and methods for your plugin.
I figure other devs arent as confortable with reflection as i am, and frankly, its easier without having to use it.

Could you move everything to a different package?

**Comment by drtshock** [comment]
https://github.com/drtshock/ObsidianDestroyer is a great example of how to do that with maven. It's even with Factions.

**Comment by kwek20** [comment]
Hmm yes i see.
Still not a good practise to leave a different plugin (it kinda is now) with the same package :)

**Comment by drtshock** [comment]
It's a fork. It's bad practice to change namespace.
