### ISSUE TITLE
Factions doesn't work with my combatlog plugin

### ISSUE THREAD

**Issue by GhastLegion** [drtshock/Factions#268]
When I hit someone in combat (combatlog plugin) The whole combatlog plugin doesn't work anymore and gives me these errors:      http://pastebin.com/1tU4PxgK

I tried already the combatlog plugin without factions, and it works perfect.
Maybe you can help me out with this problem?

**Comment by drtshock** [comment]
That plugin is super old and is built against a version of this plugin that's 3 years old. There is an updated version of that plugin somewhere that works with this one.

**Comment by GhastLegion** [comment]
hmm okay thank you I have searched but it seems that there isn't an update of combatlog so I'm going to use CombatTag. :)

**Comment by drtshock** [comment]
Ah, I think it's http://dev.bukkit.org/bukkit-plugins/combat-tag-reloaded/ that works with this fork of factions.
