### ISSUE TITLE
HCF Issues!

### ISSUE THREAD

**Issue by CanadianKush** [drtshock/Factions#270]
When using a max player power as 1 with a max of 6dtr i cannot allow factions to claim over 6 land due to the land-power method. We also need an option to be able to see where the factions home is set while using /f who. Thank you!
Cheers.

**Comment by nscwalk** [comment]
Does DTR show up on your F who because I cant get mine to work

**Comment by Lotteries** [comment]
nscwalk, if i'm correct in the 'config.yml' under the HCF settings there is DTR and raidable, both of those need to be enabled. Hope that helped, you can customize the DTR message in /f show in the 'lang.yml'! Good-luck!

**Comment by nscwalk** [comment]
No I dont have the hcf part in my config.yml I figured out I have to get a development build from the CI

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.
