### ISSUE TITLE
Don't Rely DTR on Power

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#274]
Lets start this off. I hate to break it to you, and others have been too, but DTR cannot be relied off of power. Power is a completely different concept.

The only way to make DTR function as intended, you need to make it its own system, as in a togglable mode. (HCF: true)
Converting F SHOW, and other things into the HCF system.

Recommendations for the DTR, adding a system instead of relying it on the power system,

F SHOW - http://prntscr.com/5xy88n
You should add an HCFShow option, that converts f show into HCFs version, by eliminating the enemies bar, replace "Land / Power / Max Power" with "Land: x/32". As well as moving the raidable above DTR or adding to the DTR line "DTR: -1.1/5.5 (Raidable)"
I also recommend adding point DTR as in 0.01, 0.02 going up. (Max being 5.51)

DTR REPLACES POWER!

Factions should have a maximum of 5.51 DTR, (For a full faction).
Each player is worth 0.51 DTR. 

When a player creates a faction, they should start at 0.00 DTR, and it should start increasing by 0.05 DTR every minute, I'm pretty sure, so every 12 seconds, they go up by 0.01 DTR.

If a player dies, you lose 1.01 DTR, and the DTR Freeze kicks in, no DTR regeneration for 1 hour. 
(Say the 1 hour counter is at 20 minutes, 32 seconds left, if another member dies, the timer goes back up to 60). 

Every new member to the faction accounts for 0.51 DTR, so if there is 2 people, DTR = 1.02, so on and so forth. Say there is 11 people in the faction, (Every person counts for 0.51DTR) although the match makes it 5.61, DTR would MAX at 5.51.

Adding the message for when you move land.
"&eEntering &2Wilderness&e, leaving &4Warzone"
Adding in that you cannot claim 2 chunks from another faction, (To stop traps, etc).

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.
