### ISSUE TITLE
Faction home Coordinates

### ISSUE THREAD

**Issue by Lotteries** [drtshock/Factions#277]
When a faction has there faction home set, when you have the DTR/Raidable mode set to 'true' it should show the faction home coordinates in /f show, here is a example of how it should look. http://gyazo.com/66b918993f77395761b1a60cdb1a5230 That should only show if DTR/Raidable mode is set to true.

**Comment by drtshock** [comment]
Duplicate https://github.com/drtshock/Factions/issues/166
