### ISSUE TITLE
TerritoryProtectedMaterials Issue

### ISSUE THREAD

**Issue by maxhuebler** [drtshock/Factions#28]
Hi,

I'm currently having an issue where players can still use levers, stone buttons, and wooden buttons in enemy territory. I'm quite positive we have the configuration setup correctly so that you shouldn't be able to use these items in enemy territory, but you can.

Now this is why I made an issue because I wasn't sure if this was a configuration problem or the fact that the plugin doesn't support "LEVER" and "STONE_BUTTON" etc.

Anyways, again I'm not sure if this is related to the plugin or my configuration. Below I have provided my factions conf.json.

Factions conf.json: http://hastebin.com/nixahileso.cpp

Thanks

**Comment by drtshock** [comment]
Is this still an issue?

**Comment by maxhuebler** [comment]
Yes

**Comment by blha303** [comment]
Hi, hastebin pastes expire after a month (or something like that), can you repaste your Factions config on [pastebin](http://pastebin.com) please?

**Comment by maxhuebler** [comment]
Here you go using pastebin, I didn't know hastebin auto deletes pastes after a certain period of time. http://pastebin.com/imNRmBb9

**Comment by drtshock** [comment]
So does pastebin. https://gist.github.com doesn't :)

**Comment by maxhuebler** [comment]
Good too hear, I suppose that will be my new pasting service.

**Comment by squidicuzz** [comment]
With your config, I could still use WOOD_BUTTON.  However, the current version seems to be lacking some materials.  I added the missing materials and generated a fresh config and was not able to use WOOD_BUTTON.

**Comment by drtshock** [comment]
Is this still an issue?

**Comment by maxhuebler** [comment]
I believe so, I can't test it right now but I'm 99% certain items like levers don't work.

**Comment by drtshock** [comment]
I've been using this on my server and it works fine.

**Comment by maxhuebler** [comment]
This still doesn't work properly with STONE_PRESSURE_PLATE and WOODEN_PRESSURE_PLATE, people can still use them even with those set in the territoryProtectedMaterials.

  "territoryProtectedMaterials": [
    "SOIL",
    "WOODEN_DOOR",
    "IRON_DOOR",
    "SPRUCE_DOOR",
    "BIRCH_DOOR",
    "JUNGLE_DOOR",
    "ACACIA_DOOR",
    "DARK_OAK_DOOR",
    "STONE_BUTTON",
    "WOOD_BUTTON",
    "LEVER",
    "DIODE_BLOCK_OFF",
    "DIODE_BLOCK_ON",
    "TRAP_DOOR",
    "STONE_PRESSURE_PLATE",
    "WOODEN_PRESSURE_PLATE",
    "FENCE_GATE"
  ],

**Comment by uf0h** [comment]
Similar issue but with the following types of doors: 

Birch
Acacia
Spruce
Jungle
Dark Oak
