### ISSUE TITLE
Don't Use DTR for Claiming Land

### ISSUE THREAD

**Issue by nscwalk** [drtshock/Factions#284]
![bandicam 2015-02-22 02-52-21-715](https://cloud.githubusercontent.com/assets/10702752/6318270/efb04906-ba3d-11e4-9070-51599dba9c7a.jpg)
Do not use DTR for claiming land. DTR should not be associated with land, and power at all. DTR should have nothing to do with power and should ultimately replace it completely with a new config. an example would be like this
![bandicam 2015-02-22 02-56-19-377](https://cloud.githubusercontent.com/assets/10702752/6318279/a01eb2f0-ba3e-11e4-8b00-417d2a2e74fd.jpg)

**Comment by degenorate** [comment]
Seriously dont even try to explain this to people. I bought this plugin for HCF and DTR. and its been a complete waste. The dev is amazing in his work, but without disrespecting him. he is completely ignorant when it comes to this issue. I made a huge explaination of this and he completely ignored it. claiming you can do the same thing by just "altering the config thats been there for years". it simplies isnt true and its completely different.

**Comment by MoeXIV** [comment]
Vouch. I like this!

**Comment by LynchedAcoustics** [comment]
DTR doesnt seem to show for me when i make it true in the config. i was thinking you may know what i should do :)
same with raidable

**Comment by nscwalk** [comment]
I recently figured it out. You have to ask DRTShock himself for access to the CI development build.

**Comment by LynchedAcoustics** [comment]
Okay i have it so it looks like your screen shot now, but it really isn't like I wanted it to be like haha (like kohi's). Are you having the same trouble?

**Comment by drtshock** [comment]
DTR will be added in a separate project. I'll post all the details on spigot and twitter soon.

**Comment by LynchedAcoustics** [comment]
Alright :)

**Comment by nscwalk** [comment]
Thank you
