### ISSUE TITLE
I want the plugin that I paid

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#286]
I bought this plugin, after I asked for a refund because my server was not working but now saw that the reimbursement was rejected again I would like to download the plugin that I paid. Thank You. Sorry for how to write but I do not speak English.

paypal transaction code: 99676350RT1512330

**Comment by drtshock** [comment]
You disputed the payment, lost the dispute, and now you want the plugin and support? Are you fucking kidding me?

**Comment by EvelynSubarrow** [comment]
So you don't want it but you want it?
</logic>
