### ISSUE TITLE
DTR enabled but not working?

### ISSUE THREAD

**Issue by LynchedAcoustics** [drtshock/Factions#287]
Okay, so i enabled dtr as true and hcf as true (not sure if i should have done that or not) but none of the features that i have seen in DTR are showing up. I have tried looking in the lang.yml to see if i had to change something in there (because i was looking through the other issues and saw something like that). anyways if anyone or drt can help with getting the DTR functions to show up and work please help me out!

**Comment by drtshock** [comment]
Hm? We're working on adding more of the 'dtr' features. Just be patient :)

**Comment by LynchedAcoustics** [comment]
Well what i was saying is that the F show looks nothing like i am used to atleast. 
(What i mean: http://m.imgur.com/JXTjf50)
So without that i dont really even know if the DTR options of the plugin work. Please if you could enlighten me on this :)
