### ISSUE TITLE
Unable to kick some members from factions who were offline for a while.

### ISSUE THREAD

**Issue by iaxedu** [drtshock/Factions#29]
Using build - 38
Spigot - 1529

Some factions have the issue that they cannot kick some players from their faction when they are offline. When I join this faction and do /f kick name the chat shows kicked name from wilderness. When you check the faction the player is still there. 

Another bug is that power isn't showing correctly. When a player goes offline their power often changes instantly to some other number. There are many issues with power of players hard to explain all the different issues please take a look at it.

Thanks in advance

**Comment by drtshock** [comment]
Can you please create separate tickets for these?

Let's go with the first for this ticket, does this happen to any offline player? Or is there a specific amount of time that a player has to be offline? Does it work to kick any offline players out? Which build of Factions are you using?
