### ISSUE TITLE
Faction create & Faction See Chunks

### ISSUE THREAD

**Issue by lyzha** [drtshock/Factions#291]
Error while trying to create a faction: http://pastebin.com/RSXeD3A4.
When using /f sc blocks that show border aren't disappearing.
Using Git-spigot-1487 1.7.9-R0.3-SNAPSHOT, Worldguard 6.00-beta-05.1569

**Comment by drtshock** [comment]
Paste your entire startup log and conf.json please.

**Comment by lyzha** [comment]
There you go
http://pastebin.com/jrJ8bAGK
And btw you should add a way to change greeting and farewells messages.

**Comment by drtshock** [comment]
Looks like you're using 1.7.9 or older. Upgrade craftbukkit or downgrade factions.
