### ISSUE TITLE
Friendly fire and powerloss in wg regions

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#299]
Would really be awesome to have friendly fire and power loss in world guard regions. Since many are using world guard regions instead of warzones. Thank you very much :)

Example:
  "worldGuardPowerLoss": false,
  "worldGuardFriendlyFire": true,

**Comment by drtshock** [comment]
It would make more sense to have it as a custom flag.

**Comment by mbax** [comment]
Implemented FF control.
