### ISSUE TITLE
[FACTION] in EssentialsChat creating a tilde if user isn't in a Faction

### ISSUE THREAD

**Issue by nxtboyIII** [drtshock/Factions#30]
If a user isn't in a Faction, instead of saying their faction name where "[FACTION]" is in EssentialsChat, it shows a tilde (~)

**Comment by nxtboyIII** [comment]
bump

**Comment by JordanFromIT** [comment]
To fix it make sure you have the following in your factions config file:

  "chatTagEnabled": true,
  "chatTagRelationColored": true,
  "chatTagReplaceString": "",
  "chatTagInsertIndex": 0,
  "chatTagPadBefore": false,
  "chatTagPadAfter": false,
  "chatTagFormat": "%s",

If you set these just like this then the colored faction tagw ill show at the beginning of a line of chat and will show nothing if there is no faction the player is in

**Comment by nxtboyIII** [comment]
well i dont want it to be at the very beginning i want it to be in brackets thats why I am using the "[FACTION" placeholder in essentials chat so it looks like this in essentials:

format: &8[&r[FACTION&8] {DISPLAYNAME&f: {MESSAGE}

**Comment by drtshock** [comment]
Should be fixed in recent commit. https://github.com/drtshock/Factions/commit/957f8a209d1335f78cebc2060f2c9a001019648c
