### ISSUE TITLE
Error with /f show

### ISSUE THREAD

**Issue by Miaourt** [drtshock/Factions#301]
A little error.... players can't "show" faction :')

http://pastebin.com/ZR4LMkuf

**Comment by drtshock** [comment]
Again, pastebin.

**Comment by Miaourt** [comment]
Pastebin'ed sir http://pastebin.com/ZR4LMkuf <3

**Comment by Miaourt** [comment]
Up.... hope this (https://github.com/drtshock/Factions/pull/295) will be merge

**Comment by drtshock** [comment]
Would be nice if people properly tagged their commits but one can't ask for too much I guess!

**Comment by Miaourt** [comment]
Uhoh... ._.'

**Comment by xguys** [comment]
i have same problem

**Comment by MoeXIV** [comment]
This issue still persists.

**Comment by Miaourt** [comment]
Uhuh...

**Comment by drtshock** [comment]
Remove http://prntscr.com/6wpyt5 and it'll be fixed.

**Comment by Miaourt** [comment]
Thank you sir <3
