### ISSUE TITLE
Error with... dunno

### ISSUE THREAD

**Issue by Miaourt** [drtshock/Factions#302]
Sometime I get this error, I hope this would help to catch something ^^

http://pastebin.com/dZZHWkNF

**Comment by drtshock** [comment]
Could you edit your post by putting it in a pastebin or a gist and then bump this please :)

**Comment by Miaourt** [comment]
http://pastebin.com/dZZHWkNF There is for the pastebin :p

**Comment by drtshock** [comment]
Was an issue with scoreboards being null. Has since been fixed.
