### ISSUE TITLE
F who 

### ISSUE THREAD

**Issue by lyzha** [drtshock/Factions#303]
While f who my faction i see that message http://i.imgur.com/yHLeLXD.png

**Comment by lyzha** [comment]
Using craftbukkit https://imgur.com/KN7KdGO and faction https://imgur.com/ScAUb0A

**Comment by drtshock** [comment]
What's the error?

**Comment by lyzha** [comment]
In the console ?

**Comment by drtshock** [comment]
yes...

**Comment by lyzha** [comment]
http://pastebin.com/xfHPt6hA

**Comment by lyzha** [comment]
Sorry I sent a wrong error before there you go http://pastebin.com/aP3NnHH3

**Comment by xguys** [comment]
i have the same problem

**Comment by drtshock** [comment]
not an issue
