### ISSUE TITLE
Factions UUID not compatible with ScoreboardStats (again)

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#307]
Hi,

There if again bug with ScoreboardStats. More informations: https://github.com/drtshock/Factions/issues/298

Thanks,
Yoann166

EDIT:
I must add "<my UUID>: false" on "playerBoardToggle.yml" file, or, use /f sb to activate ScoreboardStats. It's possible to config Factions UUID with default "false"?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
