### ISSUE TITLE
FactionsUUID 

### ISSUE THREAD

**Issue by zxnakzxz** [drtshock/Factions#308]
The faction name and color dont work! I recently converted to factions UUID and the relcolor and faction name doesnt work.
![screen shot 2015-03-10 at 23 18 13](https://cloud.githubusercontent.com/assets/11355851/6587416/c8be0dd8-c77b-11e4-8991-3f6375bf6e58.png)

**Comment by drtshock** [comment]
Can you paste your lang.yml file in a pastebin please.
