### ISSUE TITLE
FactionsUUID Faction Tags Not Showing

### ISSUE THREAD

**Issue by zxnakzxz** [drtshock/Factions#310]
I recently upgraded to the FactionsUUID, and it now showing the tags normally. It is now showing the loaded faction prefix.

![factionerrror](https://cloud.githubusercontent.com/assets/11355851/6647714/452a6a8e-c9c9-11e4-94d4-e3f3eb99e424.png)

This is when I used factions with massivecore. The text used to show, as factions less people as this.

![factionless](https://cloud.githubusercontent.com/assets/11355851/6647717/50f8f506-c9c9-11e4-8cd4-9b03b6259e3c.png)

And people with factions as this.

![facton](https://cloud.githubusercontent.com/assets/11355851/6647720/59fa6e8c-c9c9-11e4-8498-4d1cbf0ef680.png)

I wonder if you can help me change it back to the original prefix. If you need anything else you can contact me.

Pastebin for files:
Config: http://pastebin.com/n1A8RY6V
Lang: http://pastebin.com/cm68PMaZ

**Comment by lyzha** [comment]
I think the default prefix is the prefix in the tab or over your head, you should replace {...} by [FACTION] i guess

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
