### ISSUE TITLE
Faction chat tag not working!

### ISSUE THREAD

**Issue by oxynov** [drtshock/Factions#313]
As you see, i've added the brackets [] for factions 
http://gyazo.com/8899f512d85f9065c97fac02bef57ae4

But it shows as this
http://gyazo.com/a5c3a552787b27aef45b94186ab7f05f

Also, i want it to be like [] [Member] Poppy231: hi
when they dont have a faction and when they make one, to make it say
[myfaction] [Member] Poppy231: hi

**Comment by MoeXIV** [comment]
That's the "REPLACE" item in your conf.json, I'm pretty sure.
You must use essentials.

**Comment by perspectivv** [comment]
In essentials config under essentials chat, put '[[FACTION]] [Member] {DISPLAYNAME}: {MESSAGE}'. This will make it where [] will pop up if you don't have a faction. You can add color accordingly.

**Comment by oxynov** [comment]
Ok i did that and its working, now how do i add color to the faction tag?

**Comment by drtshock** [comment]
Use &4 or w/e number for color codes.
