### ISSUE TITLE
[HELP] Development Builds

### ISSUE THREAD

**Issue by Lotteries** [drtshock/Factions#314]
Hello, not really a issue but more of a question.
I didn't know were to message drtshock, so i thought this was the second best place
to receive help for the plugin. I've bought this plugin under the intention it had DTR (Such as Kohi, Shotbow, BasicHCF etc..) and it turned out it wasn't really 'DTR'. I've been told by friends that i can get CI Access to working DTR builds by asking drtshock, how about would i get access to the Dev. builds?

I'm really looking forward to what has been added, i hope its worth what i paid for :+1:

**Comment by drtshock** [comment]
HCFactions has it, FactionsUUID doesn't. It's a separate project and separate project and a separate purchase. Unfortunately, spigot took down HCFactions after it already had 7 buyers. We're working on a new website to sell it on. I'll be tweeting that once it's out. https://twitter.com/drtshock
