### ISSUE TITLE
People doesn't lose power :(

### ISSUE THREAD

**Issue by Nordicuniverse** [drtshock/Factions#317]
Start up message. http://pastebin.com/x5a7Sxcm
Config http://pastebin.com/VzMeFs13
Idk why people doesn't lose power when they die, kinda wierd, and many people is complaing about it :(

**Comment by drtshock** [comment]
What power do they have when they die? They should be losing 4 each death down to -10. Can you paste the log of when they are dying.

Also, what's your username on spigot?

**Comment by Nordicuniverse** [comment]
LJGz, and 10 power when they die

**Comment by drtshock** [comment]
paste the log please. Something is wrong on your end :\

**Comment by Nordicuniverse** [comment]
How do i paste the log when people die, sorry im kinda new to minecraft servers, thats why im here :3

**Comment by Nordicuniverse** [comment]
[00:02:38] [Server thread/INFO]: The_Devil_13 was slain by coleweber
[00:02:38] [Server thread/INFO]: coleweber was slain by The_Devil_13
Thats all it says when people die

**Comment by drtshock** [comment]
can't confirm
