### ISSUE TITLE
Getting "An internal error occured while attempting to perform this command" on most commands.

### ISSUE THREAD

**Issue by m9221** [drtshock/Factions#318]
I'm getting the "An internal error occured while attempting to perform this command" error whenever I try to do /f invite, /f mod, /f chat, /f desc & more. I'm running on the latest 1.8.3 Spigot build, FactionsUUID U0.1.14.

Here's the error I get in the console whenever someone tries to do one of these commands:

http://pastebin.com/aRjrxiE0

**Comment by heartz66** [comment]
update your FactionsUUID

**Comment by m9221** [comment]
I'm already on the latest version

**Comment by drtshock** [comment]
Latest isn't a version. This was fixed in a pending PR.
