### ISSUE TITLE
Make a super cool flag GUI

### ISSUE THREAD

**Issue by edasaki** [drtshock/Factions#32]
|   [] [] [] [] []   |
|   [] [] [] [] []   |
|   [] [] [] [] []   |
|----------------|
| [.] [.] [.] [.] [.] [.] [.] |
| o   x   x   x   x   x  x |

^Super beautiful representation.

[] = one "slot" of the flag, represented by a stained glass pane. Default is white. The flag is 3x5.
[.] = a color. Represented by a stained glass pane, but references a chatcolor for use in the flag.
o / x = indicates the color which is currently selected. The user, when clicking one of the flag slots, will change that slot to the color selected.

maybe a 6th inventory row for preset flags or a confirmation button.

**Comment by drtshock** [comment]
So basically:

You can customize your Faction's flag with an Inventory GUI.

**Comment by drtshock** [comment]
srsly

**Comment by mbax** [comment]
With the introduction of banners in game, this feels less useful. Closing this in favor of considering actions using banners in the future.
