### ISSUE TITLE
Problem with FactionUUID U0.1.14 & Spigot 1.8.3

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#320]
Hi, I bought your plugin a few days ago and I tried to put in a server with Spigot" git-Spigot-fcb68de-1e56438 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT )" and use the version of U0.1.14 FactionUUID. Why people are when it comes out of the faction? Sorry for the trouble, my native language is not English I hope you have understood me ;)
Link pastebin: http://pastebin.com/MewCSKZD
Image faction created before: http://i.imgur.com/X7tq9YL.png
Image faction created with FactionUUID: http://i.imgur.com/yWR5vPt.png
Congratulations for your wonderful work, I hope you can help me :)

**Comment by drtshock** [comment]
Try increasing your user cache in the spigot.yml

**Comment by ghost** [comment]
As the first and the second value ?
  user-cache-size: 1000
  int-cache-limit: 1024

**Comment by drtshock** [comment]
The user cache size and I imagine the other one needs to be increased a bit as well.

**Comment by EverMineServer** [comment]
What values ​​should I put the first and second line?

**Comment by ghost** [comment]
These are good values ​​?
user-cache-size: 10000
int-cache-limit: 3072
