### ISSUE TITLE
Spigot 1.8.3 - Error on /f invite

### ISSUE THREAD

**Issue by sojiro7** [drtshock/Factions#324]
Hello,

When a player /f invite another player, we get an internal error. I think it's because of the new 1.8.3 update, do you need a error log? or are you aware of this?

Thanks.

**Comment by drtshock** [comment]
What's the error? Which version of Factions are you on?

**Comment by sojiro7** [comment]
Hello, 

Error: http://pastebin.com/tL7jrpq7

Version: http://prntscr.com/6hqq7v

**Comment by drtshock** [comment]
Update :) Tooltips break between versions. Latest builds on the CI fix it. If you need access to the CI then read the project page on spigot.
