### ISSUE TITLE
People opening chests in claimed territory 

### ISSUE THREAD

**Issue by SoAaron** [drtshock/Factions#325]
So basically, people can open chests and stuff in claimed land. I checked config, and it's not supposed to be like that. Once fixed, can someone send it to me via skype? @aaron.pvp

**Comment by drtshock** [comment]
Can you paste your conf.json and your entire server log from startup to when this happened in a gist or pastebin please.

**Comment by SoAaron** [comment]
Conf.json: http://pastebin.com/Yb3zU4Hd
logs: https://gist.githubusercontent.com/SoAaron/ce523e9ea012f1647359/raw/gistfile1.txt

**Comment by drtshock** [comment]
You should probably fix all those issues in your log :\

Not sure exactly what it is but you likely are enemies with the faction, in bypass, or something.
