### ISSUE TITLE
Invisibility removes tag above head!

### ISSUE THREAD

**Issue by Jordantz72** [drtshock/Factions#327]
Currently once a player drinks an invisibility potion the faction name or player names doesn't go away! I was wondering if you could change that so if i player does decide to drink a invis potion that it would remove the faction tittle about it and their name! Thanks Jordan http://gyazo.com/42a0361adc10d5346a156b72e74ddc09 SHOWS WHAT I MEAN!

**Comment by Mod-masta** [comment]
I'd just like to add that only players using 1.8.x will be able to see the tag over the invisible player.

**Comment by drtshock** [comment]
Apparently feature not bug :(

**Comment by drtshock** [comment]
Not an issue we'll fix.
