### ISSUE TITLE
Faction Flight

### ISSUE THREAD

**Issue by DrinkSwagFriend** [drtshock/Factions#332]
Adding faction flight for flight in between spawn, allies,wilderness, and your own faction but disable flight while in warzone or enemy territories

**Comment by drtshock** [comment]
what is flight

**Comment by DrinkSwagFriend** [comment]
Flight as in the essentials ./fly or any type of flight mechanic currently in minecraft for example, gamemode flight so it would override gamemode flight as well but when you leave the territory that does not allow flight it will automatically regain its flight, same with essentials

**Comment by drtshock** [comment]
This would be more of a worldguard thing.
