### ISSUE TITLE
Customizable "f show"

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#334]
The title explains it all. I request the feature in HCFactions on your repo. It's a cool feature, that I thought it would be a great feature. Also adding some cool variables.

**Comment by drtshock** [comment]
It will get pulled once it's not being changed a few times a week :)

**Comment by MoeXIV** [comment]
Sounds good ;)

**Comment by MoeXIV** [comment]
Any ETA, Trent?

**Comment by nsporillo** [comment]
@MoeXIV https://github.com/drtshock/Factions/pull/387

**Comment by drtshock** [comment]
\o/
