### ISSUE TITLE
bug with /F show

### ISSUE THREAD

**Issue by xguys** [drtshock/Factions#337]
so when i do /f show it says http://gyazo.com/8b747e6fa71cb4d8b645ae738ab46f03
 http://pastie.org/private/bqbs9izxystrhuynaeq4ew thats the error

**Comment by Kakifrucht** [comment]
It's because the translated string is messed up somehow. I simply removed the (bonus: part in the lang.yml in the f show configuration.

**Comment by xguys** [comment]
i tried that it dosnt work for me please someone send me thire lang.yml ? i am opening very soon :(

**Comment by Kakifrucht** [comment]
POWER: '<a>Land / Power / Maxpower: <i> %1$d/%2$d/%3$d'

**Comment by MoeXIV** [comment]
Try not using the 1.8 version on Spigot 1.7.9?

**Comment by Favorlock** [comment]
PR #342 resolves this issue, just waiting on @drtshock to merge it.

**Comment by marium0505** [comment]
Still having this issue after updating to the latest dev version, where the change-log claims the issue to be fixed (double-checked and triple-checked that I have the latest version).

Here are the server information details:

Spigot: Spigot-c3c767f-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Factions: https://ci.drtshock.net/job/FactionsUUID/242/

In Game Error: http://prntscr.com/6q0q7e
Log Error: http://pastebin.com/7XTiUVng

No errors on startup, btw.

**Comment by drtshock** [comment]
Your lang file is messed up @marium0505. You need to add a format specifier to that string
Caused by: java.util.MissingFormatArgumentException: Format specifier '5$s'

**Comment by marium0505** [comment]
The lang file resets to previous when deleted while the server is down? ;o

**Comment by marium0505** [comment]
I deleted both the config and lang file while the server was down, but okey.
