### ISSUE TITLE
(Offline mode server) Still unable to kick offline faction members

### ISSUE THREAD

**Issue by iaxedu** [drtshock/Factions#34]
Hello,

I've reported this before and forgot to mention my server is offline mode. If you do not offer support for this I understand but I would really appreciate it. Everyone who is offline cannot be kicked from the server. We're running offline generated UUID's.

**Comment by Miaourt** [comment]
Why not just use faction without uuid ? :/ if you run a offline server....

**Comment by TheKnight787** [comment]
If he already converted the players into UUIDs. What is he supposed to do?

**Comment by Malachiel87** [comment]
old faction work 1.8.8?
