### ISSUE TITLE
was told to make a ticket for an idea? this the place?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/Factions#346]
originally from my post for feature requests ::

tells you who killed your faction member and what faction they were/are in!

[who was killed] [by whoever] from [faction]

**Comment by EthanJoyce** [comment]
This sounds like a job for the developer of your death messages plugin.

**Comment by drtshock** [comment]
@mrlolethan not really, this is something that I had said we would add at some point.

**Comment by KriticalPvP** [comment]
when do you think this will be added?

**Comment by drtshock** [comment]
Unlikely we'll add this at this point.
