### ISSUE TITLE
Get list of claimed areas

### ISSUE THREAD

**Issue by brcdev** [drtshock/Factions#347]
Hello,
How can I retrieve the list of all claimed areas of specified faction?

**Comment by Kakifrucht** [comment]
You could check board.json. You would need the id of the faction (obtained from factions.json) and then you see the chunk, for instance 31,-20 is chunk at location 31 \* 16, -20 \* 16

**Comment by brcdev** [comment]
I meant retrieve it as an object in the plugin's code, not just check it in the server files. There should be more simple way I'm probably missing than parsing json.

**Comment by drtshock** [comment]
There currently is not a way.

**Comment by brcdev** [comment]
Oh. Are you going to add it at all?

**Comment by drtshock** [comment]
Possibly. If you want to PR it, that'd be great.

**Comment by drtshock** [comment]
Board#getAllClaims(String factionId)
