### ISSUE TITLE
/f invite broken

### ISSUE THREAD

**Issue by MannyAU** [drtshock/Factions#348]
Factions itself is working alright. safezones, warzones.. creating, /f join'in; most things in general that I can see; but I have this internal error every time someone tries to invite someone to their faction. 

http://pastebin.com/Py6hMZ4W

any ideas? Thanks !

**Comment by lol768** [comment]
I wonder if `fme.describeTo(you, true)` returns null

**Comment by Kakifrucht** [comment]
Update to latest version from Jenkins.

**Comment by TheMexicanChip** [comment]
Same its broken for me also

**Comment by lol768** [comment]
@TheMexicanChip Which build are you using?

**Comment by TheMexicanChip** [comment]
For what?
My spigot?

**Comment by lol768** [comment]
No, FactionsUUID.

**Comment by TheMexicanChip** [comment]
facitons 2.6
I think

**Comment by drtshock** [comment]
not broken
