### ISSUE TITLE
factions.json does not update

### ISSUE THREAD

**Issue by comfortedbasher** [drtshock/Factions#349]
Also when i edit factions.json the changes dont take Effect...?? help

**Comment by comfortedbasher** [comment]
I try to change warzone explosion damage to false and change description of safe and warzones but the file resets....

**Comment by comfortedbasher** [comment]
{
  "2": {
    "id": "2",
    "peacefulExplosionsEnabled": false,
    "permanent": false,
    "tag": "Mavericks",
    "description": "You're on our turf now",
    "open": false,
    "peaceful": false,
    "money": 0.0,
    "powerBoost": 0.0,
    "relationWish": {},
    "claimOwnership": {},
    "invites": [],
    "announcements": {},
    "warps": {}
  },
  "0": {
    "id": "0",
    "peacefulExplosionsEnabled": false,
    "permanent": false,
    "tag": "§2Wilderness",
    "description": "",
    "open": false,
    "peaceful": false,
    "money": 0.0,
    "powerBoost": 0.0,
    "relationWish": {},
    "claimOwnership": {},
    "invites": [],
    "announcements": {},
    "warps": {}
  },
  "-2": {
    "id": "-2",
    "peacefulExplosionsEnabled": true,
    "permanent": false,
    "tag": "§4Warzone",
    "description": "Where the Brave come to Die.",
    "open": false,
    "peaceful": false,
    "money": 0.0,
    "powerBoost": 0.0,
    "relationWish": {},
    "claimOwnership": {},
    "invites": [],
    "announcements": {},
    "warps": {}
  },
  "-1": {
    "id": "-1",
    "peacefulExplosionsEnabled": false,
    "permanent": false,
    "tag": "§6Safezone",
    "description": "Prepare for Battle here.",
    "open": false,
    "peaceful": false,
    "money": 0.0,
    "powerBoost": 0.0,
    "relationWish": {},
    "claimOwnership": {},
    "invites": [],
    "announcements": {},
    "warps": {}
  },
  "5": {
    "id": "5",
    "peacefulExplosionsEnabled": false,
    "permanent": false,
    "tag": "Staff",
    "description": "Staff of MineCrave",
    "open": false,
    "peaceful": false,
    "money": 0.0,
    "powerBoost": 0.0,
    "relationWish": {},
    "claimOwnership": {},
    "invites": [],
    "announcements": {},
    "warps": {}
  }
}

**Comment by drtshock** [comment]
Why are you editing that file?

**Comment by comfortedbasher** [comment]
So creepers dont nuke my warzone claims

**Comment by drtshock** [comment]
you shouldn't be touching that file.
