### ISSUE TITLE
MongoDB backend

### ISSUE THREAD

**Issue by EthanJoyce** [drtshock/Factions#352]
This plugin should have support for using MongoDB as a back end.

**Comment by drtshock** [comment]
Would love for you to PR it <3

**Comment by EthanJoyce** [comment]
I'll start work on it soon, hopefully!

**Comment by drtshock** [comment]
\o/

**Comment by drtshock** [comment]
would still love this

**Comment by EthanJoyce** [comment]
I've left the Bukkit/Minecraft scene, but I may finish it in the future. Sorry.
