### ISSUE TITLE
/f who error

### ISSUE THREAD

**Issue by Agazed** [drtshock/Factions#353]
Using Spigot 1.8.3, and latest build from jenkins

http://pastebin.com/znhBEREH

**Comment by MoeXIV** [comment]
1.8.3 is not a compatible spigot version at this time.

**Comment by Agazed** [comment]
Well then may I kindly ask it be updated for 1.8.3? That is the point of my bug report >.<

**Comment by drtshock** [comment]
The plugin works just fine on 1.8.3.

Your issue is odd and seems to be pointing to https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/zcore/MCommand.java#L302 I'll look into it.

**Comment by drtshock** [comment]
Oh. This was already fixed in https://github.com/drtshock/Factions/commit/8354c95a148bca65235d99e3f005775115c38515 You'll want to update to build 245 or higher on the CI.
