### ISSUE TITLE
Error when converting from 1.6.9.5

### ISSUE THREAD

**Issue by DivinityCraft** [drtshock/Factions#354]
The plugin breaks when attempting to convert old Factions (1.6.9.5) data to 1.6.9.5-U0.1.14 on plugin start up. The problem appears to be happening when it tried to convert "old player files", it goes into endless error message spam. I have tested on 3 different computers. 1.6.9.5-U0.1.14 works fine for me when starting it clean without any old Factions data. Complete log of the problem and my old Factions folder and jar is included in the link below.

http://files.enjin.com/372661/Server%20stuff/Factions.zip

**Comment by drtshock** [comment]
You hit the rate limit.

**Comment by DivinityCraft** [comment]
How do I make it work?
