### ISSUE TITLE
Protection Breaking

### ISSUE THREAD

**Issue by Steev93** [drtshock/Factions#357]
Hey,

so the issue is when someone place's a block, not any block, a block that has inventory from Chest, Trapped chest, Furnace, Dropper, ect... it tell the user "you can't build in safe zone" or something, however the block still place's and remaining in there hand to where they can Spam click it like shown here

http://prntscr.com/6s9otj <- a juke box ? Cannot be placed but
http://prntscr.com/6s9ozp <-- a chest can be placed?

So all block's that can bypass the SafeZone are: http://prntscr.com/6s9poz

However i know that those error message's are Worldguard... so here is the SafeZone one http://prntscr.com/6s9r6p

Umm what else.... 

https://gist.github.com/anonymous/0de19b0ed18139f60c99  <  Conf file

https://gist.github.com/anonymous/b1580b405eb5f797ae78  < Server Log

**Now i know Factions is there twice, this has been fixed since,. but still doing the same thing. Any idea's?

Thanks in advance!

P.S this has been happening for a few months now... still unable to fix it and WorldGuard has no idea

**Comment by Steev93** [comment]
No one has anythin? or any tips?

**Comment by Kakifrucht** [comment]
Well something seems to interfere with the blockplace event. Probably Factions/Worldguard cancelling it, but some other plugin uncancelling?

**Comment by Steev93** [comment]
Yeah my thoughts, like myself and the server owner believe it's Factions, which is why i submitted this

**Comment by Steev93** [comment]
.

**Comment by drtshock** [comment]
If this was Factions then I'd have the issue on my server as well. Try testing with just Factions on your server, then slowly add plugins back one by one.
