### ISSUE TITLE
/f invite 

### ISSUE THREAD

**Issue by mufincookies** [drtshock/Factions#359]
Every time a player tries to do /f invite the server is saying "An internal error occurred while attempting to perform that command.   LOGS: http://pastebin.com/423ci77R

Really need some help here, please get back to me when you can.

**Comment by mufincookies** [comment]
Sorry, I did not read all closed issues. Found what I need to do thank you.

**Comment by mufincookies** [comment]
I did leave my name on this closed issue https://github.com/drtshock/Factions/issues/338

**Comment by TheMexicanChip** [comment]
What do you have to do?

**Comment by mufincookies** [comment]
Ok Mexican all you have to do is just leave your name to drtshock and he will give you access on https://ci.drtshock.net/

**Comment by Kakifrucht** [comment]
Most annoying repeated ticket ever.
@drtshock should probably update it on spigotmc to avoid this spam.

**Comment by mufincookies** [comment]
@Kakifrucht  I do apologize for the spam, just really need to get it to work!

**Comment by TheMexicanChip** [comment]
I do not think I have access because I do not see factions.

**Comment by Kakifrucht** [comment]
Yeah well it's not just you, just wanted to spread awareness that he should really update on spigot.

**Comment by mufincookies** [comment]
http://ci.drtshock.net/job/FactionsUUID/ I tried to go here as I got a 404 error

**Comment by Kakifrucht** [comment]
You need to have access to it and be logged in.

**Comment by mufincookies** [comment]
@drtshock my username is shmittyjones on your website

**Comment by TheMexicanChip** [comment]
I have logged in My name is TheMexicanChip on it

**Comment by RainboomDash** [comment]
Could I get access? My name on it is "Verxi"

**Comment by drtshock** [comment]
Please follow the instructions on Spigot for getting access.
