### ISSUE TITLE
Can't kick player from faction

### ISSUE THREAD

**Issue by nxtboyIII** [drtshock/Factions#36]
Hi,
When I try to kick an offline player from my faction I get the following error:

"Something went wrong with getting the offline player's faction"

Please fix that.

Thanks

**Comment by drtshock** [comment]
Can you please put your board.json in a http://gist.github.com and then tell me the name of the player that you were trying to kick?

**Comment by drtshock** [comment]
Is this still an issue?

**Comment by RenegadeEagle** [comment]
Closing this now because there has no response from the reporter for over 3 months.
