### ISSUE TITLE
BETA Builds Pull Back Internal Server Error

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#360]
I've tried the stable builds on the SpigotMC page, and I couldn't get the scoreboards to work, it seemed as if the "false" and "true" had no effect. This lead me to try the new BETA build in the CI, to see if that'd help me any. It ended up not helping me, and yes, "f sb" was toggled on. The laziness kicked in, so I decided to keep the BETA build. This came to a few more issues. When I typed "f show" if would show the first 3 lines of the Faction.
The header, "Description", and "Joining".

I also got a huge error in console, located here: http://pastebin.com/4wF7R09G

**Comment by MoeXIV** [comment]
P.S: Using 1.7/1.8 Spigot Protocol Hack.

**Comment by MoeXIV** [comment]
Fixed the issue, but this still needs to be open. Milkywayz showed me that it was the raidable variable "%5$s" in the lang.yml. So, it now works, but Raidable is not something that will be shown in "f show" as this issue persists.

**Comment by drtshock** [comment]
You can still add raidable, you were just missing a format specifier that we accidentally omitted in a commit.

**Comment by MoeXIV** [comment]
What was I missing? Could you please tell me what to add to fix this, instead of just telling me to add something.

**Comment by MoeXIV** [comment]
Hello?
