### ISSUE TITLE
/f who issue

### ISSUE THREAD

**Issue by ChaosAndCoffee** [drtshock/Factions#362]
F who doesn't seem to be working, I'm using paperspigot 1.8.3.

Error from console; http://pastebin.com/mF3ZdRBe

**Comment by ChaosAndCoffee** [comment]
Oh and I'm using the latest build of Factions UUID.

**Comment by drtshock** [comment]
see https://github.com/drtshock/Factions/issues/301#issuecomment-95464510

**Comment by ChaosAndCoffee** [comment]
Yeah I figured it out, thanks anyway.
