### ISSUE TITLE
Walking into Territory

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#366]
I've currently spotted an issue. When using the "finfo" scoreboard, the message does not show up in chat when you walk into another's land. I personally think that both should come up, the scoreboard and the message.

Also, maybe a way to edit the message of entering land and leaving land because it looks pretty plain right now.
"Entering <name>, Leaving <name>."
or
"Leaving <name>"
"Entering <name>"

**Comment by nsporillo** [comment]
This was recently added in https://github.com/drtshock/Factions/pull/387

![added](http://puu.sh/hLs98/b3283544c7.png)

Also the message can now be configured in the lang.yml under:
![lang](http://puu.sh/hLs46/6f8cef3049.png)
