### ISSUE TITLE
/f show NPE

### ISSUE THREAD

**Issue by Evap88** [drtshock/Factions#373]
Newest version of FactionsUUID from spigot as well as Spigot build. 

Fresh config and everything. Simply start the server generate factions holder. Do /f create test and /f show

Running WorldGuard 6.0 and no chat plugin. 

Error: http://pastebin.com/uK2KgmyU

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/issues/301#issuecomment-95707786
