### ISSUE TITLE
"You can't use ___ in the territory of ___" is messed up

### ISSUE THREAD

**Issue by nxtboyIII** [drtshock/Factions#374]
http://i.imgur.com/SbQY9pc.png

**Comment by Kakifrucht** [comment]
I second this.

**Comment by drtshock** [comment]
Please explain the issue.

**Comment by KriticalPvP** [comment]
It says use instead of what the item is.

**Comment by Quizzes** [comment]
Here is a simple explantion:

When you try to use lets say a chest in the Faction ClanMLG's land, it says 'You can not use chest in chest's land' instead of 'You can not use chest in ClanMLG land'

:+1:  Can confirm, just tested this on b46

**Comment by drtshock** [comment]
What exactly are you doing to bring this up? Doing what in where with what in your hand? I need the /exact/ situation that prompts this.

**Comment by Kakifrucht** [comment]
Placing/using/doing something in enemy territory.
The message should say you can't use wooden_door in the territory of Factionname.
