### ISSUE TITLE
Leaving / Entering messages?

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/Factions#377]
Hello!

How do I change this: http://prntscr.com/71ukh9

To This!: http://prntscr.com/71unho And how can I add the text &e(&cDeathban&e) after the name of the fac? What would I change it to?

**Comment by Quizzes** [comment]
Check around before posting, this is in the lang.yml. One of the very last lines in the config (lang.yml)

**Comment by Lotteries** [comment]
Wrong repo, you might want to check the 'HCFProblems' one. I think this was put in the wrong one

**Comment by KriticalPvP** [comment]
Shit, sorry xD
