### ISSUE TITLE
Plugin question

### ISSUE THREAD

**Issue by BoomScoom** [drtshock/Factions#380]
Will this plugin work with the latest 1.8.3 spigot build?

**Comment by PaulBGD** [comment]
Yes

**Comment by BoomScoom** [comment]
And it has all the same features as v1.6.9.5?

**Comment by nandox5** [comment]
yes, still buggy though. not everything is working.. most is though.

**Comment by BoomScoom** [comment]
Are the basics working? Like creating a faction disbanding it etc?  Also is there a server I can go on to test the plugin out?

**Comment by MoeXIV** [comment]
Any 1.8.3 Factions Server still using a 1.6.9.5 Factions build.

**Comment by BoomScoom** [comment]
What?

**Comment by nandox5** [comment]
Best is to create your own testserver locally on ur pc and try it. Others have custom builds based on this build.

**Comment by BoomScoom** [comment]
But is it that buggy that you can't even create a faction or nah?

**Comment by MoeXIV** [comment]
There wouldn't be a 1.8.3 build if the plugin didn't work for 1.8.3

**Comment by BoomScoom** [comment]
Ik but does /f create and /f disband work?

**Comment by drtshock** [comment]
Still buggy, what? It works fine.

**Comment by BoomScoom** [comment]
Ok great I will purchase this plugin soon!

**Comment by nandox5** [comment]
Like i said most of it works. It just minor bugs. Which to me are important. So i consider it buggy. U can create remove and do all the basics and core stuff.

**Comment by nandox5** [comment]
Awesome. On behalf(not officially) of the plugin author. Your support is always appreciated. 
Enjoy

**Comment by drtshock** [comment]
@nandox5 lol what the hell are you talking about? You have literally 1 open ticket reporting bugs so not sure what you're on about.

**Comment by nandox5** [comment]
I reported two. And just because i see bugs dont mean i have to report them. I see people already reporting them so then whats the point? Buddy. I know what in talking about. ;).

**Comment by drtshock** [comment]
Then give us more info on how you can confirm that they are bugs. Most of the tickets are for new features, not bugs.
