### ISSUE TITLE
/f invite error

### ISSUE THREAD

**Issue by DariusPop** [drtshock/Factions#382]
Hello! When typing / f invite <name> command works but a message appears : An internal error occurred while attempting to perform this command (if you / f join command works )
![poza cu eroarea](https://cloud.githubusercontent.com/assets/12300585/7520876/a6139768-f4f2-11e4-89ab-6b51041c8649.png)

**Comment by drtshock** [comment]
And what's the error?

**Comment by Kakifrucht** [comment]
Probably the same error that was repeated numerous times.

**Comment by drtshock** [comment]
I need the actual error. 'probably' doesn't get me anywhere.

**Comment by DariusPop** [comment]
Ok. Can you please give me new version of the FactionsUuid ?
(You can give pluggin the latest version)

**Comment by xLuckse** [comment]
You can give him the plug once the new version?

**Comment by drtshock** [comment]
Closing due to stupid user. Paste the damn error if you want help. Updates are posted in the same places as always which you get access to upon purchasing the plugin.
