### ISSUE TITLE
faction chat tag integration breaks Jobs Reborn plugin chat tag

### ISSUE THREAD

**Issue by nandox5** [drtshock/Factions#383]
If i disable chatTagEnabled my Jobs Reborn Chat Tag works fine. but as soon as i enable it, it breaks jobs chat tag. I already an issue on jobs reborn but it seems like factions is the issue.. 

![capture](https://cloud.githubusercontent.com/assets/12242770/7523473/0038b4ae-f4ca-11e4-9ffd-8a86fb66eafc.JPG)

**Comment by drtshock** [comment]
Please provide more info such as what happens, what should happen, your conf.json, your startup log, and a link to the plugin.

**Comment by MoeXIV** [comment]
What happens is when the "[FACTION" variable is "turned off" via the command /f config, the {jobs} variable works.

But when "[FACTION]"  variable is ENABLED, the {jobs} variable breaks.

**Comment by nandox5** [comment]
link: http://dev.bukkit.org/bukkit-plugins/jobs-reborn/

If i disable the faction tag in the confg.json (or through f config command) the jobs variable (like moe said) works.. but if i enable the chat tag from factions the variable breaks..

no errors on startup log. but ill provide it.

http://pastebin.com/jYWU32nM

**Comment by nandox5** [comment]
Problem has been repaired by a dev. You can close this issue now. thanks

**Comment by drtshock** [comment]
@nandox5 would love if it was PRd upstream.

**Comment by nandox5** [comment]
sorry, meant to say it was fixed on the other side (meaning the problem was probably with the other plugin).

as of right now, (still have more deep testing to do) this plugin (factionsuuid) works as expected.

Sent from Windows Mail

From: Trent Hensler
Sent: ‎Sunday‎, ‎May‎ ‎10‎, ‎2015 ‎4‎:‎18‎ ‎PM
To: drtshock/Factions
Cc: nandox5

@nandox5 would love if it was PRd upstream.
