### ISSUE TITLE
Minimal F Show

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#384]
Once again another request from the HCFactions repo. I was told a few features were going to be added weeks ago but never did, and disappointed me.

ETA on the "custom" f show, that allows customizations such as HCFactions?
As well as the "minimal" f show feature that comes alone with it.

(Minimal f show meaning unused lines are hidden till' they are needed, for example: No members offline = "Members offline" line is removed until someone logs off)

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/compare/2b0638f54fcf...6a1e389b9ba6
