### ISSUE TITLE
F Show Colors Missing

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#385]
As the title states. The players are missing their color. I heard from you a while back this was "meant" to be added. If this is a required feature there must be a toggle for the server owners who strongly dislike this addition, including myself.

Picture: http://prntscr.com/734d4p
The usernames are not the relationship color you have with the faction, they always remain a white, blank color.

Please push a fix :)

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/compare/2b0638f54fcf...6a1e389b9ba6
