### ISSUE TITLE
{power} and {maxPower} variables broken

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#388]
As the title states, those variables in the sidebar show 10 higher then the real number.

My real power is 10/10 but the scoreboard states 20/20.
http://prntscr.com/75d942

  default:
    - ""
    - "&7Faction&6: &2{faction}"
    - "&6  Power: {power}/{maxPower}"

**Comment by nsporillo** [comment]
What version are you using?

**Comment by drtshock** [comment]
Looks like they got changed to Faction variables. Will get those changed back.
https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/config.yml#L319

**Comment by MoeXIV** [comment]
;)
Thank you guys. 
@nsporillo newest version hun

**Comment by drtshock** [comment]
"newest" isn't a version. We need an actual version string when we're asking for that.

**Comment by DawnMC** [comment]
I have this same problem with the /f show tooltips.

**Comment by KyrneDev** [comment]
Use {player-power}.
{Power} is your factions power. The same applies for {maxpower}

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
