### ISSUE TITLE
Factions Message Customizer

### ISSUE THREAD

**Issue by Kodauer** [drtshock/Factions#39]
Submitting this issue on request of drtshock. 

Update the current version of factions 1.6.x (UUID version) to support customizable chat messages. Any and all faction commands should be able to be customized, if possible. Basic bukkit color/format codes should be supported. Messages should be able to be edited via a config file. Potentially add variables for factions data such as power, faction members, etc. 

Reference thread for more possible features can be found on the spigot forums. (Pasting link won't work on mobile)

**Comment by Kodauer** [comment]
Andddd seems I can paste the thread in the comments.

http://www.spigotmc.org/threads/hiring-plugin-dev-factions-message-customizer.25471/#post-284959

**Comment by redsoxfan95** [comment]
I would love this as well. I would also love it if "/f reload" reloaded these messages (I do not believe they updated when I tested it out about 2 weeks ago)

**Comment by blha303** [comment]
Working on issue. Referenced commit is work-in-progress.
