### ISSUE TITLE
Factions Name Tag

### ISSUE THREAD

**Issue by Vukajlovic** [drtshock/Factions#390]
Hello ,
After last update I lost faction tags in names . I test it on blank server and I haven't it again , but I test latest update plugin defined as 14 , and I got name tags.

can you fix it thanks :)

**Comment by drtshock** [comment]
Paste your server log and your config.yml please.

**Comment by Vukajlovic** [comment]
I haven't any error , you are write something wrong in last update

http://pastebin.com/XSBzDKk6

**Comment by drtshock** [comment]
Please paste your server log. I'm not necessarily looking for errors.

**Comment by Vukajlovic** [comment]
I haven't errors bro , six.pack94 please add me on skype and I will show you what I think

**Comment by drtshock** [comment]
Closing this due to not wanting to paste log. I'm not going to help you if you can't give me what I need.
