### ISSUE TITLE
Plugin causing lag

### ISSUE THREAD

**Issue by Agazed** [drtshock/Factions#394]
As seen here http://prntscr.com/78962j

Saving and claiming causes a lot of lag

**Comment by drtshock** [comment]
Can you link to the timings and also give me your server specs.

**Comment by Agazed** [comment]
http://timings.aikar.co/?url=11309043

Using an Intel Xeon E3 1231 V3 and 3gb of ram.

Also, kind of off topic, but your McMMO plugin is also causing a bit of lag.

**Comment by drtshock** [comment]
Your server is still at almost 20tps but this isn't an issue with factions. It looks like your disk is a bit overloaded.

**Comment by Agazed** [comment]
How can you tell my disk is overloaded?

**Comment by drtshock** [comment]
Because a lot of normal operations that involved saving things to disk are taking longer than they should. Like save-all

**Comment by Kakifrucht** [comment]
Offtopic, but save-all got laggy on my machine too some spigot updates ago. Don't know which one it was, but it seems like they tweaked it. Never had any issues with it before.

**Comment by drtshock** [comment]
@Kakifrucht it's with structure saving which you can disable.

Anyway, this ticket is invalid. The plugin currently does not have any known issues with lag and this isn't proof of any.
