### ISSUE TITLE
{power} and {maxpower}

### ISSUE THREAD

**Issue by Agazed** [drtshock/Factions#395]
What happened to the {power} and {maxpower} values? They showed the players power and now they show deaths until raidable. 

Can you add new tags that show the players power? Like they used to be?

Also, can you make it so you need a separate tag for faction color relationships? I'm trying to make the players faction white on a scoreboard but it shows up green for them as they are in the faction.

**Comment by zRiaz** [comment]
Fixed in latest build. {player-power} & {player-maxpower}
@drtshock close

**Comment by drtshock** [comment]
Oh didn't know there was a ticket for this. Was bugging me on my server ;P
