### ISSUE TITLE
/f show or /f who server lag

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#397]
Wihle researching this issue I found this report for HCF Factions which is also an issue on this repository.
https://github.com/drtshock/HCFProblems/issues/104

The issue occurs when you perform the command: /f who <faction> on a faction that has no online members. The command will freeze up the entire server for up to 5 or almost 10 seconds.

  Pct Total Pct Tick       Total          Avg    PerTick         Count      Event
       1.93%     852.52%    1,220.81 s     426.26 ms     0.0           2.9k     Command: factions

This is an excerpt from my timings report showing that the command takes an averages of 500ms to complete a command.

**Comment by drtshock** [comment]
Which version of factionsuuid and spigot version? Full version strings please.

**Comment by ghost** [comment]
Factions version 1.6.9.5-U0.1.15-SNAPSHOT
Currently, I'm testing it on the new release currently. Will update momentarily.

**Comment by ghost** [comment]
Updated to Factions version 1.6.9.5-U0.1.17-b267
Bug fixed, thanks.

**Comment by drtshock** [comment]
Ah yes, there were a few builds with some issues with offline permissions that I took a shot at :\
