### ISSUE TITLE
Wont announce when you enter someone's land

### ISSUE THREAD

**Issue by Zeebra456** [drtshock/Factions#4]
![fd1aac9408abf2a7d8ed308610219b23](https://cloud.githubusercontent.com/assets/2409377/2752536/d61818ac-c911-11e3-9843-b519bbcafeac.png)
![dd6f545a34e7dbe4700e49ecec84b670](https://cloud.githubusercontent.com/assets/2409377/2752539/e5f289ba-c911-11e3-9ebe-6d5345394378.png)

In the factions plugin it wont announce when you enter someone's land/warzone/safezone

**Comment by Zeebra456** [comment]
Never mind... i fixed this

**Comment by gravitylow** [comment]
Was there a configuration issue? I didn't think I touched any of this code. How did you correct your issue?

**Comment by Zeebra456** [comment]
i had to remove https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/listeners/FactionsPlayerListener.java#L93
