### ISSUE TITLE
Add / to clickable commands

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#401]
I hope that this is no duplicate, couldn't find a ticket, which is weird.
I have the json setting allowNoSlashCommand set to false, so the clickable commands don't work on my server and will just print to chat. Could you just add the / to them? It makes more sense with it either way I guess.

**Comment by drtshock** [comment]
Which version are you on?

**Comment by Kakifrucht** [comment]
I'm on b267.

**Comment by drtshock** [comment]
No since we need to have a command prefix.

**Comment by Kakifrucht** [comment]
I don't quite understand?

**Comment by cnr** [comment]
Fixed in the latest build

**Comment by Kakifrucht** [comment]
Thanks!
