### ISSUE TITLE
War Implimentation

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#403]
As the title states, faction war implementation.
A way to join in a war (Every member participating has to do /f war join). Once the countdown is complete they are teleported to the setup arena / area where they fight to the death. Last faction alive is deemed the strongest on the server.

Commands:
## /f war join / time

/f war time
## \- The next Faction war is at Sunday 6:30PM EST

/f war join
- Puts you in the f war (Must be standing still for 10 seconds to join, and must be still for 10 seconds to be teleported to the event [upon moving for the teleportation, it retried every 5 seconds until it successfully teleports you, or you leave])
- To leave /f war you type /f war leave

**Comment by MoeXIV** [comment]
P.S Not sure why those 2 are bolded...

**Comment by Agazed** [comment]
I don't like this. Takes the original concept out of factions.

**Comment by guipenedo** [comment]
There are already add on plugins that do this. For example: https://www.spigotmc.org/resources/factionwars-new-updated.10961/

**Comment by drtshock** [comment]
This should be in a separate plugin.
