### ISSUE TITLE
Internal Server Error when anyon tries to claim, ally, or enemy.

### ISSUE THREAD

**Issue by Dendrobyte** [drtshock/Factions#404]
Here's the log, first of all:
http://pastebin.com/jZ9J5fTr (starts on line 79, up. After 'Again...')

It's just those commands that bring up the issue, and I'm new to reading console errors. Thanks!

[EDIT] Running version 1.8.6

[EDIT] Everything was working all right before I updated from 1.8.1

**Comment by PaulBGD** [comment]
It's an issue with your chat tag plugin it appears.

**Comment by Dendrobyte** [comment]
Which chat tag plugin might this be? Is it part of factions? The only plugin I have that remotely edits chat is PermissionsEx.
