### ISSUE TITLE
lang.yml

### ISSUE THREAD

**Issue by flodes80** [drtshock/Factions#405]
I have a problem, when I change the message in lang.yml the file save good but when I start the server and going on, when I use /f who for example the message are the default messages and not my owns message. (I translate all the message in French, I don't have any error when I start the server) how to fix this please ?

**Comment by flodes80** [comment]
And this is my lang.yml http://pastebin.com/RZnbABY6

**Comment by Kakifrucht** [comment]
If you are on the latest version, the /f who output is now controlled by config.yml.
Regenerate it, or add the new parts manually to it to be able to edit.

**Comment by flodes80** [comment]
Okay, but it's not the only one, other command like /f claim doesn't work and are not modified

**Comment by Kakifrucht** [comment]
You may have to restart the server, as /f reload does not completely seem to work with lang.yml.
