### ISSUE TITLE
Error from console and in game command.

### ISSUE THREAD

**Issue by bear946** [drtshock/Factions#406]
When doing the /f show command, it responds with an internal error has occured, I am also prompted with this server error in console:

30.05 20:27:49 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_1.8_eb39b47-0899683.jar:git-Spigot-eb39b47-0899683]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:193) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.P.handleCommand(P.java:181) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:253) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:290) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:133) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:115) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:129) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:153) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.zcore.MCommand.msg(MCommand.java:258) ~[?:?]
30.05 20:27:49 [Server] INFO at com.massivecraft.factions.zcore.util.TextUtil.parse(TextUtil.java:23) ~[?:?]

**Comment by drtshock** [comment]
Use pastebin and paste the full log (including the command that caused it).

**Comment by bear946** [comment]
The command causing it is /f who with any factions, and here the link
http://pastebin.com/jrUMn8pr

**Comment by drtshock** [comment]
you have lots of issues.

**Comment by bear946** [comment]
What I am worried about is the massivecraft factions error, the rest are irrelevent...

**Comment by drtshock** [comment]
Yes but literally everything on your server is throwing errors. Try to fix that and send me a new log.

**Comment by bear946** [comment]
Alright so after a couple attempts I have fixed most errors in my console, new log is here:

http://pastebin.com/wuz8EDv8

**Comment by Kakifrucht** [comment]
Your log is the wrong way around.
I'm pretty sure that you are not on the latest version. Update and delete your lang.yml.

**Comment by drtshock** [comment]
You're running an old version.
`[Server] INFO Caused by: java.util.MissingFormatArgumentException: Format specifier '5$s'`
was fixed awhile ago.
