### ISSUE TITLE
Cannot join system factions. (safezone, warzone and wilderness)

### ISSUE THREAD

**Issue by MrFuzz** [drtshock/Factions#408]
Hi. Even though I'm op, have bypass enabled and also have set my role as admin, I'm still not able to join safezone, warzone and wilderness. I get this message in chat when I try, 
![8e5cca233760100500744919c10cba91](https://cloud.githubusercontent.com/assets/12702791/7922162/3ea7e37c-08a2-11e5-96ce-0a84a24c0dd4.png)

**Comment by cnr** [comment]
Why are you trying to join those factions?

If (at a guess) you're trying to claim safezone/warzone land, you can use:
`/f claim <radius> <safezone/warzone>`

**Comment by MrFuzz** [comment]
Thank you. I was using newer versions of factiosns before so that's why I though you had to join those factions.
