### ISSUE TITLE
Factions: How to remove the; Entering Wilderness From 'TestFac', Leaving Wilderness From 'TestFac'!

### ISSUE THREAD

**Issue by DepthUnderscore** [drtshock/Factions#409]
How do I remove the message when you enter into wilderness from another faction.

e.g. 
![screen shot 2015-06-01 at 21 10 48](https://cloud.githubusercontent.com/assets/12702915/7922222/b88b3392-08a2-11e5-9bab-a8631e3e78f2.png)

 Please help. :)

**Comment by Agazed** [comment]
You can edit the messages in the lang.yml file.
