### ISSUE TITLE
Adding in HCFactions Features Onto UUID Upon Release

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#410]
Basically, there are so many cool features HCFactions get implemented that I think this plugin could use, such as "minimal f show" and {color} variable to show the relationship color on certain lines you decide.

**Comment by drtshock** [comment]
We literally just merged like 50 commits lol. We put new things on HCFactions then wait until some bugs are ironed out and then put them in this project. That way we don't have to fix the same bugs in 2 projects.
