### ISSUE TITLE
FactionsUUID Error on startup

### ISSUE THREAD

**Issue by pvpdynastymc** [drtshock/Factions#413]
Hi, I am having an issue with the startup of the plugin. Here is the error:

[19:46:27] [Server thread/INFO]: [Factions] Enabling Factions v1.8.2-U0.7
[19:46:27] [Server thread/ERROR]: [Factions v1.8.2-U0.7] GSON lib not found. Your CraftBukkit build is too old (< 1.3.2) or otherwise not compatible.
[19:46:27] [Server thread/INFO]: [Factions v1.8.2-U0.7] Now I suicide!
[19:46:27] [Server thread/INFO]: [Factions] Disabling Factions v1.8.2-U0.7
[19:46:27] [Server thread/INFO]: [Factions v1.8.2-U0.7] Disabled 

Server Version: Spigot 1.8.3
Plugin: FactionsUUID by Drtshock

Any help would be greatly appreciated!

**Comment by MoeXIV** [comment]
Your server version is not 1.8...
I'm pretty sure it's saying the plugin only works on 1.3.2 or greater.

**Comment by pvpdynastymc** [comment]
Well, I am using a paperspigot 1.8.3 server jar. Any idea why it reads it as 1.3.2? 

```
 On Tuesday, June 2, 2015 8:49 AM, MoeXIV <notifications@github.com> wrote:
```

 Your server version is not 1.8...
I'm pretty sure it's saying the plugin only works on 1.3.2 or greater.—

**Comment by Lotteries** [comment]
I've noticed paperspigot does not like factions all the time.
Thats just my two cents as a developer  myself.

EDIT: Decompiled a bukkit jar file, 1.8 jars are using 1.3 code Thats why id you try to connect to a 1.8 server using 1.7 it says x1.3.2 on the server list. Haha. Here are my sources

1): Most of the messages (Vanilla messages) in 1.8 Bukkit files are reverted to 1.3 Messages
2): There are some API Features missing that are in 1.7 Code.

**Comment by pvpdynastymc** [comment]
So i'm assuming there is no fix for this? Or are you able to do something that will make it work? 

```
 On Tuesday, June 2, 2015 11:14 AM, Maxwell C. <notifications@github.com> wrote:
```

 I've noticed paperspigot does not like factions all the time.
Thats just my two cents as a developer myself.—

**Comment by drtshock** [comment]
Can you give me your version string for spigot and show me where you downloaded it?

**Comment by pvpdynastymc** [comment]
Spigot 1.8.3 Yive's Mirror | Spigot | Craftbukkit | Bukkit | Cauldron | MCPC+ | PaperSpigot | Lost Plugins
|   |
|   |   |   |   |   |
| Yive's Mirror | Spigot | Craftbukkit | Bukkit | Cauldron | MCPC+ | PaperSpigot | Lost PluginsMirror for Spigot, Craftbukkit, Bukkit, Cauldron, PaperSpigot, MCPC+ and lost plugins. |
|  |
| View on tcpr.ca | Preview by Yahoo |
|  |
|   |

  


     On Tuesday, June 2, 2015 12:07 PM, Trent Hensler <notifications@github.com> wrote:
   

 Can you give me your version string and show me where you downloaded it?—

**Comment by drtshock** [comment]
no idea what you just sent

**Comment by pvpdynastymc** [comment]
Server version -- paperspigot 1.8.3http://tcpr.ca/paperspigot --> Where I got it.

```
 On Tuesday, June 2, 2015 2:06 PM, Trent Hensler <notifications@github.com> wrote:
```

 no idea what you just sent—

**Comment by drtshock** [comment]
Can you give me the full version string please.

**Comment by pvpdynastymc** [comment]
Sorry, what do you mean by "Full version string?"

```
 On Tuesday, June 2, 2015 3:00 PM, Trent Hensler <notifications@github.com> wrote:
```

 Can you give me the full version string please.—

**Comment by drtshock** [comment]
type /version in game and paste that.

**Comment by pvpdynastymc** [comment]
Ah Yes, sorry about that. Here is it: http://gyazo.com/56431cb8ce9d6ae4f03f458d7df4c618 or 
this server is running CraftBukkit version git-PaperSpigot-6c710c1-ba32592 (MC: 1.8.3) (implementing API version 1.8.3-R0.1-SNAPSHOT)

**Comment by pvpdynastymc** [comment]
If possible, could we have a fix by Thursday? Our factions server opens Friday and we want to get this working ASAP. :) Thanks for everything.

**Comment by drtshock** [comment]
One last thing: where did you purchase the plugin and what's your username on there?

**Comment by pvpdynastymc** [comment]
SpigotMC http://www.spigotmc.org/resources/factionsuuid.1035/

**Comment by drtshock** [comment]
oh duh. You're not even using my plugin on that. Mine would show something like
`
[00:21:57] [Server thread/INFO]: [Factions] Loading Factions v1.6.9.5-U0.1.17-b255
`
when loading
