### ISSUE TITLE
Help message when executing console commands

### ISSUE THREAD

**Issue by brcdev** [drtshock/Factions#414]
Hello,
Could you add an option to disable the help message being shown after executing any command in the server console (below the executed command's output)?

**Comment by drtshock** [comment]
hm?

**Comment by brcdev** [comment]
I get the help message every time I issue any /f command in the console: http://i.imgur.com/5TKyzJ1.png

**Comment by drtshock** [comment]
Can confirm this. Looked through it a few times and couldn't figure out where D:

**Comment by cnr** [comment]
Fixed in the latest build on the CI
