### ISSUE TITLE
Chat Tag

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#417]
Hey, Im having a problem which i cant seem to solve myself. Currently everyone who is in a faction has the faction name in front of their player name. I dont want this. Ive set it up in my Chat formatting settings, that only specific ranks should have the faction name in front of their player name, yet still all players in a faction have the prefix...
factions conf.json : http://pastebin.com/UaY7keqy
essentials config.yml : http://pastebin.com/VxaTWbAG

Thanks, Will.
Also, can you give me access to your dev builds: hideroch.

**Comment by Dendrobyte** [comment]
Same issue here... I know this doesn't help but I just wanted to input saying I've scoured all the files multiple times and haven't found anything. People who didn't have tags before are glitched and I get internal errors.

**Comment by drtshock** [comment]
What are the errors @Mobkinz78?

**Comment by Dendrobyte** [comment]
The error that shows up in chat is just "An internal server error has occurred in chat.". @drtshock 

Unable to get console logs because everyone has their own prefix now and issue has fixed over time. Apologies, I am aware that is not very helpful/

**Comment by drtshock** [comment]
Ah ok. Reopen and comment with new info if this arises again.
