### ISSUE TITLE
FactionsUUID Features

### ISSUE THREAD

**Issue by ItsPurix** [drtshock/Factions#418]
Hey there drtshock, I bought the plugin because everyone was saying it was better than normal Factions. Can you list me all the features FactionsUUID has, I couldn't really find anything that it came with. Also when I looked in the config I couldn't really understand how to set up the scoreboard. Thanks again!

**Comment by Kakifrucht** [comment]
It's a maintained Factions 1.6.9.5 (the version when Factions was still a good plugin) updated to UUIDs and updated to every future updates, and no MCore dependency. It comes with alot of extra features, Scoreboards, features for hardcore faction servers (many more possibilites to configure), you can translate most strings and much more, this is just from the top of my head.

**Comment by ItsPurix** [comment]
Ah sweet, Glad I purchased it. Do you know how to configure the scoreboard. I looked at the config it just seems confusing to me.

**Comment by Kakifrucht** [comment]
I don't use it I'm sorry

**Comment by ItsPurix** [comment]
No it's fine. I finally got it to work!
