### ISSUE TITLE
/f show

### ISSUE THREAD

**Issue by Therobodavo** [drtshock/Factions#420]
I really may just not understand this. 

So in one of the new version of FactionsUUID, I guess the look of /f show changed. I looked atthe update logs, and saw it was made so you could cutomize /f show. In the lang file.. I reloaded it.. but every time I try removing something (or using n/a) it doeesn't change/go away. I don't know, do I need to reset everything? I really don't want to do that, so I guess I just don't know what I should do.

Current /f show: http://gyazo.com/584b47876e44174892032d59a1ca1441

Current Lang config: http://gyazo.com/4aff2fea4e7975cd98765b38de643aa6

If I'm just not doing it right, or there's a guide on what to do, then please just let me know.

The point is I want it to look like how it used to be....

(The Ally colors are custom to this server ik, i would just make them red)
So something like this: http://gyazo.com/b4bb2b220e95eba22b05c91d6c521cd3

Lol so if there's an explanation on this, please just try and help me out :D

**Comment by Kakifrucht** [comment]
F show is configured through config.yml, not lang.yml.
Also reloading does not reload every part of the language file
