### ISSUE TITLE
Friendly fire?

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#421]
My players are able to damage members of their own faction inside and outside of warzones.

I already have

```
  "warZoneFriendlyFire": false,
```

**Comment by drtshock** [comment]
Likely another plugin you have that is conflicting with it. Try reproducing with no plugins except factions, vault, an economy plugin, and a permissions plugin (required for factions to run).

**Comment by ghost** [comment]
You are right, it turns out it was PvPManager causing it
