### ISSUE TITLE
Lang file question with descriptions

### ISSUE THREAD

**Issue by Therobodavo** [drtshock/Factions#422]
At the bottom of the lang file, you can edit a bunch of things. One of those are this.

faction-leave: <a>Leaving %1$s, <a>Entering %2$s

So, what I want to do is make it like <a>%2$s - (description)

but.. I don't know how to get the description of the faction. I don't think there's like a wiki for this, but I just didn't see what to use.

**Comment by zRiaz** [comment]
I was thinking about this too. But couldn't find a placeholder for description. So I doubt there is one..
@drtshock ?

**Comment by drtshock** [comment]
There isn't one for this.

**Comment by zRiaz** [comment]
Could you add one? I would like this too.

**Comment by Therobodavo** [comment]
Ya lol, cause the original factions had the description.. and it's really what I would like to use. I mean, it's not the end of the world, but it would be nice.

**Comment by zRiaz** [comment]
Yea, Im just using it how it used to be atm just without the description. Would prefer to get a variable to add the description back though.

**Comment by drtshock** [comment]
There isn't a way to do this and it won't be added.
