### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by brianzhouzc** [drtshock/Factions#423]
Hi, I'm trying to translate FactionUUID into Chinese, but it seems to be that FactionUUID doesn't support UTF-8 characters.

I think this can be easy fix by changing the encoding type to UTF-8.

Please fix! Really need this!

**Comment by drtshock** [comment]
Change the encoding of your file with your editor.

**Comment by 1461748123** [comment]
yes I did, UTF8 isn't working at all

**Comment by brianzhouzc** [comment]
ANSI works, but it seems to be that FactionUUID convert it in to unicode.
Is that possible to not converting them in to unicode, and keep the origin characters?
