### ISSUE TITLE
Imports from massivecore --> FactionsUUID

### ISSUE THREAD

**Issue by Brodys** [drtshock/Factions#424]
What would these become?
import com.massivecraft.factions.entity.Faction;
import com.massivecraft.factions.event.EventFactionsChunksChange;
import com.massivecraft.massivecore.ps.PS;
import com.massivecraft.factions.entity.Board;
import com.massivecraft.factions.entity.BoardColl;

**Comment by drtshock** [comment]
Should try reading through the source. The interfaces are pretty intuitive.
