### ISSUE TITLE
Warzone and factions name when entered by a player..

### ISSUE THREAD

**Issue by bear946** [drtshock/Factions#426]
Originally, before I started using factions UUID's when a player walked into a faction territory it would display a message like this in chat:
http://imgur.com/LVo1mFY

Now with UUIDS version it is:
http://imgur.com/r9cuYWB

Just a matter of one "~" and a space, but Is there a simple way to fix it?

**Comment by drtshock** [comment]
Check out the lang.yml

**Comment by zRiaz** [comment]
Well its not possible to fix (entirely) as there is no way to add the description to it..
(pls fix drtshock)
