### ISSUE TITLE
Trying to rename warzone.

### ISSUE THREAD

**Issue by MortalPvP** [drtshock/Factions#427]
I've been trying rename warzone and its not working I really need help.

**Comment by drtshock** [comment]
Did you rename it in your lang.yml? How is it not working?

**Comment by MortalPvP** [comment]
My apologies I did I mean how do I change the color of the claims I've been trying to do it through the conf.json file but it wont work when I changed the color for warzone it still stays Dark red.

**Comment by drtshock** [comment]
Check out the lang file :)
