### ISSUE TITLE
No tag

### ISSUE THREAD

**Issue by PattyAk** [drtshock/Factions#430]
I can't get the factions tag to show no matter what I type in the essentialschat prefix section. Can I be pointed in the right direction to get this working?

Here is what I have set 

format: ' {faction_tag} {DISPLAYNAME} {MESSAGE}'

**Comment by Kakifrucht** [comment]
the tag is [FACTION]

**Comment by PattyAk** [comment]
When I use that it just displays "[FACTION]" in the chat.

**Comment by zRiaz** [comment]
You done goofed then

**Comment by PattyAk** [comment]
Yeah. Uh. Perhaps you could tell me how Ive done goofed.
 format: '[FACTION] {DISPLAYNAME} {MESSAGE}'
