### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by bear946** [drtshock/Factions#432]

**Comment by bear946** [comment]
I purchased the resource at https://mcexchange.org/threads/factionsuuid.10/, I am now trying to update and am finding that it has not yet been given the new version for download, is it a separate place to download?

**Comment by zRiaz** [comment]
Create a account on ci.drtshock.net and ask drtshock for access to development builds.

**Comment by bear946** [comment]
How do I ask him, lol?

**Comment by zRiaz** [comment]
Simple. Just tag him @drtshock

**Comment by drtshock** [comment]
I see all messages on all issues and get notifications for them already. I'm waiting for him to register.

**Comment by bear946** [comment]
I have made an account on ci.drtshock.net, but unfortunatly I am still unable to find where I can message @drtshock, I have sent a message on mcexchange.org. Is the only way to receive updates on spigot (confused). My jenkins user ID is: SmurfyAYE.

Thank you.

**Comment by drtshock** [comment]
Added to jenkins.
