### ISSUE TITLE
Faction chat showing in public

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#435]
When someone does /f c f and talks in faction chat it duplicates the message in public chat. But when I do it, it doesnt duplicate it. I havent seen any errors in console. so I have no idea what it could be.

**Comment by Kakifrucht** [comment]
Are you sure that it duplicates and you don't just have chatspy enabled with /f chatspy?
Otherwise your Chat plugin is causing the issue.

**Comment by ghost** [comment]
My players are the ones saying it duplicates. And I dont have chatspy on either.

**Comment by drtshock** [comment]
Try removing any chat plugins you have.

**Comment by ghost** [comment]
I have no chat plugins.

**Comment by ghost** [comment]
Oh it was a plugin. AdBlockPlus the faction chat. Thanks.
