### ISSUE TITLE
Headtags help.

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#436]
Hello, I want enable headtags but I didnt get it working. 
I found this in the config:

 default-enabled: false # Default to false to keep original functionality.
  default-title: "i love drt" # Can use any of the values from above but this won't update once it's set (so don't set {balance}).
  default-update-interval: 2 # in seconds.

  # This will show faction prefixes colored based on relation on nametags and in the tab.
  #   The scoreboard needs to be enabled for this to work.

But I dont know how to activate scoreboard so I cant test it. ( I tried to activate them... but nothing)
Other question is if this plugins works fine for someone (It works for me but the colors don't show up) : http://dev.bukkit.org/bukkit-plugins/battletags/ because it doesnt to me.

Any help would be awesome thanks.

**Comment by drtshock** [comment]
You just need to enable scoreboards in the config with default-enabled and default-prefixes. Then make sure you don't have any conflicting scoreboard plugins (like battletags).

**Comment by alexsatellite** [comment]
Ok thanks I got it working :). but now I have other problem. This head-tag doesnt show the full name of the faction if it is longer than 9 characters (can I fix it?) http://gyazo.com/8c819d801b68adb9b7fda4319b8db455, and is possible to change the name color and dont put the faction name? I mean like this: http://gyazo.com/be179ee5b60d02b469a69f1e80005c23

I also have other small problem, here : http://gyazo.com/c6c1b63aae7668f3be253e8cc3a50ce8 if I turn on this for prevent pistons moving slime blocks, them just stop working like a sticky pistons and start working like normal pistons and in the other version it was working fine.

**Comment by drtshock** [comment]
Shorten the length of the faction name.

Use separate tickets for separate issues.
