### ISSUE TITLE
Conf.json resets to default settings after server reloads/restarts after Edited and saved

### ISSUE THREAD

**Issue by XxSilentBeastGxX** [drtshock/Factions#437]
Here's an example: in the conf.json It says "warzonepowerloss" true. I want to Set this to false so I chage it to "false" then I click save and reload my server. Test if I lose power in warzone.. I still lose the power in war zone. So I go back to conf.json and see that it's set back to true AFTER I had just saved me setting it to false. I do the same thing again but this time I restart the server. Still doesn't work. It's not just that. ANYTHING I try to edit in the factions uuid config, as soon as I reload the server, all the customizations that I have made to the conf automaticly sets it self back to default... I want to be able to open chest in others claimed territorys if it's uncovered but no I can't do that cuz when I try and edit the config it just resets it self back to default settings! Please help!

**Comment by drtshock** [comment]
I answered you in pm. Stop your server, edit the file, reupload / save it, then start your server. Or do the same while the server is running and just /f reload. Don't /reload.
