### ISSUE TITLE
Cant claim safezone or warzone

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#440]
I cant seem to be able to /f claim warzone 1 or /f claim safezone 1. I am in bypass mode. The message is your faction already owns this land, I am in wilderness or if in any other faction it just claims for it.

**Comment by drtshock** [comment]
f claim <radius> <safezone/warzone>

**Comment by Terrobility** [comment]
Dont mean to necropost, but the command when doing /f help is outdated. It's /f claim {radius} SafeZone
