### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Varations** [drtshock/Factions#444]
I really really want this plugin because honestly I just hate the new version of factions which is so weird compared to the old good factions plugin which is this one but I thought you said it was free if you contact through Skype? I hope I can get it free or something because I am doing a really good job on setting up my server but all I need is factions and I am sort of stuck because of it and I really would like this plugin. Also maybe once I start getting donations I can pay later? Well either way thanks for reading and I hope to get a reply soon :) my Skype is jinxonmc

**Comment by Kakifrucht** [comment]
If you make a for profit server you really should pay now. Otherwise just compile it yourself.

**Comment by drtshock** [comment]
Since you accept payments / 'donations' on your server, no.
