### ISSUE TITLE
Too many allies, enemies or members can cause the client to crash.

### ISSUE THREAD

**Issue by Curtis3321** [drtshock/Factions#445]
Hey,

Using the latest version that is on Spigot of this FactionsUUID plugin, whenever a Faction has a certain amount of enemies (also works with members & allies) it will crash your client when you do /f show. 

The server is running 1.7 still but also accepts 1.8 clients. Happens on both 1.7 clients AND 1.8 clients. 

I don't really know what to send you other than that due to there being 0 stack traces or logs.

Hope this is enough information.

Thanks.

**Comment by Kakifrucht** [comment]
How many allies/enemies are we talking about?
You could set a max amount of allies/enemies in the config.yml.

**Comment by drtshock** [comment]
Can you paste the factions.json info of the faction that this happens to? Can you also tell me the specific /f version and /version you're running please.

**Comment by Curtis3321** [comment]
One of my Admins went and disbanded the Faction today.. (facepalm)

Close the issue until I can provide you with the details you need.

**Comment by drtshock** [comment]
This was fixed awhile ago.
