### ISSUE TITLE
Powerboost (Feature Request)

### ISSUE THREAD

**Issue by FlippantCactus** [drtshock/Factions#446]
Max power is set to 10 in the config, when I set to 20 it affects everyone.
I'd like it so when you do /f powerboost <username> 10, the power is still 10, how would I increase the power, is it +10 I should be doing?
I've seen many servers use power boosts and was wondering how it is set and added properly.

**Comment by Kakifrucht** [comment]
I don't quite understand what you are saying.
Powerboost can be applied to both the factions or a players power. This is seperate from setting the max power integer in the conf.json.
You use it with /f powerboost player/faction playername/factionname amount

**Comment by FlippantCactus** [comment]
The max power of the player doesn't increase when I do the above command.

**Comment by drtshock** [comment]
Try:
`/f power <name>`
`/f powerboost player <name> 5`
`/f power <name>`
and tell me what it shows.

**Comment by drtshock** [comment]
Didn't mean to close but it does work. I have this as a perk for my highest rank so players get 25 power instead of 20.

**Comment by FlippantCactus** [comment]
How do you set it? I'm using f powerboost player {name} 10 with buycraft and it's not working.
