### ISSUE TITLE
No drops

### ISSUE THREAD

**Issue by zDrakon** [drtshock/Factions#447]
I paid for your plugin but there are no visible errors in console or log files ANYWHERE. We unloaded your plugin and suddenly all item drops could happen, when we reloaded it back so it was enabled, NOTHING DROPPED! Please FIX!!!

**Comment by drtshock** [comment]
what

**Comment by zDrakon** [comment]
it seemed that the bug was moving around. sorry. i was just frustrated and we kept finding different plugins that caused this error. It was actualyl bottomlesschests with its default feature of picking up blocks intead of dropping them automatically. Sorry for the issue i closed it.
