### ISSUE TITLE
Scoreboard power bug

### ISSUE THREAD

**Issue by mxson** [drtshock/Factions#448]
http://tydrex.com/caps/gXeTEN2gU.jpg
I'm not exactly sure how to explain this, I'm going to blame it on the fact that I have a powerboost though. Before, it seemed like after every restart my max power on the scoreboard would go up by the amount that I have boosted, but now it's stopped. The number is just really off now, I'm not sure what's up, nor do I know how to explain this. Sorry for the vague report, but it is still broken nonetheless.

**Comment by mxson** [comment]
Also, powerboosts seem to mysteriously disappear. Again, I don't know what's causing this but one moment the powerboost is there, the next it isn't.
http://tydrex.com/caps/7mc14gK8Q.jpg
As seen in the screenshot, the scoreboard is still screwy even after not having a powerboost.

**Comment by Kakifrucht** [comment]
The second issue I can't reproduce, so I'm assuming there is something generally wrong with your setup.

**Comment by mxson** [comment]
I'll look into it, what about the first issue?

**Comment by Kakifrucht** [comment]
Not using scoreboards, I personally don't have any issues with Factions powerboost functionality, and I am using it myself.

**Comment by mxson** [comment]
Alright, and just a further note, the power seems to fix itself after creating/joining a faction.

**Comment by mxson** [comment]
http://tydrex.com/caps/Asg8PhPE8.jpg
An issue in tooltips too, it seems like the variables are wrong.
Possibly a duplicate of this issue: https://github.com/drtshock/Factions/issues/388
Doesn't seem like that one was fixed though.

**Comment by mxson** [comment]
I've finally realized what's happening. The scoreboard power is messed up because that's the power of wilderness, whereas I thought it was supposed to be personal power. My bad. :(

**Comment by drtshock** [comment]
Please stop discussing multiple issues on the same thread. Keep one issue per ticket please. And yes, if factionless, it shows wilderness power because that's technically their faction.
