### ISSUE TITLE
Prefixes and warzone/safezone claiming

### ISSUE THREAD

**Issue by cuddylier** [drtshock/Factions#45]
Hi

In all builds #44 and below, chat works fine but claiming warzone/safezone does not, it just says your faction already owns the land (wilderness).

Somewhere in builds #45+ the warzone/safezone claim issue is fixed and prefixes stop working with essentials chat 2.13.1.

**Comment by drtshock** [comment]
Convoluted bug report. Report each bug in its own ticket.

**Comment by cuddylier** [comment]
Why are you unable to deal with two related issues in the one report? It doesn't make sense splitting it.
