### ISSUE TITLE
Players lose power-boost when kicked / removed from Faction.

### ISSUE THREAD

**Issue by Curtis3321** [drtshock/Factions#450]
I've had numerous reports of players losing their extra power-boosts when they are kicked from the Factions due to inactivity, kicked through /f kick or just leave through /f leave.

They will lose their extra power-boosts which they can gain access to, we thought this would just be a one time bug but it has happened on many occasions now.

When they are kicked, nothing happens. It just kicks them normally. Nothing extra in console.

Latest Faction version (on Spigot)

PaperSpigot 1.7

**Comment by xXBarchticXx** [comment]
Bump if this is still an issue.

**Comment by drtshock** [comment]
Can you confirm it barchtic?

**Comment by xXBarchticXx** [comment]
Will do.

**Comment by xXBarchticXx** [comment]
Was mistaken using an outdated version, updated now. (I was testing on my local host which had an outdated version x), soz man.
