### ISSUE TITLE
Owner Claim Radius | Other Commands

### ISSUE THREAD

**Issue by dannylif** [drtshock/Factions#451]
I made a previous thread on the spigotmc forums about how I could get more commands for my faction server since I saw a server with the Factions UUID 1.6.9 version and they had commands such as "/f ownerclaim <radius>" or "/f unclaim <radius>" or "/f claim line".

You said you could help with it if I would purchase your resource which I did, so here i am :)

Thanks for reading,

Danny_L

**Comment by drtshock** [comment]
what commands

**Comment by dannylif** [comment]
'' /f ownerclaim <radius> " 

" /f unclaim < raduis > "

**Comment by dannylif** [comment]
"/f ownerclaim radius" and "/f unclaim radius"

**Comment by dannylif** [comment]
"/f ownerclaim (Radius)" 
"/f unclaim (Radius)"  and I think
"/f claim line <length>"

**Comment by drtshock** [comment]
Claimline and claim radius are already in there. Unclaiming radius is not.

**Comment by dannylif** [comment]
I really wanted the like Owner Claim Radius so you dont have to /f owner every single piece of land
