### ISSUE TITLE
F Show | Power

### ISSUE THREAD

**Issue by dannylif** [drtshock/Factions#452]
I have a problem if i hover over the "/f show" it would say the person last seen, rank, money and power.
But with the power it shows the total power of the faction and I wanted to know if it could just show the persons power 
Example: Last seen: 1 hour ago
                Rank: Member
                Power: 7/10 (instead of 160)

**Comment by mxson** [comment]
Seems like this is the same issue as seen with https://github.com/drtshock/Factions/issues/388 with the variables being swapped. Would be fantastic if this was fixed. <3

**Comment by drtshock** [comment]
Duplicate of https://github.com/drtshock/Factions/issues/388
