### ISSUE TITLE
Faction & Worldguard 

### ISSUE THREAD

**Issue by EmilKnudsen** [drtshock/Factions#453]
So people are allowed to attack allies and factions members in a worldguard claim, they are also allowed to claim in the world guard region? How do I fix this.
Here is the conf.json config http://pastebin.com/0QP8RHRs

**Comment by EmilKnudsen** [comment]
Hmm, I did, and now they are still able to hit, but it says in chat "You can't hurt (name)"

**Comment by EmilKnudsen** [comment]
Stop closing it man, I don't even have the chance to give an answer...

**Comment by Kakifrucht** [comment]
So you are saying that despite the fact that you shouldn't be able to attack allies and faction members everywhere in the world and it works outside of WorldGuard regions, you can attack them INSIDE WorldGuard regions?

**Comment by drtshock** [comment]
You have 2 separate issues on this ticket. Keep one issue per ticket.

**Comment by EmilKnudsen** [comment]
So the issue is that factions can attack allys and their own members, in the claims by worldgúard.
But outside the worldguard claims they can't. Also It's the same issue, so drtshock, try to give a wrothful answer, instead of commenting that it's x2 issues.
  "worldGuardChecking": true,
  "worldGuardBuildPriority": true,

**Comment by Kakifrucht** [comment]
It's not the same.
I can't reproduce the issue. This appears to be an issue with some of your other plugins interfering with the playerDamageEvent

**Comment by EmilKnudsen** [comment]
How should it be ?, I did try it with only worldguard and factions, and it still happens

**Comment by EmilKnudsen** [comment]
I do have the lastest update of both.

**Comment by Kakifrucht** [comment]
Which spigot version?
I personally can't reproduce this.

**Comment by EmilKnudsen** [comment]
Last version of spigot.

**Comment by Kakifrucht** [comment]
So you tested it only with worldguard and factions on your server? Because that would be quite odd.

**Comment by EmilKnudsen** [comment]
How so ?

**Comment by EmilKnudsen** [comment]
Ofc with essentials and worldedit

**Comment by Kakifrucht** [comment]
Remove essentials then.

**Comment by EmilKnudsen** [comment]
*Will do. give me just a second

**Comment by EmilKnudsen** [comment]
Nope still not working

**Comment by Kakifrucht** [comment]
Sorry, then I have no idea. Reset your configs, because Factions really shouldn't be the issue here.

**Comment by EmilKnudsen** [comment]
Delete them and run it again ?

**Comment by Kakifrucht** [comment]
Also the servers configs just for testing purposes.

**Comment by EmilKnudsen** [comment]
Did, but it's not working

**Comment by EmilKnudsen** [comment]
Uhm wanna tell me what's wrong, or is my server going to have this bug forever......

**Comment by Kakifrucht** [comment]
I'm personally out of ideas.

**Comment by EmilKnudsen** [comment]
Get drt then?

**Comment by Kakifrucht** [comment]
I have no affiliation with him, so I don't see how I could "get" him ^.^

**Comment by EmilKnudsen** [comment]
Dude I need to get this issue solved, so please tell him to "move his ass", and stop closing tickets without giving an answer

**Comment by EmilKnudsen** [comment]
dude get himm

**Comment by Kakifrucht** [comment]
With that attitude you are not going to get any sorts of support on here. I tried helping you and the only thing you do is having a negative attitude.

**Comment by EmilKnudsen** [comment]
He could give me a worthful answer ?
