### ISSUE TITLE
Adding zeroes to founded date

### ISSUE THREAD

**Issue by Agazed** [drtshock/Factions#454]
Factions that were made on a time ending in 0 doesnt include the 0 and it looks strange

http://prntscr.com/7nrck7

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/zcore/util/TL.java#L701

**Comment by Agazed** [comment]
Adding a zero after the m "MM/d/yy h:m0a" causes times to look like this

http://prntscr.com/7o0pd2

Adding an extra m will cause times to be incorrect "MM/d/yy h:mma"

http://prntscr.com/7o0pxg (This is the same time as http://prntscr.com/7nrck7)

I dont believe there is a way to configure that in the config. I think you have to edit the code so it forces 2 digits for minutes.
