### ISSUE TITLE
Conf Option Not Working

### ISSUE THREAD

**Issue by fireice007** [drtshock/Factions#457]
Hello, I seems that the conf option "chatTagInsertAfterString" and "chatTagInsertBeforeString" aren't working.

**Comment by drtshock** [comment]
how so?

**Comment by fireice007** [comment]
Well when I try using them with either adding brackets or letters, they don't seem to do any thing. Which I'm guessing it does where it adds before and after the [FACTION] string.

**Comment by drtshock** [comment]
Which chat plugin are you using?

**Comment by fireice007** [comment]
I've tested with essentialsChat, InteractiveChat, and no chat plugin.

**Comment by fireice007** [comment]
Bump

**Comment by Kakifrucht** [comment]
"Bumping" after 16 hours...
First of all this is not a forum, second of all, if somebody actually seems to have forgotten your ticket, wait a couple of days and write something nice to remind them of this, don't write "Bump" after 16 hours.

**Comment by drtshock** [comment]
Should seek help from your chat plugin.
