### ISSUE TITLE
Faction Banks

### ISSUE THREAD

**Issue by dawsondiaz** [drtshock/Factions#458]
After disabling faction banks in conf.json, but enabling econ. When a player creates a faction (charge $100) and then disbands, they get $1000 from their faction bank. This only happens the first time a player creates and disbands a faction. This can easily be abused with players who have alt accounts, and there is no option in the config for starting bank balance.

Config options mentioned below:

  "bankEnabled": false,
  "bankMembersCanWithdraw": false,
  "bankFactionPaysCosts": false,
  "bankFactionPaysLandCosts": false,

 "econEnabled": false, 
  "econUniverseAccount": "",
  "econCostClaimWilderness": 30.0,
  "econCostClaimFromFactionBonus": 30.0,
  "econClaimAdditionalMultiplier": 0.0,
  "econClaimRefundMultiplier": 0.0,
  "econClaimUnconnectedFee": 0.0,
  "econCostCreate": 100.0,
  "econCostOwner": 15.0,
  "econCostSethome": 30.0,

**Comment by drtshock** [comment]
Better explained in #509
