### ISSUE TITLE
new api compatibility

### ISSUE THREAD

**Issue by moo-im-a-cow** [drtshock/Factions#46]
hi
many plugins are now offering integration using the new factions api.
http://dev.bukkit.org/bukkit-plugins/wrg/
worldeditregions has a file called FactionsFeatures that imports the following:

import com.massivecraft.factions.entity.BoardColls;
import com.massivecraft.factions.entity.Faction;
import com.massivecraft.mcore.ps.PS;
http://dev.bukkit.org/bukkit-plugins/sentry-citizens2/
sentry for citizens2 has a file in it called FactionsUtil that imports the following:

import com.massivecraft.factions.Rel;
import com.massivecraft.factions.entity.Faction;
import com.massivecraft.factions.entity.FactionColl;
import com.massivecraft.factions.entity.FactionColls;
import com.massivecraft.factions.entity.UPlayer;

**Comment by drtshock** [comment]
Note for myself or whoever for later: just provide forward compatibility. Should be easy enough.

**Comment by drtshock** [comment]
Another plugin is attempting to provide a layer of compatibility. I'm not sure if we are going to look into making sure that we provide forward compatibility when hooking into that codebase is like trying to grab a  handful of water.
