### ISSUE TITLE
No command for truce.

### ISSUE THREAD

**Issue by PetKCH** [drtshock/Factions#460]
I have been going through configs and everywhere are options for Truce, yet, in-game there is no such command with which factions could truce each other. So could you please work something with this?
When I type /f truce I get return message: Strange argument "truce". Use the command like this: /f

Thanks in advance,
Laos

**Comment by zRiaz** [comment]
FactionsUUID does not have truces.

**Comment by MoeXIV** [comment]
@ISanderI it's understandable but there's a lot of configuration options that relate to Truces so I can see why he was confused. There's options in the conf.json about truces as well as the config.yml

**Comment by drtshock** [comment]
It was partially implemented in the backend as we were prepping for HCFactions but we ended up making that a separate project and never added it in this one.
