### ISSUE TITLE
Home teleport on Death

### ISSUE THREAD

**Issue by TheKnight787** [drtshock/Factions#463]
I set the homesTeleportToOnDeath to true in conf.json but it doesn't work. After death the player goes to spawn. I am using Factions #273, PEX v1.23.3, EssentialsX #130.

**Comment by drtshock** [comment]
Did the player set home with a bed or with /sethome?

**Comment by TheKnight787** [comment]
With /f sethome

**Comment by drtshock** [comment]
Does this happen in all worlds? It should work in any world that doesn't have power loss disabled if homesRespawnFromNoPowerLossWorlds is false. You need to have homesTeleportToOnDeath and homesEnabled set to true.

**Comment by drtshock** [comment]
^ this works fine
