### ISSUE TITLE
Hoppers

### ISSUE THREAD

**Issue by TheKnight787** [drtshock/Factions#464]
My players seem to steal from each other using a minecart with hopper. They push the minecart with hopper towards an enemy chest and steal items like that. They also steal from their faction members who have /f owner set on member's house.

**Comment by drtshock** [comment]
How does worldguard protect against this?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
