### ISSUE TITLE
Minimal F Show from HCFactions

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#466]
Simple as that, a request to add the "minimal f show" code from HCFactions into FactionsUUID as HCFactions has a lot of "cool" updates not included in FactionsUUID.

**Comment by Kakifrucht** [comment]
You can completely customize the output of f show

**Comment by MoeXIV** [comment]
@Kakifrucht This has nothing to do with that. Minimal f show removed the lines with no variables to show. For example, the allies line. If I have no allies, there's nothing to display so the line is removed until there's something there.

**Comment by Kakifrucht** [comment]
That would be nice!

**Comment by MoeXIV** [comment]
@Kakifrucht Agreed! Hope this is implemented from the HCFactions plugin.

**Comment by MoeXIV** [comment]
@drtshock anything? Do this could be implemented from the HCFactions resource?

**Comment by MoeXIV** [comment]
@drtshock I know you get notified with these messages but anything at all? Do you have any opinion on this request?

**Comment by drtshock** [comment]
I was out of town on vacation for my birthday. Getting back to fixing issues on my public plugins this weekend.

**Comment by drtshock** [comment]
Added

**Comment by Kakifrucht** [comment]
nice thanks

**Comment by drtshock** [comment]
Let me know how it works. you'll need to add `minimal-show: true` to your config.yml
