### ISSUE TITLE
Faction Warp Costs

### ISSUE THREAD

**Issue by Armannnnnn** [drtshock/Factions#469]
Faction warp costs do not take effect on version U0.1.17-b267. When /f setwarp <warp name> is used, the player isn't charged, although the cost is enabled in the configuration file.

Configuration: http://pastebin.com/75haMLYU

**Comment by Agazed** [comment]
I confirm this.

**Comment by SekiAlpha** [comment]
I think this is possible by utilizing other plugins.

**Comment by drtshock** [comment]
@cnr

**Comment by Agazed** [comment]
Friendly reminder this issue still exists!

**Comment by MrDip** [comment]
bumped. getting this issue as well.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
