### ISSUE TITLE
Scoreboard Bugs

### ISSUE THREAD

**Issue by ColtraneNadler** [drtshock/Factions#47]
issue w/ sb

**Comment by drtshock** [comment]
I'm not going to show scoreboard AND chat. I'll look into the other parts of your issue.

**Comment by drtshock** [comment]
Wasn't able to reproduce. Can anyone else reproduce this?

**Comment by RenegadeEagle** [comment]
Closing this now due to the reporter of this topic is no longer active in any aspect of minecraft.
