### ISSUE TITLE
/F Top Issue

### ISSUE THREAD

**Issue by Kozs** [drtshock/Factions#470]
http://i.gyazo.com/1da44e6a0ac14a8512f436863a86e535.png

I don't believe it's correctly adjusting the top ints. Any suggestions?

**Comment by drtshock** [comment]
Which version are you on? And what do you mean by not adjusting the top ints?

**Comment by Kozs** [comment]
v1.6.9.5-U0.1.17-b270 -> Also I mean that CRRaid should be #1 and then impulse and then Wilderness :P

**Comment by Kozs** [comment]
Any progress with this?

**Comment by drtshock** [comment]
Server factions (wilderness, safezone, warzone) shouldn't show up in the comparator. Not sure why it is. Let me figure that out.

**Comment by Kozs** [comment]
Thanks! Let me know when you do please :)

**Comment by xXBarchticXx** [comment]
@drtshock figure it out? I ran into the porblem too x)

**Comment by drtshock** [comment]
I have not but this is what I got on my server
![img](http://i.imgur.com/7BfeHZl.png)

**Comment by xXBarchticXx** [comment]
same thing with me x) http://gyazo.com/d6b9ed7b45b17137d64d2a696d246eee

**Comment by xXBarchticXx** [comment]
BTW what is your server I wanna check it out :P

**Comment by drtshock** [comment]
If any fresh eyes want to take a look https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/cmd/CmdTop.java#L42

**Comment by drtshock** [comment]
Can you try again on the latest build on spigot @Kozs

**Comment by drtshock** [comment]
lol found the issue. fixed.
