### ISSUE TITLE
Error doing /f claim on Spigot 1.8.3 AND Paper Spigot 1.8.7

### ISSUE THREAD

**Issue by xXBarchticXx** [drtshock/Factions#471]
Hello, I am receiving the following error whenever I type /f claim. It says internal error in chat.
18.07 14:26:38 [Server] INFO ... 15 more
18.07 14:26:38 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:192) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.cmd.CmdClaim.perform(CmdClaim.java:43) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.zcore.persist.MemoryFPlayer.attemptClaim(MemoryFPlayer.java:765) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.zcore.persist.MemoryFPlayer.canClaimForFactionAtLocation(MemoryFPlayer.java:690) ~[?:?]
18.07 14:26:38 [Server] INFO at com.massivecraft.factions.integration.Worldguard.checkForRegionsInChunk(Worldguard.java:120) ~[?:?]
18.07 14:26:38 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/Collection;)Ljava/util/List;
18.07 14:26:38 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
18.07 14:26:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:26:38 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.17-b270
18.07 14:26:38 [Server] ERROR null
18.07 14:25:38 [Server] INFO ... 15 more
18.07 14:25:38 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:192) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.cmd.CmdClaim.perform(CmdClaim.java:43) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.zcore.persist.MemoryFPlayer.attemptClaim(MemoryFPlayer.java:765) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.zcore.persist.MemoryFPlayer.canClaimForFactionAtLocation(MemoryFPlayer.java:690) ~[?:?]
18.07 14:25:38 [Server] INFO at com.massivecraft.factions.integration.Worldguard.checkForRegionsInChunk(Worldguard.java:120) ~[?:?]
18.07 14:25:38 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/Collection;)Ljava/util/List;
18.07 14:25:38 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
18.07 14:25:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-BT38_1.8.3_05.28.jar:git-Spigot-870264a-0a645a2]
18.07 14:25:38 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.17-b270
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/10205575/8763106/53c42a5c-2d43-11e5-9770-10810ecb51a0.gif)

**Comment by drtshock** [comment]
Use a paste service. I'm not reading through that.

**Comment by drtshock** [comment]
Actually, you have worldguard checking enabled but don't have worldguard installed 
`14:25:38 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/Collection;)Ljava/util/List;`

**Comment by Kakifrucht** [comment]
Or just an old version of WorldGuard
