### ISSUE TITLE
Make /f claim messages shorter

### ISSUE THREAD

**Issue by Terrobility** [drtshock/Factions#472]
On the new version of factions, the claim messages are only one line, compared to the multiple lines the old factions prints out. It can get really spammy, maybe this would be a feature request you may want to implement.

**Comment by MoeXIV** [comment]
Like a request to add null lines in the lang.yml. This would be a very nice update as well as the ability to "\n" on lines as well.

**Comment by drtshock** [comment]
I don't understand the issue.
