### ISSUE TITLE
Click to join! Not working!

### ISSUE THREAD

**Issue by SekiAlpha** [drtshock/Factions#473]
What is the Issue:
Clicking on a faction invitation does not produce expected results

Expected result:
Clicking a faction invitation will automatically make the player join sed faction.

What happens:
Clicking a faction invitation will cause a player to output "f join (factionname)" into the chat.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
