### ISSUE TITLE
Small lag spikes being caused by commands and PlayerPortalEvent

### ISSUE THREAD

**Issue by xPeyotii** [drtshock/Factions#476]
Recently my server has been receiving 400-1000ms lag spikes once or twice a minute. After looking into these, I've found out they are being caused by Factions commands and the portals limit feature that can be enabled in the config.yml.

I've only noticed /f who, /f show, and /f enemy causing lag spikes. I'm not sure about the other commands. They don't cause lag every time they are used, but rather every few minutes or so. Here's a timings report of a tick that /f show occured in which caused the tick to take ~600ms:
http://timings.aikar.co/?url=11930906

Here's a timings report of a tick where a player used a Portal which caused a ~800ms lag spike by Factions, this happens every time a player uses a portal:
http://timings.aikar.co/?url=11930730

EDIT: We are using the latest version even though the timings say "Factions v1.6.9.0-UUID" because we've added a few modifications to make certain things look more appealing but never changed the version in the plugin.yml. The lag spikes occur with our edited version and with the non edited version that can be downloaded straight from Spigot.

EDIT 2: I just found out that /f show [faction] will cause lag when you use a faction name that doesn't exist.

EDIT 3: It seems every command that will take a faction name as a parameter will lag if the faction name doesn't exist.

**Comment by MoeXIV** [comment]
I've noticed this as well,

**Comment by Kakifrucht** [comment]
I actually reported the spikes from the portals awhile ago, #225 

About the spikes when typing a faction that does not exist: that should be fixed. Had that issue, too. Update to the latest version.

**Comment by drtshock** [comment]
I looked into this thoroughly and determined it wasn't portals at all, just f show <factionname> on a non existant faction.

**Comment by Kakifrucht** [comment]
The onTravel check still takes around 200 ms.. I don't exactly understand why this was closed.
