### ISSUE TITLE
{header} Style Editor [enhancement]

### ISSUE THREAD

**Issue by RyanRed** [drtshock/Factions#477]
My current /f show format is as shown:
![image](https://cloud.githubusercontent.com/assets/13500510/8891012/cf84191a-330e-11e5-8241-57fc724d83bd.png)

However I'd prefer to have the '[ Example ]' faction tag on the main header line, rather than within the details section.

As far as I know, the header line changes size based on the length of the faction's tag. However I cannot do this currently as longer (max length) faction tags will force the current header line onto the second line, making the two parallel structure lines uneven in length.

Using the {faction} tag in oppose to using {header}:
![image](https://cloud.githubusercontent.com/assets/13500510/8891041/cc81907a-330f-11e5-8f03-c164aacee6be.png)
However, lines at either side do not change when number of tag characters changes, causing:
![image](https://cloud.githubusercontent.com/assets/13500510/8891048/f48f6920-330f-11e5-8a61-f00bdadbef33.png)

Default:
![image](https://cloud.githubusercontent.com/assets/13500510/8891058/3e5423b6-3310-11e5-9135-b3f0ecfecd70.png)
As you can see, side lines ( _'s) are shortened in order to maintain a specified character length on the line.

Config idea:

== Custom Header
== This allows you to edit the default {header} tag format which is configured in /f show

 header-sides: '&6_'
 padding-left: '&6.['
 padding-right: '&6].'

 header-format: '{header-sides}{padding-left} {faction-tag} {padding-right}{header-sides}'

^ The default configuration shown above will show up in-game as:
![image](https://cloud.githubusercontent.com/assets/13500510/8891083/9a8be938-3311-11e5-91ee-16888df81c6e.png)

**Comment by RyanRed** [comment]
was this ever considered to be added?

**Comment by Kakifrucht** [comment]
Well, as far as I have noticed most players change their chat to be more narrow, so adding extra logic to prevent line breaks would be wasted computing time imo. I just made it shorter to make sure that there is always enough space, even with max faction tag length.

**Comment by drtshock** [comment]
what kaki said
