### ISSUE TITLE
People are allowed to build on others land for some reason

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#479]
There is a huge issue on my server regarding the fact that players can build on faction land. I set the build permissions to false in config and it still happens for some reason.

**Comment by Agazed** [comment]
Post your configuration please.

**Comment by ghost** [comment]
Actually agazed I figured out the problem after some testing. It was just the tnt block that is allowed to be placed. After i changed the setting to false however, when tnt is lit in faction territory it does not cause a crater. I was wondering if you had an answer to that, here is my configuration. 
![image](https://cloud.githubusercontent.com/assets/13513505/8913179/08f034dc-345d-11e5-93bc-dbcf3ae95613.png)

**Comment by Agazed** [comment]
territoryBlockTNT and territoryBlockTNTWhenOffline are both true.

You need to set both options to false.

**Comment by ghost** [comment]
Yes but when that is true people are allowed to place tnt blocks on others land, then light it with flint and steel or fire arrows. The config seems to not recognize the tnt as a block but as the separate option.

**Comment by Agazed** [comment]
Try regenerating your config. You only posted a small portion of it, so I can't help you.

**Comment by drtshock** [comment]
Regenerate the configurations as I'm sure it's something you either messed up in there or another plugin that's overriding it.
