### ISSUE TITLE
Doing /f c f and all faction chats displays chat in public and private chat.

### ISSUE THREAD

**Issue by xXBarchticXx** [drtshock/Factions#484]
http://gyazo.com/1c1556c4432e6dbbfa89f13e35de9914
screenshot of the matter. My plugin list is NoMoreHunger, EssentialsX, GroupManager, Buycraft, BanManager, SuperTrails, CustomEnderChest, ChecknameHistory, CoreProtect, WorldEdit, WorldBorder, Chatcontrol (most likely the problem), Votifier, ClearLag, ActionBarAPI, MultiverseCore, NoHopper, Protocol Lib, LibsDisguises, AntiMinimap, Rename, TitleMotdAdvanced, Featherboard, Tab, Lottery, Customcrates, MCMMO, vault, holographicdisplays, world guard, player vaults, multiverse-nether portal, keepdeathdrop, booscooldowns,sexymotd,compatnocheatplus,obsidian destroyer,playerheads,fbasics,combattagplus,placeholderapi,bossmessage,floauction,what is it, silk spawners Thanks for helping :D

**Comment by drtshock** [comment]
You have another chat plugin messing with this then.

**Comment by xXBarchticXx** [comment]
Da help god ^

**Comment by xXBarchticXx** [comment]
X) but seriously thanks porbs chat control
