### ISSUE TITLE
/f invite error - not sent an invitation

### ISSUE THREAD

**Issue by LemonNick** [drtshock/Factions#487]
: Lemios issued server command: /f invite bobik

org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.17-b270

> ```
>   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1481.146]
>   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1481.146]
>   at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1481.146]
>   at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
>   at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
>   at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
>   at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
>   at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
>   at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>   at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
> ```
> 
> Caused by: java.lang.NullPointerException
>       at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:89) ~[?:?]
>       at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:78) ~[?:?]
>       at com.massivecraft.factions.cmd.CmdInvite.perform(CmdInvite.java:53) ~[?:?]
>       at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
>       at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
>       at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
>       at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
>       at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
>       at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302) ~[?:?]
>       at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265) ~[?:?]
>       at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
>       at com.massivecraft.factions.P.onCommand(P.java:192) ~[?:?]
>       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1481.146]
>       ... 13 more

**Comment by drtshock** [comment]
Apparently this version of fanciful doesn't work with 1.7.10 even though it is on FuriousPVP right now..

**Comment by drtshock** [comment]
Try redownloading the jar. I was able to get this to work just fine
https://gist.github.com/drtshock/1cd133c856de298dbe23

**Comment by drtshock** [comment]
Happens when using cauldron. Though cauldron is no longer being supported :(
