### ISSUE TITLE
Suggestion | Enter notifications

### ISSUE THREAD

**Issue by xXBarchticXx** [drtshock/Factions#488]
Add notification through titles on entering another player's claimed land. This can be configured on or off and would be like Entering: name

**Comment by SekiAlpha** [comment]
I agree

**Comment by drtshock** [comment]
This has been brought up many times but I don't want to add something that will make us break between Minecraft versions.

**Comment by xXBarchticXx** [comment]
@drtshock would this work if you did it this way? Check if the version is 1.8 (or check if there is a certain material) on enable and if it is allow titles and if it isn't don't allow it?

**Comment by Agazed** [comment]
@xXBarchticXx Yeah. That would be a good way to add stuff that will break on new versions.

**Comment by xXBarchticXx** [comment]
I will tag @drtshock just incase its helpful. Also ^ agazed is that a good thing or a bad thing? I can't seem to understand your comment correctly x)

**Comment by drtshock** [comment]
I get notifications for all comments, don't worry.

**Comment by xXBarchticXx** [comment]
So is this possible?

**Comment by Agazed** [comment]
@xXBarchticXx Some methods need to use NMS to add features like titles, as they havent been added to the API yet. This causes newer minecraft versions to be incompatible and the plugin breaks when the NMS version is out of date.

A good way to check of the version is compatible is onEnable you can check if the version matches the version the plugin was made for. This way, only the features using NMS break, and not the features that don't.

**Comment by drtshock** [comment]
It is possible but I'm not going to add something that will break between versions.
