### ISSUE TITLE
Adding faction's name to under player's displayname

### ISSUE THREAD

**Issue by irfantogluk** [drtshock/Factions#49]
Is it possible to add faction's name to under player's displayname (healthbar scroeboard) with faction color?
If it's possible, I think healthbar must to be with a integer like this "100 Health"
If this is must to be, zero number can be use. Example: "0 MyAwasomeFaction 0"
The first zero number is must to be, secon zero number for nice look.

**Comment by drtshock** [comment]
How would you want it to work? Would you want to be able to add different things down there? And I'm assuming that you'd want to have the relation color shown as well.

**Comment by irfantogluk** [comment]
Yes, relcolor would be fine. If your faction is enemy faction of mine, I'll see your faction's name red under your name. Like a MMORPG :)

**Comment by drtshock** [comment]
Not sure why I was thinking it would be possible but the relation color wouldn't be. You set the scoreboard on the player and can't choose how you show it to each player, at least not easily.

**Comment by irfantogluk** [comment]
I'm writing a guild plugin for BungeeCord and Spigot to my server. I tried to add guild name under player's name but I fail. I know, It's not easy.

**Comment by Yive** [comment]
I'm guessing you're wanting to make the players nametag similar to this?
![example](http://i.yive.me/pL1u691)
You can't set it to a string, it can only be an int. I think drtshock would be better off adding in some sort of thing that just hooks into nametag edit and put [<Faction Name>] in front of the username.

**Comment by drtshock** [comment]
I'm planning on just using scoreboard prefix and then adding their role as the suffix. All of the being configurable of course.

**Comment by drtshock** [comment]
This was added in a recent scoreboard commit.

**Comment by amgno** [comment]
How you do for Prefix with faction name and realtion color????
