### ISSUE TITLE
Duplicate chat w/ FactionsUUID 1.6.9.5-U0.1.17-b270

### ISSUE THREAD

**Issue by lol768** [drtshock/Factions#492]
Apparent purchasing user: Danny_L (SpigotMC)

Server: Spigot 1.8.7

![](http://i.imgur.com/r3rVJCP.jpg)

Was using EssentialsChat, but apparently can still reproduce with it disabled.

**Comment by drtshock** [comment]
Happens when another chat plugin interferes.
