### ISSUE TITLE
Power Display

### ISSUE THREAD

**Issue by JakeBro99** [drtshock/Factions#495]
So at this point I'm thinking it's a plugin conflicting but I may be wrong so I thought I would ask you. My server runs your latest version of the payed factions UUID 1.6.9.5. When I type /f show, /f who, /f power, or /f list the power is messed up in ways I havnt seen before. On my main server it gives me strange numbers such as 0.01332 and long decimals, and on a test server I run it says NaN. Now keep in mind I use the same plugins on both servers. I tested it without any of my plugins and it works fine. I'm not sure if there are known conflicting plugins or if there's something specific that may be causing this? Thanks you for your help,
- Jake

**Comment by juIio** [comment]
Can you post your configuration file? Thanks.
EDIT: Please make sure to use http://pastebin.com

**Comment by drtshock** [comment]
I don't understand your issue.
