### ISSUE TITLE
Bug in tab Even when disable default-prefixes

### ISSUE THREAD

**Issue by thu2468** [drtshock/Factions#496]
So i Enabled Default-enabled and disabled default-prefixes and it broke my custom tab from colored tags. All names are white

**Comment by drtshock** [comment]
Which version? Paste your entire config.yml as I fixed this a few months ago.

**Comment by thu2468** [comment]
Factions version 1.6.9.5-U0.1.17-b274
https://smallpaste.in/view/55c3e9f1569e7a310d8b4593

**Comment by drtshock** [comment]
You still have scoreboards enabled. The default-enabled and finfo-enabled.

**Comment by thu2468** [comment]
yea but i disabled  default-prefixes: false
But i want to use the scoreboard and use coloredtags
Lol i just noticed that i have a link in a link

**Comment by drtshock** [comment]
you can't
