### ISSUE TITLE
Date of time created bug.

### ISSUE THREAD

**Issue by xXBarchticXx** [drtshock/Factions#497]
Hey @drtshock, it is your friendly neighborhood bug and issue guy here and I have come across a bug with your time formatting.
![2015-08-05_21 17 51](https://cloud.githubusercontent.com/assets/10205575/9103828/da2f99d2-3bb7-11e5-868b-204bf3feff49.png)
As you can see in that image it says the faction was created at 7:7pm x)
![2015-08-05_21 21 19](https://cloud.githubusercontent.com/assets/10205575/9103840/f211f7d4-3bb7-11e5-83d5-c4d9b90339f9.png)
But in this image it is 7:13pm. IDK why but I believe you are not formatting it to 7:00pm? Also one last thing when will those fancy maps come out (the one with the colors)

**Comment by drtshock** [comment]
Not sure on the map and that's odd, it's just using the simple date format in your lang.yml file.
