### ISSUE TITLE
Reward for overclaiming enemy lands

### ISSUE THREAD

**Issue by denizaygundev** [drtshock/Factions#498]
Could you add an econ value for rewarding factions for when they overclaim land of an enemy faction so instead of the enemy faction getting the money they would get for unclaiming the faction that's raiding would. This'll help to make raids more rewarding.

Something like econOverclaimRewardMultiplier perhaps?

Thanks.

**Comment by drtshock** [comment]
Let me know if that is the functionality you wanted.
