### ISSUE TITLE
/f home is not respecting essentials teleport-delay

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#5]
previously before using the UUID version /f home would require the player to stand still for the required amount of time define in essentials config. Now players are instantly teleported which can be used to cheat in combat.

using:
essentials 2.13.152
factionsUUID 15
spigot 1442

**Comment by Zeebra456** [comment]
they removed essentials integration so your going to need to fork the repo and start working on it your self because no updates have been made. I had to start working on my fork ;\

**Comment by PhanaticD** [comment]
aint nobody got time fo dat

**Comment by Zeebra456** [comment]
well Good luck :) :+1:

**Comment by drtshock** [comment]
@Zeebra456 you can always PR it to our repo.

**Comment by drtshock** [comment]
Fixed in latest commit.
