### ISSUE TITLE
F powerboost of players dissapear

### ISSUE THREAD

**Issue by xwolfyxNL** [drtshock/Factions#500]
Dear,

My server has a lot of problems that people there f powerboost dissapear when they leave a faction.
So now every day people request me to fix there powerboost.
Isnt there a way to make this permanent?

Sincerely xwolfyxNL

**Comment by Kakifrucht** [comment]
It should be permanent already. Are you applying the powerboost to the player or faction?

**Comment by xwolfyxNL** [comment]
To the player and then when the player leaves a faction they lose it.
The powerboost for factions works fine only not for the players :/
The old normal factions 1.6.9 before mcore also had this issue

**Comment by Kakifrucht** [comment]
Cannot reproduce, for me the player always keeps his powerboost, despite leaving a faction. On which build are you?

**Comment by xwolfyxNL** [comment]
build 276

**Comment by drtshock** [comment]
Can you show me logs of this happening? I can't reproduce.
