### ISSUE TITLE
[Feature Request] Addable power boosts

### ISSUE THREAD

**Issue by xXBarchticXx** [drtshock/Factions#501]
Hey drtshock, do you think you can make a quick edit and allow addable power boosts? This is because I want buyable power with igm and I want it so that when you do /f powerboost p {name} 1 it gives them a power boost of 1 and if you do it again it adds 1 to the existing powerboost not sets it.

**Comment by Kakifrucht** [comment]
So essentially, instead of resetting the powerboost always adding IF a powerboost is already supplied?
Sounds good.
To reset you could still keep the intuitive way of just doing /f powerboost p {name} 0

**Comment by xXBarchticXx** [comment]
Also maybe you could add /f powerboostset p | f {name} to just set it.

**Comment by drtshock** [comment]
Yeah I never liked the current functionality, it doesn't make sense. I think that powerboost should always add on top of what is currently there.

**Comment by xXBarchticXx** [comment]
Can you compile it on spigot maybe?

**Comment by xXBarchticXx** [comment]
I don't have access to jenkins or anything

**Comment by Agazed** [comment]
You can use Maven to compile Maven projects. Heres a good video on how to do so: https://www.youtube.com/watch?v=mXatMgPMU4Y

Or you can message drtshock on the spigot website with your jenkins account name.

**Comment by drtshock** [comment]
I'll post a new build soon.

**Comment by xXBarchticXx** [comment]
can you add me to jenkins? Username is Barchtic. Last time I asked you said it wasn't working. I am guessing it is now?

**Comment by Kakifrucht** [comment]
Could you then also add if using /f powerboost p player 0 that resets the boost, as it currently does not support this?

**Comment by xXBarchticXx** [comment]
That sounds good :P although I would rather have /f powerboost p player reset and /f powerboostset p player (any number) to just set their powerboost not add onto it.

**Comment by Kakifrucht** [comment]
additional command is never good imo, for something that is completely the same thing. Calling the param 'reset' or '0' wouldn't make a difference for me, however I feel like 0 is more intuitive, whilst when using reset the information must be put somewhere.

**Comment by xXBarchticXx** [comment]
Bump would like to be added to jenkins build server username: Barchtic spigot username: xXBarchticXx

**Comment by drtshock** [comment]
Stop fucking bumping the tickets @xXBarchticXx. I get notifications for everything and I am not on 24/7. Jenkins access system still isn't working, I'll be posting a new build for this soon.
