### ISSUE TITLE
F Warps have some issues

### ISSUE THREAD

**Issue by Kozs** [drtshock/Factions#504]
Sometimes it won't teleport you when you type the warp. Sometime's it's automatic no warmup time and it takes you to the wrong warp. Or it just takes you to the wrong f warp... 

Hoping these issues can be fixed as they're fairly annoying.

**Comment by drtshock** [comment]
Can you narrow down the exact issue and tell us how to reproduce it? Hard to fix "sometimes it does this and that" :\

**Comment by Kozs** [comment]
That's all I know, people need to type /f warp several times for it to teleport. But then again it works. I am getting complaints and I've tested it myself and it's true.

**Comment by Kozs** [comment]
https://i.gyazo.com/802a4f22edfeecfda843df713fd50396.png
This is an example

**Comment by cnr** [comment]
This should be fixed in the latest build on the CI. If it's not, please report back.
