### ISSUE TITLE
Baltop from essentials.

### ISSUE THREAD

**Issue by xXBarchticXx** [drtshock/Factions#505]
Hello, I was wondering if you could make it so essentials doesn't detect factions in the baltop command x). This happens with issuing the /baltop command and it displays faction_# and the balance of the faction. https://gyazo.com/d8d72b6200b070e01668750aefc5dcd8 Also soz for asking :( but how will I get the build with the addable powerboosts?

**Comment by drtshock** [comment]
This would be an issue to bring up with essentials. I've never seen that happen before.

**Comment by zRiaz** [comment]
I got this too. Faction_22 showed up on baltop when i had economy enabled in factions. 
(EssX & FacUUID)

**Comment by xXBarchticXx** [comment]
Yeah I am using your essentialsx X)

**Comment by drtshock** [comment]
So make a ticket in the essentials repo.
