### ISSUE TITLE
Converting issue.

### ISSUE THREAD

**Issue by CodingLukas** [drtshock/Factions#506]
http://pastebin.com/H5ne4smC

**Comment by drtshock** [comment]
Which version are you coming from? Looks like you hit a rate limit.

**Comment by CodingLukas** [comment]
Latest from spigotmc.org

**Comment by drtshock** [comment]
which version of factions are you converting from? i need a version string.

**Comment by CodingLukas** [comment]
You are running Factions v1.6.9.5

**Comment by drtshock** [comment]
what WERE you running BEFORE you started using mine. Not what am I running ._.

**Comment by CodingLukas** [comment]
I'm running now it... "You are running Factions v1.6.9.5" (http://dev.bukkit.org/bukkit-plugins/factions/files/52-1-6-9-5/)

**Comment by Tzky** [comment]
He wants to know the version you used BEFORE 1.6.9.5. Not the current one.

**Comment by CodingLukas** [comment]
I'm running it for ~2 years, I don't really remember, I guess I used 1-6-9-4 (http://dev.bukkit.org/bukkit-plugins/factions/files/51-1-6-9-4/) two years ago.

**Comment by drtshock** [comment]
Then the conversion will work fine as long as you aren't rate limited. Wait a bit, try again. Or try on another computer.
