### ISSUE TITLE
Chat Formatting Error

### ISSUE THREAD

**Issue by Mineacer** [drtshock/Factions#507]
I believe there's currently an issue with chat formatting. There's an unknown space in front of my display name, and the only plugin managing chat is EssentialsChat.

Here's what it looks like in-game:
![image](https://cloud.githubusercontent.com/assets/13867725/9353917/c75012d2-469e-11e5-9327-f83fe2dd6ce7.png)

This is my chat format for EssentialsChat:
![image](https://cloud.githubusercontent.com/assets/13867725/9353923/d495d454-469e-11e5-98c4-9e35900fa4d7.png)

I have no idea what could be the issue, except the faction tag causing some sort of error.

**Comment by drtshock** [comment]
Is elite your faction or your rank?

**Comment by Mineacer** [comment]
Elite is the rank.

It happens for all ranks I've made so...

**Comment by drtshock** [comment]
There's a space between display name and faction tag that your rank prefix is being put in which is still there without the faction tag. There's a way to fix this with the conf.json, but I forgot..
