### ISSUE TITLE
command /f who Issue

### ISSUE THREAD

**Issue by jcalem** [drtshock/Factions#508]
I recently bought this plugins and replaced it with my old faction.jar. Everything works but /f who command:
![f who](https://cloud.githubusercontent.com/assets/13872364/9361407/4dd69b40-4669-11e5-9087-8319f0532a1a.png)
Console:  http://pastebin.com/G8Fs45AB
I tried deleting all the faction data but it still didn't fix the problem. Any Ideas?

**Comment by drtshock** [comment]
Get a permissions plugin and vault.

**Comment by jcalem** [comment]
I already have permissions ex and vault

**Comment by drtshock** [comment]
Then update :)

**Comment by jcalem** [comment]
still didn't fix the problem
