### ISSUE TITLE
Factions economy help

### ISSUE THREAD

**Issue by arreyazat** [drtshock/Factions#509]
Hello, I'll get right to the point.

I want to be able to have economy enabled in my Factions config (which I have done) and want to tax players for creating a faction, kicking players, etc. 

However when a user creates a Faction, I notice that the factions bank is founded on the faction owners balance, so for example X user creates a faction, after creating the faction he has 100 coins, if he does /f show the faction bank shows 100 coins. If the same user loses another 10 coins and his new balance is 90 coins the faction banks' balance also simultaneously update to 90 coins too.

I want the factions bank to be a standalone 'bank' which is not dependant / has nothing to do with the faction owners balance, when X user creates a Faction for 20 coins, I want the factions bank to hold 20 coins regardless of the faction owners personal balance - the faction bank should only update when money is withdrawn / donated from / to it.

Thanks!

Relevant config setup:

  "econEnabled": true,
  "econUniverseAccount": "",
  "econCostClaimWilderness": 0.0,
  "econCostClaimFromFactionBonus": 0.0,
  "econClaimAdditionalMultiplier": 0.0,
  "econClaimRefundMultiplier": 0.0,
  "econClaimUnconnectedFee": 0.0,
  "econCostCreate": 30.0,
  "econCostOwner": 0.0,
  "econCostSethome": 0.0,
  "econCostJoin": 0.0,
  "econCostLeave": 10.0,
  "econCostKick": 10.0,
  "econCostInvite": 0.0,
  "econCostHome": 0.0,
  "econCostTag": 0.0,
  "econCostDesc": 10.0,
  "econCostTitle": 0.0,
  "econCostList": 0.0,
  "econCostMap": 0.0,
  "econCostPower": 0.0,
  "econCostShow": 0.0,
  "econCostStuck": 0.0,
  "econCostOpen": 0.0,
  "econCostAlly": 0.0,
  "econCostTruce": 0.0,
  "econCostEnemy": 0.0,
  "econCostNeutral": 0.0,
  "econCostNoBoom": 0.0,

  "bankEnabled": true,
  "bankMembersCanWithdraw": false,
  "bankFactionPaysCosts": true,
  "bankFactionPaysLandCosts": true,

(Not to mention, I don't know the difference between enabling econ and enabling "bankEnabled"?)

**Comment by drtshock** [comment]
It's designed to be a standalone account which is why we've seen the issue of it showing up on baltop as a user. Can you turn on debug and show me logs of all this.

**Comment by arreyazat** [comment]
Hello, in the config file I enabled debug and restarted the Server, I will link the 'latest log' (even though I don't see any different logs even after debug mode being enabled?)

Pastebin: http://pastebin.com/Xprkgm8C

**Comment by arreyazat** [comment]
Drtshock, any news?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
