### ISSUE TITLE
ScoreBoard Configurabilty: New Features or Option to Add please!!!!!

### ISSUE THREAD

**Issue by Tribulationfu28** [drtshock/Factions#51]
yeah, but we were hoping that you would add certain features for us that the plugin doesn't have atm
[15:48] <TribulationFu> basically this is what we were wanting instead of how it is setup atm: 1. When you are just wandering around, it shows your faction name at the top, then your power, then members online Ex: like 10/23, then Faction max Power, then Amount of Land claimed. When you enter someone's territory, it shows their information instead of yours. And it is always visible unless you turn it off with the /f sb command to hide the scoreboard.

**Comment by drtshock** [comment]
What? Please don't just make tickets with blocks of text :(

**Comment by Tribulationfu28** [comment]
I'm confused? You told me to open a ticket about this when I asked you it on the IRC channel so I just copied and pasted it?

**Comment by drtshock** [comment]
Yes but no line breaks.

**Comment by Tribulationfu28** [comment]
ahhh, apologies. 
Line1 of Scoreboard: Faction name
Line2 blank
Line3 Power (This is the players power amount)
Line4 # (Players power amount)
Line5 blank
Line6 Members Online
Line7 #of members online/Total members in faction
Line8 blank
Line9 Faction Power
Line10 #of power/Total Power possible
Line11 blank
Line12 Land Claimed (amount of Land Claimed by the entire faction)
Line13 # (amount of Land Claimed by the entire faction)

If you could create this, that would be amazing for our server! I would be willing to pay you for it if needed, just let me know.

**Comment by drtshock** [comment]
Isn't that all already able to be added to the scoreboard?

**Comment by Tribulationfu28** [comment]
No it isn't. Not all of those features anyways. We would like those variables to be added and then make it where it always has the scoreboard up. Then if a player walks into another players faction land, it pulls up that factions info instead their own.

**Comment by Tribulationfu28** [comment]
But keep the /f sb option available just in case some players don't want to have the scoreboard up.

**Comment by drtshock** [comment]
It already does that though. Which ones aren't currently available?

**Comment by Tribulationfu28** [comment]
Can you link me to the page w/ the variables? I'm not currently at home so I don't have the page saved.

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/config.yml#L26-L27

**Comment by Tribulationfu28** [comment]
It doesn't have the faction name at the top of the scoreboard, It doesn't have the players individual power, It doesn't have the total power possible of the faction, and it doesn't stay open forever or show the players own faction info when not in another factions territory.

**Comment by drtshock** [comment]
This has been all added in commits today.
