### ISSUE TITLE
Getting lag spikes

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#510]
Not sure if it is factions or not however I am getting pretty bad lag spikes using 1.6.9.5-U0.1.18-b284

it seems to be completely random and I am having a hard time finding the cause but it only happens on my faction server

Here are some timings i tried to get so that they were only taken during lag spikes

http://timings.aikar.co/?url=12146754
http://timings.aikar.co/?url=12145588
http://timings.aikar.co/?url=12144639

**Comment by Kakifrucht** [comment]
Factions does not seem to be the cause of the problems. Why would you think that it is the problem, just because it is your "Factions" server?
