### ISSUE TITLE
Lockette

### ISSUE THREAD

**Issue by KyrneDev** [drtshock/Factions#511]
Is there any chance you could hook up with lockette so that when a claim is over claimed it deletes the lockette sign? If lockette is tot hard you could use deadbolt

**Comment by Agazed** [comment]
Why would you have lockette on a faction server? Doesn't make any sense imo. Faction owners can use the /f owner command to dedicate chunks to certain members in a faction.

**Comment by KyrneDev** [comment]
My reason are my reasons :D
