### ISSUE TITLE
Unable to disable commands in wilderness and ally territory

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#514]
Hey there!

As I said in the title, it seems that while there are options to disable certain commands in neutral, enemy, and warzone territory, there is no way to prevent command usage in wilderness or ally territory.

While the wilderness isn't a must, I would greatly appreciate the ability to blacklist commands in ally territory.

Thanks!

**Comment by drtshock** [comment]
Isn't the point of being an ally to trust them and let them do stuff?

**Comment by ghost** [comment]
Yes, but I have a command that automatically places blocks for the player. Since the player isn't actively right clicking, there's nothing to stop them from building in allied territory, which I don't want.

Edit: Apparently this feature was added in Factions 2.0 -- I think FactionsUUID could benefit from it as well. :)

**Comment by drtshock** [comment]
There ya go!

**Comment by ghost** [comment]
Ayy, thanks man!
