### ISSUE TITLE
Lots of exceptions

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#515]
I recently updated to the latest version of Factions with the save performance update, however that seems to have caused some trouble.
Firstly this is what happened after a player disbanded a Faction: http://pastebin.com/nX6Hygrj
This caused basically everything to completely bug around when events were fired. I don't know how this changed the gameplay. A complete reload of Factions fixed the issue apparently.
More stacktraces: http://pastebin.com/9nyX3ZaV

Rip my log

**Comment by Agazed** [comment]
Can confirm.

**Comment by cnr** [comment]
Fixed in the newest build -- thanks for reporting

**Comment by Kakifrucht** [comment]
Thanks for quick fix!
