### ISSUE TITLE
ScoreBoard Issue

### ISSUE THREAD

**Issue by S0methingpro** [drtshock/Factions#518]
So, now i did /f sb it says following: You now have scoreboards set to true. well but nothing shows up this is how it looks like in my config.

https://gyazo.com/32c602767ef81643feb0c2a54e7c9b54

What do i need to change>

**Comment by nsporillo** [comment]
Are you in a faction when you're testing this?

If not, then you want to set "factionless-enabled" to true so you see that sidebar.

**Comment by S0methingpro** [comment]
still not working and yes i am in a faction do i need some plugin for it to show or?

**Comment by drtshock** [comment]
Can you paste me your server log and show a list of plugins please

**Comment by thegiantwither** [comment]
I have the last version and scoreboard don't work for me to and drtshock only says enable in confiq but still dosen't work and he dosen't help!
