### ISSUE TITLE
bracket don't work for the factions prefix + randomlocation support

### ISSUE THREAD

**Issue by stox180** [drtshock/Factions#52]
hi there,

example:
http://gyazo.com/c6b7f4ef625d71ecf120a0f0af946c44

config:

http://gyazo.com/c15b197391981736e00ea3f96afe1572

Question:

Is there a way to get the "r" replaced with a [ or is it that im done something wrong? 

im using essentials chat.

also it seems that the plugin random location does not support this version of factions..
http://dev.bukkit.org/bukkit-plugins/randomlocation/

is there anything you can do about that or do i need to contact them about it?

Thanks in advance,

Stox180

**Comment by drtshock** [comment]
You could ask that author to add support for this. I'll look into the chat issues.

**Comment by stox180** [comment]
thank you for you're response ! 
i shall be contacting the author of random location :D

And i will await you're responce.

Stox180

**Comment by squidicuzz** [comment]
Any luck with RandomLocation?  I will look into the appearance of the mysterious r more.  Is there anymore information you can provide about your server and the plugins your are running?

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/issues/100
