### ISSUE TITLE
Warzone not claiming.

### ISSUE THREAD

**Issue by PvPBros** [drtshock/Factions#525]
I can't claim warzone in my FactionsUUID plugin. It says 'Your faction alrady own this land.' even though its not the warzone and just the wilderness. 
I have even tried deleting your config multiple times already and using different version of the plugin.
Spigot Version - 1.8.7 SnapShot

**Comment by PvPBros** [comment]
bump

**Comment by PvPBros** [comment]
@drtshock

**Comment by Agazed** [comment]
Please don't bump your issue.

**Comment by drtshock** [comment]
What's your username on spigot?

**Comment by drtshock** [comment]
[13:21:17]  @Korobi   To claim a warzone or safezone, do /f claim <radius> <warzone/safezone>
