### ISSUE TITLE
worldGuardChecking unsupported

### ISSUE THREAD

**Issue by svyoshi** [drtshock/Factions#528]
I'm running 'WorldGuard 6.1.1-SNAPSHOT.1623-96e0ffd with Custom flags plugin' with worldGuardChecking set to true, however, players are still able to claim in our regions. I'm assuming since it's a dev build, is why it isn't supported. However, this dev build is important, as it fixes redstone/pistons not working in regions. Please fix this soon!

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
