### ISSUE TITLE
Unclaiming

### ISSUE THREAD

**Issue by CakeArmy** [drtshock/Factions#529]
Hello, I saw your response to a comment saying they cant unclaim warzone and I tried doing what you instructed but it didn't work. Is there another way?

**Comment by cnr** [comment]
I'm not familiar with the comment you're referring to, however:

Assuming you have the `factions.managewarzone` permission:
- `/f unclaim` will unclaim a single warzone chunk
- `/f warunclaimall` will unclaim all warzone chunks

**Comment by CakeArmy** [comment]
do I need to join the warzone faction? Ill try adding the permission
directly onto myself.
