### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by Vultrise** [drtshock/Factions#533]
Im looking for these 2 features to be implemented.

/f fly (Allows users to fly in their faction territory with a permissions - if they leave fly disables)

/f vault (Gives factions a GUI in which they can place items and all faction members can access)

Thanks

**Comment by drtshock** [comment]
no and possibly.

**Comment by KyrneDev** [comment]
I really like the second one! Also maybe an alternative is a config option makes players able to have speed in their territory, but it disables on pvp to prevent unfair pvping

**Comment by DahFrozen** [comment]
I really like the second suggestion! That would be awesome. @drtshock Why is the flying in certain territory being denied? I've seen other servers with a plugin that does this.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
