### ISSUE TITLE
[HELP] FactionsUUID Custom Chat Tag Prefix?

### ISSUE THREAD

**Issue by Affixial** [drtshock/Factions#534]
Hello,

So I need help setting a custom faction tag prefix for the chat. Does anyone know how to do this? I'm using the latest version of FactionsUUID as well as EssentialsChat.

![image](https://cloud.githubusercontent.com/assets/14830724/10091540/b8821eca-630a-11e5-9337-6951697e67a3.png)

drtshock, if you're wondering, I didn't purchase the plugin under "Affixial". I purchased it under an alt account, I sent you a PM about it.

**Comment by drtshock** [comment]
What do you mean custom prefix?

**Comment by Affixial** [comment]
Default Faction tag: 
![image](https://cloud.githubusercontent.com/assets/14830724/10105471/de57b110-637c-11e5-8c65-d7fbffc691e7.png)

Custom one: (no faction) 
![image](https://cloud.githubusercontent.com/assets/14830724/10105479/e7311f7e-637c-11e5-9359-7ef01cf784a7.png)

(with faction) 
![image](https://cloud.githubusercontent.com/assets/14830724/10105495/f5fdc034-637c-11e5-89ae-e8e530c957fd.png)

**Comment by drtshock** [comment]
So what is the issue?

**Comment by Affixial** [comment]
I'm wondering how do you add a custom faction chat tag prefix.

**Comment by drtshock** [comment]
You already are? I'm confused.

**Comment by Affixial** [comment]
No I'm not... I'm asking for help, on 'How to set a custom faction chat tag prefix'.

**Comment by Kakifrucht** [comment]
But you did in the pictures you provided?

**Comment by Affixial** [comment]
"What do you mean custom prefix?"

I sent those pictures as an example.

Those are on a different server. Can anyone just tell me how to set a custom faction tag prefix?

**Comment by Kakifrucht** [comment]
ahh
Check the conf.json, in there you should find the value chatTagReplaceString.
This is by default [FACTION]. Put this tag in your EssentialsChat config and format it as you wish.

**Comment by Affixial** [comment]
Thanks for the help, I got it working.
