### ISSUE TITLE
Weird lag when the /f command is ran.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/Factions#535]
So my server has been starting to lag after around 4-5 hour of being online. Upon checking the timings report, the factions command is hanging like 100-200 ms with every use.

https://gyazo.com/353088c73c76d461a643f40cdefeed63
Im uploading a video showing a video of what im saying. Uploading atm.

The only thing i can think of is that FBasics might be screwing with something. Ive never had an issue with the factions plugin before. I'm thinking that FBasics is causing the lag. I wish Factions UUID had a /wild feature built in xD. But just to confirm that you dont think its the Factions plugin itself, let me know.

_Edit i removed f basics and spammed the /f who command and it froze the server. Video : https://www.youtube.com/watch?v=7GfA1dj9wv4_

**Comment by Kakifrucht** [comment]
The latest version of factions does not have any known performance issues. It's probably what you think it is.

**Comment by SnakeDaoust1232** [comment]
Well, i removed faction basics and then i spammed /f who and it froze the server. 

Video : https://www.youtube.com/watch?v=7GfA1dj9wv4

**Comment by Kakifrucht** [comment]
The tooltip messages can cause some lag, that is true.
Under normal circumstances this shouldn't be an issue though. I did the same thing you did with the powertool and it didn't lag. There were also less tooltips though.
Otherwise, is this actually causing problems? Sure, you can spam with powertool, but the players can't.

**Comment by drtshock** [comment]
Use minimal show then?

**Comment by SnakeDaoust1232** [comment]
Yes, that was the solution. Tooltips. I used to have about 5 lines on both the faction name and the player name. I shortened this down to 1 line for both and there is no lag. I hope kids who experience this issue can easily find the solution. Thank you for the help!

**Comment by Agazed** [comment]
Paste full timings report, please.

**Comment by KyrneDev** [comment]
/timings on
run some /f  commands
/timings paste
post the link here

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
