### ISSUE TITLE
Faction tag help

### ISSUE THREAD

**Issue by WPMDev** [drtshock/Factions#536]
I am trying to change the format of the faction tag (trying to change **factionName to something like [factionName]). Do I do that from the Essentials config or the factions config? If it is from the factions config where abouts in the config? I am using FactionsUUID and do have EssentialsChat download and running. Any help appreciated! Thanks.

**Comment by drtshock** [comment]
Read the conf.json

**Comment by WPMDev** [comment]
I cant find it in the config files

**Comment by WPMDev** [comment]
I have it set to [FACTION] but it still shows the faction in green when I chose another color.

My conf.json http://pastebin.com/nqMtUUuL

My config http://pastebin.com/MBjcWkvu

**Comment by drtshock** [comment]
Probably because that person is in the same Faction as you?

**Comment by WPMDev** [comment]
I figured it out myself :p thanks. And also what I wanted to do was completely change the faction tag color for different groups. But as I said I figured it out.
