### ISSUE TITLE
Factionless 

### ISSUE THREAD

**Issue by random1167** [drtshock/Factions#538]
![73ece94405ee80dae0f77f5e69823f1e0b7ed37f](https://cloud.githubusercontent.com/assets/13611085/10260085/17fe922a-69b4-11e5-92f8-9d99be711c01.jpg)
Any help please ?
to have it so factionless players can attack in faction territory.
on line 147 in config factionless-enabled: true
on line 84 conf  "enablePVPAgainstFactionlessInAttackersLand": true,
still factionless cannot attack people in faction territory

**Comment by Ichbinjoe** [comment]
At the moment, this only works the other way around, where factioned players may attack factionless within their own land.

**Comment by random1167** [comment]
@Ichbinjoe thank you, i will make a request for this option.
