### ISSUE TITLE
ScoreBoard Issue

### ISSUE THREAD

**Issue by DontayPlayz** [drtshock/Factions#542]
So, now i did /f sb it says following: You can't toggle scoreboards while they are disabled. Please help me fix this issue. Skype: DontayPlayzMC

**Comment by lol768** [comment]
Log: https://korobi.io/network/esper/channel/factions/logs/2015/10/14/#L10-62

**Comment by DontayPlayz** [comment]
So, now i did /f sb it says following: You now have scoreboards set to true or false and nothing appears on sidebar or anything on screen

**Comment by drtshock** [comment]
Yes, default-enabled needs to be set to true.

**Comment by lol768** [comment]
https://korobi.io/network/esper/channel/factions/logs/2015/10/14/#L40,43-44

**Comment by drtshock** [comment]
Then you have another plugin conflicting.
