### ISSUE TITLE
/f invite - Getting an error. Help me please.

### ISSUE THREAD

**Issue by NickFirenzo** [drtshock/Factions#544]
Hi, 
I need help about faction plugin. When any person write /f inv, /f invite getting and errror and lagging server for few milliseconds. Please tell me how to fix it, thanks.
Spigot version: 1.8.3
SS: http://prntscr.com/8s4cdy
Version: http://prntscr.com/8s73gh
Console error: http://pastebin.com/PfCb1i2U

**Comment by drtshock** [comment]
Make sure you have a permissions plugin.
