### ISSUE TITLE
Fancifull issue. 1.8.5 and above at least.

### ISSUE THREAD

**Issue by yoshee08** [drtshock/Factions#549]
Hey, 

We're getting a fancifull issue when we run the server with anything above 1.8.5
I have not tried 1.8.3, but as far as I can tell, 1.8.1 is the only version that I got to work.
spigot-1.8.1-20150304a.jar

Pastebin error:
http://pastebin.com/JhJknM5U

**Comment by Agazed** [comment]
Your factions version is months old... Hence why it only works with older bukkit versions.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
