### ISSUE TITLE
AutoLeaveProcess causing lag

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#551]
I noticed this in my timings while investigating lag spikes

https://gyazo.com/1d15e6e7285d276f73d27c3979e86382

**Comment by drtshock** [comment]
Can you give me your conf.json and the interval at which this was taken.

**Comment by PhanaticD** [comment]
conf.json http://pastebin.com/kVZ21gDC
Sample Time: 196.23s

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
