### ISSUE TITLE
Better faction colored tags.

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#552]
Hello Im here for suggest you to change the faction relationships name tags. I think that your name tags can be better and more cool.
This is your actual tag http://prntscr.com/8y433z and I want to have something like this http://prntscr.com/8y42z7 
It shouldnt be hard to implement and it'll very nice of your because being sincerious when you turn on the relation ships name tags and you have a lot of players in your server the tab become ugly as hell.

The second tag picture was made by using hcfactions that is a fork of your plugin, if you need I can send to you the .jar so you can see the code and implement this feature easier.

**Comment by drtshock** [comment]
You can already do this with the lang.yml.
