### ISSUE TITLE
More HCF dtr options

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#553]
Hello I'm back with more sugestions for your faction plugin. Now im talking about dtr.
Would be awesome if you implement some of this options to your plugin: http://prntscr.com/8y5zog
 I can pm you a fork of your plugin that has this options so you can implemente them faster and easier.

**Comment by MoeXIV** [comment]
That's a direct cut of text from the HCFactions config. Don't be cheap, if you want an HCF server buy the HCFactions version instead.

**Comment by drtshock** [comment]
Go get HCF.
