### ISSUE TITLE
Scoreboards for benzimmer123 and  drtshock

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#555]
Hello guys, Im using both of your plugins in my server and I have a small problem with scoreboards. Im using the scoreboard of factions and the relation-ships name tags but when one koth gets activated the koth scoreboard appears this is fine because my faction scoreboard is hidding while koth scoreboard is activated but the problem is that when the koth is caputared, the faction scoreboard and the relation-tags dont appear and you need to leave the server and join again for see it. Can you fix something in your plugins for have compatibles scoreboards?
This would be awesome.
Thanks for reading.
Alex.

**Comment by drtshock** [comment]
You should have KOTH reset the scoreboard once it's done then.

**Comment by alexsatellite** [comment]
what you mean?
