### ISSUE TITLE
Power loss disabled worlds ignoring warZonePowerLoss config

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#558]
I have in conf.json

"warZonePowerLoss": false,

This works fine in the main factions world. however, in another world where I have power loss completely disabled

  "worldsNoPowerLoss": [
    "factions_the_end",
    "factionshop"
  ],

I get this message: https://gyazo.com/d44dc7fecca33fd6869674b3ef027543

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
