### ISSUE TITLE
Neutral Territory Sethome

### ISSUE THREAD

**Issue by owensto** [drtshock/Factions#559]
So I try to make it so you can't set home in a faction's neutral territory, but for some reason this disabled setting homes in wilderness too.  I just want it so people can't /sethome in a neutral faction's territory, but they can set home anywhere in wilderness.

**Comment by owensto** [comment]
Still having this issue with no clue how to fix.

**Comment by owensto** [comment]
Still having this issue... Not sure what to do...

**Comment by owensto** [comment]
Still not sure what to do, players can't sethome in the wilderness.

**Comment by drtshock** [comment]
Duplicate of https://github.com/drtshock/Factions/issues/590
