### ISSUE TITLE
I cant format chat and deluxechat hoverisnt working

### ISSUE THREAD

**Issue by vladyslav300** [drtshock/Factions#561]
So i bought the Factions UUID and instaled it and my deluxe chat isnt realy doing the hover event or anything like that at all . i already have the place holder enabled in deluxe chat but still doesnt work and i cant remove the fac name before my prefix in the public chat plz help its urgent Thanks!

**Comment by drtshock** [comment]
sounds like a deluxchat issue?

**Comment by vladyslav300** [comment]
My msg i tryed to send in spigot:
Hey I would Like To Know How To Remove the **(facname) before my prefix and then name.
And My Deluxe Chat Isnt Working i Dont Know Why. plz help 

i have this plugins:
chat control pro 
deluxe chat
factions uuid
essentials chat 
protocol lib
trademe
spigot updater
pvpmenager (premium)
PermissionsEX
NoCheatPlus
Bar Ip and stuff

**Comment by vladyslav300** [comment]
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '%vault_groupprefix%&7'
    name_color: '&7'
    name: '%essentials_nickname%'
    suffix: '&7:&8 '
    chat_color: '&7'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '&b+&6&m----------------&r&b+'
    - '&b+           &d&lRank           &r&b+'
    - '&b+&6&m----------------&r&b+'
    - '          %vault_groupprefix%      '
    - '&b+&6&m----------------&r&b+'
   name_tooltip:
    - '&4&l&m=&7&l&m=&4&l&m=&7&l&m=&4&l&m=&7&l&m=&4&l&m=&7&l&m=&4&l&m=&7&l&m=&4&l&m=&7&l&m=&4&l&m=&7&l&m=&4&l&m=&7&l&m=&4&l&m='

**Comment by vladyslav300** [comment]
I am very anoyed -.-

**Comment by vladyslav300** [comment]
my deluxe chat stoped working after i instaled your plugin...

**Comment by vladyslav300** [comment]
i reinstaled the deluxe chat still not working ... well i guess nobody will help me -.-

**Comment by SekiAlpha** [comment]
dude
Disable the faction chat.....

**Comment by Calsam12** [comment]
i am also having this issue and i dont understand why...

**Comment by SekiAlpha** [comment]
Disable faction chat!
Go to conf.json and edit these settings
![image](https://cloud.githubusercontent.com/assets/12445848/12223087/a918b4e0-b79b-11e5-856a-366c5a3f5cab.png)

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
