### ISSUE TITLE
What this means?

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#562]
# Portal Creation
# Do you want to limit portal creation?

portals:
  limit: false # will disable the below check if set to false

Im looking for a option to dont let players generate portal from the nether inside of a base in the world for remove the portal raiding. Does this option fix it?

**Comment by DahFrozen** [comment]
I'm curious too.

**Comment by Kakifrucht** [comment]
Yes it does, however I do feel that it causes laggspikes.
It should block from portals being created in claimed faction land.
