### ISSUE TITLE
/f who issue

### ISSUE THREAD

**Issue by TheHeat361** [drtshock/Factions#565]
My friend types /f who, it says an internal error has occurred.
http://pastebin.com/kSB9iqey

**Comment by TheHeat361** [comment]
Using PaperSpigot 1.7.10-r01

**Comment by Gardiac** [comment]
You got zCore ? You need to install MCore not zCore..

**Comment by TheHeat361** [comment]
I don't have zCore or Mcore since I have FactionsUUID.

**Comment by drtshock** [comment]
Update spigot.
