### ISSUE TITLE
Kicking Offline Player

### ISSUE THREAD

**Issue by ryd4n** [drtshock/Factions#57]
Apparently my players cannot kick players in their faction that are offline, so I tried it for myself and I got the following message.

http://gyazo.com/551edde285059367d8bfbe057ae66069.png

If there is any fix to this, please inform me, thanks.

**Comment by RenegadeEagle** [comment]
I was able to do it just fine. Maybe something on your end?

**Comment by drtshock** [comment]
Still an issue @RydanMC?

**Comment by drtshock** [comment]
Can't reproduce.
