### ISSUE TITLE
/f powerboost is cumulative..

### ISSUE THREAD

**Issue by Kira07** [drtshock/Factions#570]
Hello,
I have an issue: the /F powerboost command is cumulative, if I do /f powerboost 25 twice to a faction they'll have +50 power etc..

It is a problem because I'm selling power packs, even if I limit them to 1 per player they can buy it a lot of times and become unraidable, the solution would be:
either making f powerboost not cumulative like it is with latest regular faction, either making a command to reset the powerboost bonus of a faction so we can make so that when someone buy the pack it resets the bonus and add 25 power.

Thanks in advance =)

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/commit/05cbf4cf5d9bc5829e6a3eda302cad32e092fa80

**Comment by Kakifrucht** [comment]
"but that existing functionality is stupid." haha.
But I agree, the way it is right now is much better and you should simply adapt.

**Comment by Kira07** [comment]
Not adding a command to reset powerboost IS completely stupid and lazy, if you are not willing to help your customers at least give me the source of the plugin so I can "adapt" as Kakifrcht said.

**Comment by Kakifrucht** [comment]
You want the source off the plugin? You are on Github...

While there is no reset you can manually set it back by giving negative powerboosts.

**Comment by Kira07** [comment]
He made the source public for a premium plugin ? ...

Yeah manually, but it's impossible to do it for all my customers who purchase this package.

**Comment by Kakifrucht** [comment]
Since you seem to be willing to change the code either way you could aswell easily hook into Factions and do it..

Also I see nothing wrong with open sourcing premium plugins. It's a fork either way.

**Comment by Kira07** [comment]
Well people can just take the code and compile it instead of buying the plugin..

**Comment by Kakifrucht** [comment]
Yes, but not all people are huge dickheads.
Honestly, this plugin was sold so much either way that it really is not difficult to find the resource somewhere either way, but otherwise if you run a for profit server and do not pay the devs that make parts of your server possible, than you should honestly not do any business at all, thats the lowest people can go. Otherwise if you do not make profit drtshock gives it out for free either way.

**Comment by Kira07** [comment]
Well I'd prefer if he didn't gave anything for free but had a minimum of respect for his customers, telling people who need help that they have to deal with it and figure out something by themselves is being a huge dickhead, especially if those people are your customers. 

Not only he isn't doing his job at all by being lazy like this towards tickets but he disrespected me.

If you treat your customers like this (he didn't even replied, he did a copy paste and closed the ticket) then you should honestly not do any business at all, thats the lowest people can go.

**Comment by Kakifrucht** [comment]
Well what do you expect from him exactly?

**Comment by Kira07** [comment]
To add a command that resets powerboost.
Like /f powerboost reset f name

**Comment by Kakifrucht** [comment]
Your ticket did not make that clear, at all.
You expressed it in a way, that made the impression that you thought that the cumulative powerboost is a mistake.
You could open another ticket, express your intent right and then you won't just get closed typically.

**Comment by drtshock** [comment]
All I said is the old functionality is stupid. 

Then you come and attack me for being nice and having the premium plugin still be open source? Clearly you didn't read any of the messages I put on Spigot, where the plugin is for sale, about why I put it for sale, why I left it open source, and why I still help out people that run servers that aren't for profit.
