### ISSUE TITLE
Change faction name, (how to disable the broadcast)

### ISSUE THREAD

**Issue by MrRoboo** [drtshock/Factions#571]
Hello,

Does someone know how to disable the broadcast message when someone changed their faction name because it's a way to bypass the mute punishment....

I'm talking about this message: http://prntscr.com/99k6xm

~vuurwerkPWN

**Comment by vuurwerkPWN** [comment]
Bump

**Comment by MrRoboo** [comment]
Can somebody help me?

**Comment by Kakifrucht** [comment]
You could add a cost to rename.

**Comment by MrRoboo** [comment]
Okay that's an option but isn't there a way to disable the broadcast?

**Comment by drtshock** [comment]
There is an option for description changes which I believe works for faction name changes as well. In the conf.json

**Comment by MrRoboo** [comment]
The option "broadcastDescriptionChanges": false,
but that option is already false in my factions plugin and it doesn't affect the name changes ;)

**Comment by drtshock** [comment]
Ah, then it looks like we need another option!

**Comment by MrRoboo** [comment]
Haha yep :P

**Comment by juIio** [comment]
I know this is old but... this has been added since https://github.com/drtshock/Factions/commit/8b6cf4fe8ca475355df44a8076d75225b6e900e9

It is now optional to broadcast tag changes.

**Comment by MrRoboo** [comment]
Okay I'll check it out

**Comment by TheDiamondYT1** [comment]
Do not disable this. It's a useful feature. Make it so you have a 1min time limit before executing it

**Comment by MrRoboo** [comment]
Sorry for my very late respond, but I'm talking about the command "/f tag" to change your faction name. this option can't be disabled in the config, people are abusing this command if they are muted so they kan still say something in the chat...

**Comment by MrRoboo** [comment]
I think @drtshock need to add an option to disable the broadcast messages when people are using "/f tag".

  "broadcastDescriptionChanges": false,
  "broadcastTagChanges": false,

Those options doesn't effect the "/f tag" broadcast

**Comment by JBlackbean** [comment]
Or just put /f tag in a plug in like booscooldown and have a limit of like 10 minutes for that comnand

**Comment by drtshock** [comment]
@JBlackbean has a good point for a temp fix, but there should be an option to disable this as well.

**Comment by mbax** [comment]
This only impacts members of the faction, who can have the spamming player removed if they are causing trouble.
