### ISSUE TITLE
Command to reset powerboost

### ISSUE THREAD

**Issue by Kira07** [drtshock/Factions#572]
I think it would be a good idea to add a command to reset the powerboost of a faction or player.

**Comment by Kakifrucht** [comment]
To make this intuitive and simple to add I would suggest to make /f powerboost [] name 0 reset it. Adding 0 makes no sense either way.

**Comment by drtshock** [comment]
I agree. Thanks for not calling me lazy (in this ticket).

**Comment by drtshock** [comment]
Wow, that was fast.
