### ISSUE TITLE
Allow Players To open chest in claimed territories 

### ISSUE THREAD

**Issue by Cqviezel** [drtshock/Factions#573]
How do I allow players to open chest in claimed territories

**Comment by Gardiac** [comment]
Well open "conf.json" and find this and mess with this how ever you want !
http://prntscr.com/9adrp9

**Comment by Cqviezel** [comment]
But whenever I restart the server it automatically goes back to normal

**Comment by Gardiac** [comment]
Contact me on sykpe I can help you "benjamin.dzelle69"

**Comment by drtshock** [comment]
Please keep contact through the issue tracker. We are not responsible for anything that goes on off of this issue tracker.
