### ISSUE TITLE
How to add "new line" to lang.yml

### ISSUE THREAD

**Issue by Gardiac** [drtshock/Factions#575]
Hey there can I add new line to lang.yml I've tried with "\n" but it didn't work uhmm some help ?!
http://prntscr.com/9adq8m

**Comment by Gardiac** [comment]
Anyone help , have a solution?

**Comment by DeriveMC** [comment]
Find where the no power loss message is and do the same as that.

**Comment by DeriveMC** [comment]
http://hastebin.com/urisigifaq.xml

**Comment by drtshock** [comment]
\n
