### ISSUE TITLE
invisibility potion bug with faction scoreboad true

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#578]
if you have the faction scoreboard in true and the name-tag prefixes and you drink a potion of invisibility while you're in a faction you get the effect but the rest of players still can see your (green, red, yellow) nick depending of your relation-ship with the other players. Can you fix this?
This doesnt happen if you're not in a faction!

**Comment by drtshock** [comment]
Yes.

**Comment by alexsatellite** [comment]
okay thanks :)
