### ISSUE TITLE
Variable for f show

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#580]
Hey can you add the variable [player-power]
so when you put the mouse over a name in /f show it display the persona pow of this player.

I ask this because the actual variable [power] it show the "Factions deaths until raidable value"

**Comment by drtshock** [comment]
Check the config.yml because this should be possible for the tool tips, just not the actual text afaik.

**Comment by nsporillo** [comment]
Based on the latest TagReplacer code found [here](https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/zcore/util/TagReplacer.java), 

both variables already exist and should represent what they're intended to represent.
