### ISSUE TITLE
Factionless Prefix Not Working

### ISSUE THREAD

**Issue by DeriveMC** [drtshock/Factions#583]
It appears that the factionless prefix is broken currently with FactionsUUID, but works correctly with HCFactions.

**Comment by juIio** [comment]
What exactly is the issue? When I added prefixes I had this result: http://prntscr.com/9e9nkx
This is my essentialschat format: format: '&6[[FACTION]&6] {DISPLAYNAME} » {MESSAGE}'

**Comment by DeriveMC** [comment]
This lang.yml formatting doesn't work - http://hastebin.com/xitelimori.vbs.

**Comment by drtshock** [comment]
I fixed that in the latest dev build.
