### ISSUE TITLE
Factions Truce Implementation

### ISSUE THREAD

**Issue by DeriveMC** [drtshock/Factions#584]
I was wondering if truce could or was planned ever be added as a relation since there are many options in the .conf and in the code?

**Comment by SekiAlpha** [comment]
From my knowledge truce is already a option. Have you tried the command before asking?

**Comment by juIio** [comment]
What would be the difference between truce and the current ally relations?

**Comment by DeriveMC** [comment]
An example would be where Allies would be allowed to do more things in your land like using levers, buttons, doors, ect for as truce cant same can go for commands where truce can sethomes and such. It also has to do with meaning where allies are more of a permanent ally faction where truces tend to be temporary.

**Comment by ghost** [comment]
Not to mention, there ARE traces of truces (Jeez, try saying that 10 times!) within the CmdChat code.

```
if (modeString != null) {
            modeString = modeString.toLowerCase();
        if (modeString.startsWith("p")) {
            modeTarget = ChatMode.PUBLIC;
        } else if (modeString.startsWith("a")) {
            modeTarget = ChatMode.ALLIANCE;
        } else if (modeString.startsWith("f")) {
            modeTarget = ChatMode.FACTION;
        } else if (modeString.startsWith("t")) {
            modeTarget = ChatMode.TRUCE;
        } else {
            msg(TL.COMMAND_CHAT_INVALIDMODE);
            return;
        }
    }
```

**Comment by drtshock** [comment]
Added fully in latest build.
