### ISSUE TITLE
FactionsUUID + EssentialsChat

### ISSUE THREAD

**Issue by RayVochi** [drtshock/Factions#588]
Hello, I am trying to configure FactionsUUID to work with EssentialsChat.

My ideal chat format is: [Faction] [PexGroup] PlayerName: message

but it is just giving me this: http://prntscr.com/9duksw

There is no other chat plugin interfering also, I am only using EssentialsChat for chat formatting. He is the full list of the plugins I have installed at the moment. http://prntscr.com/9dul3e

Essentials Config: http://hastebin.com/lajahedobu.coffee

FactionsUUID Config: http://hastebin.com/furudipego.coffee

FactionsUUID Conf: http://hastebin.com/esolexewon.sm

I really hope someone can help me with this, I've been struggling with this for the past few days.

Thank you

**Comment by drtshock** [comment]
You're only adding it for the group 'default'
