### ISSUE TITLE
about the suggestion that you closed

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#593]
I told you that because there a 0 public plugins about this but ok is your decision it show how bad are you that dont even try to improve your plugin with features. also you said you were going to fix my other problem that affect all players that use your plugin (the problem about invisibility potions) but I see 0 new updates.

**Comment by alexsatellite** [comment]
Well I was wrong.  I found it

**Comment by drtshock** [comment]
Thanks for the lecture about how I was right.
