### ISSUE TITLE
Faction warp password

### ISSUE THREAD

**Issue by DahFrozen** [drtshock/Factions#594]
Hi, 

Is it possible to add support for password in faction warps so you can lock warps to players who only know the password.

Thanks,
Frozon.

**Comment by juIio** [comment]
I didn't know this was not a thing yet. I will take a look at it in a few days when I'm back home. Thanks for your report.

**Comment by DahFrozen** [comment]
Awesome :)

**Comment by Tsyrac** [comment]
Nice, this would be cool thing to have

**Comment by drtshock** [comment]
I personally won't be adding this. I don't like the idea of storing passwords and I don't see factions as something that you need passwords within. We already have the chunk ownership.

**Comment by StillDupeGlitchLmao** [comment]
Yeah well most facs invite new players for power, and some like to restrict some from the warp - /f chunk isn't exactly a easy way of teleporting to certain places in the map and /f warp is
