### ISSUE TITLE
Renaming Warzone or Safezone.

### ISSUE THREAD

**Issue by DahFrozen** [drtshock/Factions#596]
Hi,

Is it possible to rename the tags of Warzone or Safezone? I've done so in the factions.json, but the tags are not updating :(.

  },
  "-2": {
    "id": "-2",
    "peacefulExplosionsEnabled": false,
    "permanent": false,
    "tag": "§4Warz§5oone",
    "description": "Not the safest place to be.",
    "open": false,
    "peaceful": false,
    "foundedDate": 1451134575271,
    "money": 0.0,
    "powerBoost": 0.0,
    "relationWish": {},
    "claimOwnership": {},
    "invites": [],
    "announcements": {},
    "warps": {},
    "lastDeath": 0
  }

**Comment by drtshock** [comment]
Don't touch the factions.json, that is a save file that should only be edited by the plugin.

You can change the tags in the lang.yml file :)
