### ISSUE TITLE
/f who texting problems 

### ISSUE THREAD

**Issue by remibarna** [drtshock/Factions#597]
I have a problem in the config, https://gyazo.com/e78da8d56f196d1d4717ace7f502d0b7  and in chat it looks like this https://gyazo.com/c4d5c3395324fa9fe87556d587b78a2b

the online,offline and enemy and allies are all white. When I color coded them in the config

**Comment by drtshock** [comment]
Type /f version and show me the output.

**Comment by remibarna** [comment]
v1.6.9.5-U0.1.18-b298

**Comment by remibarna** [comment]
BUMP

**Comment by nsporillo** [comment]
I believe this was an issue with an older version of the f show features ported over from HCF. 

I'm not sure if v1.6.9.5-U0.1.18-b298 is the latest or not though.

**Comment by remibarna** [comment]
Thanks for the info. but I would very much like the author to fix this or tell me what it is in doing wrong

**Comment by remibarna** [comment]
BUMP

**Comment by TheDiamondYT1** [comment]
Nice faction name xD

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
