### ISSUE TITLE
Factions - Dynmap and BattleTags!

### ISSUE THREAD

**Issue by Educationals** [drtshock/Factions#598]
Hello people,
I bought the plugin FactionsUUID version
"Factions v.1.6.9.5 -U1.18-b298

I need dynmapFactions and BattleTags for this version, please you do not have anyone working plugin?

**Comment by Educationals** [comment]
Okay i have DYNMAP in Factions. and please help me with Config dynmap, 
when set to "dynmapDefaultStyle" so I saved well by the SafeZone and Warzone how to do each one separately please.

  "dynmapUse": true,
  "dynmapLayerName": "Factions",
  "dynmapLayerVisible": true,
  "dynmapLayerPriority": 2,
  "dynmapLayerMinimumZoom": 0,
  "dynmapDescription": "<div class=\"infowindow\">\n<span style=\"font-weight: bold; font-size: 150%;\">%name%</span><br>\n<span style=\"font-style: italic; font-size: 110%;\">%description%</span><br><br>\n<span style=\"font-weight: bold;\">Leader:</span> %players.leader%<br>\n<span style=\"font-weight: bold;\">Admins:</span> %players.admins.count%<br>\n<span style=\"font-weight: bold;\">Moderators:</span> %players.moderators.count%<br>\n<span style=\"font-weight: bold;\">Members:</span> %players.normals.count%<br>\n<span style=\"font-weight: bold;\">TOTAL:</span> %players.count%<br>\n</br>\n<span style=\"font-weight: bold;\">Bank:</span> %money%<br>\n<br>\n</div>",
  "dynmapDescriptionMoney": false,
  "dynmapVisibilityByFaction": true,
  "dynmapVisibleFactions": [],
  "dynmapHiddenFactions": [],
  "dynmapDefaultStyle": {
    "lineColor": "#CC0000",
    "lineOpacity": 0.8,
    "lineWeight": 3,
    "fillColor": "#FF0000",
    "fillOpacity": 0.35,
    "homeMarker": "greenflag",
    "boost": false
  },
  "dynmapFactionStyles": {
    "SafeZone": {
      "lineColor": "#CC0000",
      "fillColor": "#FF8000",
      "boost": false
    },
    "WarZone": {
      "lineColor": "#CC0000",
      "fillColor": "#666666",
      "boost": false
    }
  },

**Comment by Educationals** [comment]
nameTag,  Tabtag factions   #Fixed

**Comment by drtshock** [comment]
Battletag isn't needed as it's already built in. And it looks like you already found the config for the warzone and safezone.

**Comment by Educationals** [comment]
yes but the config on dynmapu does not work,
I wrote that when I set Defaultstyle so it is also set to SafeZone a warzone to do for everyone else to make it work?

**Comment by Educationals** [comment]
help me

**Comment by amgno** [comment]
How you do for Prefix with faction name and realtion color????
