### ISSUE TITLE
Essentials and Factions Tag Issue

### ISSUE THREAD

**Issue by systemacc** [drtshock/Factions#599]
When trying to disable the colormember option in the factions > conf.json file ( http://prntscr.com/9jnatx )
to get the faction tag color per group in essentials, I get his  in game --> http://prntscr.com/9jnbiy and this is my essentials chat format ->> http://prntscr.com/9jnbtz

is there a way to disable the colormembers option so I can create different color variations per group? I think there is, I see servers using this exact plugin and is doing the same thing I'm having issue with.
please help!

**Comment by drtshock** [comment]
what do you mean different color variations per group? of what?

**Comment by systemacc** [comment]
I cannot make different color factions tag for different groups. I tried doing color through essentials using the [FACTION] placeholder but I cannot change the faction name color per each group. then I went into the factions conf.json and tried disabling the "colorMember=" but when I do that, the faction turns into [null**Raiders]

**Comment by systemacc** [comment]
bump

**Comment by drtshock** [comment]
The faction tag is colored based on relation.
