### ISSUE TITLE
How to allow people to use enchanting tables, anvils and chests in warzone

### ISSUE THREAD

**Issue by iAmGolem** [drtshock/Factions#600]
How do I allow people to use enchanting tables, anvils and chests in Warzone?

**Comment by drtshock** [comment]
denyUse false

**Comment by iAmGolem** [comment]
Is it in the lang file? I can't find it in the config file.

**Comment by iAmGolem** [comment]
Could you just send me the specific part of the config?

**Comment by drtshock** [comment]
conf.json
