### ISSUE TITLE
Essentials and Factions colored tag per user

### ISSUE THREAD

**Issue by systemacc** [drtshock/Factions#601]
Once again, I am sending in a ticket on an issue I am having with your Factions plugin. What I am trying to do is make it so Donors, Admins and Moderators have different colored Faction tags in the PUBLIC chat. I know it is possible because other servers use your plugin and I have verified with owners. They refuse to help me any further though. Heres a example of what I need. http://prntscr.com/9k14fm
See? Can you please assist me. I would really appreciate it, thank you!

**Comment by drtshock** [comment]
Why don't you ask them?

**Comment by systemacc** [comment]
Already tried, they just be extremely rude. I understand that you are very busy but I found a way to resolve the problem I am getting. its in the factions conf.json file, the "colorMember=GREEN," 

is there a way to set that to false? so I can use my own format through essentials.

**Comment by drtshock** [comment]
I don't believe so. We always color based on relation if you are using our tags in chat.

**Comment by systemacc** [comment]
Do you think you can add a feature to disable that or where I can setup different color faction tags for public chat through essentials? I really need something like this. Please let me know. Thanks

**Comment by systemacc** [comment]
http://prntscr.com/9k3kiv That's the default color for Factions, When I replace the green text with nothing, I get the color I input for my Faction tag in the group I specify in essentials chat but then it just [Null**Fun]

fun represents the faction name. although the Null**Fun shows the color I put in essentials chat

**Comment by systemacc** [comment]
i just want players to have their own colored faction tag that matches their chat format

**Comment by systemacc** [comment]
i think you really need to implement a feature that let us do this

**Comment by drtshock** [comment]
Faction tags match relations. That's not going to be changed. They could possibly be using a custom chat plugin.

**Comment by SekiAlpha** [comment]
Just change the chat format in essentials or dchat.
