### ISSUE TITLE
How do I "denyUse" false?

### ISSUE THREAD

**Issue by iAmGolem** [drtshock/Factions#603]
How to denyUse false for Warzone.
Is it in the configuration?
I can't find it anywhere!

**Comment by SnakeDaoust1232** [comment]
For enemies, wilderness? etc What relation?

**Comment by iAmGolem** [comment]
For Warzone.

**Comment by SnakeDaoust1232** [comment]
1) https://gyazo.com/0f46c0d4df8eb93e29d972d45e879f61
2) https://gyazo.com/8347bc81917c7b6b32af8041283834d8

**Comment by iAmGolem** [comment]
No I meant in which file? My config file looks nothing like that.

**Comment by iAmGolem** [comment]
Could you copy and paste the config file?

**Comment by drtshock** [comment]
We told you the options. Go do it yourself :)

**Comment by iAmGolem** [comment]
You guys don't get it do you? it's not there .-.
No where in the config file.

**Comment by drtshock** [comment]
He literally screenshotted the option for you.
