### ISSUE TITLE
FactionsUUID - dynmap dont work S/F

### ISSUE THREAD

**Issue by Educationals** [drtshock/Factions#604]
I have a problem with changing colors for Warzone and SafeZone, so I know where the config but I do not know how it got changed for each faction got good or bad color, and not. Please help! simply factions are all the same color.  
http://imgur.com/tNu9It2 <<-- check my conf.
http://82.208.17.11:30719/ <<-- dynmap

and also do not see the flag f home

**Comment by Gardiac** [comment]
I'd like to ask you how did you make your world on web?

**Comment by Educationals** [comment]
http://crusaders.cz/mapa.php   ?

**Comment by Gardiac** [comment]
Yes but how did you put world on website?

**Comment by drtshock** [comment]
Looks like someone else is having the same issue. Would like a conf.json and startup log pasted in pastebin (not a screenshot of them) to dig into further.

**Comment by morsay** [comment]
Config: http://pastebin.com/txNHMw4X

Im not the owner of the server so i cant give u the log right now because i cant restart the server i give u very soon.

**Comment by drtshock** [comment]
thanks, just let me know when

**Comment by morsay** [comment]
http://pastebin.com/vrx6bwVH

**Comment by drtshock** [comment]
the full startup log..

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
