### ISSUE TITLE
Neutral deny commands not working properly?

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#605]
Hey I'm trying to deny /sethome and /esethome in neutral claims but it should not affect wilderness territory right? because you have a specific option for wilderness:  "wildernessDenyCommands": [],
so If I deny the commands here: "territoryNeutralDenyCommands": []  They cant use /sethome in wilderness so plz what can I do? is a plugin problem or I need to do other thing for fix this.
If it's a problem of your plugin can you fix this fast plz this is so annoying.

**Comment by Educationals** [comment]
I have the same problem, please solve.

**Comment by alexsatellite** [comment]
This bug is important and it should be already fixed. C'mon.....  itzmonkey already found the problem.

**Comment by Educationals** [comment]
How fix??

**Comment by alexsatellite** [comment]
You can install the version of august, but I cant because I'm using addons which needs the latest version to work.

**Comment by drtshock** [comment]
Duplicate of https://github.com/drtshock/Factions/issues/590
