### ISSUE TITLE
Suggestion [Homes]

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#606]
Hello, I saw in the factionplus (2012 version, it doesnt have it now) and other servers that if you have a home set in a claimed territory you can't teleport to it if this claimed by other faction. so if you try to use /home <name> it says you cant teleport to x y z because this is claimed by other factions.or something like this. It should let you use /home <name> if the territory is claimed by your faction or you have access to it.
I searched for plugins to do this but I didnt find one so if you wont add this feautre because there is something already  can you link it to me?

**Comment by alexsatellite** [comment]
?Bump

**Comment by alexsatellite** [comment]
already made it by myself. you can close.

**Comment by drtshock** [comment]
That was a custom version I made for furiouspvp.
