### ISSUE TITLE
/f sb not working.

### ISSUE THREAD

**Issue by rwsender** [drtshock/Factions#61]
this returns 'you now have scoreboards set to false' but I am unable to set them to true.

**Comment by lerqz** [comment]
This also isn't working for me.

**Comment by drtshock** [comment]
What does your playerScoreboardToggle.yml look like?

**Comment by rwsender** [comment]
empty..havent changed it

**Comment by drtshock** [comment]
Typing /f sb doesn't put values in there? :O
Are there any errors in console when you type /f sb?

**Comment by rwsender** [comment]
nothing in the console, just the ingame message from the first post!

**Comment by drtshock** [comment]
The file is completely empty though? Doesn't even have the defaults like in https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/playerBoardToggle.yml?

**Comment by rwsender** [comment]
http://puu.sh/cdzJS/8a9ace828b.png

**Comment by drtshock** [comment]
ohhh i see why. silly mistake that i never saw before :(

**Comment by drtshock** [comment]
Finally fixed.
