### ISSUE TITLE
How to check for claim?

### ISSUE THREAD

**Issue by TheNewTao** [drtshock/Factions#610]
I was wondering how to check for the claim a player is currently standing on? I want to check if the player is a Wilderness claim, I created a FPlayer instance and I saw that there is no wilderness territorial method. I see the isInNeutralTerritory() which is the closest thing to what I need, but it doesn't work because it could be other factions other than Wilderness, does anyone how to use this?

**Comment by Educationals** [comment]
What is your version of the factions?

If you have a problem with the territory players, if you turn off the Scoreboard visitation faction in the scoreboard should you do then listing the wilderness

**Comment by grrocks** [comment]
Get the player location create a FLocation and carry on from there
