### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by KristianHansen94** [drtshock/Factions#614]
http://pastebin.com/TrpJb84s  factions config

http://pastebin.com/Dt3eRcnM  error log

When I type in /f who [factionname], i get an internal server error. I'm using the latest version of spigot.

**Comment by DeriveMC** [comment]
Try updating to the newest version of factions (1.6.9.5-U0.1.18-b302) as well as one of you message formatting may be broken?

**Comment by drtshock** [comment]
You're using a leaked build (or just happen to be on the same version that was leaked). Update.

**Comment by KristianHansen94** [comment]
Updated and it works now thank you!
