### ISSUE TITLE
Edit some commands [factionsuuid]

### ISSUE THREAD

**Issue by medericpdev** [drtshock/Factions#617]
Hello, I just bought your plugin that works very well so thank you ! I'm trying to translate the plugin in French , but I wanted ( if possible ) change commands for our future server. Example , I want to replace the / f show with /a voir. How can I do because I just put the sources of plugins on Eclipse but the changes I've made have not worked . So I need your help to change some commands plugins. If you want I can give you the translation in french plugins. Thank you in advance for your help and good day :)

Sorry for my bad English ^^

**Comment by drtshock** [comment]
You can change the base command in the conf.json, but the aliases can't be changed.
