### ISSUE TITLE
FactionsUUID /f invite [BUG]

### ISSUE THREAD

**Issue by IReportBugz** [drtshock/Factions#621]
This is a FactionsUUID bug, this bug says A internal error has occurred, in red. I tried reinstalling it nothing worked, is it me? Or the plugin.

**Comment by IReportBugz** [comment]
Heres what it says

Your are running Factions v1.6.9.5-U0.1.14
Translation: en_US(English,US) State: complete
Translation contributors: misc
Responsible for translation: misc

**Comment by Kakifrucht** [comment]
You are about 4 versions behind.

**Comment by IReportBugz** [comment]
So i have to pay $15 for the latest version :(

**Comment by juIio** [comment]
@IReportBugz The plugin itself costs $15 with lifetime updates, this is why you're not supposed to download plugins from leak sites (If that's what you did).

**Comment by IReportBugz** [comment]
Well a friend gave it xD So he must of lied, but honestly it's alright xD i couldn't care less.

**Comment by drtshock** [comment]
lol
