### ISSUE TITLE
Colors of the enemy API

### ISSUE THREAD

**Issue by kangarko** [drtshock/Factions#626]
Hello,

one of users of my plugin has requested to display 'colors of the enemy etc in the placeholder for FactionsUUID'. Especially following colors:

> "colorMember": "GREEN",
> "colorAlly": "LIGHT_PURPLE",
> "colorTruce": "DARK_PURPLE",
> "colorNeutral": "WHITE",
> "colorEnemy": "RED",
> "colorPeaceful": "GOLD",
> "colorWar": "DARK_RED",

I have try to find an API but without a luck, so I am asking if it's possible. 
Thank you.

**Comment by drtshock** [comment]
i'm not sure what you're asking

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
