### ISSUE TITLE
How to support FactionsUUID in a Faction add-on?

### ISSUE THREAD

**Issue by KablooieKablam** [drtshock/Factions#629]
I develop a small Factions add-on and a lot of my users are requesting that I "add support for FactionsUUID." How can I do this? What are the differences?

**Comment by minecrafter** [comment]
FactionsUUID is an updated fork of Factions 1.6.9.5, so the API differs between canonical Factions and FactionsUUID. We need more detail to be able to know what exactly you need.

**Comment by KablooieKablam** [comment]
Certainly. So far the only bug my users have reported is java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/MPlayer

I assume FactionsUUID doesn't use an MPlayer class. How do you get a Faction from a Player with your API, and from that the Faction ID and online players?

**Comment by minecrafter** [comment]
You want to use `FPlayers`

**Comment by KablooieKablam** [comment]
Thank you, Is it possible to obtain a copy of the .jar for development purposes? I've been trying to compile one from the GitHub but it appears a ton of the maven dependencies are missing and I can't track them all down.

**Comment by NotableOsprey92** [comment]
I can give u a jar as long as u dont use for a server with a public sever (servers that monitise it for money)

skype: NotableOsprey92

**Comment by drtshock** [comment]
If you are having compile issues then please make a new ticket.
