### ISSUE TITLE
New visual representation of chunks *Feature Request

### ISSUE THREAD

**Issue by SekiAlpha** [drtshock/Factions#630]
Hey @drtshock,

I would like to represent chunks with particle instead of blocks. This could possible cause for less lag for players and it could be a toggleable command.

For example instead of chunk representations looking like this:
![2016-02-03_18 22 24](https://cloud.githubusercontent.com/assets/12445848/12800516/95f4d4c8-caa3-11e5-8a06-7cf75e10db2f.png)

It would look like this:
![2016-02-03_18 25 32](https://cloud.githubusercontent.com/assets/12445848/12800524/aa589198-caa3-11e5-99b9-4c4a13867aa5.png)

Thanks,
Sean

**Comment by drtshock** [comment]
There's /f sc

**Comment by SekiAlpha** [comment]
@drtshock Right I don't think you understand. I want you to change the "/f sc" command. If you want check out what massive craft did with the /f sc command in their latest version of factions.

**Comment by drtshock** [comment]
Can you tell me?

**Comment by SekiAlpha** [comment]
@drtshock I'm sorry, I'm kinda bad at explaining things.

So I will try again.

Your plugin current plugin represents chunks by placing glass and glowstone blocks at the corners of the chunks. This is fine but this also causes lag for players with less powerful pcs and this implementation does not allow these markers to stay if the player moved.

What I propose is to mark chunks with a particle effect rather than blocks. This would allow players to move while using the "/f sc" and it would be less laggy. Currently, Massivecrafts' Faction plugin does this and has a very nice implementation of it.

If you want to see for yourself please log into a server that uses Massivecrafts' version of factions or use a test server and try the plugin out.

Thank you!

**Comment by Kakifrucht** [comment]
Sounds really good, the current implementation of /f sc is not very good imo, using particles is a very nice idea.

**Comment by SekiAlpha** [comment]
@drtshock can you please reopen this thread?

**Comment by drtshock** [comment]
So using particles instead of blocks for /f sc? I guess.

**Comment by SekiAlpha** [comment]
@drtshock yes. Thank you so much!

**Comment by SekiAlpha** [comment]
*bump
Not sure if this is allowed but I think this feature request would make your plugin better for players.

**Comment by drtshock** [comment]
Added
