### ISSUE TITLE
FactionsUUID chat

### ISSUE THREAD

**Issue by xGodzillaPvP** [drtshock/Factions#631]
So I bought this plugin and the chat isn't working. Before when I used massivecraft factions it worked perfectly with chatex. I've also tested other plugins like chatcontrol and it doesn't work. If I remove the plugin from the plugins folder the chat works perfectly again. Can anyone please help me?

**Comment by drtshock** [comment]
what doesn't work

**Comment by connorlurring** [comment]
May be fixed by #640

**Comment by xGodzillaPvP** [comment]
My chatplugin (Chatex) gets completely ignored. The only thing that shows
up is the faction prefix. I've tried 3 other chatplugins too.

fredag 12 februari 2016 skrev Trent Hensler notifications@github.com:

**Comment by SekiAlpha** [comment]
Disable faction chat! Factions has it's own chat system so try and disable faction chat in the config. This is a known issue that people have your could have just googled it. If that is not the issue then I am sorry but it's kinda annoying when people ask for help, make a big deal of it when it could have been solved with a google search.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
