### ISSUE TITLE
Factions UUID v1.6.9.5-U0.1.14 (/f invite error)

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#632]
Hello Drtshock
When ever any of my players do /f invite (player) they can a message saying " An internal error occurred while attempting to perform this command " and i have given them the faction.invite permission and still nothing here is the console error > http://www.heypasteit.com/clip/2G10 > and here are my plugins > https://gyazo.com/e41c572beacc6aa30dd319f1619c0be9 < PLEASE GET BACK TO ME ASAP AS THIS IS REALLY IMPORTANT TO MY SERVER! BTW it never used to do this just 1 day one of my players old me it wasn't working!

**Comment by drtshock** [comment]
update spigot
