### ISSUE TITLE
PainBuild Option Not Working

### ISSUE THREAD

**Issue by WFloydBoy** [drtshock/Factions#633]
I reported this issue some time ago for the HCFactions plugin regarding PainBuild option not entirely working as intended and thus allowing pressure plates to serve as "landmines." It was fixed in HCFactions but I guess that fix wasn't implemented to FactionsUUID. These are my PainBuild config options:

  "actionDeniedPainAmount": 0,
  "territoryPainBuild": false,
  "territoryPainBuildWhenOffline": false,
  "territoryEnemyPainBuild": false,
  "territoryEnemyPainBuildWhenOffline": false,
  "territoryAllyPainBuild": false,
  "territoryAllyPainBuildWhenOffline": false,
  "territoryTrucePainBuild": false,
  "territoryTrucePainBuildWhenOffline": false,
  "ownedAreaPainBuild": false,

And a display of what happens if you dare stand on one of these pressure plates https://gyazo.com/a549f8d1fd8c82ffd884c7e13746a3dc 

Faction Version: https://gyazo.com/4d39562cfb3f167d4e7952b30209625e

**Comment by drtshock** [comment]
@nsporillo can you pull from downstream? :)

**Comment by WFloydBoy** [comment]
Saw this resource updated in January on Spigot. Hope to see this fix be made in the future still

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
