### ISSUE TITLE
[BUG] Factions UUIDs are shown in Essentials's /baltop

### ISSUE THREAD

**Issue by xph11** [drtshock/Factions#634]
I disabled the factions economy feature on my server, but after some time it starting to show factions UUIDs in /baltop of the Essentials plugin anyway, even if the factions economy is disabled.

I saw MCFactions got updated with a bugfix for this issue, maybe you can update FactionsUUID with that bugfix?

**Comment by drtshock** [comment]
https://github.com/MassiveCraft/Factions/commit/f77750fc912c21010a11d8c31004b4580b977475#diff-a8371da2e46afd9ce12cbd07a47a268bR70 reference of what massivecraft did.

**Comment by xph11** [comment]
@drtshock 
I'm not a dev so It's not really helping me xD

Can you maybe fix it with an update? :P

**Comment by drtshock** [comment]
I don't have time right now but I wanted to leave a note of what massivecraft did so we have a reference for when I get time / if anyone else picks it up.

**Comment by 1mRAAAH** [comment]
Well Since it seems only idiots comment on spigot...
When do you expect to fix it? Like you said: it's not breaking the server, but it looks very sloppy and amaturistic.
Hope you fix it within a few (2?) days.
Thanks

**Comment by drtshock** [comment]
lol? Thanks for insulting me for legacy code that was in the project before I forked it. That really goes a long way in getting me to fix this quicker.

**Comment by 1mRAAAH** [comment]
I didn't insult you? And If I did, not my intention tbh.
The fact it looks sloppy says nothin about nor the plugin, says something about OUR baltop...

**Comment by Bear53** [comment]
There should be something in the config for this to disable the economy feature. It does not show up for me. Try editing in the factions.json or something I forgot the name the factions balance because maybe they got it before you disabled it. This should be a easy feature for you if you read the files

**Comment by connorlurring** [comment]
Do we know why this is happening, any inkling of the classes involved? @drtshock I could submit a PR with some more information seeing as @1mRAAAH is being so unreasonable about the whole situation.

**Comment by drtshock** [comment]
I haven't had much time to look into it. I just know what massivecraft did to apparently fix it on their branch (linked above). Any insight / code from anyone would be greatly appreciated.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
