### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by SunyEnthu** [drtshock/Factions#635]
Hellow,
so im Using factions UUID latest
and im getting this error
`java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/Factionat uk.co.umbaska.Managers.Enums.runRegister(Enums.java:106) ~[?:?]at uk.co.umbaska.Managers.Register.registerAll(Register.java:60) ~[?:?]at uk.co.umbaska.Main.onEnable(Main.java:201) ~[?:?]at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.entity.Factionat java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_95]at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_95]at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_95]at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_95]at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-3f3c65f]at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_95]at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_95]... 14 more`

im currently using spigot 1.8.8 and java 8

**Comment by drtshock** [comment]
Your other plugin is built against massivecraft's factions, not factionsuuid.
