### ISSUE TITLE
Chatspy not disabling after taking away permission

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#636]
If you enable chatspy mode while having a permission, it will stay that way even after removal. You cannot toggle it via admin command either.

**Comment by drtshock** [comment]
How do you propose a fix?

**Comment by Lord-Cuddles** [comment]
perhaps when the player relogs it checks to see whether they have the permission, and if they don't - turns it off automatically.

**Comment by Kakifrucht** [comment]
Yes, this is a quite annoying issue as you would have to manually edit the json db.
