### ISSUE TITLE
plugin economy

### ISSUE THREAD

**Issue by medericpdev** [drtshock/Factions#637]
Hello, I want to use the variable {player-balance}  in my f show except that it does not work "no balance" then I want to know which plugin to use the economy. I use vault 1.4.1 -b436 and I use craftconomy 3

thanks !

**Comment by drtshock** [comment]
Can you paste your startup log in a pastebin?

**Comment by medericpdev** [comment]
http://pastebin.com/db6z1MH7

Here is a picture of the problem in game:  http://www.noelshack.com/2016-07-1455649065-aie.png

**Comment by drtshock** [comment]
[19:45:41] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.18-b302] NOTE: Economy is disabled. You can enable it with the command: f config econEnabled true

Turn economy on :)

**Comment by medericpdev** [comment]
Thank you for your help but it does not solve my problem. I already have a economy plugin and I not want to have the economy of the faction. I saw a server that has disabled the economy of faction that has successfully display player's money when making / f show and he uses crafteconomy3

**Comment by drtshock** [comment]
Don't give people permission for /f bank then.

**Comment by medericpdev** [comment]
Ok thank :+1:
