### ISSUE TITLE
Factions Config not saving

### ISSUE THREAD

**Issue by EdasOG** [drtshock/Factions#639]
Now i have a problem. I am currently running paper spigot 1.8.8 (but 1.8 works too). Now i am been trying to configure factions however when i restart the server all the changes i made in the config/conf havent saved. I made sure i saved the file eachtime but after each restart it keeps resetting to the default config. Any ideas why this is occuring? I am using the latest version of factions
Any help would be appreciated!
Thanks :)

**Comment by drtshock** [comment]
Sounds like you're having an issue with saving files.

**Comment by EdasOG** [comment]
So what shall i do?

**Comment by drtshock** [comment]
Figure out how to save files. You're probably not actually saving it to disk. Make sure you do that while the server is completely off before you start it.
