### ISSUE TITLE
prefixes and options.

### ISSUE THREAD

**Issue by alexsatellite** [drtshock/Factions#641]
Hey I wanted to know if you can change that you have to turn on the scoreboard if you want the prefixes in the nametags. This is annoying because the scoreboard is very limited and if you want to use a better scoreboard you cant have the feature of the nametags.

I mean. If you want the nametags, you have to enable "default-enabled" and "default-prefixes", so my sugestion is that if you dont want the scoreboard but you want the nametags you only have to enable "default-prefixes"

**Comment by drtshock** [comment]
unfortunately no since the prefixes are scoreboards.
