### ISSUE TITLE
Newest version but still not support \n (newline)

### ISSUE THREAD

**Issue by Gardiac** [drtshock/Factions#644]
@drtshock What is wrong here? http://prntscr.com/a7a957

**Comment by drtshock** [comment]
idk, i didn't change anything there O_O

**Comment by drtshock** [comment]
Can you show me that line in your messages file?

**Comment by Gardiac** [comment]
http://prntscr.com/a7fli9 even if you update it , my account got hacked on spigot ...

**Comment by TheDiamondYT1** [comment]
Why is it not hiding the <code>\n</code>?

**Comment by Gardiac** [comment]
I found what is it ! @drtshock the \n isn't good you have to use /n/
