### ISSUE TITLE
Commands are Case-Sensative

### ISSUE THREAD

**Issue by juIio** [drtshock/Factions#646]
Commands should be able to be executed without the need of worrying about case. This PR fixes the issue https://github.com/drtshock/Factions/pull/645

**Comment by Gardiac** [comment]
Yea thats little bit annoying but Im pretty sure that, this is too much for trent like he would need to add "if(cmd.getname().equalsignorecase" etc to every command in code aswell I think he would need to re-edit it...

**Comment by juIio** [comment]
Look at my PR, it fixes this issue in less than one line of code.

**Comment by gsand** [comment]
fixed in https://github.com/drtshock/Factions/pull/645

**Comment by Gardiac** [comment]
@gsand does that mean the new update of FactionsUUID will have fixed case sens?
