### ISSUE TITLE
Faction Balance 

### ISSUE THREAD

**Issue by Abeoji** [drtshock/Factions#648]
So 
# \- {faction-balance}      : Faction bank balance

This shows faction bank balance in f show etc..
can you make it so when we do /f who
EXAMPLE:
FactionName
Balance: 100,000
So what this would do is total every members essentials eco balance and show it in the desc of the faction, would this be possible to do?  because it confuses me faction balance I thought it already added all of the members balance's together for a variable to show the total money they combine together  maybe make it 
# \- {faction-ess-balance}      : Faction's Essential's Eco Balance Totaled

Many servers that I have talked to were confused about this.

**Comment by Titaxiam** [comment]
yeah i also need this ;p

**Comment by mbax** [comment]
This has existed for a little while now, forgot to close.
