### ISSUE TITLE
/f autoclaim Bug

### ISSUE THREAD

**Issue by Thomastremix307** [drtshock/Factions#65]
Hello there,
When I do /f autoclaim warzone or safezone the message comes up ""you must be moderator to claim land" and I have this problem for quite sometime I'm currenly using version v1.6.9.5-uo.1.4 ,please try and fix this bug asap ,Thanks for reading.

**Comment by drtshock** [comment]
even with /f bypass and the warzone claim permission.

**Comment by Thomastremix307** [comment]
Yes

**Comment by Thomastremix307** [comment]
factions.managewarzone correct ?

**Comment by squidicuzz** [comment]
Do you have the "factions.autoclaim" permission node included as well?

**Comment by Thomastremix307** [comment]
yep ,I reset the language file and it seem to of fixed it.
