### ISSUE TITLE
F Bank

### ISSUE THREAD

**Issue by SprinkleDonuts** [drtshock/Factions#653]
Hey how much would you charge for there to be a /f bank that opens up a double chest that only the moderators of the faction and the owner can edit and it says at the top of amount of money everyone in the faction put together has ? (FactionsUUID)

**Comment by drtshock** [comment]
eh

**Comment by SprinkleDonuts** [comment]
Yeah responding Eh helps? What does that mean...? @drtshock

**Comment by drtshock** [comment]
that it sounds like something that would be nice but i doubt it will get added.

**Comment by SprinkleDonuts** [comment]
@drtshock  And why is that? I put alot of time into thinking of ideas for your plugin and I quite alot of other ones,  but is my main priorty... I'm willing to pay for you to just add this for me, but it'd be cool if you added it for everyone

**Comment by mbax** [comment]
This ismostly covered by the `/f vault` command
