### ISSUE TITLE
f owner 

### ISSUE THREAD

**Issue by 69Gamerss** [drtshock/Factions#654]
i have a problem where f owner is not working properly , when people use f owner , it shows as an ownered , but people in the faction can still mine / use it , can some one help me ?
Thanks !

**Comment by drtshock** [comment]
which version, spigot version, and where did you buy it?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
