### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by thegiantwither** [drtshock/Factions#657]
How do I enable the Scoreboard? 
Cause can't find it can you guys send me a config? so I can copy - paste?

**Comment by gsand** [comment]
If you have other plugins that mess with scoreboards, it might not display right.

If you don't, you can try typing `/f sb` to turn it on.

**Comment by thegiantwither** [comment]
No I mean the faction scoreboard is disabled when I do /f sb it says 'You can't toggle scoreboards while they are disabled' .

**Comment by drtshock** [comment]
config.yml

**Comment by drtshock** [comment]
config.yml

**Comment by thegiantwither** [comment]
But where ? can you send me a screenshot ?

**Comment by drtshock** [comment]
default-enabled under the scoreboard section..
