### ISSUE TITLE
/f invite error

### ISSUE THREAD

**Issue by Titaxiam** [drtshock/Factions#658]
Whenever i type the command /f invite it says "internal error occurred while performing this command" But the weird part is that it invites the player... but the player doesn't receive a message of the invite but allows them to join the faction...

**Comment by Kakifrucht** [comment]
Buy the plugin, download latest version.

**Comment by TheDiamondYT1** [comment]
well thats  fcking great solution.

i thought you uploaded it to github so people can compile it themselves.

also, you are selling a plugin made by massivecraft...

**Comment by thegiantwither** [comment]
TheDiamondYT1 add me on skype GiantWither and I have a way to help you :)

**Comment by Kakifrucht** [comment]
Derps I have nothing to do with this, if you want to use this plugin unlicensed that is your decision I personally don't give a shit, don't come here though asking for support, especially if you don't understand the concepts of licensing.
