### ISSUE TITLE
Add autodelete bypass

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#659]
Basically a permission which ensures that your faction files won't be deleted after autoLeaveAfterDaysOfInactivity setting. Good donation perk with EULA compliance.

**Comment by drtshock** [comment]
The problem is how do we handle this with offline players / permissions

**Comment by Kakifrucht** [comment]
Yeah that's true, maybe additional JSON boolean which updates on logout? hasBypass sets to true if certain permission node is set, once the cleanup task runs it simply checks this permission.

**Comment by drtshock** [comment]
perhaps. just wouldn't add it retroactively.

**Comment by drtshock** [comment]
There ya go :)

**Comment by Kakifrucht** [comment]
Amazing! Thanks alot.

~~I don't have access to ci anymore though, so it would be nice if you could push to spigot once you are done.~~ ninja'd
