### ISSUE TITLE
Factions Scoreboard and Colored Nick name (red : enemy and etc. )

### ISSUE THREAD

**Issue by Crusby** [drtshock/Factions#661]
Hello drtshock can u split these thinks beacuse faction scoreboard block other thinks and i want Colored nick names .

**Comment by drtshock** [comment]
no, sorry. the names use scoreboards.

**Comment by Crusby** [comment]
And u know its block other ScoreBoards ?

**Comment by drtshock** [comment]
it uses scoreboards.
