### ISSUE TITLE
Lost CI Access

### ISSUE THREAD

**Issue by MoeXIV** [drtshock/Factions#662]
As the title states, my username on the CI was MoeXIV. I can no longer create an account or login for that matter.

I purchased FactionsUUID and HCFactions (hcfactions being from you personally).

**Comment by drtshock** [comment]
CI user database got wiped (staminus was sponsoring the machine, rip). Get Factions from spigot and hcf was given up on :(

**Comment by juIio** [comment]
@drtshock what do you mean hcf was given up on

**Comment by drtshock** [comment]
I didn't have time so I gave it to @nsporillo and then he didn't have time :(

**Comment by Lmmb74** [comment]
then @drtshock can you upload the source if sb decides to continue it?

**Comment by MoeXIV** [comment]
I think that's a good idea. Developers can add what they want to the plugin, this will also allow a more custom HCF server type feel.

**Comment by drtshock** [comment]
Factions is already open source. I hated working on HCF so I don't want to put it up anywhere or keep working on it.

**Comment by MoeXIV** [comment]
I'm aware factions is open source. Just because you don't like working on it doesn't mean other people won't. I really feel like it could impact the way a whole game mode works. 

Don't do it for yourself, do it for those who supported you along the project.

**Comment by Lmmb74** [comment]
I meant that you make HCF open source
