### ISSUE TITLE
/f Not working

### ISSUE THREAD

**Issue by StefvanderMeer** [drtshock/Factions#664]
Here is the crash log.

27.03 16:40:41 [Server] INFO blijgozertje issued server command: /f
27.03 16:40:41 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to Factions v1.6.9.5-U0.1.18-b298
27.03 16:40:41 [Server] INFO org.bukkit.event.EventException
27.03 16:40:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
27.03 16:40:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
27.03 16:40:41 [Server] INFO Caused by: java.lang.NullPointerException
27.03 16:40:41 [Server] INFO at com.massivecraft.factions.listeners.FactionsPlayerListener.preventCommand(FactionsPlayerListener.java:502) ~[?:?]
27.03 16:40:41 [Server] INFO at com.massivecraft.factions.zcore.MPluginSecretPlayerListener.onPlayerCommandPreprocess(MPluginSecretPlayerListener.java:23) ~[?:?]
27.03 16:40:41 [Server] INFO at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[?:?]
27.03 16:40:41 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
27.03 16:40:41 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
27.03 16:40:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
27.03 16:40:41 [Server] INFO ... 16 more
27.03 16:40:41 [Server] ERROR null
27.03 16:40:41 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.18-b298

**Comment by drtshock** [comment]
Can you paste you server startup log in pastebin? It looks like something didn't load correctly.

**Comment by StefvanderMeer** [comment]
Here it is.

Dear Regards,

BlazeVortex

Date: Sun, 27 Mar 2016 11:04:30 -0700

**Comment by drtshock** [comment]
Yeah something happened with your factions save files. Do you have an older version you can revert back to? Also, run them through a json parser.
