### ISSUE TITLE
Ally sethomes even though its blocked?

### ISSUE THREAD

**Issue by FactionsFTW** [drtshock/Factions#665]
In the config I've blocked /sethome in ally territory, however ingame when they do it this happens: https://gyazo.com/746442f6428fc7147e74131b07126100

It gives the message that its blocked but still sets the home.

Only happens in ally territory too, the same commands are disabled for neutral and enemy territory and the plugin disables it perfectly.

**Comment by drtshock** [comment]
Please update, this was resolved awhile ago.
