### ISSUE TITLE
Chunk 0,0 not affected by Worldguard Flag

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#67]
When having the config option worldGuardChecking set to true, it will not check chunk 0,0, making it claimable for everyone.

**Comment by drtshock** [comment]
But it works in any other chunk?

**Comment by Kakifrucht** [comment]
Yes, every other slightly worldguard secured chunk cannot be claimed.

**Comment by squidicuzz** [comment]
I cannot seem to duplicate this issue.  Could you please provide more details?

**Comment by Kakifrucht** [comment]
Well, what else can I say about it, when tping to location xz 00, I am able to claim that zone, even though it is protected. This works on the complete chunk 0,0, even though the chunk is claimed till the top, so it shouldn't work. Every other protected chunk cannot  be claimed.

**Comment by Kakifrucht** [comment]
Are you unable to reproduce the issue? If that is the case I would do some further testing to narrow the issue down myself.

**Comment by Kakifrucht** [comment]
This is the exception that is being thrown:
http://pastebin.com/Py8NxET3

**Comment by Kakifrucht** [comment]
Seems like Worldguard is the problem here: https://github.com/sk89q/WorldGuard/blob/master/src/main/java/com/sk89q/worldguard/protection/regions/ProtectedCuboidRegion.java#L152
Issues with multiplying 0*0?

**Comment by drtshock** [comment]
Can you not post a modified log please? And post the complete log.

**Comment by Kakifrucht** [comment]
The log is not modfied, but I copied it out of McMyAdmin, that is why it looks funny.
I should add though, that my region at 0,0 is a ProtectedPolygonalRegion, this might be the issue here.
http://pastebin.com/p58EUiEn

**Comment by drtshock** [comment]
Which version are you using?

**Comment by Kakifrucht** [comment]
Factions 1.11
Worldguard 5.9 (not on Beta)
Latest spigot

**Comment by drtshock** [comment]
https://github.com/sk89q/WorldGuard/blob/7086a1d0d2f52ffc1c069820bd14ebd33a9182f6/src/main/java/com/sk89q/worldguard/protection/regions/ProtectedCuboidRegion.java#L152 would be the line your error points to then. Investigating that now.

EDIT: Looks like it only works for ProtectedCuboidRegion and ProtectedPolygonalRegion. Not sure what other region type would be causing that.

EDIT2: The only thing I can think of is it's intersecting with a global region and that isn't supported in your WG version. Is that possible @Kakifrucht?

**Comment by Kakifrucht** [comment]
Sorry I did not get Email notification about your edits.

Yes that is the case! When I remove the **global** it works ;)
I guess you can't do anything about that on your side?

**Comment by drtshock** [comment]
Yeah I don't think this is anything we can fix :\
