### ISSUE TITLE
Uncompatible with worldborder for 1.7.10

### ISSUE THREAD

**Issue by Kira07** [drtshock/Factions#670]
The option to prevent players from clamining near the map limit doesn't work with worldborder for 1.7.10

**Comment by drtshock** [comment]
talking about the plugin or the built in minecraft worldborder?

**Comment by Kira07** [comment]
The plugin worldborder, but maybe it's a misunderstanding ? Your plugin hooks with the plugin worldborder or with the build in minecraft worldborder (which isn't available for 1.7.X) ?

**Comment by drtshock** [comment]
It only hooks into the minecraft worldborder, not the plugin.
