### ISSUE TITLE
Issues with FactionsUUID

### ISSUE THREAD

**Issue by SnowPiex** [drtshock/Factions#672]
basically, it works but at the same time it doesn't. Here's the log:

http://pastebin.com/jaC5CwPw

**Comment by drtshock** [comment]
Which version of spigot are you on?

**Comment by SnowPiex** [comment]
1.8.8

**Comment by SnowPiex** [comment]
Still having this issue.. Can you please Fix@ @drtshock

**Comment by drtshock** [comment]
Update vault
