### ISSUE TITLE
Offline Player balance?

### ISSUE THREAD

**Issue by Titaxiam** [drtshock/Factions#673]
So i recently bought the plugin and configed it a bit.... But there is an issue with it, doesnt show the players right balance when there offline... But when there online it shows there correct balance?

**Comment by drtshock** [comment]
which econ plugin are you using? Can you show your startup log in pastebin please

**Comment by Titaxiam** [comment]
http://pastebin.com/9DqMHH24

**Comment by drtshock** [comment]
That log is a mess... what did you do to make it so unreadable? :(

**Comment by Titaxiam** [comment]
I really dont know... Just copied and pasted it from the log... But were using Essentials for the eco...

**Comment by Titaxiam** [comment]
http://pastebin.com/Z4FLDeX0 this is the new log...

**Comment by drtshock** [comment]
Where is it showing the wrong balance? I'm confused. Because this isn't an econ plugin.

**Comment by Titaxiam** [comment]
it keeps showing ${player-balance} when ever you hover over the name in someones faction... But i configed it and changed it to ${balance} and the balance is working but not showing there correct balance.... "${player-balance}" isnt working and "${balance}" isnt either...

**Comment by drtshock** [comment]
It's just {balance} but you need vault installed for it to work as well as econ enabled in conf.json

**Comment by Titaxiam** [comment]
i cannot find conf.json in my vault folder?

**Comment by drtshock** [comment]
in factions

**Comment by drtshock** [comment]
Issue with econ plugin.
