### ISSUE TITLE
1.8 Doors Can Be Opened

### ISSUE THREAD

**Issue by Darklite38** [drtshock/Factions#674]
All players can open 1.8 doors. I've tried adding "BIRCH_DOOR", "SPRUCE_DOOR", etc. to the territoryProtectedMaterials and territoryProtectedMaterialsWhenOffline lists while the server was stopped. But after starting the server up again the items are removed from the list.

**Comment by uf0h** [comment]
Exact same issue. Still existent.

**Comment by Kakifrucht** [comment]
Use a proper text editor like Notepad++ and set it to use spaces instead of tabs.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
