### ISSUE TITLE
Faction-less players can raid all faction bases

### ISSUE THREAD

**Issue by Darklite38** [drtshock/Factions#675]
Any player that isn't in a faction can walk right into any base and raid without any restrictions. I've looked over all the configs thoroughly. Am I missing something here?

**Comment by drtshock** [comment]
Can you paste your conf.json please? You likely changed something.

**Comment by Darklite38** [comment]
Yeah I probably missed something. Here's my conf.json:

http://pastebin.com/3d5uL8f1

**Comment by JBlackbean** [comment]
Apologies this has been fixed. I work for darklite and I fixed it by deleting config.yml and config.Json files and letting them regen themselves as if new. Then just edited what we needed. However issue #674 is still a problem.
