### ISSUE TITLE
F Map Size Configuration

### ISSUE THREAD

**Issue by SlayerMarth** [drtshock/Factions#677]
I think adding the ability to specify how many lines you want your f map to be via config would be a nice feature. I've noticed Massive's Factions upped the size of their map size. But, not everyone would like it. So the option to specify would be great. 

OR

Turn it into permission nodes. Default node is the normal size, then you have 2-3 larger sizes. Special players can have access to the different sizes, donations, crate rewards, etc. I think it'd be nifty.

**Comment by grrocks** [comment]
I was going to do this but looks like its already configurable:
    public static transient int mapHeight = 8;
    public static transient int mapWidth = 39;
Look for mapHeight and mapWidth in config and just change it to your liking

**Comment by SlayerMarth** [comment]
@grrocks 
Config has been removed and regenerated a couple times. We're not seeing it. It's also not in any other the configurations on the main page in the resources folder, so I can't copy and paste it in from those either. Are you sure it's there? Could you potentially point me in the right direction so I can let the team know?

**Comment by SlayerMarth** [comment]
[Bump]

**Comment by SlayerMarth** [comment]
Just kind of bumping this, again. 

I've check the config like @grrocks suggested and I'm not seeing it. Also checked the conf files, nothing. If this is something just isn't going to happen, that's fine. I just would like to be told and have this request closed. No point continuously checking in on this hoping for a response of some kind only to keep being seemingly ignored, missed, or whatever's going on. It's been alittle over 2 months and nothing. So I just want to know a legitimate answer/update so I know to either stop checking and close this or keep waiting.
