### ISSUE TITLE
LANG FILEAGAIN 

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#679]
CAN YOU UNDERSTANG wHEN I REPLACE THE FILE, THE BASIC LANGUAGE FILE APPERS AND MY EDIT DISAPEARS. CAN YOU UNDERSTAND " edit like another file language " YOU FUCKING FILE LANGUAGE DONT WORK

**Comment by drtshock** [comment]
It's not my job to teach you to edit files :\

**Comment by SnakeDaoust1232** [comment]
#rekt
