### ISSUE TITLE
Warzone and Safezone Claim not working

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#68]
Whenever I try to claim Land with /f claim warzone or safezone, it will tell me in chat "You claimed Land for Wilderness from Wilderness", not claiming anything at all. I have translated the String Wilderness though.
Autoclaim works neither.
I am in a Faction myself when trying this out.

**Comment by RenegadeEagle** [comment]
Do you have permissions to claim land?

**Comment by Kakifrucht** [comment]
Yes, I have the full set of permissions and Operator. I also tried giving the permission node to my self manually, this changed nothing, just like the bypass didn't work.

**Comment by squidicuzz** [comment]
Could you please provide more details relating to this issue? I cannot seem to duplicate it.

**Comment by Kakifrucht** [comment]
If I want to claim warzone and safezone land, I can't. First it tells me that I can't claim land for any of them. When I enable the /f bypass, it just says "You claimed land for Wildnis from Wildnis". Maybe this is the case because I translated the string Wilderness?

**Comment by drtshock** [comment]
Did you change anything in the lang.yml for the warzone and safezone names?

**Comment by Kakifrucht** [comment]
Well there we go, yes I did and using those translated string in the command made it work. Thanks!

**Comment by drtshock** [comment]
\o/
