### ISSUE TITLE
/f invite doesn't work for me

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#683]
If players try to invite others into their factions with /f invite <name> this error occurs and the player can't invite the other one: http://pastebin.com/jn5B7Y9B

Version: KCauldron version 1.7.10-R0.1-SNAPSHOT (1.7.10-1614.201)
FactionsUUID: v1.6.9.5-U0.1.18-b302

What can I do about this issue? Found some issues which are like this but without any solution :/

**Comment by drtshock** [comment]
You need to be on 1.8 with the latest builds.
