### ISSUE TITLE
Powerboost Loss

### ISSUE THREAD

**Issue by RoyalRaid** [drtshock/Factions#689]
Hey,
I have a issue where players randomly lose their powerboosts. Ill come on and give them their extra 40 powerboost then a few days later it will gone. 

Thanks in advance!

**Comment by drtshock** [comment]
are you sure you're not having issues with files not saving or something with a user changing their name in offline mode? Please give the version and show this happening in debug mode.

**Comment by Kakifrucht** [comment]
This happens when a user is factionless. Don't know if bug or not though.

**Comment by drtshock** [comment]
That isn't set anywhere.. It's never reset.

**Comment by Kakifrucht** [comment]
Yes, I reviewed the code once already myself and couldn't really narrow it down.
I know for sure though that it's the cause, as I have players with powerboost who never lost it, having it for a long long time already, and the couple ones who did lose it just stayed factionless for a day and then lost it randomly. It is definitely happening though.

**Comment by drtshock** [comment]
Are those players getting auto removed from their faction?

**Comment by Kakifrucht** [comment]
No, they just leave themselves. They do not lose it immediately. I wasn't able to reproduce personally, but once they leave the power will sooner or later be gone.

**Comment by drtshock** [comment]
Perhaps it's just not getting applied when they rejoin a faction?

**Comment by Kakifrucht** [comment]
No,  it really gets lost while they have no faction.

**Comment by Mod-masta** [comment]
Not sure if it only happens to players not in a faction, but I definitely have heard players tell me they've seen it happen after leaving a faction or making a new one. But it definitely only happens over a fairly long period of time, a week+ in most occasions. 

I'll try doing more testing with it and get back. I'll see if it has to do with leaving a faction. Maybe it's when players get autokicked from their faction after not being on.

**Comment by Kakifrucht** [comment]
For me one day of being factionless was enough. But I couldn't reproduce it during shorter offline testing.

**Comment by Mod-masta** [comment]
I believe I just found out the issue, there is an option that resets faction data when a player is autokicked. 
  "autoLeaveDeleteFPlayerData": true

This would explain why it seems to happen when players haven't been on for a while. I'm setting this to false and seeing if the issue persists @Kakifrucht have you tried this?

**Comment by Kakifrucht** [comment]
Good find, setting it to false aswell. Although that wouldn't explain why it removed the power from factionless players in my case, as they weren't auto removed. I checked the code and that config setting is only queried from the auto leaving task. I'll test it, thanks.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
