### ISSUE TITLE
Faction Plugin wont enable

### ISSUE THREAD

**Issue by BlueDemonic** [drtshock/Factions#690]
i get this when ever i try to start my server with factionsuuid it was working yesterday but now it doesn't idk why

[8:56:37 AM] BlueDemonic: 09.05 06:29:01 [Server] INFO [Factions] Enabling Factions v1.6.9.5-U0.1.18-b302
09.05 06:29:01 [Server] WARN [AutoSaveWorld] Plugin Factions attempted to establish connection http://www.spigotmc.org/api/resource.phpser_id=7154&resource_id=1035once=99456894 in main server thread
09.05 06:29:01 [Server] INFO [Factions v1.6.9.5-U0.1.18-b302] === ENABLE START ===
09.05 06:29:01 [Server] ERROR Error occurred while enabling Factions v1.6.9.5-U0.1.18-b302 (Is it up to date?)
[8:56:44 AM] BlueDemonic: Do you know how to fix it

**Comment by markhughes** [comment]
You're missing quite a bit from your logs, can you please provide a few more lines (at least 15 above and below)
