### ISSUE TITLE
FACTIONS tag in chat.

### ISSUE THREAD

**Issue by Crusby** [drtshock/Factions#691]
How i can add somethink after FACTION tag in chat beacuse in conf.json its not working.

**Comment by juIio** [comment]
In Essentials navigate to your "Chat Format" section of the config.yml
Once there you can do something like this:
format: '&6[[FACTION]&6] {DISPLAYNAME} > {MESSAGE}'

**Comment by Crusby** [comment]
I need some symbol after faction tag when faction will be crate. Rather how i can edit these messages in lang.yml http://hastebin.com/feyiwapiqu.vbs beacuse when i eddit somethink then lang.yml is not working i how i can allow messages faction-login: and faction-logout: .

**Comment by Crusby** [comment]
I got it plz close it.
