### ISSUE TITLE
Request: Change class paths

### ISSUE THREAD

**Issue by StargateMC** [drtshock/Factions#692]
Hi DrtShock,

I'm currently trying to support FactionsUUID, FactionsOne and Factions with my plugin and having some serious issues between all three of you using some of the same class, package and method names.

Would it be a problem if in future releases you considered changing the classpath - so you no longer identify as factions to unsuspecting plugins like mine?

If not, all good... (but some help on my end would be appreciated! :D )

My GitHub is https://github.com/DraksterAU/Regenerator

**Comment by drtshock** [comment]
learn2maven

**Comment by StargateMC** [comment]
Thanks for the help, dick.

**Comment by drtshock** [comment]
I'm sorry but changing class paths would break any plugins hooking into it so I'm not sure why you asked that. And you should learn how to use maven to hook into multiple versions of a project. Such as https://github.com/drtshock/ObsidianDestroyer
