### ISSUE TITLE
Working with Skript

### ISSUE THREAD

**Issue by JeremyBankes** [drtshock/Factions#696]
Hi DrtShock!

I have my server hugely based off of Skript. It runs FactionsUUID, because I don't like all the newer 1.8 factions plugins. Sadly when I run my server with it (and any other 1.6 factions plugin) it disallows Skript's plugin hooks to connect with vault causing a ton of errors to follow. I don't really know causes Skript's plugin hooks to mess up, but I'm sure it can't be to hard to fix. Perhaps just a small tweak in the code. I would greatly appreciate your help!

Thanks!
~Orcane

**Comment by drtshock** [comment]
You should submit a pull request if you need skript help :)
