### ISSUE TITLE
Factions F map

### ISSUE THREAD

**Issue by TheTechnologyStudio** [drtshock/Factions#699]
/f map is broken. It shows out of place and all wierd yet i claimed in a exact square. I know this because i built a sqaure using blocks and claimed along it as a template.

Please fix.

Image: http://prnt.sc/b9cke1

**Comment by drtshock** [comment]
Which factions version, which spigot version, and are you using a resource pack?

**Comment by TheTechnologyStudio** [comment]
Factions uuid, Spigot 1.8.8 and Yes a custom built resource pack

**Comment by drtshock** [comment]
Can you reproduce it without the resource pack?

**Comment by TheTechnologyStudio** [comment]
let me try

**Comment by TheTechnologyStudio** [comment]
Ok works fine with out resource pack. Any ideas how to fix my resource pack for that? Also when are you going to update and add more features? FYI your HCF link is dead. Please fix.

**Comment by markhughes** [comment]
It's the font, use a font that has equal spacing for the map characters

**Comment by TheTechnologyStudio** [comment]
ok
