### ISSUE TITLE
/f show and /f who show the UUID if they are offline

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#7]
not sure if this is intended or not, but if the players are offline it shows the UUID next to their name: http://gyazo.com/448857394b7d72a10631f5629e27306f.png

using:
factionsUUID 15
spigot 1442

**Comment by drtshock** [comment]
Yes that's unfortunately not an easy work around.

**Comment by Zeebra456** [comment]
just do it where every fplayer has a get a lastknownusername

**Comment by Zeebra456** [comment]
i had to fix everything

**Comment by externo6** [comment]
@Zeebra456 Did you say you fixed this? If so share the code.
