### ISSUE TITLE
/f show new message

### ISSUE THREAD

**Issue by Crusby** [drtshock/Factions#700]
Hello can u add error message "You dont have a faction." for /f show command when u dont have a factions.

**Comment by drtshock** [comment]
It already tells you that it couldn't find the faction.

**Comment by Crusby** [comment]
I think no when i type /f show in chat its show me player without faction its looking like that https://ctrlv.cz/shots/2016/05/30/dSeB.png

**Comment by drtshock** [comment]
you spelled show wrong?
