### ISSUE TITLE
Scoreboard - possibility to off the scoreboard

### ISSUE THREAD

**Issue by Crusby** [drtshock/Factions#703]
Possibility to off scoreboard when i want colored nickname´s in TAB.

**Comment by drtshock** [comment]
Make separate tickets for separate issues.

**Comment by Crusby** [comment]
Complete.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
