### ISSUE TITLE
/f show error message add.

### ISSUE THREAD

**Issue by Crusby** [drtshock/Factions#704]
/f show to add error message "You don´t have a faction" when you´re without FACTION! Photo here https://ctrlv.cz/shots/2016/05/30/v6gn.png

**Comment by drtshock** [comment]
Can you paste your config.yml

**Comment by Crusby** [comment]
Here is it. http://hastebin.com/ikelaqoroh.coffee

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
