### ISSUE TITLE
Bypass not disabling when taking away permission

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#705]
Same thing as #636 , but with /f bypass. For both there is no way to do this via command or anything, so only way to remove chatspy or bypass of a player who previously had the permission is either to manually edit the db or to quickly give the permission, sudo the command on him and take the permission away again.

I'm proposing to either add a command arg for admins to toggle off (like essentials socialspy for example) or to check on login if the player has the permission and remove the feature if not (probably more elegant).

**Comment by drtshock** [comment]
There we go

**Comment by Kakifrucht** [comment]
That was fast, thanks!
