### ISSUE TITLE
Autoremove not working anymore?

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#706]
I downgraded Factions due to the unclaim bug and noticed some cleanup happening (more than usual), checking the logs showed that while having the new version installed autoremove did not occur. The permission was not granted to anyone though (besides staff).

---
## To fix this:

Go into your players.json, search and replace `"willAutoLeave": false` with `"willAutoLeave": true`. Do this while the server is off. Ensure that you are on the latest version.

**Comment by drtshock** [comment]
what auto remove?

**Comment by Kakifrucht** [comment]
The one you updated with the autoremove here https://github.com/drtshock/Factions/commit/efb5d335f6bd176a8b74c2d3404ffbc8fdbc4b6b

**Comment by drtshock** [comment]
Whats the issue? It just sets the player to _not_ be auto removed if they have a permission node.

**Comment by Kakifrucht** [comment]
Yes, the issue is that nobody gets autoremoved at all.

**Comment by drtshock** [comment]
Can you show the logs of this happening in debug mode?

**Comment by Kakifrucht** [comment]
I will do further testing and get back to you.

**Comment by drtshock** [comment]
Also let me know if it _does_ autoremove with that permission.

**Comment by Kakifrucht** [comment]
Did some further tests in testing environment and everything worked as expected. I will be deploying it into live environment and monitor logs. Also saw in the logs that it printed that basically every player that was supposed to be autoremoved was set not to (didn't catch that on my last grep's). Could this have something to do with them not having joined yet since updating Factions?

**Comment by drtshock** [comment]
Yeah they'd have to join since they got the permission for the auto remove immunity to take affect. I'm still confused to whether there is an issue here or not.

**Comment by Kakifrucht** [comment]
Well yes, because most people getting cleaned didn't yet visit the server once. By default that value should be false.

**Comment by drtshock** [comment]
No because by default they should auto leave if their time is up which is how it was before and how the default is now.

**Comment by Kakifrucht** [comment]
Oh sorry, yes that is what I meant. And the issue right now is that by default they won't be removed, since they never joined the server since update, even though they should be, as that is default behaviour.

Another issue directly related: The information that he wasn't removed should probably be printed to debug channel, as it can get quite spammy.

**Comment by drtshock** [comment]
Yeah I'll move it to debug. 

Can you compile https://github.com/drtshock/Factions/commit/830ffff022e45bdb5ee4500f197543cffa2641f0 and see how it works?

**Comment by Kakifrucht** [comment]
Not without bigger hassle, can you drop the jar somehow?

Also this [code](https://github.com/drtshock/Factions/blob/830ffff022e45bdb5ee4500f197543cffa2641f0/src/main/java/com/massivecraft/factions/util/AutoLeaveProcessTask.java#L52) should be moved to [here](https://github.com/drtshock/Factions/blob/830ffff022e45bdb5ee4500f197543cffa2641f0/src/main/java/com/massivecraft/factions/util/AutoLeaveProcessTask.java#L58), otherwise it will always log an exempt player even if he is not going to be removed.

**Comment by Kakifrucht** [comment]
Actually can't compile due to maven error with playervaults repo.

**Comment by drtshock** [comment]
what maven error?

**Comment by Kakifrucht** [comment]
Dependency '''com.drtshock:PlayerVaults:3.5.9-SNAPSHOT''' not found, also tried 3.6.0

**Comment by Kakifrucht** [comment]
There is a little issue here, since I already ran Factions when the value was false by default it stored them all in my database, so now the default is false. I could just manually clean that up, but other users who also updated will have this issue aswell.

**Comment by drtshock** [comment]
It was always defaulted to false though.

**Comment by Kakifrucht** [comment]
Yes, but it should have been true by default (willAutoLeave -> true by default). It was false, you fixed that in the commit you referenced. This issue is fixed now, however I'm guessing other users will have the same issue now if they updated to the build where it is by default false, since the commit does not change these now in JSON stored values.

**Comment by JBlackbean** [comment]
Little bit lost here. What JSON config line do I change to get rid of this spamming the console?

Thanks

**Comment by Kakifrucht** [comment]
Go into your players.json, replace `"willAutoLeave": false` with `"willAutoLeave": true`. Do this while the server is off.

Updated issue as I suspect more people will want to know.

**Comment by JBlackbean** [comment]
Yeah Thanks so much i have seen like 7 posts relating to this. And all he did was close my report and point me to here. At least now people will know what to do. Thanks.
