### ISSUE TITLE
/f vault error

### ISSUE THREAD

**Issue by BoostedRAM** [drtshock/Factions#707]
30.05 20:56:09 [Server] INFO BoostedRAM issued server command: /f vault
30.05 20:56:09 [Server] ERROR null
30.05 20:56:09 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.19-RC1
30.05 20:56:09 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1388) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
30.05 20:56:09 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
30.05 20:56:09 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getPlayerVaultFile(Ljava/lang/String;)Lorg/bukkit/configuration/file/YamlConfiguration;
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.cmd.CmdVault.perform(CmdVault.java:59) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:299) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:262) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.P.handleCommand(P.java:189) ~[?:?]
30.05 20:56:09 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:200) ~[?:?]
30.05 20:56:09 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.2.jar:git-Paper-651]
30.05 20:56:09 [Server] INFO ... 15 more

**Comment by BoostedRAM** [comment]
This was when i typed /f vault and checked console for errors and this is what i saw.

**Comment by Kakifrucht** [comment]
Did you install PlayerVaults?

**Comment by BoostedRAM** [comment]
I did, Let me try using his recommended build. WORKS, ISSUE NOW CLOSED!
