### ISSUE TITLE
Frost walker causing raiding bug in faction territory.

### ISSUE THREAD

**Issue by BoostedRAM** [drtshock/Factions#708]
DRTshock i have a request for you. Frost walker is VERY OP when it comes playing factions as it causes water to change into ice and tnt of course breaks _compacted-ice_ when you blow things up, so i was wondering if you could add an option for enabling/disabling frost walker in FACTION CLAIMS ONLY and allow options of its use in Wilderness and Warzone? Thanks!

**Comment by BoostedRAM** [comment]
that will cause very big problems in the future if not fixed^^^

**Comment by Kakifrucht** [comment]
Would be nice to have, the event to handle this is EntityBlockFormEvent.

**Comment by BoostedRAM** [comment]
Okay, does it disable the enchant.. or?

**Comment by BoostedRAM** [comment]
does it perm disable the enchant or...?

**Comment by Kakifrucht** [comment]
No I just put that there for faster reference, in case drtshock didn't know that yet.

**Comment by BoostedRAM** [comment]
oh lel haha... i have tested the tnt issue so thats why i reported this, people also told me so that when i release i wont have any op raids happening because of this problem :)

**Comment by drtshock** [comment]
Assuming the entity https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/EntityBlockFormEvent.html#getEntity() returns the player?

**Comment by BoostedRAM** [comment]
yes it does return to the player, I was just wondering if you could add the feature to enable/disable people from changing water/lava to compacted ice when in CLAIMED territory, because when you explode tnt on compacted ice it breaks and no water forms back thus allowing the player to use creeper eggs or tnt cannons with obsidian destroyer to get into the base and there ya go a raid has been completed.

**Comment by BoostedRAM** [comment]
Still waiting for that reply :P

**Comment by drtshock** [comment]
There ya go
