### ISSUE TITLE
f top

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#71]
A top command should let you sort factions but different ranks. You should be able to sort by power, members, enemies, allies, land claimed, and bank value. Default /f top will ask you which you want to sort by.

/f top <criteria> [amount] - list up to 25, default 10.

**Comment by drtshock** [comment]
should be implemented with t00th's storage abstraction.

**Comment by blha303** [comment]
Working on this.

**Comment by drtshock** [comment]
FINALLY
