### ISSUE TITLE
Enter/Leave message

### ISSUE THREAD

**Issue by SenPr** [drtshock/Factions#710]
Hi
I got FactionsUUID quite a while and I've noticed that any version above 1.6.9.5-U0.1.16-SNAPSHOT has a new enter/leave message. But I wanted to use the old one (Ex: ~Warzone - Not the safest place to be) instead. I've tried to look into config files but couldnt find any options, or tried to config in lang.yml
Is there any config to enable the old enter/leave message? I like the new futures but I use the old version just because of the message.

**Comment by Crusby** [comment]
Download new version and replace new messages to old ? :+1:

**Comment by SenPr** [comment]
@Crusby I dont get what you mean...

**Comment by drtshock** [comment]
Look at the lang.yml file..

**Comment by SenPr** [comment]
I've tried to look into config files but couldnt find any options, **or tried to config in lang.yml**
Is there any config to enable the old enter/leave message?
