### ISSUE TITLE
New un-claiming does not work

### ISSUE THREAD

**Issue by danjb2000** [drtshock/Factions#713]
Okay, so when you claim some land for your faction and attempt to use /f unclaim you can't do it without parameters anymore. You get this: http://d-l.pw/i/92fc979.png
You can't even /f unclaim 1 to do that specific chunk, the only solution is to /f unclaim all in order to un-claim one bit of land.

Appreciate a fix :).

**Comment by Kakifrucht** [comment]
This was fixed in the latest release.

**Comment by drtshock** [comment]
^ was fixed here https://github.com/drtshock/Factions/commit/46805200ddb0643ddbf3a9567de67f193409a58b and is in the latest release on spigot.
