### ISSUE TITLE
/f perm

### ISSUE THREAD

**Issue by MrCleverTrevor2** [drtshock/Factions#715]
Please add /f perm command with everything that normal factions has but also what factions uuid has like vaults and stuff

**Comment by drtshock** [comment]
can you please describe the functionality because i have no idea what "normal factions" uses

**Comment by MrCleverTrevor2** [comment]
I would appreciate if you can look things up it takes like 10 seconds to find out what /f perm does and then you can start working on it, i do not get on here a lot so my responses are slow which makes it so you cant start as early;
http://imgur.com/a/4hRox

**Comment by drtshock** [comment]
Please tell me the functionality that you'd like.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
