### ISSUE TITLE
Issue with /f top balance (FactionsUUID EssentialsX and Vault)

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#716]
Spigot 1.9.4
factions 1.6.9.5-U0.1.19-RC1
EssentialsX build 345
Vault 1.5.6

So the issue is with the economy, specifically with the "/f top balance" command and more recently brought to light by me purchasing a spigot premium plugin that does special /f top which has the same exact issue. (reported here https://www.spigotmc.org/threads/factions-top-f-top-for-factionsuuid-massivecore-factions-like-opticcraft-minelink-and.111687/page-19#post-1620404 ) 

Anyways the following occurrs: http://pastebin.com/1Ehjcsvs

all of those UUID appear to be offline UUID's, and creating them causes massive lag. They should not need to be created and I have no idea why they are being made

Searching usermap.csv right after this happened shows an entry:
6369d420_32f8_48ef_9605_e870bc690055,bf03470f-4aa8-3e38-801c-a86e316c5d01

I am not sure what is up with that

Opening bf03470f-4aa8-3e38-801c-a86e316c5d01.yml in the essentials userdata folder shows
npc: true
lastAccountName: 6369d420_32f8_48ef_9605_e870bc690055
money: '500'

If I replace the underscores with dashes, it opens up the userdata file of a valid player on my server. Maybe that is the issue? somewhere the dashes are accidentally replaced with underscores?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
