### ISSUE TITLE
Bypass the limite of /f ally

### ISSUE THREAD

**Issue by tristiisch** [drtshock/Factions#717]
Hi, we can have 2/1 ally if we send request to 2 fac and if they accepte in the same time.

Pls fix this x)

Thanks you

**Comment by drtshock** [comment]
what

**Comment by tristiisch** [comment]
I configure they can have 1 ally per fac.

There is an issue, we can have more allies than fixed if  send /f ally in the same time.

**Comment by tristiisch** [comment]
Up ?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.

**Comment by tristiisch** [comment]
wtf it was not fixed.

If 1 faction use /f ally fac2 & /f ally fac3

and fac2 & fac3 use /f ally fac1, the fac1 will have 2 ally (even if the maximum of ally is 2)

**Comment by CmdrKittens** [comment]
Thank you for your comment @Tristiisch74 . I'll investigate this soon. :)

**Comment by CmdrKittens** [comment]
@Tristiisch74 Check out build 152, which should fix this.
https://github.com/drtshock/Factions/commit/165216e53a994481b9acf3b7e0c5bdf89a6614bf
