### ISSUE TITLE
~ Wilderness Message

### ISSUE THREAD

**Issue by AcePlays** [drtshock/Factions#718]
Greetings,

Is there anyway to disable the message "~ Wilderness" When walking into the wilderness territory? Or any faction, I just dont want it to say ~ wilderness in chat.

Thanks

**Comment by drtshock** [comment]
Remove the message in the lang file

**Comment by AcePlays** [comment]
Where Would this be located in the lang file?, 
Can you specify under what title it is under? eg. COMMAND, CHAT, CHATSPY ect.
