### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by random1167** [drtshock/Factions#719]
`[Factions v1.6.9.5-U0.1.19-RC1] PLAYER was going to be auto-removed but was set not to.`
i get spammed by this message every few mins, can someone please tell this fool ""me"" whats what,thank you

**Comment by tristiisch** [comment]
I have the same bug

**Comment by Kakifrucht** [comment]
Duplicate of #706

**Comment by drtshock** [comment]
Not an issue. It's just a leftover debug message that has since been removed.

**Comment by random1167** [comment]
so to get this update i need to build my own factions jar? i dont see an update on spigot

**Comment by drtshock** [comment]
Yeah it's not on spigot yet.
