### ISSUE TITLE
Commands work when they are not meant to

### ISSUE THREAD

**Issue by GoldyHD** [drtshock/Factions#720]
so, In config i have set it up so players cant do /sethome and stuff in enemy territory but for some reason they still can...

http://pastebin.com/ShDsiJHs

**Comment by Kakifrucht** [comment]
Are you talking about Essentials /sethome? This references the /f sethome

**Comment by GoldyHD** [comment]
read my config i thought this was essentials home.... if it isnt how do i stop  essentials homes and stuff

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
