### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#722]
Failed to execute goal on project Factions: Could not resolve dependencies for project com.massivecraft:Factions:jar:1.6.9.5-U0.1.19-RC1: Could not find artifact com.drtshock:PlayerVaults:jar:3.5.9-SNAPSHOT in vault-repo (http://nexus.theyeticave.net/content/repositories/pub_releases)

**Comment by Kakifrucht** [comment]
Yeah, same problem here.

**Comment by drtshock** [comment]
Odd.. it should be getting playervaults from my own repo. Try cloning and mvn clean installing playervaults.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
