### ISSUE TITLE
Losing power and not dying

### ISSUE THREAD

**Issue by AJ844FB** [drtshock/Factions#723]
hi, i am using the 0.1.18-b302 version of factions and i am not dying and when i restart the server, my power is back down to 0 or close to 0 power. could anyone please help me?

**Comment by drtshock** [comment]
you're not dying? I don't get it.

I don't understand the issue.

**Comment by AJ844FB** [comment]
I am at max power and when i restart the server a couple of times for testing some other features unrelated, i check my power is and is reset to a new player faction power.

**Comment by drtshock** [comment]
You need to generate the power.. It starts at 0 when you're a new player.

**Comment by AJ844FB** [comment]
i have been on the server for a few hours and i am at max power but when i restart the server is reset automatically somehow.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
