### ISSUE TITLE
Buggy language feature

### ISSUE THREAD

**Issue by Anzure** [drtshock/Factions#731]
Some variables don't have a translate option in lang.yml, also some messages (like errors) don't have a translate option in lang.yml. I have to say this looks terrible, sometimes the messages are half english and half Norwegian.

Sir, I have a question. Have you tested the translation feature properly with another language? I very much doubt you have. I mean no offense, but this ain't good enough. And it is NOT made up.

Sorry for leaving bad review, but if you promise to fix it I will leave 5 stars instead.

**Comment by drtshock** [comment]
Can you give specific ones that don't work?

I don't speak other languages and I don't promise that it all works in other languages. The messages that are in the file are fully translatable, but no where do we promise that 100% of all messages are translatable.

**Comment by Kakifrucht** [comment]
Yeah, tried to do a partial German translation myself, with the given grammar structure it is pretty much impossible to do correctly.

**Comment by Anzure** [comment]
You should redo (or something like that) the translation feature. Make it simple, one line for each message. It's better for us to have many lines to translate, so we can get the grammer correct and everything translated.

The plugin do support UTF-8 in the lang.yml, so all the characters (in my language) works perfectly. I'm pretty sure there is a lot of buggs messing up.

My lang.yml: https://pastebin.com/v7nb4Yk4

Some bugs amount MANY others:
- You must give the admin role to someone else first. (this becomes english no matter what I put in the lang.yml)
- You have demoted x from the position of faction admin. (same with this)
- no value no refund (not in lang.yml)
- You gave x the leadership of your faction. (won't change from default/english)
- You have promoted x to the position of faction admin. (same again)

**Comment by drtshock** [comment]
Can you give the yaml keys that aren't correct or need to be changed? And then also the messages that you can't translate that you want to be able to.

**Comment by Anzure** [comment]
I don't have time to find all the yaml keys.

**Comment by drtshock** [comment]
Then I don't have the time to read through thousands of lines of code guessing at what you mean.

**Comment by Anzure** [comment]
I made a follow-up here: https://github.com/drtshock/Factions/issues/734
