### ISSUE TITLE
Spawner Error Due to API

### ISSUE THREAD

**Issue by AJ844FB** [drtshock/Factions#732]
I am using the SilkSpawners plugin and when i try to creeper egg the spawners, it errors out in the console. I have already spoken to the author of the SilkSpawners plugin and he said it is because FactionsUUID differs in the API. Is there any way to fix this? here is the log. http://pastebin.com/18jCFpfV

**Comment by drtshock** [comment]
Silkspawners is built against a different factions version. They would need to also build against this one.
