### ISSUE TITLE
Infinite Claims bug

### ISSUE THREAD

**Issue by xDacon** [drtshock/Factions#735]
If you set

  # Should we allow Factions to over claim if they are raidable (above has no effect on this)?
  # This has always been true, allowing factions to over claim others.
  allow-overclaim: true

to false, it will allow players to claim infinite wilderness land, disregarding their power level.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
