### ISSUE TITLE
FactionsUUID Prefixes

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#736]
Ok, so before I downloaded FactionsUUID and everything was going fine, prefixes worked, and everything else.  Then I downloaded FactionsUUID and my prefixes suddenly disappeared and now everyone's name was this:  <Name>: message.  Instead of this:  Prefix Name: Message.  Any way I can enable the my old prefixes?

**Comment by drtshock** [comment]
what do you mean

**Comment by ghost** [comment]
well my prefixes dont work.  Prefixes don't show, only the name of the player shows in <>.

**Comment by drtshock** [comment]
you need to use a chat plugin

**Comment by ghost** [comment]
I have a chat plugin!!!!  I use bChatManager...  I'm not stupid, I know my plugins....  The only reason I'm posting this is because YOUR plugin is doing something wrong...  And if you READ my post you would know that I said THE PREFIXES WORKED UNTIL I DOWNLOADED FACTIONSUUID!  I'm about to stop using your plugin and ask for a refund, from what I've seen from you, you are ignorant and not very nice for someone trying to help people....  We're the ones spending $15 on your plugin, start acting thankful..

**Comment by Kakifrucht** [comment]
To his defense, you weren't very precise. I would have no idea what to tell you from the information you provided.

**Comment by ghost** [comment]
hm.... I wonder what would have happened if he asked: "Ok, So blah blah blah... But I still don't get blah blah blah...."

**Comment by ghost** [comment]
And to my defense, he didn't read my original question so how could he know if it was or wasn't precise?

**Comment by drtshock** [comment]
The way you wrote your message indicates that it worked fine with FactionsUUID then broke randomly while using it so if you want to argue semantics or if I actually read your message, maybe you should proof read.

Paying $15 doesn't mean I have to put up with everything.

> The only reason I'm posting this is because YOUR plugin is doing something wrong

My plugin only puts Faction prefixes, rank, and relation in chat if you have another chat plugin that you use. It doesn't handle the brackets or anything. So the most likely explanation is that your chat plugin broke when you installed FactionsUUID.

If you can post more information like which chat plugin you're using and which version, server logs, examples of how it works with and without FactionsUUID, that would be helpful.

**Comment by ghost** [comment]
Ok, finally, and read my message again, does it really indicate that?  I don't think so.  And you said this:  "My plugin only puts Faction prefixes".  That is my point, somehow YOUR plugin's prefix system broke and now my prefix's won't work.  I'm wondering how I might disable prefix modification on your plugin.  Here is some info:
Server Version:  
![version](https://cloud.githubusercontent.com/assets/12384589/15987787/f0adf6cc-3003-11e6-8cf0-3eb347aff4f8.png)

Without Prefixes(With FactionsUUID):  
![withoutprefixes](https://cloud.githubusercontent.com/assets/12384589/15987790/0ba81584-3004-11e6-802e-8448a30b2046.png)

With Prefixes(Without FactionsUUID):  
![2016-06-06_16 55 29](https://cloud.githubusercontent.com/assets/12384589/15987803/1a0314fc-3005-11e6-926a-84d7bee6bc64.png)
The prefixes are shown multiple times in that screenshot.  Sorry for the really awkward conversation going on in the background xD.

Chat Plugin:  bChatManager
bChatManager Version:  bChatManager - 3.1

Server Logs After Restart:  [http://pastebin.com/3aRxUuHx](url)

**Comment by drtshock** [comment]
It hooks in with the 2.x version of Factions. You'll need to ask him to hook into FactionsUUID too.

**Comment by ghost** [comment]
the chat plugin?  If it is can you recommend a good Chat plugin to use?

**Comment by drtshock** [comment]
You said you're already using one...

I personally used EssentialsChat

**Comment by ghost** [comment]
Yes, I did...  But you said it didn't work because it didn't hook with FactionsUUID, thanks though!
