### ISSUE TITLE
When applying new scoreboard, old scoreboard is not being saved

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#74]
When you walk into a territory, the current code applies the newly generated scoreboard. However, once you walk out of it, it will remove the sidebar display, however not revert to the old scoreboard.
Would it be possible to get the Players current scoreboard before applying the new one, store it in a variable, and when an unclaimed region/wilderness is being entered, apply the old saved scoreboard again.

**Comment by drtshock** [comment]
Not really a bug more like just how things work. I suppose we could attempt to save the scoreboard and restore it after the timer runs out. You could also tell your players to toggle the scoreboard off if they have another one on, even though that feature is apparently broken but should be fixed soon.

**Comment by Kakifrucht** [comment]
Should have marked it as enhancement.
It would be nice if you could add that. I'm pretty sure that most people have somewhat their own mind in how to use the scoreboard. I personally only care about the sidebar display, I'm  not sure if Factions currently even uses the colored names and stuff.
Maybe, instead of overwriting the whole scoreboard, why not just add the sidebar display to the already used scoreboard?

**Comment by drtshock** [comment]
I think it'd be easier to just save the old scoreboard and reapply it after the timer runs out for ours. Will create a quick flicker each time but that's ok.

**Comment by drtshock** [comment]
Here ya go https://github.com/drtshock/Factions/commit/525d31c2b2328f91f9bef75110e0e5a8e80072a3
