### ISSUE TITLE
AutoKick Bug

### ISSUE THREAD

**Issue by DeriveMC** [drtshock/Factions#742]
There seems to be an issue with the most recent update to where players are not being removed for being offline for more than the autokick time. I've made sure they don't have the anti auto kick permission, I've even tried negating the permission.

Console: [http://hastebin.com/uqakaquram.vbs](http://hastebin.com/uqakaquram.vbs)

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
