### ISSUE TITLE
Faction vault issue

### ISSUE THREAD

**Issue by MrRoboo** [drtshock/Factions#746]
I thought the faction vault would only be accessable per faction.
is it right that all factions have access to the same vault??? (that's how it works now)

**Comment by drtshock** [comment]
they don't..? Can you show logs of this / a video

**Comment by MrRoboo** [comment]
You should check the code again, because sometimes people are sent to another factions vault and sometimes it wont... (it does work half, to my opinion)

**Comment by drtshock** [comment]
Can you just show me?

**Comment by MrRoboo** [comment]
How can I show you? I dont know how I can prove this bug.
many people in my server reported the issue so I disabled the faction-vaults.
(Not every faction experienced this problem).

**Comment by drtshock** [comment]
Then it's not an issue. You need to reproduce it and be able to show me.
