### ISSUE TITLE
FactionsUUID Error (/f who) - Latest MC Version 1.10

### ISSUE THREAD

**Issue by Mikeyqwerty** [drtshock/Factions#747]
Whenever i type /f who on my server, the following pops up on console: http://prntscr.com/bhzjmf

http://prntscr.com/bhzqcf - Proof of Latest MC Version 1.10

**Comment by drtshock** [comment]
Delete your lang.yml and let it refresh.

**Comment by Mikeyqwerty** [comment]
Even after refreshing all files, the problem is still occurring. Same errors popping up: http://prntscr.com/bhzjmf
