### ISSUE TITLE
Spaming messages player auto-removed

### ISSUE THREAD

**Issue by Arkazium** [drtshock/Factions#749]
Hello, i have installed latest version and i have this message in my console, for all player of my server.

Message:

Factions v1.6.9.5-U0.1.19-RC1] palyo64 was going to be auto-removed but was set not to.
Factions v1.6.9.5-U0.1.19-RC1] Snyd3rs was going to be auto-removed but was set not to.
Factions v1.6.9.5-U0.1.19-RC1] Ir0x was going to be auto-removed but was set not to.

Pls fix it, thanks you.

**Comment by Kakifrucht** [comment]
#706
