### ISSUE TITLE
The plugin makes the server stops every few minutes

### ISSUE THREAD

**Issue by Kira07** [drtshock/Factions#750]
How to reproduce: 
- Update from 1.6.9.5-U0.1.18-b302 on a live server
- Use paperspigot 1.7.10 (PaperSpigot-1.7.10-R0.1-SNAPSHOT-b43.jar from https://tcpr.ca/downloads/paperspigot)
- Wait a few hours max and the server will stop by itself for no reason (no error displayed)

**Comment by drtshock** [comment]
Can you show an error log or crash log? Or something showing that factions is the one that stops the server?

**Comment by Kira07** [comment]
My bad, it wasn't FactionsUUID.
