### ISSUE TITLE
BUG - territoryAllyDenyCommands don't cancel

### ISSUE THREAD

**Issue by Anzure** [drtshock/Factions#751]
The commands specified in territoryAllyDenyCommands in conf.json don't work correctly. It sends an error message correctly, but is still allows the players to execute the command. I haven't seen the source code, but it seems like someone forgot to cancel the event.

**Comment by drtshock** [comment]
Which version are you on and can you paste your conf.json please using a paste service

**Comment by Anzure** [comment]
Spigot 1.9.4 with the latest FactionsUUID version.
https://pastebin.com/LmQvRpVS

**Comment by drtshock** [comment]
what does it say when you type /f version

**Comment by Anzure** [comment]
1.6.9.5-U0.1.19-RC1

**Comment by Anzure** [comment]
So? Bump.

**Comment by Anzure** [comment]
Can you please do something about it?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
