### ISSUE TITLE
FactionUUID | AutoRemovePlayers | HELP!

### ISSUE THREAD

**Issue by ExoticPlayz10** [drtshock/Factions#753]
So im using ur faction plugin for my server, but however. I get messages like:

[09:40:04 INFO]: [Factions v1.6.9.5-U0.1.19-RC1] Player <playername> was auto-removed due to 
inactivity.>

It has been spammining my console ever since! Plz help! Is there a different version tat may disable this? Or can i disable this using the config?

**Comment by drtshock** [comment]
#706
