### ISSUE TITLE
/f desc (Any player can input color).

### ISSUE THREAD

**Issue by StillDupeGlitchLmao** [drtshock/Factions#754]
/f desc (Any player can input color).

For example:

If player does /f desc &r &r&l

It makes his faction desc bold. This also works for colors, and other various things such as underline.
Would be appreciated if this can be fixed. Thanks

**Comment by CheatSupport** [comment]
?

**Comment by CheatSupport** [comment]
Confirmed. please fix @Vemacs @drtshock

**Comment by CheatSupport** [comment]
?

**Comment by CheatSupport** [comment]
Damn! He's on holiday. @Kakifrucht are you able to help with this issue too please? If not no worries, but @drtshock seems to go on holiday most of the time

**Comment by vemacs** [comment]
No he's playing csgo

**Comment by drtshock** [comment]
^

**Comment by CheatSupport** [comment]
Thanks @kakifrucht, @drtshock you must love @vemacs and @kakifrucht xD

Can we push this into the build? and https://github.com/drtshock/Factions/pull/761
