### ISSUE TITLE
FactionsUUID Error (/f who) - Latest MC Version 1.10

### ISSUE THREAD

**Issue by Mikeyqwerty** [drtshock/Factions#757]
Whenever i type /f who on my server, even after refreshing the lang.yml file, the following pops up on console: http://prntscr.com/bhzjmf

**Comment by JBlackbean** [comment]
Wow - AliaCraft uses Paper Spigot?

**Comment by MrAxeTv** [comment]
I have the same problem 
and I use paperspigot

**Comment by Mikeyqwerty** [comment]
@drtshock

**Comment by JBlackbean** [comment]
It has been fixed #752
Just waiting for him to compile it..

**Comment by drtshock** [comment]
I'll post a new 1.10 update before the weekend.
