### ISSUE TITLE
Can't Do Any Commands In Enemy Territory!

### ISSUE THREAD

**Issue by U2EZKid** [drtshock/Factions#759]
Hey,

When im in enemy territory i cant do any commands how can i fix this:

  "territoryEnemyDenyCommands": [
    "",
    "sethome"
  ],

**Comment by WesJD** [comment]
I would assume that it does String#startsWith or #contains, in which "" (nothing) would be true. Remove the "" from the array and see what happens.

**Comment by U2EZKid** [comment]
Yes! Thank u it worked!

Can u tell me any plugins that are really good that work with FactionsUUID

**Comment by U2EZKid** [comment]
Plugins
