### ISSUE TITLE
f warp cost does not work

### ISSUE THREAD

**Issue by CheatSupport** [drtshock/Factions#760]
.

**Comment by CheatSupport** [comment]
.

**Comment by CheatSupport** [comment]
@drtshock

**Comment by CheatSupport** [comment]
Damn, looks like @drtshock is on holiday. Hey @Kakifrucht, do you think you can help with this issue please?

**Comment by Kakifrucht** [comment]
Set econEnabled to true and if you do not want to use faction bank accounts bankEnabled to false. (/f config node value)

**Comment by CheatSupport** [comment]
Didn't fix :/ I want it to take $5000 from essentials economy

**Comment by Kakifrucht** [comment]
Please paste your conf.json

**Comment by CheatSupport** [comment]
@Kakifrucht This is my conf.json: http://pastebin.com/r9ugnKb5

**Comment by Kakifrucht** [comment]
econEnabled is still set to false. Use `/f config econEnabled true`.
