### ISSUE TITLE
Faction claiming for safezone/warzone not working

### ISSUE THREAD

**Issue by LoginRequired** [drtshock/Factions#762]
So,  when I go to claim for safezone or warzone it simply does not work. When I do the command as it is said to do, it just claims for wilderness of the faction i am in  not for warzone or safezone. The commands I am referring to are /f claim warzone and /f claim safezone. I am using FactionUUID

**Comment by LoginRequired** [comment]
bump

**Comment by drtshock** [comment]
To claim a warzone or safezone, do /f claim <radius> <warzone/safezone>
