### ISSUE TITLE
Lagging from factions command

### ISSUE THREAD

**Issue by selectj** [drtshock/Factions#764]
Server is getting long, frequent lag spikes. Here is the timings I recorded: https://timings.aikar.co/?url=17908279

Notice the playerCommand factions.

**Comment by Kakifrucht** [comment]
The only thing in Factions that actually takes a bit too long is claiming while specifying a radius.
Could you try to solely record the timings while executing /f claim x, where x is the radius? Maybe players do something like /f claim 1000, unsure about that.

Although that wouldn't really explain the way to high average of 423 ms.

bookmark https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/cmd/CmdClaim.java#L51

**Comment by selectj** [comment]
Maybe I could downgrade the version, and I think the plugin puts a limit on max radius for claiming (Not too sure on this one).

I'll try changing the version later and see if it still happens.

**Comment by selectj** [comment]
I've recorded some timings solely for /f who and /f claim, nothing has produced the high average that I got before.
