### ISSUE TITLE
Player Vaults still 0

### ISSUE THREAD

**Issue by ampavre** [drtshock/Factions#765]
When using the latest FactionsUUID and Player Vault jenkins build 205, with the following:

Factions conf.json:
  "defaultMaxVaults": 1,

Players can't seem to use /f vault as it doesn't show them owning any:
![](https://gyazo.com/40127ff8391de62235002393096f52d8.png)

When checking factions.json:
    "maxVaults": 0

Its also the same for every other Faction and also when creating a new faction the maxVaults is still 0? Also have tried restarting the server, then disbanding and creating new factions to try it but still shows 0 vaults the faction has.

**Comment by drtshock** [comment]
They need to make a vault by opening one like /f vault 1. The max is just what they can go up to.

**Comment by ampavre** [comment]
Ahh, works.

![](https://gyazo.com/9025d03805bac010653e92fdae617135.png)

Though how come it says 'test has vaults:' but doesn't show any vault amounts? e.g.
![](https://gyazo.com/ab06c4e3ed4f4f465cffde9295288c3f.png)

**Comment by drtshock** [comment]
Because those are the vaults that they have stuff in.
