### ISSUE TITLE
Lagging on startup

### ISSUE THREAD

**Issue by selectj** [drtshock/Factions#766]
Seeing as my last post was closed, I noticed my server was lagging for about 10 mins after startup, while a lot of players where trying to connect. Here I timings I recorded during startup: https://timings.aikar.co/?url=17999124.

Pls help.

**Comment by drtshock** [comment]
Can you also show the server log during this

**Comment by selectj** [comment]
It'll be hard for me to get a copy of the server log during startup due to all the players connecting, however I'm fairly sure nothing about Factions is mentioned. Regardless, I'll try and get a paste ASAP

**Comment by drtshock** [comment]
Need to get it all

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
