### ISSUE TITLE
Create new factions

### ISSUE THREAD

**Issue by mpennanech** [drtshock/Factions#767]
Hello, i try to create a new factions like warzone, safezone.. but i don't have find how make, thanks for your help

Your plugin is awesome :D

**Comment by drtshock** [comment]
they are made by default

**Comment by mpennanech** [comment]
Thx for your help.
If i can't create a factions like warzone... Maybe i can create faction with color but when i /f tag &9Redstone then i can't write &. I have try to modify this in factions.json but don't run.

Thanks :)
