### ISSUE TITLE
Where to access 1.7 HCF Plugin

### ISSUE THREAD

**Issue by Svenergy3** [drtshock/Factions#768]
I bought FactionsUUID in the hopes I could config it to work as an HCF factions plugin. I soon learned that wasn't really the case and that there was a separate HCF plugin I had to download. The problem was, though, that there was only a 1.9 version of the HCF plugin which wouldn't work correctly (or at all) on a 1.7 server. Is there a link to the 1.7 HCF plugin I can have?

**Comment by drtshock** [comment]
no where
