### ISSUE TITLE
Essentials chat color and factions Prefixes

### ISSUE THREAD

**Issue by milkmoron** [drtshock/Factions#77]
The color chat of factions prefixes does not work with the latest prerelease builds of essentials. instead of green it displays just an "a"

**Comment by drtshock** [comment]
Can you give us your config and steps to reproduce this?

**Comment by milkmoron** [comment]
http://gyazo.com/6826d9938fc883d9175ea31c39fc42bd

config.json
http://pastebin.com/9DziBsZJ

essentials config - I'm using essentialschat for formatting.
http://pastebin.com/G2NTiUMx

**Comment by drtshock** [comment]
@kashike

**Comment by squidicuzz** [comment]
I will look into this more.

From past experience there is a weird issue with chat character replacement and conflict between various plugins.  Please let me know any more details about your server to help me resolve this issue.

**Comment by drtshock** [comment]
Better described in https://github.com/drtshock/Factions/issues/100
