### ISSUE TITLE
 Bug ID Faction plugins

### ISSUE THREAD

**Issue by Ziratoxdu36** [drtshock/Factions#771]
Can solve this problem please?

![capture](https://cloud.githubusercontent.com/assets/20214255/16470151/db202ab4-3e54-11e6-8b60-fe5e0752214e.PNG)

**Comment by drtshock** [comment]
can you actually show the exception please

**Comment by Ziratoxdu36** [comment]
certain player make control and that is that its mark
![capture](https://cloud.githubusercontent.com/assets/20214255/16479949/cf8614a8-3ea3-11e6-8acd-eebc14e8b35d.PNG)

**Comment by drtshock** [comment]
Looks like an issue with groupmanager.
