### ISSUE TITLE
Chat Question

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#772]
Hello!

I am trying to setup in chat where it shows brackets around the faction name before the players IGN.

Such as:
[Faction] IGN : MSG 

Here is what I have so far:
  "chatTagFormat": "§8[%s§8]§f"

I have the brackets working etc, but when I add the '§8' it changes the whole color of the bracket & faction. I only want the brackets colored, I've tried to add §r after the first bracket but then the faction colors dont work (Ally, Enemy etc.)

So I was wondering how can I color the brackets & have the faction inside the brackets still show if you're ally, enemy etc. 

Thanks a bunch!

**Comment by drtshock** [comment]
Can you show me a picture of what you're trying to achieve and which chat plugin you're using

**Comment by ghost** [comment]
Without a faction: 
http://prnt.sc/bn3nht

When you have a faction:
http://prnt.sc/bn3nqn

Enimied Faction:
http://prnt.sc/bn3nv8

Allied Faction:
http://prnt.sc/bn3nzi

I am using the Essentials Chat plugin for my chat, this is what im trying to accomplish, having gray brackets, while still having the colors of ally, enemy, etc. in chat. But when I try to color the brackets, it colors it all (the faction inside the brackets) and then it doesnt show ally, enemy etc.

**Comment by ghost** [comment]
Any idea?

**Comment by drtshock** [comment]
You should just leave the default conf.json for chat and then do this all with essentialschat configuration.
