### ISSUE TITLE
Factions.json - Internal Error Occurred

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#773]
I mistakenly messed up the config when trying to edit a faction in the factions.json. Now it says Internal Error Occurred. Can you tell me what's wrong with it and how to fix it? It would mean a lot!

Here is my factions.json:
http://pastebin.com/BBn1Jwbe

Please help!

**Comment by ghost** [comment]
I can get you a server log if you want.

**Comment by Kakifrucht** [comment]
https://jsonformatter.curiousconcept.com/

**Comment by drtshock** [comment]
Don't touch that file :(
