### ISSUE TITLE
factions.json not working properly

### ISSUE THREAD

**Issue by Koncealed** [drtshock/Factions#775]
Trying to edit my spawn claim, but it does not work properly. I change my factions .json to it and it does not change it  right. For EX when I turn permanent to true and /f reload and I /f leave it still disbands the faction. Awhile back in the old factions plugin I use to be able to edit like this http://pastebin.com/pZMmhxFB how do I edit perm, peaceful, infpow etc.

**Comment by drtshock** [comment]
Don't edit your factions.json
