### ISSUE TITLE
Factions Api

### ISSUE THREAD

**Issue by MrAxeTv** [drtshock/Factions#776]
Hello there I need example how to use your factions Api 
I want to check if players are in the same factions

I want replace this code with your API 
if(entity instanceof LivingEntity && MPlayer.get(damager).getRelationTo(MPlayer.get(entity)) == null
                                                || entity instanceof LivingEntity && MPlayer.get(damager).getRelationTo(MPlayer.get(entity)) == Rel.ENEMY) {}

ps 
I have buy your plugin

**Comment by drtshock** [comment]
`FPlayers.getInstance()` then stuff
