### ISSUE TITLE
Frost Walker (1.9+)

### ISSUE THREAD

**Issue by Anzure** [drtshock/Factions#777]
Frost Walker can convert water to ice in all territories. It shouldn't be like this, right? My suggestion is that you need build permission to be able to Frost Walk water to ice.

**Comment by drtshock** [comment]
https://github.com/drtshock/Factions/commit/a7aeb26fd0fc2cc92ab24fcc70067ebd5d0a2087

**Comment by Anzure** [comment]
Wait... Can you export it and release the update? That would be very great.
