### ISSUE TITLE
Placeholder dont work?!

### ISSUE THREAD

**Issue by Emielboeitwel** [drtshock/Factions#779]
# Replace {name} - player's name. {faction} - player's faction title, factionless if none.
# **{totalOnline}** - total players on the server. {balance} - player's balance.
# {maxPower} - player's max power.

**{totalOnline}** « That placeholder dont work.

**Comment by drtshock** [comment]
where are you trying to use them?

**Comment by Emielboeitwel** [comment]
I try to use them in the scoreboard.

**Comment by drtshock** [comment]
Can you screenshot them not working?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
