### ISSUE TITLE
Allies enemies etc dont show in f show

### ISSUE THREAD

**Issue by iFluzzer** [drtshock/Factions#780]
I have this on f show http://pastebin.com/Y10CqUau
But it only shows this on f show: http://prntscr.com/bmowem
http://pastebin.com/rJLPik6X
These are not shown in f show http://pastebin.com/fDchsgS6

Allies, enemies, online and offline, whats wrong?

**Comment by iFluzzer** [comment]
I have this on f show http://pastebin.com/Y10CqUau
But it only shows this on f show: http://prntscr.com/bmowem

http://pastebin.com/rJLPik6X
These are not shown in f show http://pastebin.com/fDchsgS6

Allies, enemies, online and offline, whats wrong?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
