### ISSUE TITLE
prefix in Tab, and Prefix next to name

### ISSUE THREAD

**Issue by Justawave** [drtshock/Factions#781]
How do i set up so the prefix in tab or prefix over head, to the pex prefix the group they are in has?
For example if they are a helper on my server, then they would have the helper prefix in the tab menu, and over their head.

`default-prefix: '{relationcolor}[GROUP] &r'`

**Comment by drtshock** [comment]
You have to enable it and make sure no other plugin is interfering with scoreboards.
