### ISSUE TITLE
/f vault Duplicate bug

### ISSUE THREAD

**Issue by SenPr** [drtshock/Factions#782]
First, I'm not sure if I'm in the right issue tracker, PlayerVaults or FactionsUUID since it's about Factions Vault but the Vault Operation is by PlayerVaults. If I'm in the wrong one, sorry for this post.
2 seperated factions can have the same vault after allying. Then they became neutral (or enemy), the vaults will stay seperated and duplicates all the items in there. I'm not too sure on how to do this glitch.
Some of my players found it, and I also saw it accidentally.

**Comment by drtshock** [comment]
They don't have the same vault after allying. It's only for the faction. Can you show server logs of this with debug enabled as the vaults are based on the id of the faction.

**Comment by SenPr** [comment]
There is no error log, And I wasnt able to replicate the bug.
However it did happened. It showed the same factions id when open the vaults (both factions). And the vault is sync.

**Comment by drtshock** [comment]
I'm asking for the server logs, not the error logs.

**Comment by SenPr** [comment]
I dont think its needed. It reported nothing from the bug. And while I was in debug mode I wasn't able to replicate the bug. It might be a one time bug.
But if you still need it, heres the link anyway (it was at the time when we found out the bug)
http://hastebin.com/sewodukovu.vbs
Explain: A player was trying to open their factions vault and somehow there is already items in there. Then he asked the faction that he allied with if they see the items in their vault. SayWut (Me), joined the server and was trying to replicate the bug and somehow did it.
Maybe the way to replicate is to continously spams?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
