### ISSUE TITLE
Incompatibility with ChatControl

### ISSUE THREAD

**Issue by Kira07** [drtshock/Factions#783]
The faction chat works in a strange way as chatcontrol has no effect on it, it's the most used chat manager plugin so it would help a lot of people if you could fix this.

I already posted this ticket a while ago and you replied

 "Oh actually, I see why.

Issue is that instead of modifying recipients, event is cancelled and message is sent manually. This needs to be fixed."

 but since you posted a major update since then you closed all the opened tickets, I re-open it since it's still happening.

Thanks in advance,

**Comment by drtshock** [comment]
I didn't close _all_ open tickets.

And the problem with that one is that it's something from the original factions (before I forked) and quite a bit of work to redo :c

**Comment by Kira07** [comment]
Oh :/ Alright

**Comment by Cretezy** [comment]
This is still happening. Any fixes?

**Comment by CmdrKittens** [comment]
@Cretezy If you want to use a separate chat plugin instead of factions, you need to tell factions that. 

Set `tagHandledByAnotherPlugin` to true in the config.

**Comment by Cretezy** [comment]
@CmdrKittens That isn't working for me, and stopping me from using it. I have all chat features disabled yet ChatControl can't parse it (event on LOWEST)

**Comment by CmdrKittens** [comment]
@Cretezy Hop onto our discord support channel and we can work on figuring it out. https://discord.gg/PHpuzZS

**Comment by Cretezy** [comment]
@CmdrKittens invite expired, mind giving me another link?

**Comment by CmdrKittens** [comment]
@Cretezy that's our non-expiring, primary invite link. What's your discord username?

**Comment by Cretezy** [comment]
Oh it does work. Seems like Discord bugged out, will join later
