### ISSUE TITLE
scoreboard help

### ISSUE THREAD

**Issue by NoobyChicken** [drtshock/Factions#784]
I have the scoreboard working and everything just want to know if there is a way to put the /f title behind the name in the scoreboard

**Comment by drtshock** [comment]
behind what name where in the scoreboard?

**Comment by NoobyChicken** [comment]
for some reason on the scoreboards {online-list} & {offline-list} don't work :(

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
