### ISSUE TITLE
territoryProtectedMaterials cauldron server (ironchest,biomesoplenty,simpleores)

### ISSUE THREAD

**Issue by Donitovan** [drtshock/Factions#786]
Hello, when I want to add new chests or new furnace it does not work.
with /f config or to make him in the file but by restarting the serveur/plugin it posts me null!

i'm running FactionUUID 1.6.9.5-U0.1.14 on cauldron server, thanks.

**Comment by Donitovan** [comment]
please help me :sss

**Comment by Kakifrucht** [comment]
outdated, you won't get any support with an outdated plugin. update

**Comment by Donitovan** [comment]
I will not even pay once

**Comment by Kakifrucht** [comment]
and yet you expect help? like what is wrong with you? retardation at it's finest

**Comment by Donitovan** [comment]
It is what this mess? I am not going to pay second time the plugin jerk!

**Comment by Kakifrucht** [comment]
??
Who told you to pay for it a second time?

**Comment by Donitovan** [comment]
i can't download the latest version

**Comment by Kakifrucht** [comment]
why would that be the case?

**Comment by Donitovan** [comment]
That tells me to pay to redownload him

**Comment by Kakifrucht** [comment]
I'm sorry but I am having a hard time understanding what you want to say.
Also I am not affiliated with this plugin, I wouldn't be able to help you either way.

**Comment by Donitovan** [comment]
look this screen https://gyazo.com/da99de79824b89ef43e6eb843000d7b2

**Comment by Kakifrucht** [comment]
which would mean that you didn't buy it. SpigotMC doesn't clear past purchases without a reason. Otherwise contact @drtshock with proof.

**Comment by Donitovan** [comment]
ok

**Comment by Donitovan** [comment]
I was not connected to my account, I have the last version with the same problem

**Comment by drtshock** [comment]
Please paste your server log

**Comment by Donitovan** [comment]
it said only "null" in protected material

**Comment by drtshock** [comment]
Please paste your server log

**Comment by Donitovan** [comment]
nothing in log, totally normal

**Comment by drtshock** [comment]
I'm not going to help you if you won't listen.
