### ISSUE TITLE
Factions Prefix

### ISSUE THREAD

**Issue by Justawave** [drtshock/Factions#790]
I have bought the factions uuid plugin. I set up all my groups and permissions using permissionsex. When i set the prefix in the lang.yml of factions uuid config to {group} it just shows up as {group} in game. I have vault installed and that is all it says you need to have it work. Please help, if anyone knows how to fix it, please inform me how.
![untitled](https://cloud.githubusercontent.com/assets/20308733/16942979/21dbd05e-4d67-11e6-8f35-e1cac7733213.png)
![minecraft 1 8 9 7_19_2016 2_48_01 am](https://cloud.githubusercontent.com/assets/20308733/16942993/2c325226-4d67-11e6-94a1-cba0ee21a835.png)

**Comment by drtshock** [comment]
I don't believe group applies to the prefix. It's meant for Factions related replaces only.
