### ISSUE TITLE
/f who doesnt work!? An internal error has occured?

### ISSUE THREAD

**Issue by ProwolfHD** [drtshock/Factions#791]
I bought the factionuuid and every time I try to use /f who i get this error in the console
http://prntscr.com/buzy1i what do I do?

**Comment by Kakifrucht** [comment]
Ensure that you have Vault installed.

**Comment by ProwolfHD** [comment]
I do have vault installed.

**Comment by Kakifrucht** [comment]
In that case more information is needed. Full stacktrace, version number, Spigot version..
Any additional information you could give that may be helpful?

**Comment by drtshock** [comment]
Update vault and factions and what kaki said.
