### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by Wealh** [drtshock/Factions#792]
Is there a way to set permissions, I want to enable the noboom but only for faction members.

On my server, people can fly in allies territories, but they can't if their factions are peaceful since they can't have allies.

Though, I need noboom.

**Comment by drtshock** [comment]
Can you please explain what noboom is? Pretty sure you can get what you want in the conf.json

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
