### ISSUE TITLE
Async Chat messages

### ISSUE THREAD

**Issue by BlazeToToast** [drtshock/Factions#793]
I have just purchased this plugin and noticed that it sends double chat messages. I am not sure what is causing this but I would appreciate any information on what I can do to fix this.
Console messages:
[15:13:47] [Async Chat Thread - #0/INFO]: [Guest]Player: ? 
[15:13:47] [Server thread/INFO]: [FACTION] [Guest]Player: ?

**Comment by BlazeToToast** [comment]
Been checking this everyday, still nothing?

**Comment by ghost** [comment]
> [15:13:47] [Server thread/INFO]: [FACTION] [Guest]Player: ?

This is printed to chat, while the other one is printed to console.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
