### ISSUE TITLE
Adding Custom Commands

### ISSUE THREAD

**Issue by DownUndaDevGames** [drtshock/Factions#799]
Hey, I am looking into adding custom commands so they show up on the /f show and so they are compatible with aliases, for example /f [args0] [args1] etc. any idea how to do this? Thanks~

**Comment by PlethoraOrange** [comment]
There are plugins that allow you to do this. For example, MyCommand will allow you to do this.

**Comment by drtshock** [comment]
Not with factions unfortunately.
