### ISSUE TITLE
Error with /f show <playerName>

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#8]
Hello,

When using this /f show <playerName> command, there is an error.
Screeshot: http://puu.sh/8cMGc.png

Can you fix this?

Thanks,
Yoann

**Comment by gravitylow** [comment]
Hello, could you please paste the full error from the console?
Also, what build are you using?

**Comment by ghost** [comment]
I use the latest version (build #15).
Full error from the console (connection and command): http://pastebin.com/0Pz6TDMH
