### ISSUE TITLE
Scoreboards not updating correctly

### ISSUE THREAD

**Issue by Chris8130** [drtshock/Factions#80]
Basically with the always there feature like if you're not in a claim, and then you walk into a claim it changes which is normal, but once you leave the claim it does not update back to the normal default title message. I hope that made sense :P.

**Comment by drtshock** [comment]
Does it just leave the info scoreboard up and not bring back the default one?

**Comment by Chris8130** [comment]
Yeah so basically let's say I go into a faction called "Vortex" once I leave Vortex it just leaves the information not going back to the default title stuff like the balance, power, and all that.

**Comment by Kakifrucht** [comment]
I want to add, that when leaving a region on the newest build, the Expiration task does not always seem to reset, making the faction zone scoreboard stuck there until you relog.

**Comment by Chris8130** [comment]
^ That's basically the problem xD.

**Comment by Kakifrucht** [comment]
Yes, but you were talking about the default scoreboard, I was also talking about not even using the default scoreboard. Just wanted to add that. But it seems to be the same issue.

**Comment by Tribulationfu28** [comment]
I can't even get my scoreboards to show up. Also my config file doesn't have the "finfo enabled: false" line so I tried it without it then I tried adding it and still no luck. Players do have the /f sb permission as well and everytime they type it, it only says "you now have scoreboards set to false." It never says true.

**Comment by drtshock** [comment]
@Tribulationfu28 you should update and let the config regenerate.

**Comment by Tribulationfu28** [comment]
I did. I overwrote the old jar file, restarted the server, opened up the config file after restart and it has the new layout of the new config but it just doesn't have certain things, and the scoreboards aren't working.

**Comment by drtshock** [comment]
Fixed.
