### ISSUE TITLE
Lang File Issue

### ISSUE THREAD

**Issue by ItsArdo** [drtshock/Factions#801]
Hello, i'm currently trying to change the messages in lang.yml.

And i've got an issue.

I'm trying to make it so when someone goes to factions territory land, instead of it saying

Leaving: Wilderness, Entering: Faction

I'd like it to say instead (Faction Name) - (Faction Description)

How do i do this?

Also, how do i for warzone to so instead of the 'Leaving: Wilderness, Entering: Faction'

I'd like it to say when entering warzone: Warzone - Not the safest place to be.
and for Safezone: Safezone - Free from pvp and monsters.

Like i'm trying to change it in the YML however it not having any affect? MY lang file.

http://pastebin.com/DbwyW7G3

Please help this is quite necessary :/

**Comment by ItsArdo** [comment]
Hello?..

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
