### ISSUE TITLE
Chat Formatting

### ISSUE THREAD

**Issue by NZSwAg40** [drtshock/Factions#807]
Using Essentials Chat and when using the [FACTIONS] tag, if I put a space in between factions chat tag and prefix when player is not in a faction there will be an empty space in chat. How can I fix this ?

Example: 

![screen shot 2016-08-06 at 4 31 14 pm](https://cloud.githubusercontent.com/assets/3402420/17454679/3f493c72-5bf3-11e6-929d-0ccfb93a7b2a.png)

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
