### ISSUE TITLE
Faction Warzone/Safezone Claims

### ISSUE THREAD

**Issue by WatchAc** [drtshock/Factions#808]
Hello , I have a problem with your plugin , I want to know how does the /f claim Warzone/Safezone work . Can I do WorldEdit selections for Warzone/Safezone or if I want to do /f claim (radius=1) Warzone/SafeZone what does the radius mean , blocks or chunks. Can anyone please reply fast to this (with a correct answer , no trolls please , I'm fed up with them) ? I really need help with it.

**Comment by drtshock** [comment]
Can't do worldedit selections sorry. You can do it with a radius
