### ISSUE TITLE
f Claim NoSuchMethod

### ISSUE THREAD

**Issue by Kakifrucht** [drtshock/Factions#81]
When using /f claim on build 77, an exception is being thrown, no land is claimed:
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/Collection;)Ljava/util/List;

**Comment by drtshock** [comment]
Do you have worldguard installed? And if so, which version?

**Comment by Kakifrucht** [comment]
Obviously, I would not have posted this else.
This only happens on build 77, the one from spigot works fine.
Worldguard 5.9 installed on spigot, latest patch.

**Comment by drtshock** [comment]
Fixed.
