### ISSUE TITLE
Questions about the plugin.

### ISSUE THREAD

**Issue by jhdk1** [drtshock/Factions#811]
Hello! Sorry to bother you, I know you are very busy, I just have a few question before purchasing your plugin.

So first off is this a remake of the faction plugin of massivecraft, and in what ways is this one better?

Also If for my factions, I want it so if to take someones factions, the only way is to launch tnts into the base, for that I can use a tnt launching plugin, but I want to make it so even if chests are in a faction protected by their own territory, if someone gets inside they can still open it and loot it.

and is there a way to check factions that are inactive, so I could disband them.

Another thing I would like to know is that if it is possible to modify the how the energy works for a faction, maybe killing players gain energy, or you can buy it, and what happens when you run out of energy?

Thank you so much, sorry for the troubles.

This is what I left the author of this plugin but since he says this is support I must post it here, can any of you answer a few of my questions that would be great help!

**Comment by drtshock** [comment]
1. Project overview on spigot has this.
2. Yes
3. Yes
4. Not currently really.

:)

**Comment by jhdk1** [comment]
thanks!
