### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BenjisCollector** [drtshock/Factions#818]
Okay so let me start off by saying I desperately need help. I had Factions 2.x and then wanted to to FactionsUUID, so i just replaced the Factions with FactionsUUID and it gave me new names of factions, the placeholders in essentials chat don't work anymore since Factions over rid them, and now I am confused. Please help me on skype: yousefm619

**Comment by ghost** [comment]
I'll just say it, nobody wants to add a random on Skype just to help them out.

**Comment by drtshock** [comment]
Please be more descriptive with your issue on here.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
