### ISSUE TITLE
[FEATURE] Faction Announce

### ISSUE THREAD

**Issue by ExpoPvP** [drtshock/Factions#82]
Hello there!

/f announce (messagefromtheuser) would be a great addition. This message could have a configurable value to broadcast the announcements on login to other members of the faction and a way to format the message colors and such.

**Comment by drtshock** [comment]
What syntax?

**Comment by drtshock** [comment]
right now I have
factiontag [playername] message
but it looks kinda weird..
![screen shot 2014-10-18 at 12 13 46 am](https://cloud.githubusercontent.com/assets/2638275/4688637/8f4aa99c-5685-11e4-93e9-56a10b38a2a2.png)

**Comment by drtshock** [comment]
Added :)

**Comment by drtshock** [comment]
/f ann <message> or /f announce <message>
