### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by xxJinxedxx** [drtshock/Factions#820]
Hello, 
i'm sorry this is not an issue ticket but i just don't know where else to ask for this.
I have searched everything that i could think of even the online chat but with no results.So I'm looking for a permission node that is **exclusive and only applies to faction leaders**.I'm using a 3'd party plugin with which i em trying to implement a feature to be used only by the leaders.But in order for them to use this feature i will need a permission which the rest of the faction members do not have not even mods or admins.Does anyone knows one?I just can not find one...This place is my last hope that i have of finding the permission i need, if even exists.Sorry again for the non issue ticket...
Please if someone can help comment!
Cheers and thanks in advance!

**Comment by ghost** [comment]
What would the permission do?

**Comment by xxJinxedxx** [comment]
It does not have to do like anything...I just need it to be unique for the leaders of the factions and no one else...
What i em trying to do is:
Make a GUI that would have 1 item and only one command executed from it.
"command when clicked"- '[ConsoleCommand] f peaceful %factions_chat_tag%'
And then the GUI would have a Click delay or Access delay (as u like) for like 30 days.
But now this GUI is accessible from every faction member.And they can change their faction status few times, which i don't want.So in order for me to restrict it only to the leaders of a faction i need to have a permission node that only they have.I will add that permission node to the GUI plugin to look for when a player open it.And this way only leaders can change the status of their faction.And i can add a delay on that so that it is not abused.
But i do not know of such permission...so... -.-
Help! xD
P.S. - Imo i think that a standard should be made from the dev community, in which every plugin has an option for custom permission node.That is going to be so good for "special" occasions like this one.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
