### ISSUE TITLE
/f show from my view

### ISSUE THREAD

**Issue by Crusby** [drtshock/Factions#821]
When I don't have a faction and I use command /f show it shows me line from classical faction show, but I need some error message. Example "You don't have a faction"

**Comment by ghost** [comment]
Screenshot of the message printed when you `f show` without a faction?

**Comment by Crusby** [comment]
![dsadasd](https://cloud.githubusercontent.com/assets/16446913/18028319/11640c9e-6c7c-11e6-96cb-207533c38c2b.png)
There it is.
