### ISSUE TITLE
/f invite shows up with 

### ISSUE THREAD

**Issue by LukaRuso** [drtshock/Factions#822]
Hello.

Today i opened my server and players have been reporting that /f invite doesn't work and when i checked it thru console i found that /f invite brings up these errors 

27.08 11:55:24 [Server] ERROR null
27.08 11:55:24 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.14
27.08 11:55:24 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
27.08 11:55:24 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
27.08 11:55:24 [Server] INFO Caused by: java.lang.NullPointerException
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:573) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:552) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:540) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.cmd.CmdInvite.perform(CmdInvite.java:55) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:49) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:49) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:290) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:253) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.P.handleCommand(P.java:163) ~[?:?]
27.08 11:55:24 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:175) ~[?:?]
27.08 11:55:24 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
27.08 11:55:24 [Server] INFO ... 15 more

I hope u can help me with this problem.

Thanks

**Comment by Crusby** [comment]
`ss`

**Comment by Crusby** [comment]
Paste it in www.hastebin.com thanks.

**Comment by LukaRuso** [comment]
http://www.hastebin.com/umuzimepub.avrasm

**Comment by drtshock** [comment]
Update and buy the plugin
