### ISSUE TITLE
FactionsUUID Version 1.6.9.5 1.14 not working

### ISSUE THREAD

**Issue by ImNachoMans** [drtshock/Factions#824]
This factionuuid is not working for my spigot 1.7.9 r02. Like when i type /f, nothing shows up like I did nothing. It might be the version of my server thats affecting it or your version thats affecting my server. Please look into this and find the solution. Thank you.

**Comment by ImNachoMans** [comment]
Also It never extracted when I started the server

**Comment by drtshock** [comment]
Please paste your server startup logs

**Comment by ImNachoMans** [comment]
[15:33:03 INFO]: [Factions] Enabling Factions v1.6.9.5-U0.1.14
[15:33:03 ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.1.14
(Is it up to date?)
java.lang.RuntimeException: Access to this plugin has been disabled due to
piracy! Please contact SpigotMC!
        at com.massivecraft.factions.P.loadConfig0(P.java) ~[?:?]
        at com.massivecraft.factions.P.onEnable(P.java) ~[?:?]
        at
org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
~[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at
net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[server.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]

**Comment by Kakifrucht** [comment]
Buy the plugin and download the latest version.

`java.lang.RuntimeException: Access to this plugin has been disabled due to
piracy! Please contact SpigotMC!` :unamused:

**Comment by ImNachoMans** [comment]
I have to buy it again?

**Comment by Kakifrucht** [comment]
No, if you already bought it you may just login to the account you bought it with and download the latest version.

**Comment by drtshock** [comment]
lol
