### ISSUE TITLE
Friendly Fire Wilderness Faction

### ISSUE THREAD

**Issue by TomGrozev** [drtshock/Factions#825]
When people first join they are automatically put into the Wilderness Faction. I want them to be able to kill each other if in the wilderness faction and don't need to enemy another faction. I want friendly fire to be enabled for the wilderness faction.

Thanks

**Comment by SekiAlpha** [comment]
You know that in the wilderness faction no one is protected from each other? Have you even tried testing before asking here?

**Comment by TomGrozev** [comment]
I have it says "You can't hurt neutral factions. Declare them as enemy." Please help
