### ISSUE TITLE
f claiming with radius bypasses worldborder border

### ISSUE THREAD

**Issue by Elgorond** [drtshock/Factions#826]
in config i have it so 1 chunk buffer between border and faction claiming, well turns out using /f claim (radius) can bypass it.

**Comment by Elgorond** [comment]
Actually, you don't need to radius claim to bypass. With the 1 chunk buffer I can simply /f claim right next to world border.

**Comment by drtshock** [comment]
Did you set the worldborder through Minecraft and not through a plugin like worldborder?

**Comment by Elgorond** [comment]
Worldborder plugin v.1.8.6

**Comment by drtshock** [comment]
You need to set it via the minecraft world border.
