### ISSUE TITLE
worldsNoclaiming protection bug?

### ISSUE THREAD

**Issue by Elgorond** [drtshock/Factions#829]
I've just noticed that worldsNoclaiming is keeping the faction claims that are currently there, in this case my warzone claims.  The issue is that the warzone claims aren't acting exactly as a warzone claim in normal claim-active worlds, such as block protection and item-frame protection. If this could be fixed that would be nice.

**Comment by drtshock** [comment]
That just makes it so players can't make new claims in that world. I don't understand what the issue is?

**Comment by Elgorond** [comment]
Like the protection isn't there.

Breaking blocks won't display the message "You can't destroy in a warzone". And in these worlds players can take stuff from itemframes.

Also /f bypass doesn't allow you to claim more land while the world is on no claiming.

**Comment by mbax** [comment]
Solution is to remove the claims.
