### ISSUE TITLE
Factions not saving?

### ISSUE THREAD

**Issue by Chris8130** [drtshock/Factions#83]
So I created a faction called 'test" and when I shut down my server it did not save. Everything else on my server seems to working but this, I'm using the latest version.

**Comment by drtshock** [comment]
Paste your entire logs (both the first and second run) then paste your factions.json after you shut down the server.

**Comment by Chris8130** [comment]
http://pastebin.com/mxFvriJ9

**Comment by Chris8130** [comment]
Big error when it trys to disable Factions.

**Comment by Chris8130** [comment]
http://pastebin.com/mA150Bn8 - 1st run
http://pastebin.com/SgRDRb4a - 2nd run
http://pastebin.com/YmqepQ4L - factions.json

**Comment by maxhuebler** [comment]
I had this issue about a year ago, it's very possible that you might not have enough disk space on your server to be able to save new factions/player data.

**Comment by Chris8130** [comment]
There's enough, 1TB KS4.

**Comment by drtshock** [comment]
I can't reproduce this at all.

**Comment by Chris8130** [comment]
What?

**Comment by drtshock** [comment]
Using your setup on my laptop, faction save just fine.

**Comment by squidicuzz** [comment]
Please provide more detail relating to this issue.

Have you been able to reproduce this since?  Are the permissions set correctly on the directory? Please try reinitializing the plugin from a clean state so the directory and files are recreated.

**Comment by Chris8130** [comment]
It's working fine now.
