### ISSUE TITLE
Prefix Problems

### ISSUE THREAD

**Issue by samgogogo** [drtshock/Factions#830]
So i have just bought this plugin and been having problems with the prefixes.

Is there a way to set a priority on the prefixes so the other plugin i use (DeluxeChat) can display its chat format.

Basically i want the chat format to not be the default prefixes in Factions but instead the ones i have set up in Deluxe Chat, is it possible to disable the chat format for factions?

Thank you
- Sam

**Comment by drtshock** [comment]
Not sure, you should ask what others have done. You can disable chat formatting in the conf.json though.
