### ISSUE TITLE
Factions unlimited claims... [URGENT]

### ISSUE THREAD

**Issue by ItzBlaze** [drtshock/Factions#831]
When a player claims land NO power is lost I checked config but I couldn't find anything please help!!!!!!!!!

**Comment by drtshock** [comment]
You don't lose power, you can only claim land for as much power as you have.

**Comment by ItzBlaze** [comment]
drtshock players can claim like unlimted like /f claim 500 and it will work and all the land will be claimed

**Comment by Kakifrucht** [comment]
Then set appropiate power limits.. Default is 10, so you must have messed with the config without understanding what you did.

**Comment by drtshock** [comment]
Or it might be someone with factions.bypass permission or op.

**Comment by ItzBlaze** [comment]
Hmm I deleted the config and set everything back and everything is fine... Thanks Kakifrucht and drtshock
