### ISSUE TITLE
F TOP, AND CONFIG ISSUES

### ISSUE THREAD

**Issue by BenjisCollector** [drtshock/Factions#832]
1.F top Shows some wrid balance thats only in the 1000s Times table, it doesnt include the value of spawners and the balance of players. the config files are way different than the ones my friends have. I also have an issue with my players not being able to make warps, it says you do not have permission to set warps for your faction.

**Comment by ItzBlaze** [comment]
You need to give the players permisions to set factions warps

**Comment by BenjisCollector** [comment]
how?

**Comment by drtshock** [comment]
1. Not sure where it says it adds up spawners.
2. Config files different from friends? Maybe they have a different fork?
3. Give them the permission to set a warp.

**Comment by BenjisCollector** [comment]
Fiverr

```
  {
      "@context": "http://schema.org",
      "@type": "EmailMessage",
      "action": {
        "@type": "ViewAction",
        "url": "https://www.fiverr.com/s2/133f2189fb",
        "name": "Browse Services on Fiverr"
      },
      "description": "Browse Services on Fiverr"
  }
























    Sttk is tired of keeping Fiverr a secret.



    Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.



    Sounds too good to be true? See for yourself!









                                                        Browse Services On Fiverr










        The Fiverr Team

















                                © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                Your personal information will not be stored or used for any marketing purposes.
```

If you would like to unsubscribe and stop receiving these emails click here.
