### ISSUE TITLE
How do i change the name wher the faction is?

### ISSUE THREAD

**Issue by Huzini** [drtshock/Factions#833]
i don't understand how i like change the stuff around the faction name behind my name please some one help me!

**Comment by lol768** [comment]
Please provide an annotated screenshot of the "stuff" you want to change.

**Comment by Huzini** [comment]
https://gyazo.com/761df5c27187a179a4d92f04afb5ff98 the thing with the faction name

**Comment by drtshock** [comment]
The chat tag? With a chat plugin
