### ISSUE TITLE
f setwarp option to require an f home (feature request)

### ISSUE THREAD

**Issue by Elgorond** [drtshock/Factions#834]
I'd like an option to make it so players must have an /f home to use /f warp and /f setwarp. This option makes sense because it's a large part of Factions to decide whether you have an f home or not, because with it you'll respawn there which other factions could abuse in order to take down your power, but without the f home your faction would have to use other means to return to their base, but without the risk of getting spawn killed.

But factions having the ability to setwarp without having a sethome would defeat this well known faction principle.

Having this as an option in the config would be veryy nice.

**Comment by mbax** [comment]
After six long years of waiting, this will go live in 0.6.5 as setting `requiredToHaveHomeBeforeSettingWarps`
