### ISSUE TITLE
homesteleportondeath option not working?

### ISSUE THREAD

**Issue by Elgorond** [drtshock/Factions#835]
"homesEnabled": true,
  "homesMustBeInClaimedTerritory": true,
  "homesTeleportToOnDeath": true,

With this after dying, players are being teleported to spawn instead of their faction home. I believe this was functioning correctly before I turned homesTeleportToOnDeath to false for a bit.

Is there something I'm missing?

**Comment by mbax** [comment]
Could not replicated, but it has been nearly 5 years so I assume this changed since then.
