### ISSUE TITLE
Not compatible with ColoredTags / More Problems

### ISSUE THREAD

**Issue by LightDragons** [drtshock/Factions#838]
So i decided to install FactionsUUID and this happened.

http://prntscr.com/cq80y8

Problem: Why are there 2 OWNER Tags and how do i disable them?

http://prntscr.com/cq81aw

Problem: Instead of showing &b&lOWNER Light_Dragons or MEMBER lantaren4 it shows us with white name and only the faction name. No prefix. No Nothing. How do i fix that?

**Comment by TheTechnologyStudio** [comment]
What chat plugin do you use?

**Comment by drtshock** [comment]
You're probably having factions and your chat plugin add it in. Disable one and leave the other :)
