### ISSUE TITLE
Ally blocked commands not being blocked

### ISSUE THREAD

**Issue by Mod-masta** [drtshock/Factions#839]
If a player uses a command blocked in allied territory, it will say the command is blocked but run it anyway. 

Example: https://gyazo.com/5034cd1dbdb2daec0d8d2d79741bd89e

This only happens with blocked commands in allied territory, it does not happen for neutral or enemies.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
