### ISSUE TITLE
/wild sending them to the world named "world"

### ISSUE THREAD

**Issue by kylew66** [drtshock/Factions#840]
Hello I'm having a issue were players are tping to a hole different world. I need /wild to tp them to the factions world. Not the world named "world". This is kinda a big issue. I need this fixed fast.

**Comment by Kakifrucht** [comment]
What does any of this have to do with Factions?

**Comment by kylew66** [comment]
I was pretty sure the /wild command is in the factions plugin.

**Comment by kylew66** [comment]
Am I wrong the /wild command is not in the factions plugin? I don't really like how you came off rude about it.

**Comment by Kakifrucht** [comment]
It was just a straight up question, if you expect me to end my sentence with a smiley face then here: :)
If you have Essentials installed you could type /help wild and it will most likely show you the plugins name.
The command /wild is not in Factions.
