### ISSUE TITLE
Trying to remove the scoreboard completely

### ISSUE THREAD

**Issue by ceasetoexist** [drtshock/Factions#841]
Hi, we have FactionsUUID and KOTH (king of the hill) plugins working together, the only problem is that KOTH conflicts with Factions' scoreboard. 
I was wondering if there would be an easy fix to disable the scoreboard from FactionsUUID.

FactionsPlus had this option, but it's been discontinued.
Any help would be greatly appreciated!

**Comment by Kakifrucht** [comment]
You can disable all scoreboard related features in config.yml. Also remove/negate the permission node `factions.scoreboard`.

**Comment by ceasetoexist** [comment]
Hi Kaki, I've tried and failed with the permissions - it seems like the scoreboard perms only relate the aesthetics, but the main issue is two plugins clashing together.

**Comment by Kakifrucht** [comment]
It shouldn't interfere if it is properly disabled. Shutdown the server and set `scoreboard.finfo-enabled`, `scoreboard.default-enabled` and `scoreboard.default-prefixes` in config.yml to false. If there is a scoreboard file in the Factions folder, remove it. Start the server. The scoreboard perms disable the possibility to use /f sb, which toggles the scoreboard. It might not be necessary if you have properly disabled it.

**Comment by ceasetoexist** [comment]
Thanks for your reply.
It turns out that the jar my client was using is a custom, and had no references to disabling the sidebar. It could be that the jar is outdated, I'm not sure.

**Comment by drtshock** [comment]
Can you paste your startup log?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
