### ISSUE TITLE
A couple issues.

### ISSUE THREAD

**Issue by kylew66** [drtshock/Factions#843]
For some reason I am not able to allow people to open materials in territories.  I turn it to false, even with the  server off, and it resets every time.  Also, how do I enable people to be able to set truces?

**Comment by kylew66** [comment]
Any help?

**Comment by kylew66** [comment]
Its been a week? Hello?

**Comment by kylew66** [comment]
This is getting ridiculous.

**Comment by Kakifrucht** [comment]
What text editor are you using when modifying the json file?

**Comment by kylew66** [comment]
I don't even have a json file?

**Comment by kylew66** [comment]
I'm just using multicraft.

**Comment by Kakifrucht** [comment]
That will be the issue. The json files are very prone to parsing errors. Please try with a proper text editor, like for instance Notepad++.

**Comment by kylew66** [comment]
Alright will do.  how do I enable people to be able to set truces?

**Comment by Kakifrucht** [comment]
This is what I found about them: https://github.com/drtshock/Factions/issues/460

**Comment by SekiAlpha** [comment]
Also if you want a better way to access your server files find out how to use an FTP with your server. You can ask your server host for more info about this or just google it.

**Comment by kylew66** [comment]
I'm running on a dedicated server so I know how to use SSH FTP a and etc. But thanks for the help. Also I'm still having the issue were I can't change it to allow people to open other people's chests in claimed land. I edited it with notepad++ and still having the same issue.

**Comment by Kakifrucht** [comment]
Try not to us tabs but spaces instead. Ensure that the server is off while editing conf.json. Backup the file.

**Comment by TheTechnologyStudio** [comment]
or do /f config ConfigOptionName and then what u want

He has a built ingame config editor.
