### ISSUE TITLE
Creeper eggs can't blow up certain blocks in other faction claims?

### ISSUE THREAD

**Issue by Elgorond** [drtshock/Factions#844]
Is this a bug?

Blocks such as trapdoors, hoppers, fences, etc. Am I missing something?

**Comment by WiggyWigo** [comment]
Check around line 175 in the conf.json 
should read something like this "territoryProtectedMaterials":

Make sure you have the materials removed in all the sections here.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
