### ISSUE TITLE
Feature Request? | Entering New Territory Help/Support

### ISSUE THREAD

**Issue by WiggyWigo** [drtshock/Factions#847]
On line 682 in the language file

faction-leave:
I believe the default is '<a>Leaving %1$s <i>Entering %2$s', Not too sure about this though...

Could this be added to config with variable support?

I am trying to Have it show as 

faction-leave: '{faction} - {description}'

So when you enter a territory the description and the faction name show in chat.

I am unsure if this is doable as the plugin is and if someone could help figure this out that would be greatly appreciated.

If not, I would really appreciate if it was added.

**Comment by ZombieAssassin** [comment]
mmmph. I love month long waits for a single reply.

**Comment by mbax** [comment]
Doable now.
