### ISSUE TITLE
/f promote/demote

### ISSUE THREAD

**Issue by MandiKro** [drtshock/Factions#850]
Hey there, why can't players use /f promote, demote. Is there something in the config I need to change?

**Comment by Trickster489** [comment]
"Why can't players use x" isn't a proper question. In order for developers to try and replicate this bug you have to attach screenshots and be more elaborate.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
