### ISSUE TITLE
Factionless players can't pvp faction players

### ISSUE THREAD

**Issue by TomGrozev** [drtshock/Factions#853]
So basically people in the wilderness faction cannot pvp people in a faction. Factionless players can kill each other but not someone from another faction. Please help!

**Comment by bagelcoder** [comment]
Can you paste your configuration on [hastebin.com](hastebin.com) and send a screenshot of your console/game client whenever this problem happens?

**Comment by TomGrozev** [comment]
Here is my cone.json: http://pastebin.com/5RFzXguW and my config.yml: http://pastebin.com/XgzQZVXA. There is nothing that is logged to console. It says you can't hurt neutral factions. Yes I do want this but I still want faction less players to be able to pvp with faction ones. Also is there a way to only require to enemy a faction if piping on their territory but allow php everywhere else?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
