### ISSUE TITLE
Ice Generating

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#854]
Hello, is there any way to stop Ice from generating in faction claims?

**Comment by WiggyWigo** [comment]
you can disable this globally using worldguard line 150 in the config. It is not possible to do through the factions plugin that I am aware of.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
