### ISSUE TITLE
Factions' Scoreboard Activation

### ISSUE THREAD

**Issue by Artztuga** [drtshock/Factions#855]
Hello, can someone help me how to activate the scoreboards, when I do /f sb it says

"You can't toggle scoreboards while they are disabled."

**Comment by Kakifrucht** [comment]
Did you try enabling it in config.yml?

**Comment by ReyDatCrafts** [comment]
I have the same problem, I can't seem to find the option to enable it

**Comment by Kakifrucht** [comment]
Check the scoreboard section in config.yml.
