### ISSUE TITLE
FactionsUUID and DeluxeChat incompatibility

### ISSUE THREAD

**Issue by ReyDatCrafts** [drtshock/Factions#856]
drtshock,

I've currently been using your plugin, which I bought about a week ago. My issue here is, I can't get it to work with DeluxeChat once I enable the placeholders (I think that causes the issue), and when I try to get them to work together, I never succeed. I've already went into extended_clip's help chat and asked there about if there's any fix and funnycube told me that maybe a good fix is getting older versions of either plugin. And that didn't work. I was wondering if you could maybe find out a fix on how to get it to be compatible or maybe contact extended_clip and colaborate together to maybe make both plugins compatible. Anyways, that was my issue.

Kind regards,
_ReyDatCrafts_

**Comment by Sean040299** [comment]
I've managed to have this bug but not as bad. I have got it workiing by using this placeholder within DeluxeChat placeholders:
`%factions_relation_color%%factions_chat_tag%`

The problem now is that the green colour to represent them being in the faction doesn't show but the neutral, ally and others work. Please fix the colour bug with them!

**Comment by BiggDaddyy** [comment]
in the faction folder there is a conf.json 

you need to set  ChatTagEnabled to false

then it will work

  "chatTagEnabled": false,

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
