### ISSUE TITLE
FactionUUID, enemy can open door,chest,...

### ISSUE THREAD

**Issue by duckweedvn** [drtshock/Factions#857]
I don't understand why my players can open the door,chest,... of a another faction? but only a faction that(my player create it), while the another faction is normal. I sure my config : disable denybuild,... and raidable false, let me know what happen. Thanks :'(

**Comment by Trickster489** [comment]
Paste your configuration

**Comment by duckweedvn** [comment]
Thanks for reply!
My conf.json : http://pastebin.com/7QtGi1i1
My config.yml : http://pastebin.com/kW8bBpfD

**Comment by duckweedvn** [comment]
bump

**Comment by duckweedvn** [comment]
Another question : Why i can't use command : /f truce, i can see truce in config! Why?

**Comment by drtshock** [comment]
Fixed in latest build.
