### ISSUE TITLE
Unable to build project, since PlayerVaults cannot be found

### ISSUE THREAD

**Issue by timbru31** [drtshock/Factions#858]
Hi there,

I was trying to build the project, but unfortunately PlayerVaults is not in the Jenkins repo:
https://ci.drtshock.net/plugin/repository/everything/

I'm not sure if a simple re-build is enough, but wanted to point out that the automatic deployment of your Jenkins build failed.

I've mirrored it in the meantime:
https://repo.dustplanet.de/artifactory/ext-snapshot-local/com/drtshock/PlayerVaults/

**Comment by drtshock** [comment]
Looks like nothing is there and it got wiped O_O

**Comment by timbru31** [comment]
ping @drtshock any news? ;)

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
