### ISSUE TITLE
Fly in claim land

### ISSUE THREAD

**Issue by danielm175** [drtshock/Factions#863]
What do I need to allow fly in claim land and ally land ? how do I allow players to fly in there territory with this plugin

**Comment by LTEethan** [comment]
find an factions addon plugin 
here is one that is made for factionsUUID:
https://www.spigotmc.org/resources/factionfly.19614/

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
