### ISSUE TITLE
Request and Bugs.

### ISSUE THREAD

**Issue by Alex0Klain** [drtshock/Factions#864]
**Bug:**
{
"baseCommandAliases": [
"g"
],
Changes in the letter /f help, but does not change the command! 
When I enter /g help, it gives: "Command not found"
**Request:**
Please add {factions_relcolor} how in Factions Massive Craft

Thx :)

**Comment by Alex0Klain** [comment]
I really like your plugin, but it's 2 big flaws for me :c

**Comment by Kakifrucht** [comment]
Define the command alias via Bukkit's [commands.yml](http://wiki.bukkit.org/Commands.yml). Factions doesn't offer this functionality.

**Comment by Alex0Klain** [comment]
In Factions Massive Craft this works

**Comment by Kakifrucht** [comment]
Did you try restarting the server after setting it to g?

**Comment by Alex0Klain** [comment]
yes

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
