### ISSUE TITLE
Problem compatibility with essentials and FactionsUUID (Money-Vault)

### ISSUE THREAD

**Issue by EpicProt** [drtshock/Factions#865]
When I set up the max of money a player can have in essentialsx, if he tries to deposit money in the bank through /f money deposit, it transfers them to the faction correctly, but the faction can't have more that the max of money a single player can have! For example: if the max amount of money a player can have is set to 10.000.000$, the faction max amount of money is 10.000.000$ (no sense)

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
