### ISSUE TITLE
F Show colour bug?

### ISSUE THREAD

**Issue by Sean040299** [drtshock/Factions#866]
I've been having this problem recently where if you use &l it changes this text colour to white when it's meant to be gray:

When it's meant to be gray with bold:
[http://imgur.com/YW13IZN](url)
Code (Text):
- '<a>&7Allies &8&l»(<i>&c{allies}<a>/<i>{max-allies}<a>): {allies-list}'
Without bold:
[http://imgur.com/qOUCjEw](url)
Code (Text):
- '<a>&7Allies &8»(<i>&c{allies}<a>/<i>{max-allies}<a>): {allies-list}'
How do I fix it to stop coming out white??

EDIT: The 3 bottom rows (Allies, Online and Ofline) also do this colour glitch?

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
