### ISSUE TITLE
Factionless | Prefix Tag

### ISSUE THREAD

**Issue by TheC0ller** [drtshock/Factions#876]
Hello, is is possible to add prefix to Factionless faction ? I'm using latest FactionsUUID from spigot.

**Comment by Crusby** [comment]
Pročti si config, to je vše. Jestli umíš aspoň trochu anglicky tak si to opravíš(spustíš) za 15, max 30 minut. Jo PS:. tady ti nikdo nepomůže je to tu mrtvý jak Chernobyl.

**Comment by TheC0ller** [comment]
Neviem no, skúšal som všetko čo mi prišlo za vhodné no nedokázal som aj tak Factionless frakcii nastaviť tag. Nedokážem ho ani len nájsť vo /factions.yml súbore pričom je v príkaze /f list zaznamenaný..

**Comment by CmdrKittens** [comment]
This is doable in latest.
