### ISSUE TITLE
FactionsUUID overrides EssentialsChat 

### ISSUE THREAD

**Issue by LTEethan** [drtshock/Factions#880]
ive been having this problem for ages and dont know how to fix it. Tons of people are saying that factionsUUID is overriding essentials chat. Which seems true. ive been lookin in the conf.json, config.yml and lang.yml to see there is no way you can edit the chat format. when i edit the chat format in essentials config, it never works.

**Comment by NovaLegion** [comment]
Set the index to 0?

**Comment by BiggDaddyy** [comment]
conf.json 

you need to set ChatTagEnabled to false

"chatTagEnabled": false,

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
