### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#882]
Failed to execute goal on project Factions: Could not resolve dependencies for project com.massivecraft:Factions:jar:1.6.9.5-U0.1.19-RC1: Failure to find com.drtshock:PlayerVaults:jar:3.6.0-SNAPSHOT in http://nexus.hc.to/content/repositories/pub_releases was cached in the local repository, resolution will not be reattempted until the update interval of vault-repo has elapsed or updates are forced -> [Help 1]

**Comment by drtshock** [comment]
Looks like my maven repo died https://ci.drtshock.net/plugin/repository/everything/ Will need to get that fixed.

**Comment by PhanaticD** [comment]
any news

**Comment by drtshock** [comment]
I'm not sure why it's not working.. I'm telling it to publish and it's just.. not.

**Comment by markhughes** [comment]
@PhanaticD there is a way around this.

Download it from https://dev.bukkit.org/projects/playervaults

Edit: above outdated, get from https://ci.drtshock.net/job/PlayerVaults/

Then in your project:
```
mvn install:install-file -Dfile=/path/to/playervaults.jar -DgroupId=com.drtshock -DartifactId=PlayerVaults -Dversion=3.6.0-SNAPSHOT -Dpackaging=jar
```

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
