### ISSUE TITLE
issue on 1.11

### ISSUE THREAD

**Issue by Mineacer** [drtshock/Factions#885]
http://pastebin.com/z8Yq26rP

**Comment by Mineacer** [comment]
Anyone know how to fix this?

**Comment by Kakifrucht** [comment]
Wait for update.

**Comment by Mineacer** [comment]
Okay, waiting thanks brother.

**Comment by drtshock** [comment]
Can you give me your server version? The method is there, just deprecated https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageByEntityEvent.html

**Comment by drtshock** [comment]
Duplicate of #883
