### ISSUE TITLE
/f invite bug?

### ISSUE THREAD

**Issue by Jacobvs** [drtshock/Factions#886]
Im trying to use this plugin on my server, and everything works except for /f invite which returns an internal error. Heres my console after i do /f invite (player): https://hastebin.com/oneboveqiv.vbs 
if you need anything else message me because i dont know whats causing this issue

**Comment by Kakifrucht** [comment]
````v1.6.9.5-U0.1.14```` outdated

**Comment by Jacobvs** [comment]
how do i build the current version into a .jar from the repo? @Kakifrucht
