### ISSUE TITLE
f create

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#890]
Hi,

can you add those values :
YOURS: <h>%1$s<i> created a new faction. (Exemple : Vous avez créé une nouvelle faction.)
NOTYOURS: <h>%1$s<i> created a new faction. (Exemple : **** a créé une nouvelle faction.)
Because in french, it's not the same.
If you could add this, it would be great.

Thanks bro !

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
