### ISSUE TITLE
A list of Suggestions and additions

### ISSUE THREAD

**Issue by TheTechnologyStudio** [drtshock/Factions#891]
- update the /f owner command so it can do radius - f owner radius

- Update the /f warp system to allow allys to warp - f setally warp - f ally warp <name>

 - /f Co-Owner , Same perms as owner just no /disband

 - Add a permission system for faction leaders to assign what faction mods can do in a gui.  So you can make it so some mods can kick people some cant and so on.

- Sister Factions :More explained here https://hastebin.com/xeleviwaxa.vbs 

- /f requestjoin [FACTIONNAME] and when a mod or person logs on their chat will say:
Player 1 -Player 2 -Player 3 -etc wants to join your faction! then u do /f acceptjoinrequest [PLAYERNAME]

**Comment by mbax** [comment]
Other than radius (which is a system to be reworked soon) this is doable now.
