### ISSUE TITLE
"You can't destroy in ..." message changing/disabling

### ISSUE THREAD

**Issue by wouter-blockken** [drtshock/Factions#893]
Hello,

I was wondering if there is a way to disable the message when players interact with terrain and they can't build. if they click grass it keeps spamming them with "you can't destroy in a war zone". Is there a wayto disable this, maybe in the plugin itself ? I would love to hear a solution :) Thank you for reading

Regards,

Wouter

**Comment by mbax** [comment]
Disabling messages is coming in an upcoming release. Clearing out repetitive tickets of this for now.
