### ISSUE TITLE
Error on /f invite, /f who and /f show

### ISSUE THREAD

**Issue by christiaanbruijnes** [drtshock/Factions#895]
Error: http://pastebin.com/yhYFUYyE

**Comment by Kakifrucht** [comment]
Please give some further information about this. Server version, does it happen for every player chatting?

**Comment by christiaanbruijnes** [comment]
Latest spigot 1.8.*

I switched from FactionsOne to FactionsUUID, rest seems okay, besides some commands.

**Comment by Kakifrucht** [comment]
Probably corrupted format somehow, as it seems like the role variable is not set. Can you check your players.json and see if for every player there is a "role" variable that is either "ADMIN", "MODERATOR" or "NORMAL"?

**Comment by christiaanbruijnes** [comment]
Wow! That could be true, because that gave me an error aswell with deluxechat, it couldn't found a ROLE.

https://gyazo.com/3ea6e93e39e4e491f004d979b63b762e

No ROLE at all, how could this happenend and can it be fixed?

**Comment by christiaanbruijnes** [comment]
Some players do have a ROLE by the way, but some of them doesn't.

**Comment by Kakifrucht** [comment]
I don't know how FactionsOne stores its roles, but it seems to have a seperate file for that?
You would need some kind of converter.

**Comment by christiaanbruijnes** [comment]
Hmm, how would I do this? What would be the smartest move?

**Comment by Kakifrucht** [comment]
It depends on how FactionsOne stores roles, as the information is not in the players.json, I suspect there is another file for that. You would most likely need to write a converter or reset the databases entirely and start from scratch.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
