### ISSUE TITLE
[Suggestion] F Perms, F Near, Roles, Customisable Roles

### ISSUE THREAD

**Issue by ItsDomHD-zz** [drtshock/Factions#897]
Somewhat directed here by drtshock when I PM'ed him about my friends requests xD You remember boi :D.

Anyways the ideas are:
Introduce /f perm to FactionsUUID including a new rank (like Recruit/Member),

Allow players within their Faction role to access different Faction warps (ties into /f perms),

Allow the manual creation of roles (I.E Within config, predefined roles would be Admin/Leader Officer/Mod, Player/Member and so on (somewhat ties into /f perms) ,

Add a section within config where you can set unprotected blocks (I.E When raiding for spawners you can mine it on their land with no permissions),

THIS ONE IS DEBATABLE Adding /f near which can find nearby faction claims withing a X radius. (I know a potential piece of code like literally a line that could work, Idk I'm not a programmer so don't take my word on it being good xD just ask me for it if you want it :D)

**Comment by NovaLegion** [comment]
Just use massivecore factions?

**Comment by ItsDomHD-zz** [comment]
I rather this because its more smoother personally!

**Comment by judehek** [comment]
I think the idea of uuid is that gameplay features would stay relatively the same
