### ISSUE TITLE
Power boosts being lost

### ISSUE THREAD

**Issue by Mod-masta** [drtshock/Factions#899]
It seems that players who don't log in for a while (like 1-2 weeks+) lose any power boost they have. This has happened to quite a lot of players for me.

**Comment by Kakifrucht** [comment]
Please continue here #689

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
