### ISSUE TITLE
Factions Getting deleted / cancelled 

### ISSUE THREAD

**Issue by ElectroBiloo** [drtshock/Factions#902]
Hey guys

I Bought FactionsUUID not a while ago but i'm having this problem when every time I reload , restart , or the player leaves the server it cancels their faction / delete it. Please help me fix it!

I'm using the latest version with the auto config that is created by the .jar
Version: 1.8.9

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
