### ISSUE TITLE
PLayers can place  lava/water buckets in enemy claims at the border with claiming.

### ISSUE THREAD

**Issue by StefvanderMeer** [drtshock/Factions#907]
Players have 1 claim and if you claim basicly next to it you can place water/lava on their claim if you place it on a block that is on your claim.

**Comment by StefvanderMeer** [comment]
And when doing /f stuck you can get teleported outside the border and die.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
