### ISSUE TITLE
Players are able to remove water/lava sources unless chunk is /f owner claimed.

### ISSUE THREAD

**Issue by EmperorPvP** [drtshock/Factions#908]
Hello one of my staff members recently found a big problem with factions, players can remove water/lava sources in claimed land without it being theirs unless it's /f owner claimed, they don't receive the water/lava in their inventory but it removes the source. Hope you can fix it thanks!

**Comment by PressurePlates** [comment]
I'm pretty sure this is just for their screen and does not show up for others.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
