### ISSUE TITLE
Carbon Compatibility

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#91]
Carbon injects new materials and breaks with enums.

**Comment by maxhuebler** [comment]
Just got this problem, any way this can be fixed? Would be unfortunate. Also, where can I download the latest dev builds? Do I have to compile it myself now?

**Comment by drtshock** [comment]
It was fixed here. I made this issue just to reference it in the commit. Forgot to close it :) https://github.com/drtshock/Factions/commit/307724a419f5d7e32b36f62ca56422f96208dc02

**Comment by drtshock** [comment]
If you've purchased http://www.spigotmc.org/resources/factionsuuid.1035/ then you can sign up on http://ci.drtshock.net and pm me your username on spigot (so I can check your account against the buyer list) and add you to the dev build job. You'll then be able to get a dev build from each github push on http://ci.drtshock.net/job/FactionsUUID

**Comment by maxhuebler** [comment]
Sorry! I guess I missed the memo that this was changed to a premium resource. I was worried you stopped development on this a few months ago, since the build tracker was closed. I'll be purchasing the resource now, cheers.
