### ISSUE TITLE
Adding brackets

### ISSUE THREAD

**Issue by farmkitecarry** [drtshock/Factions#910]
I wanted to know if their is anyway to add brackets to the chat so [{factionname}] like this but i want the brackets to be white i figured out how to put them on I am just not sure how to change the color of them.

  "chatTagFormat": "[%s]§f", 

I tried to put &f before and after but it just stayed green would be nice to make them white help would be appreciated.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
