### ISSUE TITLE
HCF and Config Help

### ISSUE THREAD

**Issue by OfficialTheosis** [drtshock/Factions#913]
Hello,

I really need some help regarding the configuration of this plugin. I'm struggling to get my head around it, but I've never configured a Factions-related plugin before so please be gentle.

I'm trying to make my server partly regular Factions and partly HCF (Hardcore Factions). The raiding system will be like that of HCF. I also don't want "power" to be a thing, claiming land should only cost money and nothing else. I want "DTR" to be exactly the same as that of HCF, but I can't even get it to display on "/f show".

These are the only queries I can think of off the top of my head, but there may be more. My server is 1.11.2.

**Comment by CmdrKittens** [comment]
#1223
