### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#917]
How do I enable the Factions scoreboard?

**Comment by amgno** [comment]
i don't know

**Comment by kashalls** [comment]
Approximately on line 138ish, you should find a line that says "default-enabled: " in your Config.yml

It should be set as "default-enabled: true". If it doesn't show up, you either have a conflicting plugin or you need to delete scoreboard.dat from your world data folder.

If you cannot find it, try using the search function and search for it.

**Comment by jogozin** [comment]
@Kashalls I looked through conifg and changed it to true. I do f reload and it still says
"You can't toggle scoreboards while they are disabled."

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
