### ISSUE TITLE
Need features to translate

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#919]
Hi,

I've a little problem to translate few sentences.
I will show you an exemple :
In english, to disband your faction, it's in the config :
YOURS: <h>%1$s<i> disbanded your faction.
If it's you, that will give "You disbanded your faction." or if it's your mate "Billy disbanded your faction."
But when you want to translate it in french, it will be
"Vous avez détruit votre faction." or "Billy a détruit votre faction."
You won't understand a single shit but you see there is a difference...
If you could add a feature to give me the possibility to translate.

Thanks !

**Comment by Kakifrucht** [comment]
#734, I really don't think that this will be fixed though.

**Comment by ghost** [comment]
Ah yeah 1 year later it keeps buggy :/
RIP

**Comment by ghost** [comment]
Bump, maybe they'll check it one day... :D

**Comment by MarkehMe** [comment]
Fixed this bug in LegacyFactions

https://github.com/redstone/LegacyFactions/releases/tag/v1.1.0

**Comment by Kakifrucht** [comment]
That looks great, will try it out soon!
