### ISSUE TITLE
Cannot use certain {tags} for default leader board

### ISSUE THREAD

**Issue by maxhuebler** [drtshock/Factions#92]
When trying to edit the default leader board you cannot use the tags:
- {online}
- {members}
- {leader}
- {chunks}
- {raidable}

You also cannot use any {tags} in the default leader board default-title, for example if you wanted to make the title for the default leader board be "{faction} information", it wouldn't display as "MyFaction Information" but instead {faction} information.

Of course the {faction} tag should replace with the name of your faction.

**Comment by drtshock** [comment]
Reason I didn't put most of those is because what would we put if someone doesn't have a faction?

**Comment by maxhuebler** [comment]
Maybe just have it say NoFaction like you do with the {faction} tag. It's a faction server, they'll eventually get a faction. Maybe have it so everyone has it disabled by default and you have to type /f sb to re-enable it. I believe how it works right now is everyone sees it and would only type /f sb to disable it.

**Comment by squidicuzz** [comment]
If the player has no faction, it shouldn't display at all.  We could have a filter where if the faction is wilderness, it would just not display for that player.  Thoughts?

**Comment by maxhuebler** [comment]
That sounds perfect.

**Comment by drtshock** [comment]
We now have separate f shows for things.
