### ISSUE TITLE
FactionsOne to FactionsUUID Transfer

### ISSUE THREAD

**Issue by antares330** [drtshock/Factions#923]
Currently using FactionsOne, but really want to use SkRambled for custom features.

My question: Do FactionsOne Factions and data convert over to FactionsUUID?

If not, I'll just have to wait till a reset.
Thanks
Justin

**Comment by mbax** [comment]
Leaving this message for others searching for it: Reach out to me (mbaxter) on discord and I'll look into how converting would go.
