### ISSUE TITLE
DeluxeChat takeover

### ISSUE THREAD

**Issue by chaz2601** [drtshock/Factions#928]
I use DeluxeChat to handle my chat, but when i drop factions into the plugins folder, my chat gets destroyed and becomes ugly. Please fix this!!! Bought the plugin, but still unable to use it because of this.
http://imgur.com/a/xf38r the top format is without factions installed, bottom is when i drop factions in.

**Comment by chaz2601** [comment]
Just noticed why it was taking over. whenever i set chatTagEnabled to false and reloaded, it saved the previous setting changing it to true everytime i reload.

**Comment by ACrispyCookie** [comment]
Where's the chatTagEnabled option?
