### ISSUE TITLE
Filoghost's Health Bar plugin breaks leader boards

### ISSUE THREAD

**Issue by maxhuebler** [drtshock/Factions#93]
Testing using Health Bar v1.8.2 for 1.7.4 breaks the leader board functionality. Using latest spigot build as of October 20th.

Using /f sb does nothing besides display the message, and both leader boards were enabled in the configuration.

**Comment by Kakifrucht** [comment]
Once Factions scoreboard is enabled, it will override all other uses of the scoreboard. You can disable the default scoreboard, than it should work.

**Comment by maxhuebler** [comment]
Well, it's not overriding all other scoreboards because it's not showing up when this Health Bar plugin is enabled. I know it works fine if the Health Bar plugin is disabled, but that's not the point because I want these two plugins to work together and not have to compromise.

**Comment by Kakifrucht** [comment]
Oh I see what you mean. I can confirm this, leaderboards are not working for me either on latest build 99.

**Comment by drtshock** [comment]
No leaderboards? Or nothing with the healthbar plugin.

**Comment by Kakifrucht** [comment]
I personally don't get the sidebar leaderboard and no prefixes, actually nothing on the build 99 I think it was. I can personally not say that this is a conflict with Healthbar, but OP seems to have narrowed it down to it.

**Comment by drtshock** [comment]
@Kakifrucht are you running healthbar plugin too?

**Comment by maxhuebler** [comment]
When I have the Health Bar plugin enabled, it works fine but breaks the Factions leader board, everything else with factions is working well.

**Comment by Kakifrucht** [comment]
I am running Healthbar too, I can confirm the issue silverbrit is reporting. Although I didn't narrow it down myself.

regards

**Comment by drtshock** [comment]
Scoreboard still isn't very friendly ;c
