### ISSUE TITLE
Create factions manually?

### ISSUE THREAD

**Issue by danielscholtes** [drtshock/Factions#931]
I was wondering if it was possible to create factions and players manually via config. I am planning to convert from 2.8.2 MCore Factions to FactionsUUID and I need to convert factions and players so it seems like just some stuff is different and they don't need to make a new base, faction and invite everyone again.

**Comment by mbax** [comment]
Old ticket.

Confirming yes, you can do it manually, but reaching out to me on discord can get help converting from other systems like `mstore` folders.
