### ISSUE TITLE
/f desc Limit.

### ISSUE THREAD

**Issue by ItalianPenquin** [drtshock/Factions#936]
Mabey I have overlooked every time I have looked but I don't seem to see any option to limit how many characters you can use as your /f desc. Mabey this is something that has not been added if not it needs to be. This would be a great small feature!

**Comment by MarkehMe** [comment]
We're adding this to [LegacyFactions](https://github.com/redstone/LegacyFactions).

https://github.com/redstone/LegacyFactions/issues/106

**Comment by mbax** [comment]
Finally added for 0.5.25
