### ISSUE TITLE
Enhancement: Generate a log for alliance/faction private chat

### ISSUE THREAD

**Issue by maxhuebler** [drtshock/Factions#94]
I believe this would be a useful feature considering other chat plugins don't currently log it.

**Comment by drtshock** [comment]
Are chat events not thrown? This should be in the normal server.log

**Comment by maxhuebler** [comment]
Yes, but it would nice if there was separate log that only included faction chat discussions, would be very useful.

**Comment by drtshock** [comment]
Why? It wouldn't make sense to do that without doing all chat anyway. Chat could get mixed up between the 2. I feel like this is the job for another plugin.

**Comment by maxhuebler** [comment]
Currently I use a plugin called [ChatControl](http://www.spigotmc.org/resources/chatcontrol.271/), it logs normal all chat nicely, I was just wondering if it was possible to do the same for factions.

**Comment by mbax** [comment]
Plugins not aware of Factions wouldn't be able to generate as nice of a log. Could be a neat feature. Or something for a factions-aware logging plugin to handle.

**Comment by squidicuzz** [comment]
Duplicate/Relates to issse #37 

Fix via throwing an async chat event for faction and allied chat.

**Comment by squidicuzz** [comment]
Logging via what if thrown from the chat event, or to the server.log should be sufficient.  Anything extra is going above and beyond the desired scope.

**Comment by drtshock** [comment]
I can still see how it'd be nice to have a separate log though especially with how easy it would be. And disabled by default of course.
