### ISSUE TITLE
Mine Spawners In Enemy Land

### ISSUE THREAD

**Issue by KillDevlicious** [drtshock/Factions#941]
Is there a way to make spawners mine-able in enemy land? and if so how?

**Comment by ghost** [comment]
Yes, I need that as well!

**Comment by MarkehMe** [comment]
We're adding this to [LegacyFactions](https://github.com/redstone/LegacyFactions).

https://github.com/redstone/LegacyFactions/issues/105

**Comment by dariasc** [comment]
PR in the private repo :)

**Comment by mbax** [comment]
Doable at this point with the block exceptions list.
