### ISSUE TITLE
Your plugin is breaking other plugins that listen to chat

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#948]
You need to stop cancelling the chat event and instead just remove non-recipients.

You are breaking every other plugin that listens to chat, these plugins include [DiscordSRV](https://www.spigotmc.org/resources/discordsrv.18494/), [CoreProtect](https://www.spigotmc.org/resources/coreprotect.8631/), other loggers, etc.

**Comment by markhughes** [comment]
If people still want to use relational colours and their chat plugin doesn't support it they can enable `chatTagRelationalOverride` 😄
