### ISSUE TITLE
FactionsPlayerListener high PCT tick

### ISSUE THREAD

**Issue by icecraftsurvival** [drtshock/Factions#95]
Hi! So basically, the issue is in the Gyazo below..
http://gyazo.com/860084c87f335d4dbf5a8b99701bcab0
I'm unsure how to fix this or improve the tick rate, can anyone help me out? Or will the fix simply come in an update?

**Comment by icecraftsurvival** [comment]
This is also happening... and the Scoreboard isn't even enabled. 
http://gyazo.com/df6672a2e4ee8243907b146e1dfec0db
I have no idea what to even do anymore...

**Comment by Kakifrucht** [comment]
I can confirm this, however it's not really a big deal (besides the scoreboard, that should be fixed).

**Comment by cnr** [comment]
Will look into this today. (it's a regression from the added complexity of faction-based prefixes)

**Comment by cnr** [comment]
I think I may have found a way to reduce the load; please ~~try this build~~ join IRC to grab a build and confirm/deny (:

**Comment by drtshock** [comment]
Let us know how it works :)

**Comment by drtshock** [comment]
This has been resolved over a few scoreboard commits.
