### ISSUE TITLE
Event for promotions to mod & leader

### ISSUE THREAD

**Issue by andre-paulo98** [drtshock/Factions#952]
If you making a API based on FactionsUUID you can only get the Leader of the Guild, when it's created.
There is no event for setleader or setmoderator.
Would be possible to make one?

**Comment by MarkehMe** [comment]
We're adding this to [LegacyFactions](https://github.com/redstone/LegacyFactions).

https://github.com/redstone/LegacyFactions/issues/104

**Comment by MarkehMe** [comment]
Added in https://github.com/redstone/LegacyFactions/commit/6d24c74527650a29182f2e237e702c923ca26052

**Comment by mbax** [comment]
Event now exists, in upcoming release.
