### ISSUE TITLE
FactionsUUID Truce/Nametags

### ISSUE THREAD

**Issue by harriss212** [drtshock/Factions#953]
How can i add truces because there seems to be no concept of truce which is sad and also the nametags for the tablist which shows the color relation is not adjustable in the configuration. How can i adjust this? thanks

**Comment by MarkehMe** [comment]
Truce isn't working in FactionsUUID, but it has been added in the 1.6 alternative LegacyFactions: https://www.spigotmc.org/resources/legacyfactions.40122/

**Comment by drtshock** [comment]
Please let me know of any issues with truces. They were added a long time ago. https://github.com/drtshock/Factions/commit/8c2f08b69436beb4946be18f5134d849fb000deb
