### ISSUE TITLE
Cant toggle scoreboard

### ISSUE THREAD

**Issue by DontEver** [drtshock/Factions#955]
Mhm Hello. I was wondering how I can enable the scoreboard. http://prntscr.com/g6i6qv
I looked in the config and didnt find anything. Do you have any idea?

**Comment by ghost** [comment]
Try using /f sb

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
