### ISSUE TITLE
Faction 1.7.10

### ISSUE THREAD

**Issue by PiggieCEO** [drtshock/Factions#956]
Hello there,

I love this plugin and I use it on my 1.7.10 server; however, whenever someone tries to invite players to their faction, "An internal error" shows up. Any possible solution?

**Comment by drtshock** [comment]
what's the error

**Comment by PiggieCEO** [comment]
The latest console log is from the top.
I made a faction called "Test"
and tried inviting someone "WhiteHusky2017".
It says "An internal error occurred while attempting to perform this command" while I typed in /f invite Whitehusky2017

`11.08 20:05:44 [Server] INFO Eggland [Shout] [Member] The_Names_Storrm > are the playervaults strictly for me
11.08 20:05:44 [Server] WARN Failed distorting outgoing text message! Args: [TextComponent{text='The_Names_Storrm', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg The_Names_Storrm '}, hoverEvent=null}}, !are the playervaults strictly for me]
11.08 20:05:38 [Server] INFO Eggland [Shout] [Member] The_Names_Storrm > piggie
11.08 20:05:38 [Server] WARN Failed distorting outgoing text message! Args: [TextComponent{text='The_Names_Storrm', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg The_Names_Storrm '}, hoverEvent=null}}, !piggie]
11.08 20:05:37 [Server] INFO Eggland [L][Member] WhiteHusky2017 > just do it
11.08 20:05:37 [Server] WARN Failed distorting outgoing text message! Args: [TextComponent{text='WhiteHusky2017', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg WhiteHusky2017 '}, hoverEvent=null}}, just do it]
11.08 20:05:35 [Server] INFO Eggland [L][Member] The_Names_Storrm > are playervaults
11.08 20:05:35 [Server] WARN Failed distorting outgoing text message! Args: [TextComponent{text='The_Names_Storrm', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg The_Names_Storrm '}, hoverEvent=null}}, are playervaults]
11.08 20:05:32 [Server] INFO Eggland [L][Member] The_Names_Storrm > waiut
11.08 20:05:32 [Server] WARN Failed distorting outgoing text message! Args: [TextComponent{text='The_Names_Storrm', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg The_Names_Storrm '}, hoverEvent=null}}, waiut]
11.08 20:05:21 [Server] INFO Eggland [L][Member] WhiteHusky2017 > storm*
11.08 20:05:21 [Server] WARN Failed distorting outgoing text message! Args: [TextComponent{text='WhiteHusky2017', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg WhiteHusky2017 '}, hoverEvent=null}}, storm*]
11.08 20:05:20 [Server] INFO Member: [Member] The_Names_Storrm, [Member] WhiteHusky2017
11.08 20:05:20 [Server] INFO Leader: Leader Piggie
11.08 20:05:20 [Server] INFO default: [Player] Egglanoir
11.08 20:05:18 [Server] INFO Eggland [L][Member] WhiteHusky2017 > torm come outside with nothing
11.08 20:05:18 [Server] WARN Failed distorting outgoing text message! Args: [TextComponent{text='WhiteHusky2017', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg WhiteHusky2017 '}, hoverEvent=null}}, torm come outside with nothing]
11.08 20:05:12 [Server] INFO Eggland [Shout] [Member] The_Names_Storrm > damn it
11.08 20:05:12 [Server] WARN Failed distorting outgoing text message! Args: [TextComponent{text='The_Names_Storrm', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg The_Names_Storrm '}, hoverEvent=null}}, !damn it]
11.08 20:05:08 [Server] INFO ... 13 more
11.08 20:05:08 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.P.onCommand(P.java:200) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.P.handleCommand(P.java:189) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:262) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:299) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.cmd.CmdInvite.perform(CmdInvite.java:53) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:80) ~[?:?]
11.08 20:05:08 [Server] INFO at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:91) ~[?:?]
11.08 20:05:08 [Server] INFO Caused by: java.lang.NullPointerException
11.08 20:05:08 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
11.08 20:05:08 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
11.08 20:05:08 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
11.08 20:05:08 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]
11.08 20:05:08 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
11.08 20:05:08 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
11.08 20:05:08 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.21
11.08 20:05:08 [Server] ERROR null
11.08 20:04:58 [Server] INFO Piggie created a new faction: Test`

**Comment by drtshock** [comment]
Something else is playing with your chat. Re open this with full server logs if it's still happening. Also, please try on the latest dev build.
