### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by SunyEnthu** [drtshock/Factions#957]
Hello this is not really an issue just would like to know if there is a sourcecode of factionsuuid that i can edit,
i cant really program but i can edit code just fine,
the plugin is good but the only problem is that it is hard to understand because it is in english and most of my players dont understand english.

i would just like to translate the commands and everything else,
or is this plugin sourcecode not available for the fact that it is paid?

i would decompile it but i would rather not withought the permission of the owner,
and because decompiling might lost some of the funcionalities and i might have issues with it later on.

my country is brazil in case you whanted to know :)

**Comment by drtshock** [comment]
This is the source code repo.
