### ISSUE TITLE
Error when /f show

### ISSUE THREAD

**Issue by maximesahagian** [drtshock/Factions#958]
Hello,

Thx for your plugin,

I have an error when i make /f show command,

Caused by: java.lang.ClassNotFoundException: mkremins.fanciful.FancyMessage

**Comment by maximesahagian** [comment]
![image](https://user-images.githubusercontent.com/12551218/29671013-b0b6a642-88e8-11e7-85ea-71cc86a23d17.png)

**Comment by drtshock** [comment]
Was an issue with a bad build not shading properly.
