### ISSUE TITLE
FactionsUUID not working!

### ISSUE THREAD

**Issue by BirminghamBoy** [drtshock/Factions#959]
I am not the one with the problem, so I do not have too much info on it, but **[here](https://pastebin.com/n3HPPrsK)** is the error message, and **[here](https://pastebin.com/NTLKePNY)** is the config.

**Comment by MarkehMe** [comment]
FactionsUUID doesn't work for MC 1.7. I fixed this in LegacyFactions

https://www.spigotmc.org/resources/legacyfactions.40122/
