### ISSUE TITLE
Event on Leader change ?

### ISSUE THREAD

**Issue by maximesahagian** [drtshock/Factions#962]
Hello, i can't find an event when the leader of the faction is changing,

can u help me to solve it ?

Thx.

**Comment by drtshock** [comment]
Why are you looking for this? It's not as straightforward as roles can change for various reasons:
* Current admin removed for inactivity by cleanup process.
* Current owner of faction setting new owner.
* Admin on server setting new owner of faction.
* Permanent factions going from having an owner to not.

**Comment by mbax** [comment]
Event now exists. edit: Upcoming release.
