### ISSUE TITLE
Brackets on Factionless Members

### ISSUE THREAD

**Issue by Tayzn** [drtshock/Factions#966]
My chat format is set to display the player's faction in brackets, this works fine and no issues with players who are in a faction; however, for players who are factionless, the brackets remain with nothing in between them. Is there any way to remove the brackets for factionless players or perhaps put something like a "-" in between the brackets?

Current Chat for Factionless Players: https://gyazo.com/d6f3014caa4351142814b4729d361ab3
Current Essentials Chat Config: https://gyazo.com/8db46f665ee36c848de909a3176e3ea8

I am running the latest version of FactionsUUID.

**Comment by drtshock** [comment]
Fixed in https://github.com/drtshock/Factions/commit/8fee985e99ae08e09163111c2784a4d464c89b1d
