### ISSUE TITLE
Claiming Land Causes Server Lag

### ISSUE THREAD

**Issue by nhulston** [drtshock/Factions#970]
Don't know much about the cause of this, but whenever a player claims land, it causes huge amounts of server lag until the claiming is done. Each faction can be claiming land for up to 5 minutes each because I give each player 100 power, and in this time the TPS drops from 20 to 5-10.

**Comment by drtshock** [comment]
Can you give me the command the player is executing when this happens? Probably need to limit the max claim radius in your conf.
