### ISSUE TITLE
API

### ISSUE THREAD

**Issue by JTGgamer2123** [drtshock/Factions#971]
Where would i obtain the api for this plugin?

**Comment by FabioZumbi12** [comment]
I want an API too, to add support tags on my plugin https://github.com/FabioZumbi12/UltimateChat

Actually, with FactionsUUID some users are having this issue: https://github.com/FabioZumbi12/UltimateChat/issues/49

**Comment by drtshock** [comment]
You're already in the repo... This is the source code. Just take a look.
