### ISSUE TITLE
The Factions are deleted everytime i stop/reload/restart!

### ISSUE THREAD

**Issue by GeorgiKappa** [drtshock/Factions#976]
******
New The plugin is good but when i get my server restarted all the factions are delted i tried this: /f save|/f saveall and this happen in the game http://prntscr.com/h6gx18(error) and in the console:http://prntscr.com/h6gx18 (btw its not from the spigot i tried papper spigot and the original one all the same)**

**Comment by WizzleBear** [comment]
You don’t need to do that. Just leave it like it is and it should save automatically.
