### ISSUE TITLE
FactionsUUID Scoreboard

### ISSUE THREAD

**Issue by Verxace** [drtshock/Factions#978]
So I have been trying to find this all over the interwebs but can't. Does anyone know how to enable the scoreboard?!?

**Comment by GrizzsChannel** [comment]
Ignore it and do the following:
Download TitleManager, it has a scoreboard in it
Download PlaceholderAPI
Read the documentation of PAPI and find the placeholders for Factions
Open the config in TitleManager and find the scoreboard section, adding the placeholders to it

Anything else, just ask me!

**Comment by drtshock** [comment]
Check the config.yml
