### ISSUE TITLE
[BUG] Faction List (/f list) Tooltips not working.

### ISSUE THREAD

**Issue by ItsDomHD-zz** [drtshock/Factions#983]
Inside the Config.yml is gives you options for tooltips, one of them being for the command /f shop which shows all Factions.
The default config shows this:
`  list:
    - "&6Leader: &f{leader}"
    - "&6Claimed: &f{chunks}"
    - "&6Raidable: &f{raidable}"
    - "&6Warps: &f{warps}"
    - "&6Power: &f{power}/{maxPower}"
    - "&6Members: &f{online}/{members}"`

However hovering over a faction name does not show anything.

**Comment by drtshock** [comment]
There's no /f shop command though.

Tooltips only go on for /f show and /f list.
