### ISSUE TITLE
[BUG] Faction Who - Allies

### ISSUE THREAD

**Issue by ItsDomHD-zz** [drtshock/Factions#984]
When doing /f who, you see all the information about your current faction. But beside Allies it shows your how many allies you have out of a battery, yes, a battery.
![2017-12-19_23 32 22](https://user-images.githubusercontent.com/25137513/34183874-e698bd62-e514-11e7-9377-cf05269c9485.png)

I use the default config for Factions.
`show:
  # First line can be {header} for default header, or any string (we recommend &m for smooth lines ;p)
  - '{header}'
  - '<a>Description: <i>{description}'
  - '<a>Joining: <i>{joining}    {peaceful}'
  - '<a>Land / Power / Maxpower: <i> {chunks}/{power}/{maxPower}'
  - '<a>Founded: <i>{create-date}'
  - '<a>This faction is permanent, remaining even with no members.' # only shows if faction is permanent
  - '<a>Land value: <i>{land-value} {land-refund}'
  - '<a>Balance: <i>{balance}'
  - '<a>Allies(<i>{allies}<a>/<i>{max-allies}<a>): {allies-list} '
  - '<a>Online: (<i>{online}<a>/<i>{members}<a>): {online-list}'
  - '<a>Offline: (<i>{offline}<a>/<i>{members}<a>): `{offline-list}'``

**Comment by ItsDomHD-zz** [comment]
I think the placeholder for max allies is broken but you never know :D

**Comment by drtshock** [comment]
it's infinity

**Comment by ItsDomHD-zz** [comment]
but what if I have a cap set for max allies?

**Comment by drtshock** [comment]
Oh. I see. Let me take a look then :)

**Comment by drtshock** [comment]
@Unforgivinq can you show me your config.yml please?
Can you confirm you have https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/config.yml#L173 set to true?

**Comment by SayNada** [comment]
lmfao a battery, its the infinite symbol xd
 

if you have a max amount of allies, just remove the infinite symbol and replace it with your amount of max allies.

**Comment by drtshock** [comment]
Waiting on a response about the config.
