### ISSUE TITLE
Faction unknow error

### ISSUE THREAD

**Issue by xSystem32x** [drtshock/Factions#985]
https://pastebin.com/vG14U736

Error is in the pastebin link. When i'm using /f or another command it gives this massive error in the console.

**Comment by drtshock** [comment]
Can you update? Or can you give me the build you're on? It looks like that line points to nothing.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
