### ISSUE TITLE
/f perm

### ISSUE THREAD

**Issue by Nedjii** [drtshock/Factions#987]
Hello, a lot of players asked me about /f perm since i left factions to factionsuuid, this is a factions feature that allow you to manage permission like building or opening doors on your faction, you can allow allies to open your chest or whatever, this is describe here : https://www.massivecraft.com/factions at the section "PERMISSIONS"

**Comment by drtshock** [comment]
Hey! Thanks for making the ticket. I'm moving the conversation over to https://github.com/drtshock/Factions/issues/991 since he added a picture I really like.

Check out the comments there for dev builds to try <3
