### ISSUE TITLE
PlaceholderAPI Support

### ISSUE THREAD

**Issue by instantout** [drtshock/Factions#988]
i was wondering if you can add..
- PlaceholderApi Support.
With a little Bit of Love, Some Magic.. and Chaos.

**Comment by drtshock** [comment]
<3

**Comment by drtshock** [comment]
What place holders should I add?

**Comment by instantout** [comment]
[https://www.spigotmc.org/resources/placeholderapi.6245/](url)
Connect with this So "%<Placeholder>%" uses the % Percent Brackets would be nice, so this would unlock alot of features+ the MVDW Placeholder (of course owning one of the plugin condition).

**Comment by drtshock** [comment]
Yeah but what values do you want to see

**Comment by Nedjii** [comment]
How many vault a faction have, how many extra power ...

**Comment by drtshock** [comment]
Just added https://github.com/drtshock/Factions/commit/e343ac69fa9b88edce0148ac0ac095af94584638
