### ISSUE TITLE
It'd be nice to be able to configure this....

### ISSUE THREAD

**Issue by Mr4Skinz** [drtshock/Factions#990]
![fm](https://user-images.githubusercontent.com/33971997/34465792-0839d01a-ee74-11e7-82bd-c0c74446c8f8.png)
It'd be nice

**Comment by drtshock** [comment]
Can be configured by removing {header} line and replacing it with whatever you want, and having {faction} for the faction tag. https://github.com/drtshock/Factions/blob/1.6.x/src/main/resources/config.yml#L233
