### ISSUE TITLE
Would Love this Feature if Possible..

### ISSUE THREAD

**Issue by instantout** [drtshock/Factions#991]
[https://i.imgur.com/6jmJabK.png](https://i.imgur.com/6jmJabK.png)
I dont recall were i took this Screen shot also wondering if Factions UUID has this, Since the colors match
"has this" i know it doesnt but would love this to be Added if possible.

**Comment by drtshock** [comment]
If you want to be a guinea pig, try https://ci.ender.zone/job/FactionsUUID/13/ to check out an initial implementation. I'll add the GUI next.

Please run that on a test server, not production, and let me know how it goes <3

**Comment by Nedjii** [comment]
This is the factions mcore /F perm

**Comment by drtshock** [comment]
What

**Comment by Nedjii** [comment]
The screen is from Factions mcore by massivecraft. This is the /f perm i already asked about !

**Comment by drtshock** [comment]
Yes hats why I merged the tickets.

**Comment by Nedjii** [comment]
I was just telling so you can take a look at /f perm from factions mcore. I mean how it works ^^

**Comment by drtshock** [comment]
We have it in latest dev builds.
